### ISSUE TITLE
pick, axe, sword (reported by Shadauer17)

### ISSUE THREAD

**Issue by Driesboy** [ImagicalCorp/ImagicalMine#128]
pick, axe, sword etc ... because they do not damage? are ilimited hp? '-' they don't break -.-

(reported by Shadauer17)

**Comment by MCPEPIG** [comment]
I think this is cause the item isn't being updated.

**Comment by keithkfng** [comment]
Is this fixed?

**Comment by robske110** [comment]
No, still there in Build #323

**Comment by thebigsmileXD** [comment]
-.- we are 50 commits later, dude. 376 or so

**Comment by Driesboy** [comment]
update your server man
