### ISSUE TITLE
xp command

### ISSUE THREAD

**Issue by KubixQ** [ImagicalCorp/ImagicalMine#130]
Can you add /xp (count) command?

**Comment by keithkfng** [comment]
Sounds more like a plugin than something actually implemented.

**Comment by thebigsmileXD** [comment]
This is a vanilla pc command. Should be alright

**Comment by KubixQ** [comment]
Of course

**Comment by thebigsmileXD** [comment]
We'll fix xp first

**Comment by KubixQ** [comment]
xD

**Comment by GamerXzavier** [comment]
Then why dont put all the minecraft pc vanilla command XD

**Comment by thebigsmileXD** [comment]
I tried to code the /setblock command. And enhanced it. It also sets the block in your hand if no block is specified. Please list what vanilla commands are missing, i'll do them

**Comment by GamerXzavier** [comment]
dont forget the achievement

**Comment by thebigsmileXD** [comment]
What archivement? You don't get one when you gain XP..

**Comment by TahaTheHacker** [comment]
the xp API..

**Comment by AndreyNazarchuk** [comment]
Make sure you guys add a function to the api that does that also, probably addXp(int $num);

**Comment by thebigsmileXD** [comment]
https://github.com/ImagicalCorp/ImagicalMine/commit/691270c723bad9107fde8c3f40b998e2653238a0
The API will be $player->giveExpLevels($amount);, for taking it will be $player->giveExpLevels(-$amount);

**Comment by AndreyNazarchuk** [comment]
Maybe just giveXp()?

**Comment by thebigsmileXD** [comment]
Nope. I would love it to be the same as Bukkit

**Comment by AndreyNazarchuk** [comment]
Pm is not Bukkit, just make it $player->giveXp to make it less confusing,
Bukkit is written by people who do not know English, it makes it confusing
and longer than needed.

**Comment by thebigsmileXD** [comment]
PocketMine is a ported version of Bukkit.

**Comment by AndreyNazarchuk** [comment]
No, it was inspired by Bukkit. But the Bukkit api makes less sense for
English speakers.

**Comment by AndreyNazarchuk** [comment]
OK fine idc what the function is, just please make sure it has an event, and make sure there are functions to get, add, take, and set xp.

**Comment by thebigsmileXD** [comment]
take = add(-amount)
set would be interesting.

**Comment by MCPEPIG** [comment]
Check this commit: 253c90e7de7ab23a7c66f7484e3a71d518413c90
