### ISSUE TITLE
Doors

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/ImagicalMine#169]
On the latest commit #293
Spruce doors are now working but the other new doors are still either 1/2 or disappear.

**Comment by thebigsmileXD** [comment]
How closed? Fixed or just disappeared?

**Comment by NML32** [comment]
Sorry, my mistake didn't mean to close.

**Comment by NML32** [comment]
How hard is it to fix the other doors?

**Comment by thebigsmileXD** [comment]
Try the latest build, are they still gliching?

**Comment by NML32** [comment]
I tried build 320 and doors still glitching.

**Comment by thebigsmileXD** [comment]
In what way? what happens? Can't place? Can't break? half if they are opened?

**Comment by thebigsmileXD** [comment]
Do OakDoors work?

**Comment by keithkfng** [comment]
I hope they do. Last time @ZombiePower and I tested doors, oak and spruce doors worked. Nothing else.

**Comment by thebigsmileXD** [comment]
The whole door opening is written so beta.. it causes pretty much load on the server. And it doesn't use new bitwise things like bukkit does.. thats why the doors are placed weird, the doors update weird etc.

**Comment by NML32** [comment]
Still not working.

**Comment by ZombiePower** [comment]
I know...we need tpneed to make a buikd first

**Comment by MCPEPIG** [comment]
@ZombiePower  I've tested your fix, doors still won't work.

**Comment by NML32** [comment]
I compiled the latest and doors are working!! 
Thanks for fixing the doors.
Iron doors don't open.

**Comment by MCPEPIG** [comment]
Iron Door aren't  supposed supposed to open unless powered.

**Comment by thebigsmileXD** [comment]
Iron doors dont open. Currently i am working on adding something to make doors open with redstone. 
And i know doors work. I fixed them some releases ago ;)
Now i made them crash again lol

**Comment by NML32** [comment]
@thebigsmileXD thanks for fixing the doors you made a lot of people happy on my server.
