### ISSUE TITLE
build 294, lot's of new items do not work

### ISSUE THREAD

**Issue by carstenberger** [ImagicalCorp/ImagicalMine#174]
build 294, lot's of new items do not work, cannot be placed in world

**Comment by keithkfng** [comment]
More specific please.

**Comment by legoboy0215** [comment]
Like skulls

**Comment by TahaTheHacker** [comment]
classes missing.. D:

**Comment by Rodrigo294X** [comment]
some of the doors and Redstone items also do it

**Comment by NML32** [comment]
trapdoors disappear

**Comment by NML32** [comment]
I compiled commit #306 and Snowballs are working.
Bow and Arrows are still broken (don't shoot arrows)
Tested in creative mode only.

**Comment by legoboy0215** [comment]
They still work...

**Comment by GAalexandres** [comment]
Furnaces still not working, for some players work and for other not, they have to break and replace the furnace to get it working, but after a while it doesn't work again. Is it "normal"?

**Comment by thebigsmileXD** [comment]
@GAalexandres i can see furnaces, but if i open them, the game crashes.
Bows work.
But trapped chests turn invisible..

**Comment by GAalexandres** [comment]
Same here.

**Comment by ZombiePower** [comment]
Fixed?

**Comment by NML32** [comment]
@ZombiePower the 1/2 door bug still exists.

**Comment by matcracker** [comment]
Somethings are fixed, check other issues
