### ISSUE TITLE
Respawn page Glitch.

### ISSUE THREAD

**Issue by EnderKenji** [ImagicalCorp/ImagicalMine#196]
Sometimes no show respawn page. Like my screenshot.
![screenshot_2015-12-02-07-49-44](https://cloud.githubusercontent.com/assets/15629214/11518099/7e02a018-98c9-11e5-9397-b6a4b6c9a984.jpg)
Cant even chat & move. Stuck at spawn.

**Comment by EnderKenji** [comment]
This is after the dead. No respawn page & cant even move. BTW, Hunger working great. :) Hope fix this prob ASAP

**Comment by keithkfng** [comment]
Check out my gitter message to you.

**Comment by thebigsmileXD** [comment]
Not everyone has/uses gitter, please post that here ok?

**Comment by MCPEPIG** [comment]
This hasn't been fixed yet. Sometimes when a player dies, the respawn screen won't show up and when someone tries to move, they can't.

**Comment by EnderKenji** [comment]
Others plugin detected onDeathEvent. So is not MCPE Cilent prob. Maybe is PM.

**Comment by robske110** [comment]
I have explained the bug very complete in the issue #185

**Comment by keithkfng** [comment]
This should be fixed by @ZombiePower very soon.

**Comment by EnderKenji** [comment]
When new build will be release?

**Comment by MCPEPIG** [comment]
Can u check if the fix works?

**Comment by EnderKenji** [comment]
How to test?

**Comment by keithkfng** [comment]
Get newest src folder, then run from the source.

**Comment by keithkfng** [comment]
Get newest src folder, then run from the source.

**Comment by EnderKenji** [comment]
Idk how...

**Comment by XiangZhao969** [comment]
Still getting that creepy error :v

**Comment by ZombiePower** [comment]
confirm it first :P

**Comment by MCPEPIG** [comment]
Already have...

**Comment by EnderKenji** [comment]
Is back

**Comment by EnderKenji** [comment]
Glitch is back

**Comment by robske110** [comment]
Reals?

**Comment by robske110** [comment]
*Realy?

**Comment by robske110** [comment]
Wich build?

**Comment by EnderKenji** [comment]
487,,

**Comment by robske110** [comment]
Try this: https://github.com/ImagicalCorp/ImagicalMine/blob/master/releases/PocketMine-MP_0.13.0dev%23517.phar

**Comment by thebigsmileXD** [comment]
Please dont spam so much, theres an edit function!
Also, if there would be some players on my server i could also test..

**Comment by Tolo0** [comment]
Hi thanks for all the new builds thst keep coming. Your doing a great job. Not sure if this is a known issue but effect. Speed and doble hearts don't work. And roses and those pink flowers. Doble stack when placed.

**Comment by robske110** [comment]
@Tolo0 Please start an new issue for theser reports!

**Comment by Tolo0** [comment]
Sorry. I'm still learning.

**Comment by EnderKenji** [comment]
Latest build , please fix. This never fix before...
