### ISSUE TITLE
Speed effect does not work.

### ISSUE THREAD

**Issue by legoboy0215** [ImagicalCorp/ImagicalMine#201]
^^^

**Comment by keithkfng** [comment]
Sprint? Double tap forward button?

**Comment by legoboy0215** [comment]
SPEED -_- Dude, read my #TITLE.

**Comment by MCPEPIG** [comment]
Same with slowness.

**Comment by astersx** [comment]
You cant use speed or slow becouse of sprint option ;).  Even shoghip cant fix that.

**Comment by thebigsmileXD** [comment]
Sure? Lol.. I'll have a look into it tomorrow

**Comment by PeratX** [comment]
Don't be silly!I have fixed it a month ago!Check it in Genisys!

**Comment by keithkfng** [comment]
LOL

**Comment by MCPEPIG** [comment]
Then why not fix it here @PeratX

**Comment by thebigsmileXD** [comment]
He's busy with exams

**Comment by MCPEPIG** [comment]
Made a pull request to fix it.

**Comment by Tee7even** [comment]
```
I have fixed it a month ago!Check it in Genisys!
```
If it wasn't fixed here, then what does Genisys have to this issue?

**Comment by MCPEPIG** [comment]
Don't understand you @Tee7even
