### ISSUE TITLE
Suggest: Add experiences using the available plugin

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalCorp/ImagicalMine#205]
I think we have a place where we aren't using it correctly: the PlayHarder plugin by @HmHmmHm. We could implement the Experience, Experience Orb and also even the perfect Hunger for this version of Pocketmine. If @deotern implemented the Hunger from Katana, in some way, it should work with the Experience from PlayHarder.

**Comment by Gamecrafter** [comment]
@XiangZhao969 You forgot to follow me! :P

**Comment by keithkfng** [comment]
Seriously... @Gamecrafter... You didn't read the "this isn't a forum, it's an issue tracker" part of the README file? Not like you...

**Comment by SavionLegendZzz** [comment]
hmmm this seems like a good idea why not go ahead and do it(by that i mean assign someone)

**Comment by Gamecrafter** [comment]
@keithkfng Hehehe I'm not the only one... You guys use the comment functionality to talk about stuff too!

**Comment by thebigsmileXD** [comment]
Daz true :P

**Comment by Gamecrafter** [comment]
Wups never mind he was already following me. Anyways, if any of you guys aren't following me, now would be the time to do it!!!

**Comment by keithkfng** [comment]
LOL....

**Comment by thebigsmileXD** [comment]
Command is done. https://github.com/ImagicalCorp/ImagicalMine/commit/691270c723bad9107fde8c3f40b998e2653238a0
