### ISSUE TITLE
When I break leave I crash

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalCorp/ImagicalMine#215]

**Comment by EpicSteve33** [comment]
Why was this closed

**Comment by ZombiePower** [comment]
It works

**Comment by EpicSteve33** [comment]
I still crash

**Comment by deotern** [comment]
@ZombiePower 
https://github.com/ImagicalCorp/PocketMine-0.13.0/issues/212
This bug is exist, check Crash Dump posted here
