### ISSUE TITLE
Jumping issue

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/ImagicalMine#224]
When you jump from a height going outwards eventually something stops you from moving forward and you just fall down.
Tested in SMode.

**Comment by deotern** [comment]
This is typical Anti-fly system implemented in Pocketmine :) I already looking into this for days, it included a code to setMontion keep dragging players down when air ticks is exceeded at a  limit... Un-fixable, u can only choose to remove Anti-fly system to fix this "bug"
