### ISSUE TITLE
The "door block" and "door" had been switch

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalCorp/ImagicalMine#227]
When i used some of the "door" in the creative item, it turn out to be a "door block" (half the door, i think). And when using the "door block" (that half of the door), it's changing into a full door. This problem just happened with all the door in the newest release, not the default door. Please check the error, tks :)

**Comment by ZombiePower** [comment]
Thanks for the reminder, nearly forgot about that one lol

**Comment by XiangZhao969** [comment]
Well, at least you remembered, hope that the issue will be fixed soon :smile: Waiting for good news :wait:

**Comment by ZombiePower** [comment]
Waiting to get the approval :P

**Comment by XiangZhao969** [comment]
That's ok :)
