### ISSUE TITLE
Skeleton Heads are duplicated

### ISSUE THREAD

**Issue by UltimateMcraft** [ImagicalCorp/ImagicalMine#230]
![hr5](https://cloud.githubusercontent.com/assets/6726237/11613178/d279068e-9c28-11e5-9d03-dfdc8f10062c.png)

**Comment by thebigsmileXD** [comment]
How many times: READ THE EXISTING ISSUES BEFORE POSTING. 4th DUPLICATE! #CLOSED

**Comment by ZombiePower** [comment]
I think, they are still the different heads, but have the same image in the inventory? Can you please confirm that by clicking on each one of them, and read the names.

Thanks

**Comment by XiangZhao969** [comment]
I think that's 2 diffrents type of skeleton head :v

**Comment by thebigsmileXD** [comment]
:stuck_out_tongue_winking_eye:  fixed

**Comment by UltimateMcraft** [comment]
Hi, Its still duplicated the skeleton heads :/

**Comment by thebigsmileXD** [comment]
Its not on iOS and win 10 Edition

**Comment by UltimateMcraft** [comment]
I still see it on android, not sure about win 10 and ios
