### ISSUE TITLE
Server Stopping Randomly...

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalCorp/ImagicalMine#231]
Error: strlen() expects parameter 1 to be string, array given
File: /src/pocketmine/utils/Binary
Line: 102
Type: warning

Code:
[93] 					$m .= self::writeLShort($d[1]);
[94] 					break;
[95] 				case Entity::DATA_TYPE_INT:
[96] 					$m .= self::writeLInt($d[1]);
[97] 					break;
[98] 				case Entity::DATA_TYPE_FLOAT:
[99] 					$m .= self::writeLFloat($d[1]);
[100] 					break;
[101] 				case Entity::DATA_TYPE_STRING:
[102] 					$m .= self::writeLShort(strlen($d[1])) . $d[1];
[103] 					break;
[104] 				case Entity::DATA_TYPE_SLOT:
[105] 					$m .= self::writeLShort($d[1][0]);
[106] 					$m .= self::writeByte($d[1][1]);
[107] 					$m .= self::writeLShort($d[1][2]);
[108] 					break;
[109] 				case Entity::DATA_TYPE_POS:
[110] 					$m .= self::writeLInt($d[1][0]);
[111] 					$m .= self::writeLInt($d[1][1]);
[112] 					$m .= self::writeLInt($d[1][2]);

Backtrace:
#0 /src/pocketmine/utils/Binary(102): strlen(array Array())
#1 /src/pocketmine/network/protocol/AddPlayerPacket(68): pocketmine\utils\Binary::writeMetadata(array Array())
#2 /src/pocketmine/network/RakLibInterface(203): pocketmine\network\protocol\AddPlayerPacket->encode(boolean)
#3 /src/pocketmine/Player(937): pocketmine\network\RakLibInterface->putPacket(pocketmine\Player Player(2889), pocketmine\network\protocol\AddPlayerPacket object, boolean , boolean )
#4 /src/pocketmine/entity/Human(237): pocketmine\Player->dataPacket(pocketmine\network\protocol\AddPlayerPacket object)
#5 /src/pocketmine/Player(346): pocketmine\entity\Human->spawnTo(pocketmine\Player Player(2889))
#6 /src/pocketmine/entity/Entity(1488): pocketmine\Player->spawnTo(pocketmine\Player Player(2889))
#7 /src/pocketmine/Player(3499): pocketmine\entity\Entity->spawnToAll(boolean)
#8 /src/pocketmine/Player(3526): pocketmine\Player->checkTeleportPosition(boolean)
#9 /src/pocketmine/Player(794): pocketmine\Player->teleport(pocketmine\level\Position Position(level=Lobby,x=-45,y=7,z=133))
#10 /src/pocketmine/Player(738): pocketmine\Player->doFirstSpawn(boolean)
#11 /src/pocketmine/Player(1686): pocketmine\Player->sendNextChunk(boolean)
#12 /src/pocketmine/Server(2518): pocketmine\Player->checkNetwork(boolean)
#13 /src/pocketmine/Server(2237): pocketmine\Server->tick(boolean)
#14 /src/pocketmine/Server(2115): pocketmine\Server->tickProcessor(boolean)
#15 /src/pocketmine/Server(1716): pocketmine\Server->start(boolean)
#16 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string /home/epicsteve33/Desktop/Servers/KingdomCraft/KC/, string /home/epicsteve33/Desktop/Servers/KingdomCraft/KC/, string /home/epicsteve33/Desktop/Servers/KingdomCraft/KC/plugins/)

it crashes whenever new  players join

**Comment by EpicSteve33** [comment]
players cannot join because it crashes whenever they join 

I might have to close down until this gets fixed.

**Comment by thebigsmileXD** [comment]
Uuhh.. I use the latest build and my server never crashed..

**Comment by EpicSteve33** [comment]
I have the latest build and it crashes whenever new ppl join

**Comment by EpicSteve33** [comment]
and if it doesn’t crash then this appears in chat 

01:08:35] [WARNING]: InvalidArgumentException: "strlen() expects parameter 1 to be string, array given" (E_WARNING) in "/src/pocketmine/utils/Binary" at line 102

**Comment by keithkfng** [comment]
/home/epicsteve33/Desktop/Servers/KingdomCraft/KC/plugins/
Plugin problem.

**Comment by EpicSteve33** [comment]
Lol sorry
