### ISSUE TITLE
Chest dont open 

### ISSUE THREAD

**Issue by MrSwa9** [ImagicalCorp/ImagicalMine#232]
hi 
i try lot of pocketmine-MP.phar but nothing results 
for anyone who isn`t op can´t open the chests :(
please help

**Comment by ZombiePower** [comment]
Are you sure... It can be a trapped chest

**Comment by MrSwa9** [comment]
no is trapped chest 
i try with two tips the chest and don´t open

**Comment by keithkfng** [comment]
PurePerms or other permission plugins? It works perfectly for others.
