### ISSUE TITLE
ImagicalMine 1.0dev - ISSUES/PR'S - README first before submitting.

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#24]
Hi, it's Keith from the Imagical Corporation.
While you might think this repo is highly helpful, there may be a couple of bugs. You can submit them here. However, try to be as informative as possible, so we can try and fix the bug. Make the title a short summary of the problem(e.g. if it's about the creative inventory hot bar bug, make your title "Creative Inventory Hot Bar Bug"), then start providing your information on the issue in the description. Please don't duplicate an issue that has already been submitted and the team has been trying to fix.
As for pull requests, they can be helpful as this repo is growing hour by hour. Make sure your title is again, a short summary, and the description being on what you fixed, and how you fixed it. This will help us and you improve our coding skills. Please don't duplicate a pull request that has already been submitted or merged.

Well, I think that explains a lot. If you have any questions, feel free to post it under this thread. Remember, we're third-party, so don't treat us like the developers and creators of PocketMine! We're only voluntarily helping out the PocketMine community! Enjoy, and we'll try and keep the repo updated!

------------------------------------------------------------------------------------------------------------------------------------------

Team Members: If you feel this post has an error or is misleading, feel free to edit the post to suit the community's needs.

**Comment by ZenaGamingsky** [comment]
There is a bug when you select a item you get a shovel and port some of the block to mcpe such as different doors and fix double plants

**Comment by keithkfng** [comment]
Open a new issue please.

**Comment by DJTommyMurray** [comment]
How can we get a 1.7 download

**Comment by keithkfng** [comment]
Read. It's getting too annoying with these questions. I've locked this thread.

**Comment by legoboy0215** [comment]
keith, please block ZenaGamingsky from the repo. His PRs are useless. Even on the official one XD https://github.com/PocketMine/PocketMine-MP/pulls/?q=author:ZenaGamingSky

**Comment by keithkfng** [comment]
Will do, thanks.

**Comment by legoboy0215** [comment]
Thanks.

**Comment by PocketKiller** [comment]
also, tell them to post the crashdump using hastebin or doing a code block
```
example

```
the code block can be made with 3 of ` and closed with 3 of `
so the when posting the crashdump it won't mention other issues and PRs..

**Comment by PocketKiller** [comment]
also, tell them to post the crashdump using hastebin or doing a code block
```
example

```
so the when posting the crashdump it won't mention other issues and PRs..
> i can't tell you how to make a code block because github doesn't have plain mode

**Comment by legoboy0215** [comment]
```
```
```
