### ISSUE TITLE
about Door

### ISSUE THREAD

**Issue by ibookcc** [ImagicalCorp/ImagicalMine#243]
Some doors, placed only in the upper half, and the lower half is transparent

**Comment by NML32** [comment]
This has already been reported #169

**Comment by ZombiePower** [comment]
Yes, get the latest build and try it

**Comment by MCPEPIG** [comment]
and now normal doors are broken 0.o

**Comment by MCPEPIG** [comment]
I mean oak doors

**Comment by keithkfng** [comment]
Seriously.... STOP DUPLICATING ISSUES.
