### ISSUE TITLE
When i tap on iron door server crashes (release #451)

### ISSUE THREAD

**Issue by MasterWolf** [ImagicalCorp/ImagicalMine#247]
Info from crash dump:

===BEGIN CRASH DUMP===
eNrVPA1z2zayfwWnZN7Z9/RFSv5Sx51xbKdJ6yR+lnO5edVNBiJBCTVJsARoWe3kv9/uAvyS3MRO
/O710sYmFsBiv3cBgvm9Y2QiOhNvPD7a94b+8KjbEXmu8s7k945ZZ9DVOf94fnX17qrT7SRCa75A
2ClPU2VYxrWGHzlPhBE589l8zXIRiVykgYAJkYxx9EDnwSBTwY0wiUzFYB7D8+BMwTLdTgyQzsT3
xp+6nSwuFjLtTCIea9HtBCoUSIg/3AMsM4P/fYIp/nDftW3rAFr0cOjAuTBFnrLn8/l3BD8iOA32
hm6w5xEwK+axDFhUpIGRKmUqfZ+F3Iid58j+7u801Hd4ZWTB7Pj4mF2IWxFPJi8u3p3+9PH95dnJ
9fnHt++u3pxcuFmjimiY95fnZil173upT2ChW2lE+GJ9JUJtVCp2dt2UcTVlZtyEhTC00s5u7/tC
i9dGJO/SHersMmxNJievr7psuEu8ehui8kpRPSepv1W5WbJjViOfylDs+LvfscHgB2E0M0vBaKhm
PFdFGiIkIVQHLVRTVdyHauToOGwNPufabI/dc2OPWmM/iPvGjonEN/xGgIlZsTGOouSoN0TjD5sC
35g+3KXn1+HOLmlPizgiye3+DmivRBbzQLCVBJYClSRgCfNc8BsGlr1UIaH3Pq8cLcwLJH975S5L
xYqdyHwHHsm2Ld++38C4TbK3y2SqDQdfUhFDd7FW4o8a0x5FivfHpDQt71MHfNHkIJDO5OfOsyHb
2Z2w2n9ns6nIb0Xe+z7IuV6eFUm2M1cqFjzd7fyz21mIVOQ8Rs+FURq1M+l4/f1Q3MJS80LGYWcy
BG/PlVGBgoGjw26HZ5KGeaP+EIYtpIHm8IF/YELOb2I5xzn9A8JQpBxDW+dCpsUdA3HweKnAskb9
cX/43+yZx6ZvLtnl1fn5m8trdl0I9lbdMs9j3uFkeDTxDtlP02vmD70xOEJyexADzmyZAca9/n7f
h9ZvIgVOOj40h7bzo9LligCgBk/DXMmwU4U3jYK5JGn+UPA8xKYjtQntNoTn90EuAOHgcSrXqJU3
oAgQfwRx98fLtyh2EuDPKMEhkAMAkfJ5LAC/yQuIpqHIgF6cDH1aReasCUg4Bt4NtLNZm6JYcWT4
8t30+sO7q4szAK3EXEMwA+jSmExPBgPQ3LKY98GLBm1sgwayAcrjtAA3Tk7Az3RDCE1oQwhei/24
CLh/mAnT5tz/es4by85mbxD2eH4rqgZNJoDT80ClKlmfXL5uMNoAtpU97B+2lQ2xbg5/W7wOyeaA
Z/fbr3579Hvk2iPXHrv2GNpfKSJHxmwmLOVAy2zW4uJzAkuLOG6IoqB8e484XMemSPz/P5E0NfUY
8VhOahFVnD1cTKdcy1RtS8nB//OFFBAjlYwqvh4uoh/VfFs+CNwUzvg/wql+UfNKGpaLB4ji78qI
K7FqZ5MGsCEKYKUlhouzfzxIBKOvD62wxGxWU/Og8OoYO4llKznYdrdVWFgKGyz9Lw9e8eDmyVID
LWqpPo1hy/Mo85yKON62T4JuGuj+lw30i2x8pRtCORxXZueIewSPS5XdwyNC/0w8Aj01j5a4h/P4
Xhf5eptJC24b5HCzWPt3clkgQRWbJXkP4PNFDmMgHEOx1mCzCW1z6W2o8vxWxVMg8sncrrH0ZsiY
Xp9cXb+/3KrHoBxbrVZ9AaQg1r65qevMK57ebNeZFrqpv42AApazWMog2wqUX8lZiW82axDxqLAY
wkbsRyWb9VMNa3Mz2rTGJw+P5cKPDpFTmWSxeKUS0eCjAWyW/32/xcRZYdTNU+mjXhL2ts3lH8DD
6ZKblzJue00DuOE0DwgM99QeX7unqcgAS2uS9CDdLNKp4abQLd1UwM+UFHfZOjBF8nTaKRdF7TQI
eLCFnQBtWxZGwLZ2Djb1Y3esuI1l14LjKdi9oeBbvKcmprQ9R9gXQt3G1rOmdNDAgmGdp3hK2Azp
DrJxwtD5Yln4LeWfW/QxQe4naS7z5t7HAZp0jzfofqpzELvUbFYt+QB6r3l2rc6aBJeQtqS3ZP2S
x08WygzPjAqB8nrthzp7u4irQBsBrD9qE38HPXO5AGD51NKB941+TzVbg5YvHsmAWzhC+qkwWqW6
r/LFwJ29DSpUwPUrGYprvmgwXUL+8NzpA0+NCG9kHEM/2zmhnl0YPxWpyk8V9KZGsZ3zUBrseCp7
bK0LcdARimpefEkqW1HiA89zCQwNlo7d+iwO0Jt7DuMsuG0J/9flX3PpslCqCPmqOvBFrFT48h/N
UOggmza+Uf8t1VqmiTdOAvZf7HQ9F/lpMRe9Vz/ZrPBUHNfLzGZzpCy6g8BZkfgAP8Yq7FQlCSfU
FZstcJvX8VbKk3ci/qFYH+w9VUiqMc5mTUoekwsuBQ9EVMTTjK+aRW8b3qpJxp/NZ80TnG/Jay0C
HsPRleDxtWxVvhXoC2f/PxQQB3iRiNGe91RKKtd+dA0vX+aS3oNUbJSQzU3VxvnbhYxPc6mzta+O
BifpQsSK/V2GEJmeLIM4Sh6jlulpLHh+wRfNtNAANpl6IQz/uHXoOhX5Qqw/nkGk4mmLlcNvyIVN
pJAQK4Kaz8jlSxWHWO63oZ+NmI5zLM9OuRaX5w3OG8BNdW68o+CxLOL1dsLrlu/0vpJzi3c2A1KT
ACjJxGPU+UIVabCml6HNgNgC/2GyP+N5kUruHba4Ovp6XiqEENYbFLRbX/HeqcI7aCFCc07V6hWP
+ca7lha4rdjDHo+zJd9IgBtJzp6D+98ScGRkIHeCoTZIabceqGEe3JwJ3trg1bAvHOyc38iX6sk2
OtWyuN2pKXjUNvWViLPWUcJW1+aJ6ujLfvjFo8bGlvEBrrgkQr76LSmPxS/0VhzQNa4F9coS3eRC
DBI69xtscV8JC4rYbEtMBNzMnsPt3ZbMwT2+rWwDPNpc5zzVESllGqtVo3muNewEJI81hM5ahJFb
fDbTRPAKCC73/Y74B27Xtvh3oLbF723WDp8N098shA8qj0PYMBsRmM624Wgg0nL8bzEdJ5FPePWi
vKRWskE3WPpZrsCojBR4U+PZZdVisJOL5ILhBbZZPkuf4fWQMxGwQ+Z7E/9o4h+y99eneDtkD/st
uh7q4nhWDIf8ILa/jl68mn5g9nn+9hy5/Mk1o7+5hxH8GnsH+NOnZ9+jnz79HOLP4T490xjPQsb0
HNBPwWoUkFyqDn/0lwZ1mcrNsXfkjXwELoDWRIXieIithN+BEPkaBHS8RxCNBW0vs7oEczr29hG8
WoJyYqnNsYoiBFhj6f1aiHx9DCG8BuUBzHKjQqGDXGaE6M8noESZ8M+rN7xxeJyqPOExEQtqy9e9
WCbSHPt7+28QCPW66RV0c7EUOV7RhGJAOL32eLCU4lYkEJa0U9StFKteKO0ds2PSL48hjvWiWC6W
lYqtKfBUAgXlVAtL1LwELHkeBiqvls9uM9cTyiiSQRGb9bG1PLofZlTe08IYmS70MbGAt9esC60w
jNQwLUTYGELyODt/efL+4hqhaGd9vIoK08Ljv9EfYKQwqqf5rXBUkOH2mpYbqRykU/mBg+JFriqw
9NdJjJGBYbxiAQWFIqfqhGIDAxysPnrtvbmEWMGul0ILVjLHeC7oVqVKBV6v5IYF9vrsXDCZBnER
ihAe2FZMQlxTlcDMCBFs4tQ8El2moCfXiNLdWFyrIne4mIwY8CYjSSuAenJwZojEgPitWFXoBqGI
OChIs5VK/2oYzzLYPDAUYQLMBmAUayCf4W1Cy/dqKVJWZIuch4CgP0vRWi2yySxlz66XEIl7MYCA
ipini4IvBMMLvSQyZ9laQptu5snfbAEIU0+XInBctCcCAWVKEGl/JW9kJkLJ6XgPW4MLUO5HFX18
PX33cX901PM/4jwQY4VowmaQ3RazDi70YSlQdswooCcNGXDJtMlJvgZzGpShIDfqJmkSpUAHPAlD
Kg3FrQwEW0JOiknJCSC2dlUvSdcsAa6XhQkVeo29R43E2JuULIiVFqEl6wQ9kKGhAiXMZTZ2Kzn7
H4yxMIRibZnzJgyzNE6cLmEeRyvVCqhxq1hVcYeIFRqMEDI6GAJxd3L52t1xRTnVHT0gaw5E1ejP
KaqXeIBjhu7OwFzBIpDU+Zo5O4LhLgdUvbUYnn2QIGiVgknxMGS50NbykEywNbxyy3WRU6BiYG9z
gfIAoYtfCx6jOhbyFsbe8hiS8o5bElLxLiC360HuEZjteqDNxULkE+jFld8WyRykDe50otdpcM31
DVh8fgMO1Mf+96AEss+SSRy1zBUEUjAJGK27jGITczEMTLaL94VBahprLhILVDB0hxi2ZAENIdxT
MhngB5wrV3cQSyGPrpEdMvW0Ig2lasl5HaGH4hD0xC6T5q8gOZPTrFBgYiYr3JjLdoAD0DPzUSLE
Q89xOSFM6K02i5Cv/hCrOQgWKztmwYySC8akRCz4fG2AIDa1pAxpcalRvdbTgaeVJMJI2AwTiEtS
DqRJLpEEc4EwBUE8JVQRxIhyRat+YKYgo10o4EOha6DMYJ0FEWmz3oQNZxQqKCobCDU8/JOTj4Xw
Z4jH5PlNxGujMlrfhaqKHodNM3ApzJEQZRw1uGZJkjf0x5aqS5FLRekIfVHjggEFZEdd5W8eLAWh
JkQboxE98AdhPY3CuILtTwoeCnLD6PBHYrXihOwcU4RHX7fDZpRwEQd4X+3JNhzhCu8whGCGo+H9
7cHIttvLgAgzEWAitF84IK1WxnZuxQBIUmS6ZnM0dHzq3XsJclyPLNcLns9B/71AxbEtm9HD7pUq
mROS4uYwNwd8N+FpQSm3SQWUIwXYwm63jAkbxuCswcbVKCpjQ1JbWZ+9s/mOWmARS1XEYUWIhAiy
SllNOtoty4hyYHB/OLQ8smcvyRO2YiPZip1dMRXlKilDLM51/b1mVGroFJhwqts0hXvspzEPty/B
skhvtJX3BVk9BkQCImW41URumC2Hu+SeORQg2g7qYQ2AtUyNC1GVanaOcrTv6DxTdtqm+uw3ROW0
Jga7ihv2BDxTIuoFUNYLy7WzhXIh7Kiy92dRzdJUGNRFVbqBacQ2E865gX0DFiIcq1xIgGBPLiqR
A9rC1PXaYDQXVU6kcPOsGb7KHnT8fG0Qd5f1vIYxY+6jZXumJAXCyt6+jSp1rqXdACa60IY7p0A7
F4COpj57BZsZEO8x1MJguKeX77swFyiYQ/xZydAsbdQm/67Q9wj9hB24wqAuGTQJpjG0z05C8Kcl
j6MBfpZEVUwowM7cQrCktT+VNh2yys4NXI066fwOnQ/LIB53rWPjwh9kClUksAVmI8i0Mde/v0wv
y0qhrtmxCMJJdO0WC/Y067lmsybD/fm8WExc0fE987DYcJkFq0rqLitKTXFsKcpKc+ZUAWmkrhM1
G2i6p9Nlg0VgRUtv/RqLlru71r5BlEUk0g2c2B0TDXXmheySwgMQoiELc1N6dsqEJdC1cPsJYIjO
sZDcW3x9bIMSb+GHyIk7MtNYHoRptqkhHyXVPXv77vp8wijqwv9BAZurFDZXhIgO9FB1RJ5buSKv
UvFJS1sB7CMgkjheyYooJQElaDUGLccfuhSCocxmJjQj3Owi3KUj5/VtcBnDbC08rT7241o0Ftvx
wFHuWaXLfOjw7usQJujvktNq0aSCzOEaMePWyh0vMQGBya6Hqd9qkjax9e4WAwHtgrB6wnDA4xVf
a4vb4WnYUSt+kxmdJKpImwlAu5qtJALJR2y4ZcAjFnicsPEfT3WfQhLtFkc76zDvyL93NllXKuw+
ci4strmIMBLRGQpGLFRDhdWerDRCn418U34LSRfrO4nbZYHbr2ztjgZcLqoKGgoUEZ2DlmHRhbGo
iGmY0mCqPXRRGdhUQluwHPfjYBiAthTVLwp3QtY3NE/QVhKKlZhgKv43lIECLZXxht8xvikX2AMF
lB9qe2jrgoz0ioey0I1pTg/cUUdOaqc6u8PxUK1gTMIjLHcmVhMIW23B7SJ0GFRnQUt4vbErae9v
E+/i34pL2qPDfrwQTr9uPrk9wXsalDVhh1+FLVNZETts7hlT0wbiWUo+2QPpIdH2oK5HdqRRkijK
BGK1wSMXB/VceMATsgmzxV2pUvySs8ig2LEVnzVICh620HC4AMsBznILItI9bK44LlQBCcaTuQTL
t0Pc4Zzdo09sMMLjBPyalFmozbHOSKz1ukq+Cm5o1z084GlDqnTSgmbLTKaRqs0APwWd2CX7jfM+
KISIvlSl6wTLfPIQDfLVFaG4b3HdrO4mgsHWOOOLBWQfdzhQHbtgjYjf1N7cz42lB9Hp++hBeVlT
JhVvzgabsL0Tq4A87bnkXFeABFVZ48DoFM8M6RBLxCrDbNWFNnCAJ3SmLMUy+qI/FyBsyE8p5nkc
5FJrgdoBf2wgYe4FVKOGKKDg1MYmuDLgOWyoIdtd4tcbQsGbXPeIBD/KsZUvVEoc861tYMEC+B0R
k5Ia6gJjx53yhP2Mjz1IMl3aOv8TMdooWJYhzdNWYqLcL9hNW3mGTbux+w5vaXNLWUxTxYBsJ1BI
SCDUpfgG6bQqEUBPDI+80XUpJdWrTdjLi5Prif/dQXfv6M7rju5GXf8777sQMrGNWjv4CizACHN8
OGQLsG9tW+O9XTrcFndGpCgQug9xCnmo8UUzmlCjCelgUf1rDFmAQ11D/xpLI0b2c+ue/bL7N/v9
tb23Pg8Seidf/lMOPAbP4XkNsP+6RNkq8rhqRO42PaD27NvbyGRV7yKpn5fgvfbFPgz6RVffg+E7
z2Ruz3KrwVATrjNTc2A4EhQ22J1eXtCq+JwFUMvVc9fAMH3s7Z7YHn7l4yHnrIevAf3h3nAEj89f
g96i0cFI8L0w3NsbHR7se+PhPj8c+j4fzw/56GA89g7n/ngo2HNY6XKJYqk+38yUlne10N1m3Q3w
kNErEbmdJkBpvUOxFwUcKtUxLDuMDg6Cg8PD/b09WHp05I/EaDg/OjgKQ1pPLxNVi1CTY+k2p9IK
HwYbdSNSyDN5Bfkg+A1EBCuo/h5A1pxeknjuotpvMrMtvz/ufPr0L7qXzno=
===END CRASH DUMP===

**Comment by FunnyCrafteur** [comment]
Same error with door
Fatal error: Cannot pass parameter 2 by reference in phar:///home/gsp_6/srv5.hmserv.eu-19132/PocketMine-MP.phar/src/pocketmine/block/Door.php on line 214
[36m[22:38:29] [m[31m[EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump[m

**Comment by thebigsmileXD** [comment]
Build 451 and 452 have this bug, i am working on that. Please try fencegates.. I am sure they'll also crash

**Comment by MasterWolf** [comment]
Ok! We will wait!

**Comment by Taki21** [comment]
Got the same error!
Cannot Pass Parameter 2!

**Comment by thebigsmileXD** [comment]
Are you now on the latest build?

**Comment by FunnyCrafteur** [comment]
fixed with last build !
