### ISSUE TITLE
Redstone Torch cannot be placed.

### ISSUE THREAD

**Issue by BlackShadow1** [ImagicalCorp/ImagicalMine#251]

**Comment by aodzip** [comment]
which release do you use?

**Comment by thebigsmileXD** [comment]
What build?

**Comment by BlackShadow1** [comment]
Ehm.. Lol ahahah, in other way pressure plates cannot be placed in the last build, same the mob head. Sorry for the error

**Comment by thebigsmileXD** [comment]
They can't because they are gone from the block list i guess. I'll test

**Comment by BlackShadow1** [comment]
Uhm, ok.

**Comment by thebigsmileXD** [comment]
Yup, fixed that.

**Comment by BlackShadow1** [comment]
Good job, i have fixed a bug with redstonewire too.
