### ISSUE TITLE
Pressure plates.

### ISSUE THREAD

**Issue by BlackShadow1** [ImagicalCorp/ImagicalMine#253]
Pressure plates don't charge the redstone if the player is up it. This way i'm playing on the last build xD

**Comment by aodzip** [comment]
And if you open DEBUG there will print *hit on your screen
LOL

**Comment by thebigsmileXD** [comment]
They are really beta. The bug is, that the string "meta" isnt found on line.. 144 or so. Atleast you can place them :p

**Comment by BlackShadow1** [comment]
Yes, but i wait the pressure plates fixing :P

**Comment by MCPEPIG** [comment]
It's been fixed

**Comment by thebigsmileXD** [comment]
But they are a bit laggy. We are working on that ;)
