### ISSUE TITLE
PocketMine Crash 

### ISSUE THREAD

**Issue by MrSwa9** [ImagicalCorp/ImagicalMine#255]
![crash](https://cloud.githubusercontent.com/assets/16043344/11692963/2e22a4cc-9e9a-11e5-9328-10b2e774672a.png)
Hi 
PocketMine crash
src/PocketMine/PocketMine

**Comment by PocketKiller** [comment]
it **might** be @keithkfng or @aodzip they both edited that file

**Comment by MrSwa9** [comment]
its possible correct this bug or i have change the pocketmine ?

**Comment by keithkfng** [comment]
It should work. Something wrong with YOUR version.
