### ISSUE TITLE
Pocketmine 0.13.0 #453 crash

### ISSUE THREAD

**Issue by andris155** [ImagicalCorp/ImagicalMine#257]
PocketMine-MP Crash Dump Wed Dec 9 05:37:16 GMT 2015

Error: Cannot pass parameter 2 by reference
File: /src/pocketmine/block/Door
Line: 214
Type: E_ERROR

Code:
[205] 			}
[206] 		}
[207] 
[208] 		return $bb;
[209] 	}
[210] 
[211] 	public function onUpdate($type){
[212] 		if($type === Level::BLOCK_UPDATE_NORMAL){
[213] 			if(!$this->isActivitedByRedstone()){
[214] 				$this->getLevel()->useItemOn($this, Item::AIR, 0);
[215] 			}
[216] 		$blockNorth = $this->getSide(2); //Gets the blocks around them
[217] 		$blockSouth = $this->getSide(3);
[218] 		$blockEast = $this->getSide(5);
[219] 		$blockWest = $this->getSide(4); //Make redstone activation
[220] 			if($this->getSide(0)->getId() === self::AIR){ //Replace with common break method
[221] 				$this->getLevel()->setBlock($this->getSide(0), new Air(), false);
[222] 				if($this->getSide(1) instanceof Door){
[223] 					$this->getLevel()->setBlock($this->getSide(1), new Air(), false);
[224] 				}

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux pe.infinityhosting.hu 3.14.32-xxxx-grs-ipv6-64 #5 SMP Wed Sep 9 17:24:34 CEST 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ZipPluginLoader 1.1.3 by aliuly for API(s) 1.10.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
LimitedCreative 1.0.0 by basprohop for API(s) 1.10.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
Slapper 1.2.7 by jojoe77777 for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SimpleGamemode 1.0 by MamayAdesu for API(s) 1.2.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
SimpleAuth 1.8.1 by PocketMine Team, shoghicp, ecoron for API(s) 1.13.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVO4ly27iSv4KVU/XsLVH3YSvlqfLYTiZv7dhrOZutHU65IBKUGJMEhwAtK1P59+1ugJfkTJzE
W/U27zDRBBp9HwD1V0uHsWjN+qPR0WR4NBpO2i2RZTJrzf5q6U0Kr1rnd+c3N1c3rXYrFkrxJcJO
eZJIzVKuFPxfxmOhRcYGbLFhmQhEJhJPwIIgjHB2V2VeN5XevdBxmIjuIoLn7pmEbdqtCCCt2aA/
+tJupVG+DJPWLOCREu2WJ32BhAx6Y8DiavzPF1gy6E3s2IymMKKHQwvOhM6zhL1aLF4T/IjgNLnf
s5P7fQKm+SIKPRbkiadDmTCZfEh9rsX+K2T/4C+aOrB4w8CA2fHxMbsQDyKazX69uDr9j7sP12cn
t+d3769uLk8u7KphSTSs+7dXehUq55dQncBGD6EW/q+bG+ErLROxf2CXjMolrrYLlkLTTvsHzi+5
Eu+0iK+SfXrZZjiazU7e3bRZ74B47W+Jql+I6hVJ/b3M9Iodswr5PPTF/uDgNet23wqtmF4JRlMV
45nMEx8hMaGaNlDNZf4UqqGl47Ax+ZwrvTt3bOceNeZ+FE/NHRGJl/xegIkZsTGOouSoN0Qz6NUF
vrW8d0DP7/z9A9KeElFAkjv4C9DeiDTinmDrEFjyZByDJSwywe8ZWPZK+oS+//fKUUL/iuTv7txm
iVizkzDbh0eybcP3YFDDuEty/4CFidIcfEkGDN3FWMlgWFv2XaT0v05K3fK+tMAXdQYCac1+b+31
2P7BjFX+67pzkT2IzPnFy7haneVxur+QMhI8OWj90W4tRSIyHqHnwiyF2pm1+p2JLx5gq0UeRn5r
1gNvz6SWnoSJw8N2i6chTesPOz2Ytgw1DHvP/AcLMn4fhQtc05kShjzhGNpaF2GSP7JUdMIkCJNQ
b1ZS6TBZdlY5G3b6o85w4DzCP2eZKSdMHybOZMT2xmx+ec0+Cp/NRcqOWH86G4xmwxE7PZ/fskGv
P2aPh5O7yQh2Slcp7DPuTDoDGH0WCfDXGsCwZ17eSVXQAQAaRDQoQ55CYV3nmbgWWUwDS3wFazeE
OaCtOHigzBRqaTJ68wbk8IcV5O8oyUGHACLhi0gATTrLIar6IgUKcRG8UzLQZ3VAzDEAt+4MPtct
Cag9YtSWHJmc357c3H64BsBaLBQENYCttE7VrNsFDa7yRQe8qUsrDaPdCgtwPw/jNBKXJq/U+d56
UWMeeG8wfpZred/gu/fjbDe3BUPfJsPyfX01v/14dXNxVuc8yaMIeDr3ZCLjzcn1uxo/NWBdkaCh
zlFTkRDXFvC/HY7aqFH7d1D+7dPfoR0P7XhkxyMY/6AkLBmuKwzlQIvrNrh4hij+J0yN2i9grshq
8th+07Ru4KQpFB6FebRpWvdPqHlrd9e9RPj3WjWPxCee+JkE4mrljWNdugtliOjGkPhE1t3mt7KT
uYiiXUMh6LalTL9tKd/0+bolfof6IV1Gpf4tcc8wgP96dz2PpK57dgmqcwe67Iya3IX/lGqV89/O
XiymlRhdt0bE9+k8/EQ4Vn63RAFshteQyoSnZd3Ea8A6q+CjvMnpxdl/N3g8+nEWAZXrVhtvG/aT
qnqKTcDjXJ5en3drTACfpyuuT0WiGnzWgE0v3lLo+YOM5kD3S/Fa7fs9/rterzsCKEGsHX2PXF2E
MZbjp1DvQTkpaqxtv2nyZ6JyjcMFV1DTrGT6YoGqxOi6u7R8ndtmJpojRbsRBqH/ShGGuGwS94wI
8ytPsAmq8VdAmrz1/97nej/pc3bTZzmcpXwe8TRtJMUCsl3qbWnlk/wkxRT/vVhoVGZn142fTf4l
X4berYjENbSUvJ7Ctt802RluV64vnNsNOuBEp9+jDWt4/5SLXVdB4LanjP5fVG2f5KL0KcPFcwyT
it63IILYHsA0ivLyxVY0bArkksd8c+ILlTdk8hM2GiNGjhhdVxElS0vJ9vh5bJ6uhNIXWLY1s1kF
3fLDZ6Szw59JZ+XGP5nPrL4vOPah27ZM0B9oQf6vwn4E9JQmaol7hvJOojXfqHnK10mNxzq0yeNO
v3y9CqMwZXP4A7348sUiaUp4lUXrupxIUkgS5PCi2flm6r48fTud3H2UWeSf+3gUUkXXrTfNMnq8
zSd2JF7GA70USZir6eSl7DX2ltOJ65pmx3XXSJAAgly3pA07nnfJ9wSdEyB8J+AQsOmLh9v5/Jra
r0tglt0Kjskf6onlKvSwjABTy2BhQ8XDnz0kQKqKAwJL4XceipQkd2tYMDBFgmcXfLmsh6UStt0p
b8XdCwGK9q8CrN5fqsIpN9+14Od3FDW6uhU3Dc3/JqKtgmj71Tey8FOlxDfjVk34zygrVkTIDzdW
33NmsMM9CAtPz7Dx2ToiJNB2nTX89glh/1vCqU7rdmTTesPpykRBi9j6yskh0lU9/fS5ISHBDKeU
SHTIIwVGXktxdfA3TpSMPSpjkCZmvFQKqJPxUh7TYO0LnhsXt24FMXQk34FuESxFh3iY2tq7Lkfs
VCZBuGR4I+dmbrKHJ9tnwmNHrDeeDSezwRF7e2kOtvF9LLV/7Oa9Hp8emj+R4zi/m0fvdiWuIp+Z
UeDYB36KeQYosuMhsN/A8AegQOSGVieF9uC4f9QfDhC4XoEknChU+riHY7xhzBMPXYNvYDb3VqF4
EDGIQR3LhPBgVnVSc0IBmj7uE+n80a5Rx0ODKork2gmicLnSjaU8CWMQaQMWy0UBKOpJQ1AgM6Cm
hMkgQOiKZz6kl3KcPqR2tR8GQejlkd4cE4PmWkTLzFFC4wWEOkZwhJc2DlrwMeXQCqaE8GtT8OLx
+Oz8zcmHi1uEGtN0/sxFtrFbWlAG1VRBDz538J4WkPvH/07/QCK5lo7iD6Jg3WgkTI/HUOiOoQM5
hBTbG+K7h1CsHT80F1HHEwThtUYZuzqbOEJjYxgSmUd2lmd0K0fmxkBwrEp2zuU1mB8DE1KCFZJg
PBN08wilIV5Bcs08c8W8ECxMvCiH2gIe2I6ZI665jGFlgAi2cSoeiDaT8AbMElDaW72NzDOLi4UB
A4WGQUg7gC4zsCYI9YD4vViX6Lq+CDhoU7G1TP6hGTbMPGMoyRiY9cDINkA+wxs3w/d6JRKWp8uM
+3jd5CYoZ4Ns5iZs73YFwd6JAARUQB28zPlSMLz0JpFZnagQxpEE/OFnEiouhWbBs1w0FwIBRSgR
SWcd3ocpFGW8I7NlF0fdC1DknQzu3s2v7ibDI2dwh+tAjCWiGXMh7C3dFm70cSVQdkxLoCfxGXDJ
lM5IvjrjiYq4BrnRa5ImUQp0wJPQpFJfPISeYCtIexEpOQbExpmqLekqEuBqlWtfohuaOxck5oSp
z4RcA04MJaIfRfTX11JrA7nvsP25mUbhJ+CfMrBH384zk9SB4eoEAwLDWAOMMJt72UPI2X+iN8EU
8qoiK1fk7c1XsJCjlSsJ3Fgqjaq5xcRyBUYMqQIMiaQDLZG9R0Y5Vy8cIHYhFTCJ2QXRn5MDF3hA
YgxjCwNzB4tCWhcbZu0Qplt3L9/W6PwI/QcYA5gk932WQdNMlotkgq3itTZXkFAxmjKw14VAgYDS
xJ85j1Cdy/AB5j7wKBds324J2eEAkJv9IMwIjOAOWMNyKbIZvMWd3+fxAnQA7niiNol3y9U9eEwG
ba3q4PsPCiSC9l0wibNWUJ/LHEwKZqs2o0DIbMAEk2/jnTxITWE+J7FA5qR7+jwBz8MphHtOJgf8
gHNm8hGCuxYgAmCHXCUpSUOpGnLeBejhOAU9uc1C/Q+QnM5olS8ws5AVb61l+8AB6JkNUCLEg2O5
nBEm9HbMFNmGfP1tJBcgWCwZmAGD+cWhxpgWiyVfbDQQxOaGlB5tHipUr4kUwNM6JMJI2AwTmsFT
yF+RXIIQzAXCHGSMhFAFEGOKHY36gZmcjHYpgQ+JDoMyg32WRKRDhM1Yz6VQQ1FdQ6ji/r84+Vh+
/Q3xmKl/inilZUr721BX0mOxKQYuhalW+AU1uOcWSVBNh5JyGTqiwt08iuaWtNLZ+rAPxBkfDYxm
OOAMwrgZ5QAJBWEC7glCw9DwNZkaWUJ5FVF6QEc301zK1ogDXK9yYxOLcIcrjB+YHml6Z3cy8mwr
ZJBfKjzMouYTIqTVCNisLRkAMYpUVWwOe5ZPdfAkQZbroeF6ybMFKN/xZBSZog/d60mpki0hKXYN
s2vAcWOe5JSv61RALZODIRy0i4CwZQnWFExQDYIiMMSViXXYlUmWNAJzWMk88ktCQggf64RVpKPR
spQoBwYnvZ7hke29ITfYCYxkK2Z1yVSQybiIr7jWvnfqIammU2DCqm7bFJ6wn9o6LKq9VZ7cKyNv
uo2iaEhApAz7G+SGmeK7Tb6ZQfWizCQHCwgshCpciKpQs/WSo4ml80yaZdvqMx/pFcvqGMwudtoL
8ExZyPGg8RCGa2sLxUb4okzdf4vKTRKhURdl3QemEZk0uOAaOhssQziWyJD9wJ5sSCIHNFWtfWsi
0UKUCZFizV49dhVv0PGzjUbcbeb0a8aMiY+2dXRBCoSV8cRElSrRUt+BWc43sc4q0KwFoKWpw36D
zgrEewyFNBju6fWHNqwFChYQf9ahr1cmZJN/l+gdQj9jU1sVVPWCIsHUpnbYiQ/+tOJR0MXv/qiE
8QXYmd0ItjT2J5O6Q5apuYarViSdP6LzYQ3Eo7ZxbNz4I5SNcg1sgdkIMm1M9B+uk+uiTKgKfqyA
cNEaAr2L1X6SOnZYL8igGxSLfDmzFccvrI+Vhk0rWFLS66KcVBTHVqIoM12rihnrV0WiYl1oyXQO
BtNdeka0ENd8Vdu06CMbTYcoKkikGzgx7RZNteaF7JLCPbxsJguzSxyzZMZieLW0zQgwRKcjSC5W
6coEJd7AD5ET2zld2x6EqXepIR8l1e29v7o9nzGKuvBfL4fOLIHOjBDR2RiqjsizO5fklSo+aWjL
gyYEIonllayIUhJQglaj0XIGPZtCMJSZzIRmhA0zwm06sl7fBBcxzBTC8/JrWq5EbbP9PjjKE7u0
2QBe9J96IbTXOSCnVaJOBZnDLWLGvsweejABgcnsh6nfaJI64Ko1xkBAPRCWThgOzDWFwW3x1Oyo
Eb/JjE5imSf1BKBswVYQgeQjNuwXIDbjIwjm60vtt8ZEu8HRzDrMhKedxWRciTA96EIYZAsRYCCi
Ax0MWKiFEqk55qlFvv6I1MUfIOdibRdiqy2w9Uo39ljBpqKynqE4EdAxbREVbRQL8oimSQWW6qCH
hp7JJNR+ZdjLg10A2kJSnyR2QcY1FI/RVGIKlZhfSva3dIHyLHRxyR8Z35YL9D8epYfKHBqqGJKN
3nA/zFVtmVUDt9SRj5ql1uxwvlEkHac5OX0tX2uRPTzbN4aEDXaVBA3hVVNX0N7ZJd6GvzUPqUGH
ZjwXVr92PXk9wR0Fypqxwx/Clso0jyw2+4yZaQuxm5BLOiA9JNqcGjpkR8D4CMs2UHiC1lBC+zY6
4CHbjJnarlApfimdp1DrmILPGCTFDlNnWFyAZYqr7IaIdIzDNceNSiDBeLwIwfLNFHu+Z/rzmYlF
eJSAX2szAzUp1hqJsV5byJexDe3awcOhJqTMJg1oukrDJJCVGeBH1jOzZad2Vgh1ENGXyGQTY5VP
HqJAvqokFNsW+5pVr4lgsDXO+HIJycceDJRHLlgi4jfr91vcNAlCfOopglBgxpZJxzvLwSrM65lR
QZY4NjtXJSBBZVqJZu8UTxzpCExEMsV01YYx8IDne7qoxVL6zUwmQNyQoBJM9DjJ5tYc9QMeWUPC
7NVGrYjIoeJU2mS4IuRZbKgj87rAX1FopIIfETwhkyiEfGP0cv7IMeGaAVYsgN8SMSuoQSml9VGS
34v6eBnPWPMbktkyxp1MfCzqk/oZLjFXNBKmmyuO0alNe+pImLpeSm+KSgkURwwVRggb29xfY4l2
JQLoieGpOzo1JYVqtxl7c3FyOxu8nrbHR4/99vBx2B687r/28XKZbHEf7+48jD3Hhz22BMtXZjQa
H+Al9KMWCQqCPoY9hfxU+80AGlZtCGliWf4KKvVwqh2oP6NQi6H5mYNjflHx2fzuwXxetPCg3FlV
P6HiEXgUzyqA+VVXMcqzqBwEYaTx+hVQ9829cqDT8u0yrp5X4NXlRz+fVPmhGl7KxwtzPlxOhlJx
k+qKA82RIL/G7vz6gnbF59SDEq9auwGG6ecU9omNO0gdcs4cvK0a9Ma9ITy+eofOOpwOBR/7/ng8
PJxO+qPehB/2BgM+Whzy4XQ06h8uBqOeYK9gp+sVioWukWljqcLHSui2h7cT+sjojQhsAwpQ2u9Q
jAOPQwE7gm17wXTqTQ8PJ+MxbD08GgzFsLc4mh75Pu2nVrGsRKjI3VST09AIHyZreS8SyD9ZCfko
+D3ECSOozhggG04XL3i5iRM+h6kZDTqj1pcv/wvLdN7q
===END CRASH DUMP===

**Comment by thebigsmileXD** [comment]
This is already fixed.

**Comment by andris155** [comment]
Thanks!
