### ISSUE TITLE
Redstone, redstone, lamps + tnt

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalCorp/ImagicalMine#262]
So I put a lamp down, then a redstone block, then tnt, the redstone block blows up, lamp is fine. However now it glitches to a state where its still powered with no signal until you give it redstone (other block updates do not work)

**Comment by aodzip** [comment]
Try the latest code plz

**Comment by InfornoFire** [comment]
ok

**Comment by InfornoFire** [comment]
Fixed, new bug found regarding this, if you place dust on top of the lamp then the redstone block and tnt, it will have it charged without signal

**Comment by aodzip** [comment]
Oh, I set redstonewire can get power from up block.
Is this wrong?

**Comment by aodzip** [comment]
Fixed

**Comment by thebigsmileXD** [comment]
Its not. But i also saw an issue: when you place a powered wire of redstone, then a 2 high row of lamps next to it the top row also glows
