### ISSUE TITLE
Dying sometimes won't call the PlayerDeathEvent

### ISSUE THREAD

**Issue by MCPEPIG** [ImagicalCorp/ImagicalMine#263]

**Comment by MCPEPIG** [comment]
Oops ._. Kept assigning the wrong person

**Comment by keithkfng** [comment]
LOL

**Comment by robske110** [comment]
New bug: Dying never calls anything, except it blocks moving!
Never seen the death screen even with /kill!

**Comment by thebigsmileXD** [comment]
You can't place blocks where players died

**Comment by robske110** [comment]
But the respawn screen never pops up anymore!

**Comment by NML32** [comment]
I'll be happy when this bug is fixed.

**Comment by smyb** [comment]
sorry if i made 3 commits :grin:
