### ISSUE TITLE
Probably...

### ISSUE THREAD

**Issue by legoboy0215** [ImagicalCorp/ImagicalMine#264]
https://github.com/PocketMine/PocketMine-MP/commit/c803dd8e6930fa7bce65d6758758ce3184cfd243

Important.

**Comment by legoboy0215** [comment]
Also, doesn't this look promising? https://github.com/PocketMine/PocketMine-MP/pull/3765/files

**Comment by keithkfng** [comment]
That cheater...

**Comment by thebigsmileXD** [comment]
Hmm, but our Redstone still is more advanced.
That attach class is not bad.

**Comment by keithkfng** [comment]
Tested and crashes ImagicalMine.
