### ISSUE TITLE
Players to death

### ISSUE THREAD

**Issue by ibookcc** [ImagicalCorp/ImagicalMine#265]
When the player killed by a monster.
They can't be reborn.
Will not normal popup rebirth.
(Is that there's two buttons.)
But we can see in the chat.
("sb is died by .....").
And then the player to re-enter the game.
Players on the resurrection of the dead in the place of death.
Other private moderate condition.
If there is other way will also to death.
I will continue here.

**Comment by ibookcc** [comment]
I use biology plugins.

**Comment by PocketKiller** [comment]
i didn't understand you too much, please improve your english.

**Comment by thebigsmileXD** [comment]
You must say :p @PocketKiller

Well, the respawn bug is caused by IM, can your players get slain by other players?

**Comment by PocketKiller** [comment]
Yes they can, so Plugin's fault?

**Comment by ibookcc** [comment]
sorry, i english is not enought good

**Comment by thebigsmileXD** [comment]
Nope. Then its IM fault

**Comment by ibookcc** [comment]
just If the players killed by a monster.They can not rebirth.

**Comment by ibookcc** [comment]
https://github.com/PocketKiller

**Comment by thebigsmileXD** [comment]
Oh.. Okay, then its the plugins fault :)

**Comment by ibookcc** [comment]
is it ?Then why it work in version0.12.

**Comment by ibookcc** [comment]
And plug-ins without any pay.

**Comment by ibookcc** [comment]
pay = Error.

**Comment by thebigsmileXD** [comment]
Idk, packages i guess

**Comment by ibookcc** [comment]
:p @PocketKiller

**Comment by MCPEPIG** [comment]
253c90e7de7ab23a7c66f7484e3a71d518413c90
