### ISSUE TITLE
put items problem

### ISSUE THREAD

**Issue by ibookcc** [ImagicalCorp/ImagicalMine#266]
Items cannot be placed.
have :
1,Skull baptism.
2,Harvesters.
3,ship.
4,all Redstone pedal
Thank for you work.
please fix this

**Comment by PocketKiller** [comment]
what
do you mean
ship = boat
skull baptism = Skulls
Harverstaers = ?
all Redstone pedal = All Redstone tools
1. some of redstone tools are placeable
2. YOU CAN PLACE SKULLS, I'VE NOTICED YOU'RE ON AN OLD BUILD, USE THE LATEST BUILD

**Comment by thebigsmileXD** [comment]
Skull i am working on
What are harvesters? Hoppers?
Of cause boats can't be placed. They are entities, in PocketMine/ImagicalMine are no entities yet
Many redstone things (pressure plates, redstone wire/block, levers) already work, make sure you use the latest version

**Comment by robske110** [comment]
There are some entitys though

**Comment by thebigsmileXD** [comment]
Squids have buggy AI, and i havent counted falling blocks or tnt as entity. But they are, sorry -.-"
Mobs, boats and minecarts dont work.

**Comment by MCPEPIG** [comment]
Skulls can be placed but are invisible.

**Comment by thebigsmileXD** [comment]
Not really. That happened to flower pots first. But you cant place skulls. Best thing is still using the FlowerPit plugin

**Comment by FienixEC** [comment]
Where can u get flowerpot plugin?

**Comment by thebigsmileXD** [comment]
Search beito on github
