### ISSUE TITLE
About map generation

### ISSUE THREAD

**Issue by ibookcc** [ImagicalCorp/ImagicalMine#267]
Chengde map of hell have't Soul sand,As well as the mineral specific to the hell.

Ordinary survival map not mined and high.

●ｖ●just it

**Comment by PocketKiller** [comment]
not us, PM, idk when we'll improve the terrain.

**Comment by thebigsmileXD** [comment]
Well, someone made a plugin called BetterGenerators, he wanted to add that as long as i know

**Comment by PocketKiller** [comment]
@thebigsmilexd yes i know but i think he's inactive now.
