### ISSUE TITLE
Redstone not working well

### ISSUE THREAD

**Issue by EnderKenji** [ImagicalCorp/ImagicalMine#268]
![screenshot_2015-12-10-23-12-43](https://cloud.githubusercontent.com/assets/15629214/11719013/bf9ab13e-9f93-11e5-9ddb-24a8d753d335.jpg)
Another torch should turn off

**Comment by PocketKiller** [comment]
WE DID NOT FULLY FINISH REDSTONE SUPPORT YET, PLEASE READ OTHER MESSAGES
(Sorry for caps, i didn't know i was writing with caps xD)

**Comment by EnderKenji** [comment]
...
