### ISSUE TITLE
Hi,  a little bug!!

### ISSUE THREAD

**Issue by astersx** [ImagicalCorp/ImagicalMine#269]
Mybe player dead glich will be duplicated if i mention here!!!

The problem is,  in the last version of IM keepinventory plugin dont work,  player dont drop item but it vanish!!
-And becouse of new items map lag a lot and client crash!!!
Only thing that is disturbing is compatibility with keepinventory,  i beg you to make it work :D

**Comment by keithkfng** [comment]
Please read the CONTRIBUTING guidelines before submitting an issue.
