### ISSUE TITLE
Server Crashing Please Fix 

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalCorp/ImagicalMine#270]
its not a plugin problem, its a binary problem it crashes whenever new players join and its annoying cuz my server needs to run 24/7 and im not home much

**Comment by EpicSteve33** [comment]
PocketMine-MP Crash Dump Thu Dec 10 21:18:44 EST 2015

Error: strlen() expects parameter 1 to be string, array given
File: /src/pocketmine/utils/Binary
Line: 107
Type: warning

Code:
[98] 					$m .= self::writeLShort($d[1]);
[99] 					break;
[100] 				case Entity::DATA_TYPE_INT:
[101] 					$m .= self::writeLInt($d[1]);
[102] 					break;
[103] 				case Entity::DATA_TYPE_FLOAT:
[104] 					$m .= self::writeLFloat($d[1]);
[105] 					break;
[106] 				case Entity::DATA_TYPE_STRING:
[107] 					$m .= self::writeLShort(strlen($d[1])) . $d[1];
[108] 					break;

**Comment by EpicSteve33** [comment]
line 107

**Comment by thebigsmileXD** [comment]
Just finally UNDERSTOOD the issue.. Okay.. Idk if thats the faukt of the official pm code

**Comment by EpicSteve33** [comment]
Well hopefully it gets fixed soon

**Comment by EpicSteve33** [comment]
[17:15:29] [WARNING]: InvalidArgumentException: "strlen() expects parameter 1 to be string, array given" (E_WARNING) in "/src/pocketmine/utils/Binary" at line 107

**Comment by EpicSteve33** [comment]
please fix

**Comment by FienixEC** [comment]
Mine was a very similar  error, all i did was delete that specific player
.dat file and problem solved. (If u know what player is crashing the
server.) Hope it helps,

**Comment by EpicSteve33** [comment]
I know what player is making it crash and I've deleted there dat file lots of times

**Comment by FienixEC** [comment]
Delete their .dat file including every file they may be associated with i.e
any .yml with their name in pureperms, simple auth etc. Basically when they
join, it will be like them joining for the first time and they will need to
re register.

**Comment by EpicSteve33** [comment]
Ya that didn't help

**Comment by EpicSteve33** [comment]
Ya it helped at first but when they rejoined they crashed it again

**Comment by FienixEC** [comment]
Strange, i had 2 players with the same issue, they happened to ve my staff
members. And i deleted any file associated with them and it worked. Which
pocketmine.phar build are you using?

**Comment by FienixEC** [comment]
Do u have kik? Easier to talk to there add me if you do @ fienixic

**Comment by EpicSteve33** [comment]
I'm using the src

**Comment by keithkfng** [comment]
Please read the README file before commenting.
