### ISSUE TITLE
Crafting Glitch?

### ISSUE THREAD

**Issue by deotern** [ImagicalCorp/ImagicalMine#271]
When u crafted something... ingredients won't be consumed in some circumstances... Example:

I want to craft a stone sword, so I used 2 cobblestone and 1 stick..
In result: I get 1 stone sword, 0 stick left, but 2 cobblestone are still in my inventory... ?? To be confirmed, I relog so my inventory will be refreshed and check if that 2 cobblestone is still there... And yes! That 2 cobblestone still in my inventory... (Of course, this happened when I craft other stuff, not cobblestone thingy only)

My inference:
1) This is purely a crafting glitch, item won't be consumed when u crafting
2) This is an inventory glitch, item is actually consumed... But, due to inventory glitch, it still display the item to player (Actually that item is just an virtual image)

Based on my observation, it's most likely an inventory glitch... But idk where the bug is...

**Comment by deotern** [comment]
Confirmed, inventory glitch... The item is removed.. But it still shows in player inventory

**Comment by thebigsmileXD** [comment]
Hmm.. Just for testing.. Try to craft.. A stone slab or an oven/furnace with these glichy stones

**Comment by deotern** [comment]
@thebigsmileXD Unable the craft... That's why I said this is an inventory glitch... I confirmed item is removed... But it still shows in player inventory after u crafted... Even u relogged, it still show u "fake" items

**Comment by legoboy0215** [comment]
:)

**Comment by BlackShadow1** [comment]
@keithkfng this is fixed
