### ISSUE TITLE
Team Members Warning - 0.13.1 UPDATE - 16th December 2015

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#273]
Well, the new update's coming straight at us -
http://mcpenews.com/mcpe-0-13-1-update/

**Comment by deotern** [comment]
LOL... I dont think we need to change anything... 0.13.0 => 0.13.1 will just be an minor update... I think we should focus on 0.13.1 =◇>

**Comment by keithkfng** [comment]
Hmm... What about protocol version? Any changes?

**Comment by Driesboy** [comment]
i search

**Comment by PocketKiller** [comment]
(Hope they add redstone repeaters..)

**Comment by deotern** [comment]
@PocketKiller I think it will be 0.14.x update :+1:

**Comment by thebigsmileXD** [comment]
I just found a funny dupe bug:
Throw items into portal, after rejoin they are there again.. And again.. And.. Again

**Comment by PocketKiller** [comment]
@thebigsmileXD then?

**Comment by thebigsmileXD** [comment]
What then?
I'll report this dupe bug

**Comment by matcracker** [comment]
Can be close this?
