### ISSUE TITLE
MCPE-Market.com

### ISSUE THREAD

**Issue by RandomAltThingy** [ImagicalCorp/ImagicalMine#278]
Hey guys,

I was just wondering if you would post every new (Stable) build of ImagicalMine to [MCPE-Market](http://mcpe-market.com)? Basically, submit every build that you add to the GitHub **Resources** page.

To submit to website, sign up > click resources > click submit resource > choose PocketMine Phars category.
To update the resource there will be a button on the resources' page.

Thanks and if you need any more info PM TheDiamondYT (Me) on the website.

**Comment by PocketKiller** [comment]
Ok, wait for @keithkfng to see this.

**Comment by thebigsmileXD** [comment]
Actually.. I would say: create a scrip wich copies that files to your server. Thats done in 1 Minute -.-

**Comment by RandomAltThingy** [comment]
Nah

**Comment by thebigsmileXD** [comment]
What "Nah"
Nah isnt even a word. This is not a kiddie chat.
And whatever. When you mean "nah" for the time: should i show you?
If you mean "no script".. Why.not?

**Comment by RandomAltThingy** [comment]
Tell that to http://twitter.com/_tomcc

**Comment by thebigsmileXD** [comment]
I do not have a teitter account and never ever make one.

**Comment by RandomAltThingy** [comment]
Tomcc is a MCPE developer. He codes stuff like the enchantments in mcpe

**Comment by thebigsmileXD** [comment]
And well.. What does this have to do with "i have no twitter" and the issue?

**Comment by keithkfng** [comment]
Nope. We are not affiliated with that website and I hate @TheDiamondYT even though he is following me. And I hate having to update it every day.

**Comment by RandomAltThingy** [comment]
I can update it if you would like. Technically, I am aloud to post it due to it being open source (Pointed to me by one of the Lifeboat staff). We have been getting quite popular with over 45 users registered (Website has been up for a day!).

**Comment by RandomAltThingy** [comment]
I kinda hate working with him sometimes. But he's alright when you get to know him. However, I will respect what you say and if you're sure that you don't want us to post a phar I will not.

**Comment by keithkfng** [comment]
LOL you can post it yourself if you like. You have permission under the team.

**Comment by RandomAltThingy** [comment]
Thanks.

**Comment by RandomAltThingy** [comment]
Sign up never know when we're giving away a moderator rank :)

**Comment by keithkfng** [comment]
Fine. But you keep creating issues everywhere about this website - https://github.com/Hydreon/Steadfast2/issues/61

**Comment by RandomAltThingy** [comment]
Lol kk

**Comment by RandomAltThingy** [comment]
Any chance of you putting in a file like the README with the following:

"If you would like to give us a review, go [here](http://mcpe-market.com/index.php?resources/imagicalmine.14/)"

**Comment by thebigsmileXD** [comment]
No.
