### ISSUE TITLE
The iron door doesn't work

### ISSUE THREAD

**Issue by killer549** [ImagicalCorp/ImagicalMine#279]
When u put an iron door it changes to 2 different blocks and it doesn't open or close please fix

**Comment by thebigsmileXD** [comment]
.. I am sure you do not use the latest build. Because it works for me. Since build 249 or so.

**Comment by killer549** [comment]
Im using #517 i downloaded the unstable #478 i opened the folder "releases" and i found "PocketMine-MP_0.13.0dev#517.phar" when i started the server with that build version i started using redstone and i pot iron door but it doesn't work

**Comment by MCPEPIG** [comment]
Iron doors are in fact broken.

**Comment by MCPEPIG** [comment]
Nvm

**Comment by killer549** [comment]
Yes i know its 2 blocks but if u click on one of the 2 blocks of the door the both will be opened like a real door

**Comment by thebigsmileXD** [comment]
They. Work. As. They. Should. Also.. Iron doors cant even be opened by hand, only redstone!
