### ISSUE TITLE
Half slabs

### ISSUE THREAD

**Issue by AndreyNazarchuk** [ImagicalCorp/ImagicalMine#281]
Hello,
When someone places a half slab, RakLib blocks them for 5 seconds and turns it into a full block, when they try to break it, it blocks them again for 5 seconds. This causes the player to disconnect, please fix.

**Comment by robske110** [comment]
Are you using the last jenkins build?

**Comment by AndreyNazarchuk** [comment]
No, I am using #374

**Comment by keithkfng** [comment]
We'll look into this issue, thanks for submitting it!

**Comment by thebigsmileXD** [comment]
Its already on the issue list. Only happens for stone slabs

**Comment by AndreyNazarchuk** [comment]
Happens to all slabs I have encountered.

**Comment by thebigsmileXD** [comment]
:/ oh. WHO BROKE THEM! Just kidding.
Okay, i haven't had that problem on 475 or so. So that means they broke between

**Comment by AndreyNazarchuk** [comment]
I still have them in #12 on Jenkins.

**Comment by aodzip** [comment]
I confirm that someone just copy the stone class and rename it into slab.

**Comment by AndreyNazarchuk** [comment]
Wow! Why the heck?

**Comment by aodzip** [comment]
No , it is not true , I open Wrong file .

**Comment by thebigsmileXD** [comment]
Hahaha xD
Well.. But slabs were gliching on 1.5 also

**Comment by AndreyNazarchuk** [comment]
Not like this...

**Comment by matcracker** [comment]
Try the last build and all work fine :+1:

**Comment by robske110** [comment]
Nope still raklib block

**Comment by matcracker** [comment]
For me works...

**Comment by thebigsmileXD** [comment]
They dont work

**Comment by matcracker** [comment]
I'm confused :/ I try to place and breaks all the half slabs and I'm not blocking from raklib ._.

**Comment by keithkfng** [comment]
Make sure you're on the newest build...

**Comment by matcracker** [comment]
I didn't use the .phar but the directly source folder because I frequently need to coding in it. I don't try with the .phar but I think is the same :|

Do you check if there are some problems during the compilation?

**Comment by keithkfng** [comment]
Yep. We added the Jenkins server while you were away. http://jenkins.imagiclacorp.ml:8080/job/ImagicalMine

**Comment by thebigsmileXD** [comment]
Error on phar.

**Comment by keithkfng** [comment]
On compile or while running?

**Comment by matcracker** [comment]
I try the 41.phar but works fine :/

Or I don't understand how to reproduce the bug or you use wrong version xD

**Comment by robske110** [comment]
My last confirmation was on 39, will test it again today

**Comment by matcracker** [comment]
Any update of this "bug"?

**Comment by thebigsmileXD** [comment]
Tested. When a slab is at the lower part and a block is above, you cant place into the space.
But.. atleast this is like on 0.11 and not critical

**Comment by aodzip** [comment]
That is just same in singal mode .
