### ISSUE TITLE
Hunger - still occurs on easy / peaceful

### ISSUE THREAD

**Issue by richardcbristol** [ImagicalCorp/ImagicalMine#282]
I know you got the hunger implementation from deot. i messaged him about this on the pocketmine forums but no reply.

Unfortunately for my server which has plenty of maps to explore with no food in them unless i can disable hungering then all future releases you produce are completely useless to me. Which is a shame as otherwise you're doing a great job :-)

**Comment by PocketKiller** [comment]
Hunger too fast was fixed and duplicated

**Comment by thebigsmileXD** [comment]
I am working on it. As i wrote in the forums..

**Comment by richardcbristol** [comment]
Cheers all

**Comment by keithkfng** [comment]
@thebigsmileXD is rewriting the hunger core. Check the repo for progress.
