### ISSUE TITLE
Chest destroy bug

### ISSUE THREAD

**Issue by GAalexandres** [ImagicalCorp/ImagicalMine#283]
If a player place a block of sand above a chest and it falls on the chest, the chest becomes a block of sand and if a player breaks that block of sand he will break the chest and the items come out. With this bug the players on my server break locked chests, I've blocked the sand and gravel, but it's a temporary fix, can you fix this please?
Sorry for my bad english.

**Comment by robske110** [comment]
Chest is not registered as an solid block?!

**Comment by GAalexandres** [comment]
Idk, you have to place the sand 1-2 block over the chest and when it falls the chest becomes a block of sand. If you place the sand directly on the chest it does nothing.

**Comment by robske110** [comment]
It is fixed
