### ISSUE TITLE
Redstone CRASH

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalCorp/ImagicalMine#287]
Put redstone dust on stairs or slab, they produce inf redstone causing lag then chrash

**Comment by keithkfng** [comment]
Already known issue.

**Comment by thebigsmileXD** [comment]
Its not known. Thanks for reporting.

**Comment by keithkfng** [comment]
It is. Somebody submitted it before to myself...

**Comment by aodzip** [comment]
I think redstone rewrite solve this
