### ISSUE TITLE
PlayerDeathEvent Error

### ISSUE THREAD

**Issue by Taki21** [ImagicalCorp/ImagicalMine#288]
I used to do this in my plugins while creating them:

public function onDeath(PlayerDeathEvent $event){
       $pl = $event->getPlayer();

Now when im doing it (Checked like so many times if i made a mistake) my server crashes! It is saying undefined method for getPlayer()

**Comment by Taki21** [comment]
Here is Complete Error:

Fatal error: Call to undefined method pocketmine\event\player\PlayerDeathEvent::getPlayer() in C:\Users\hossa\Desktop\PocketMine-MP\plugins\CTFpm\src\Taki21\CTF\Main.php on line 140

On other plugins its happening to not just this one. It wasnt like this when i had other build of ImagicalMine!

**Comment by Taki21** [comment]
Case Closed: It is getEntity() Now! Idk why?

**Comment by keithkfng** [comment]
LOL resolving your own error, eh?

**Comment by Taki21** [comment]
Yup!

**Comment by Taki21** [comment]
but why getEntity?

**Comment by keithkfng** [comment]
Ask devs...

**Comment by thebigsmileXD** [comment]
We should change it back

**Comment by MCPEPIG** [comment]
We should not. We would have to edit plugins using PlayerDeathEvent on our servers.

**Comment by thebigsmileXD** [comment]
That are plenty. It must be reverted
