### ISSUE TITLE
Spawn Protection does not work

### ISSUE THREAD

**Issue by robske110** [ImagicalCorp/ImagicalMine#292]
It did work in Build #323, then i upgraded to the jenkins build and noticed that spawn protection does not work anymore (players can break and place blocks)

**Comment by Driesboy** [comment]
Work for me

**Comment by Driesboy** [comment]
I work withworldprotect

**Comment by robske110** [comment]
I don't even have ANY plugin on my test server but since i started to use the jenkins build everyone can break blocks in the spawn area

**Comment by thebigsmileXD** [comment]
Confirmed issue. But! I think its because @aodzip added redstone on off switch to the server.properties. After deleting the config and reconfiguring it should work

**Comment by robske110** [comment]
Ok, wil try that

**Comment by robske110** [comment]
Still not working!
### Please fix!

**Comment by MCPEPIG** [comment]
@thebigsmileXD Stop blaming everything on others.

**Comment by MCPEPIG** [comment]
What build are you using now?

**Comment by deotern** [comment]
Please note, u MUST have at least an OP on your servee to enable spawn protection... Otherwise, spawn protection will be disabled.. =_= Are u sure there's at least one op on your server?

**Comment by robske110** [comment]
Build 50, still there

**Comment by robske110** [comment]
Oh, i will check if there is an op on my server...

**Comment by robske110** [comment]
Was that op issue
So guys, remember to always have an op on your server :(

**Comment by Driesboy** [comment]
No-OP players can break blocks on spawn

**Comment by robske110** [comment]
Do you have one op on your server

**Comment by Driesboy** [comment]
yes

**Comment by robske110** [comment]
Need more info here...
For me it works, but is realy slow (takes 10Sek to replace the blocks, that were broken)

**Comment by Driesboy** [comment]
no-OP can break blocks on protect places

**Comment by thebigsmileXD** [comment]
Source code or phar? Can you track the load on the server when someone breaks a Block? 100% load?

**Comment by astersx** [comment]
There is a hack wich allow to break protection on spawn,  there was many on my server and economyLand fixed this!!!!!  Note: I tested with no-op player and cant break,  but some can!!!

**Comment by Driesboy** [comment]
Fix it

**Comment by smyb** [comment]
@astersx  :open_mouth:

**Comment by PocketKiller** [comment]
Is this fixed?

**Comment by thebigsmileXD** [comment]
In my latest test yes

**Comment by Driesboy** [comment]
yes

**Comment by Driesboy** [comment]
close it work
