### ISSUE TITLE
Activator Rail

### ISSUE THREAD

**Issue by FunnyCrafteur** [ImagicalCorp/ImagicalMine#294]
Hi :)

When i put a Activator Rail. the rails drop

http://upload.hmsw.fr/uploads/afc65b408095dd1e34eecbc907a880feimg-3206.png

Thanks
FunnyCrafteur

**Comment by thebigsmileXD** [comment]
I already said i fixed that and need to commit

**Comment by thebigsmileXD** [comment]
I am sorry that they change to powered rails now :P
#alreadyfixedwaitingtocommit
