### ISSUE TITLE
DayLight Detector Not working

### ISSUE THREAD

**Issue by Driesboy** [ImagicalCorp/ImagicalMine#296]
DaylightDetector dont work

**Comment by PocketKiller** [comment]
it's not an error.. xD

**Comment by Driesboy** [comment]
oops

**Comment by matcracker** [comment]
All the redstone items and function is in very instable, we know that some items don't work.

**Comment by Driesboy** [comment]
ok

**Comment by thebigsmileXD** [comment]
It is

**Comment by keithkfng** [comment]
This is another duplicate. Please review the contributing guidelines first.
