### ISSUE TITLE
dead

### ISSUE THREAD

**Issue by Driesboy** [ImagicalCorp/ImagicalMine#297]
if your dead you can't move and you have no respawn button

**Comment by robske110** [comment]
Confirmed
You have made it worse!
Before when you issued /kill the respawn buttons appeared, now nothing works anymore!

**Comment by Driesboy** [comment]
i have not fix it 
not my fault

**Comment by thebigsmileXD** [comment]
Its McpePig's fault

**Comment by keithkfng** [comment]
STOP DUPLICATING ISSUES

**Comment by robske110** [comment]
No, this is a new issue caused by trying to fix another issue

**Comment by keithkfng** [comment]
It's already posted in a list of another issue.

**Comment by robske110** [comment]
Ok, sorry

**Comment by MCPEPIG** [comment]
Have you tried the newest build? If you haven't then don't report issues til you try cause I've tested the newest fix and it works.

**Comment by MCPEPIG** [comment]
I just tested with /kill and it shows the respawn page. I'm using the latest build.

**Comment by FienixEC** [comment]
Does the newest build fix the Pressure Plate crashes?

**Comment by Driesboy** [comment]
![image](https://cloud.githubusercontent.com/assets/15795262/11833320/a9e50b82-a3c1-11e5-920a-7a80fbf02526.png)
Dont work

**Comment by thebigsmileXD** [comment]
Yes, if you would read the changes then you would known! -.-



> Am 16.12.2015 um 01:25 schrieb FienixEC <notifications@github.com>:
> 
> Does the newest build fix the Pressure Plate crashes?

**Comment by MCPEPIG** [comment]
Well it works for me but haven't tried with drowning...

**Comment by MCPEPIG** [comment]
Just shut up, @thebigsmileXD

**Comment by keithkfng** [comment]
@MCPEPIG @thebigsmileXD IF YOU TWO SWEAR OR ARGUE AT EACH OTHER AGAIN I WILL KILL YOU

**Comment by SalmonGER** [comment]
Cant stop laughing. xD

**Comment by thebigsmileXD** [comment]
Hahaa me too xD
Much lol such rofl
Anyways, this isn't a chat.

**Comment by Driesboy** [comment]
its not only for drowning

**Comment by robske110** [comment]
/kill does not show the respawn page on Build50 with 0.13.0

**Comment by robske110** [comment]
Will soon test with Build56 on 0.13.1
