### ISSUE TITLE
Pressure Plate Bugs

### ISSUE THREAD

**Issue by EnderKenji** [ImagicalCorp/ImagicalMine#308]
@thebigsmileXD told me to create a new issue about this.

> Pressure plates delay duration too long.
> Pressure plates will not reset to normal after restart server.

**Comment by thebigsmileXD** [comment]
thebigsmileXD, not BigSlime
When will people understand that every username is unique? Also BigSmile is wrong. Google why.

But thanks for the issue. 1 more thing to that: click sound on scheduled update also you are still collided.

**Comment by keithkfng** [comment]
I'll change it to avoid anymore statements saying "you spelt it wrong", etc. etc.

**Comment by EnderKenji** [comment]
Ma english is bad , sorry

**Comment by keithkfng** [comment]
At least it's understandable.
