### ISSUE TITLE
Respawn Page

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#315]
Just creating a new issue, because this seems to be the most important of all. Don't mark this a duplicate XD

**Comment by SavionLegendZzz** [comment]
the reason why this happens is because i think that when hunger is active that it gives player(s) health while they are dead or just died(i use player harder so i did if(!$player->getHealth() === 0.5){ //code
} to cancel it)

**Comment by keithkfng** [comment]
Some people say it isn't even showing up anymore though.

**Comment by SavionLegendZzz** [comment]
well that could be that the hunger tick wasnt active or they had low hunger

**Comment by keithkfng** [comment]
Do you think you could fix it? Since you're a team member...

**Comment by InfornoFire** [comment]
I think it is just the game saying "Hey, you just died, wait... it says here to bring respawn thing up, overload with hunger (drum for puns), I am dead." It means just restart mcpe and it is maybe fixed

**Comment by SavionLegendZzz** [comment]
yea probably

**Comment by robske110** [comment]
Look, in build #323 Respawn Page worked good, smetimes you couldn't click Respawn
Then you tried to fix that and now it's gone completely!
Try to reverse any commits to this!

**Comment by keithkfng** [comment]
We can fix it thank you very much. We don't need to reverse anything.

**Comment by thebigsmileXD** [comment]
I'll take a look at this this evening or tomorrow.

**Comment by thebigsmileXD** [comment]
:P i'll overwrite the hunger core and the xp core.

**Comment by keithkfng** [comment]
Yay! Thanks Dan! Actually the hunger code was from Katana XD

**Comment by Jelly9912** [comment]
Which build have fixed this problem?

**Comment by MCPEPIG** [comment]
I didn't close it -_-

**Comment by InfornoFire** [comment]
Lel

**Comment by robske110** [comment]
RESPAWN PAGE 90% FIXED (Possiblily 100$)
Never saw that bug again since somebuild
