### ISSUE TITLE
Inventory glitch

### ISSUE THREAD

**Issue by EoflaOE** [ImagicalCorp/ImagicalMine#316]
When I open inventory, on building blocks tab, on the bottom of the page, the farmland, with 2 blocks are duplicated 6 times, When we open the decorative tab, and it's on the bottom, I saw the half door (dark oak and complete), and more repeated itself 6 times, When we open the Combat (sword icon) tab, on the buttons it render as block and not item, When we scroll down, I saw the redstone lamp turned off and on, and more blocks, repeated by 6 times.

**Comment by keithkfng** [comment]
Which build?

**Comment by thebigsmileXD** [comment]
Not ok the latest. There are just 2 empty slots and the meta bugs with fish and golden apple

**Comment by keithkfng** [comment]
I reverted the changes for items.

**Comment by thebigsmileXD** [comment]
Which one

**Comment by keithkfng** [comment]
My ones from the official repo.

**Comment by keithkfng** [comment]
Still an issue?

**Comment by ZombiePower** [comment]
hm...

**Comment by robske110** [comment]
Yeah, the two blank fields are still there!

**Comment by thebigsmileXD** [comment]
I really checked everything, they shouldn't be there

**Comment by robske110** [comment]
![image](https://cloud.githubusercontent.com/assets/16020100/11991321/2e8f6a64-aa19-11e5-9ca4-77d011e77289.png)

**Comment by thebigsmileXD** [comment]
-.-" i mean they SHOULDN'T be there, i know that they are there

**Comment by robske110** [comment]
I hate the following english verbs: -Should/n't -must/n't -would/n't
For a german guy they are so annoying

**Comment by ZombiePower** [comment]
and why did we had to know that? xP

**Comment by robske110** [comment]
Because I misunderstood @thebigsmileXD because of that :(

**Comment by ZombiePower** [comment]
oh X(

**Comment by thebigsmileXD** [comment]
I am German. Not annoying for me

**Comment by keithkfng** [comment]
I love those verbs. They're very useful if you know English very well. You shouldn't do this. See? It saves you from typing should not + if you hate handwriting(like I do), you can just save up yourself writing the o.
