### ISSUE TITLE
Redstone Power doesn't work from underneath

### ISSUE THREAD

**Issue by HimbeersaftLP** [ImagicalCorp/ImagicalMine#319]
For example, if you put a lever on the bottom of a redstone lamp,
![wp_ss_20151218_0003](https://cloud.githubusercontent.com/assets/16354747/11906038/262b91ac-a5ca-11e5-9e25-3873df0ec92b.png)
and turn it on. It won't glow:
![wp_ss_20151218_0004](https://cloud.githubusercontent.com/assets/16354747/11906039/262e9514-a5ca-11e5-9454-462e39945d19.png)
But in singleplayer it does:
![wp_ss_20151218_0002](https://cloud.githubusercontent.com/assets/16354747/11906037/262a7858-a5ca-11e5-8c4b-09e56fc735a4.png)

It works fine with redstone torches.

**Comment by aodzip** [comment]
I will fix this after rewrite the redstone.
