### ISSUE TITLE
Stairs issue

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#320]
Even if servers have an anti-griefing plugin installed, played can still break stairs.

**Comment by matcracker** [comment]
All stairs or a particular stair?

**Comment by keithkfng** [comment]
All.

**Comment by matcracker** [comment]
Ok, try to remove function isBreakable() from Stair.php and test :)

**Comment by keithkfng** [comment]
You can do that, I don't want to mess it up XD

**Comment by PocketKiller** [comment]
@matcracker then it will be IMPOSSIBLE TO BREAK IT

**Comment by keithkfng** [comment]
LOL true... isBreakable = false, means unBreakable!

**Comment by MCPEPIG** [comment]
I've made a pull request to fix this.

**Comment by matcracker** [comment]
No, I'll want to do how in #322

**Comment by matcracker** [comment]
Have you test if works?

**Comment by smyb** [comment]
It's not working :/

**Comment by ZombiePower** [comment]
works?
