### ISSUE TITLE
Although this is not very serious.....but could you fix it?plz.

### ISSUE THREAD

**Issue by jerryzooyoyo** [ImagicalCorp/ImagicalMine#323]
[CRITICAL]: InvalidArgumentException: "Value 21 exceeds the range!" (EXCEPTION) in "/src/pocketmine/entity/Attribute" at line 107

As you see,in the console it keep showing.
I use the latest build ( Build 87 ).
Could you guys fix it ? Or just tell me how could this happen?
Sorry,my English is pretty poor ....:(

**Comment by keithkfng** [comment]
Checkout the contributing guidelines before making an issue, this issue doesn't match them.
