### ISSUE TITLE
Level Management Broken

### ISSUE THREAD

**Issue by robske110** [ImagicalCorp/ImagicalMine#325]
After i upgraded from 72 to 86 i tried to insert a world from another server in the /worlds/ folder
but i just couldn't teleport me into that world it kept saying level "null" not exists...
Then I remembered I just done that a few days ago with an older build, so i used 72 and it worked as it should!
Realy don't know what broke there!

**Comment by HimbeersaftLP** [comment]
But creating worlds (ManyWorlds) is working in Build 86

**Comment by robske110** [comment]
Creating does work but not loading worlds pasted into the worls folder
##### please fix

**Comment by keithkfng** [comment]
Well, check if ImagicalMine loads your world by editing the pocketmine.yml file. You’ll see a worlds setting at the bottom.

**Comment by robske110** [comment]
That close button is stupid

**Comment by robske110** [comment]
@keithkfng pocketmine.yml has worlds settings?

**Comment by HimbeersaftLP** [comment]
Yes, there you can change which worlds should load on startup.

**Comment by robske110** [comment]
But i load them while running and that doesn't work in 86 but it works in 72

**Comment by robske110** [comment]
New info: When i add an map i must downgrade to 72, then upgrade to the newest build: works
just adding a map in the new builds: worls does not load

**Comment by robske110** [comment]
No one knows why

**Comment by robske110** [comment]
Somehow fixed in the latest builds. closing
