### ISSUE TITLE
Misleading readme

### ISSUE THREAD

**Issue by PEMapModder** [ImagicalCorp/ImagicalMine#327]
The readme says that FastTransfer does not work on ImagicalMine, making it sound like it doesn't work on ImagicalMine only.

**Comment by HimbeersaftLP** [comment]
You're right, it's on every Pocketmine. It's MCPEs "fault".

**Comment by keithkfng** [comment]
Will edit.

**Comment by da123rrell** [comment]
And thats why i tought that it was only on imagicalmine :p
