### ISSUE TITLE
FURNACE BUG

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/ImagicalMine#328]
I can not open the furnace. When I try to open, Minecraft (not server) crash. Please fix.

**Comment by Godsoft029** [comment]
Not everytime

**Comment by Godsoft029** [comment]
It also crashes (Mcpe crashes not the server) when you have slow Internet, and try to open 2 chest at the same time

**Comment by thebigsmileXD** [comment]
DUPLICATED ISSUE.
