### ISSUE TITLE
Is There Any Way to Fix Paintings?

### ISSUE THREAD

**Issue by Taki21** [ImagicalCorp/ImagicalMine#329]
This bug has been on pocketmine forever. Try to put a painting but it doesnt work, plus you cant place skulls. 

Im wondering if ImagicalMine Could Fix Paintings bug and Skull placement too.
Thx...

**Comment by MCPEPIG** [comment]
You can place skulls but they'll be invisible.

**Comment by aodzip** [comment]
@MCPEPIG 
How about your /xp works?

**Comment by MCPEPIG** [comment]
I didn't add /xp

**Comment by daany123** [comment]
@MCPEPIG Ok, how about the Experience Orb?

**Comment by thebigsmileXD** [comment]
I added /xp. Seems to work. I'll test again.

Paintings are entities. No comment. *ENTITIES*

Skulls are about to be fixed.

**Comment by robske110** [comment]
Entities when i hear that, i am always remembered that there is no game/server where thes work...

**Comment by thebigsmileXD** [comment]
There are plugins that add some.
Also, squid ai is implemented, but buggy

**Comment by robske110** [comment]
Sorry meant working good

**Comment by Jelly9912** [comment]
About painting - guys, try data packets ;) 
this is AddPaintingPacket i think or something like this, try to do something with this

**Comment by thebigsmileXD** [comment]
You would have to write the whole Painting class. Its not as easy as adding packages

**Comment by Jelly9912** [comment]
I know, but this is my idea

**Comment by Taki21** [comment]
._. Off-Topic Up there...AddPaintingPacket...Don't you need paintings image file too or no?

**Comment by thebigsmileXD** [comment]
I don't think so, but no idea how to calculate what image is used.

**Comment by Taki21** [comment]
I will try to do something ifff I can... 0_o
