### ISSUE TITLE
[DevOnly] Should we cleanup the code?

### ISSUE THREAD

**Issue by aodzip** [ImagicalCorp/ImagicalMine#331]
We write many code.
But some are useless and some are totally wrong and some are not completed.
They cause performance issue or some bug we don't know.
should we stop add new things and sit down to clean the code ?

**Comment by aodzip** [comment]
Or , anyone start a new feuture plz finish it . not leaving a messy code and stop continue work on it.

**Comment by thebigsmileXD** [comment]
Well, we should only clean up the files we created.

**Comment by matcracker** [comment]
I think that a cleanup of your code is useful, it can be strange for other people :)

**Comment by aodzip** [comment]
@matcracker
Me? These for Redstone?

**Comment by thebigsmileXD** [comment]
Well.. If we would clean up other things, we cant push to the official PM anymore

**Comment by keithkfng** [comment]
We don't want too... Or do we?

**Comment by aodzip** [comment]
Develop as you like guys , neber mind XD
