### ISSUE TITLE
Crash when used plugin Slapper 1.2.5

### ISSUE THREAD

**Issue by miker059** [ImagicalCorp/ImagicalMine#332]
Hello! Crashdamp in
[CrashDump_Sun_Dec_20-13.52.55-MSK_2015.txt](https://github.com/ImagicalCorp/ImagicalMine/files/67780/CrashDump_Sun_Dec_20-13.52.55-MSK_2015.txt)

 attach

**Comment by Jelly9912** [comment]
Fault of Slapper, wait for updates from author of plugin

**Comment by miker059** [comment]
Sorry, I wrote not there

**Comment by thebigsmileXD** [comment]
Well, isSkinSlim is the fault of Slapper, but thats an easy fix.

**Comment by robske110** [comment]
So how to fix?

**Comment by lolcraftboy14** [comment]
Y hat dat to

**Comment by robske110** [comment]
In english please
