### ISSUE TITLE
My Plot No Longer Work

### ISSUE THREAD

**Issue by CraftingMania** [ImagicalCorp/ImagicalMine#335]
It work wit official pocketmine but with imigialmine it doesnt recognize plots  and evrything got griefed please fix imigialmine thing myplot works with 0.13.1 it is imigialmine

**Comment by thebigsmileXD** [comment]
Tell that wiez ;)

**Comment by thebigsmileXD** [comment]
Wait.. Maybe its like the spawn protection! CRITICAL

**Comment by ZombiePower** [comment]
can someone specifically describe it?

**Comment by CraftingMania** [comment]
ok the plugin works well on official pocketmine and recognize plots and clear and claim them but on imagialmine it doesnt recognize plot so the problem is not wiez problem it is imagialmine problem

**Comment by thebigsmileXD** [comment]
What a wonder, i use MyPlot on ImagicalMine too, and ohoo, it works!

**Comment by CraftingMania** [comment]
it works for 2 minutes then no more protection

**Comment by CraftingMania** [comment]
and no more plot recognized i use latest imagialmine build from your jenkins website

**Comment by thebigsmileXD** [comment]
Works all time..

**Comment by CraftingMania** [comment]
what build you use from jenkins
