### ISSUE TITLE
Error in entity Attribute 

### ISSUE THREAD

**Issue by peepzandmeepz** [ImagicalCorp/ImagicalMine#338]
Hi there! Unsure if this issue is duplicated or known, but I skimmed the current issue submissions and didn't find anything related. Once again ahead of time, sorry if this is duplicated or already a known issue.. :)

I am currently using the most recent build.

Error: Value -1 exceeds the range!
File: /src/pocketmine/entity/Attribute
Line: 107
Type: notice

Code:
[98]             return $this;
[99]         }
[100] 
[101]         public function getValue(){
[102]             return $this->currentValue;
[103]         }
[104] 
[105]         public function setValue($value){
[106]             if($value > $this->getMaxValue() or $value < $this->getMinValue()){
[107]                 throw new \InvalidArgumentException("Value $value exceeds the range!");
[108]             }
[109] 
[110]         $this->currentValue = $value;
[111] 
[112]         if($this->shouldSend)
[113]             $this->send();
[114]         }
[115] 
[116]         public function getName(){
[117]             return $this->name;

Backtrace:
#0 /src/pocketmine/entity/Entity(638): pocketmine\Player->setHealth(integer -1)
#1 /src/pocketmine/entity/Living(111): pocketmine\entity\Entity->attack(integer 2, pocketmine\event\entity\EntityDamageEvent object)
#2 /src/pocketmine/Player(3420): pocketmine\entity\Living->attack(integer 2, pocketmine\event\entity\EntityDamageEvent object)
#3 /src/pocketmine/entity/Living(197): pocketmine\Player->attack(integer 2, pocketmine\event\entity\EntityDamageEvent object)
#4 /src/pocketmine/Player(1547): pocketmine\entity\Living->entityBaseTick(integer 1)
#5 /src/pocketmine/Server(2360): pocketmine\Player->onUpdate(integer 8097)
#6 /src/pocketmine/Server(2529): pocketmine\Server->checkTickUpdates(integer 8097, double 1450640501.2369)
#7 /src/pocketmine/Server(2251): pocketmine\Server->tick(boolean)
#8 /src/pocketmine/Server(2129): pocketmine\Server->tickProcessor(boolean)
#9 /src/pocketmine/Server(1730): pocketmine\Server->start(boolean)
#10 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/jar/PocketMine-MP.phar/, string /home/minecraft/multicraft/servers/server6/, string /home/minecraft/multicraft/servers/server6/plugins/)
#11 (1): require_once(string phar:///home/minecraft/multicraft/jar/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by keithkfng** [comment]
I've seen many issues like this already. But I don't think it's actually been fixed. I'll make it critical.

**Comment by thebigsmileXD** [comment]
I havent closed this.. dumb github
