### ISSUE TITLE
Code style issues

### ISSUE THREAD

**Issue by PEMapModder** [ImagicalCorp/ImagicalMine#340]
Your CONTRIBUTING.md specifies the use of PSR-2 code standard, but it appears that your commits do not follow PSR-2 at all.

**Comment by robske110** [comment]
I love how you just close issues without commenting why...
(Ironic)

**Comment by keithkfng** [comment]
If I don't comment, it means that this issue serves no purpose at all.

**Comment by PEMapModder** [comment]
So explain how your code conforms to this, while you are requiring pull requests to satisfy them?
![screenshot_2015-12-23-15-54-41](https://cloud.githubusercontent.com/assets/5618466/11972882/8ed43c4c-a98d-11e5-9fdf-31fd2ea44f56.png)

**Comment by keithkfng** [comment]
-_-

**Comment by PEMapModder** [comment]
?

**Comment by keithkfng** [comment]
-_-

**Comment by matcracker** [comment]
The code is more cool with PSR-2, I follow this method and I try to fix some files when I found

**Comment by PEMapModder** [comment]
Or simply use Ctrl+Alt+L in PhpStorm

**Comment by thebigsmileXD** [comment]
Or ctrl+i for selected lines in eclipse

**Comment by PEMapModder** [comment]
Irrelevant?

**Comment by matcracker** [comment]
Yes, irrelevant because isn't very important to fix immediatly
