### ISSUE TITLE
Event Problems

### ISSUE THREAD

**Issue by Underpippo** [ImagicalCorp/ImagicalMine#341]
We have Problems with  Events in our Plugins.
The Events for despawning Items, for Example to despawn an Snowball or an Egg is not implementiert yet. And you cant change the Playername.

**Comment by robske110** [comment]
You can change playername (look at NameCorrector, still works)
https://github.com/PEMapModder/Small-ZC-Plugins/blob/master/NameCorrector/src/NameCorrector/NameCorrector.php#L79
Despawn items? I don't use it so can't reporoduce this...

**Comment by Underpippo** [comment]
Despawning Items is for example to use a snowball as a enderperl

**Comment by keithkfng** [comment]
I've never heard of despawning items.

**Comment by thebigsmileXD** [comment]
I guess its not items, its entities

**Comment by Underpippo** [comment]
Yeah Entities :P

**Comment by PocketKiller** [comment]
```php
$entity->kill();
$entity->close();
```
you mean despawning/killing Item Entities?

**Comment by Underpippo** [comment]
Yeah or that xD

**Comment by Underpippo** [comment]
So the last Problem
