### ISSUE TITLE
Skin error bug fix crashing

### ISSUE THREAD

**Issue by TBNRFrags2468** [ImagicalCorp/ImagicalMine#344]
please help me i fixed the corupted skin on my server but i crash when i join

**Comment by TBNRFrags2468** [comment]
is there a way to stop making my friends and me crash

**Comment by thebigsmileXD** [comment]
Nope

**Comment by TBNRFrags2468** [comment]
oh

**Comment by TBNRFrags2468** [comment]
well then this will take a while

**Comment by thebigsmileXD** [comment]
Do not spam, okay?!
We were working on that, theres also a branch where we try to fix it

**Comment by TBNRFrags2468** [comment]
ok

**Comment by TBNRFrags2468** [comment]
i hope this gets fixed :)

**Comment by keithkfng** [comment]
What?! Corrupted skin? Wasn't that fixed ages ago?

**Comment by robske110** [comment]
Try the latest build on jenkins @TBRNFrags2468
jenkins.imagicalcorp.ml:8080/job/ImagicalMine/106/

**Comment by thebigsmileXD** [comment]
@keithkfng i am not sure. i only get this error on MineDox after i tried to change my skin, after resetting it i still can't join

**Comment by keithkfng** [comment]
Me too, contact @deotern. I don't think he's even using ImagicalMine...

**Comment by TBNRFrags2468** [comment]
i mean i crash when i try to join i got the fix for pocketmine skin bug

**Comment by TBNRFrags2468** [comment]
keith are you the owner of pocketmine

**Comment by robske110** [comment]
keith is the LEADER of ImagicalMine, shogicp is the LEADER of PocketMine
That are OPEN source projects!

**Comment by TBNRFrags2468** [comment]
ok ok

**Comment by TBNRFrags2468** [comment]
is there a fix for the corrupted skin fix because everyone says they're crashing when they join

**Comment by keithkfng** [comment]
Which build are you currently using?

**Comment by TBNRFrags2468** [comment]
the skin corruption fix one

**Comment by TBNRFrags2468** [comment]
how do i become a callobrater

**Comment by TBNRFrags2468** [comment]
like i got the skin corruption fix and tried to join my server i got in and i crashed 15 seconds later

**Comment by robske110** [comment]
1. Stop spamming
2. removed <-Was too offense
3. SKINS DO WORK IN Build 100
