### ISSUE TITLE
Looking into the code, find out /xp, try it out and it doesn't even work (Say it with Jingle Bells theme)

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalCorp/ImagicalMine#348]
Hey fix it up, fix it up, its broken nowadays, I want to try it out but it says Nope (Unknown command.)

Get the point, its not working even with your fix, lel

**Comment by thebigsmileXD** [comment]
:) Yay! :christmas_tree: :santa:
I'll check

**Comment by InfornoFire** [comment]
How do you add labels, or is it a dev thing

**Comment by robske110** [comment]
Its a collaborator thing

**Comment by MCPEPIG** [comment]
It doesn't work cause the command isn't registered.

**Comment by InfornoFire** [comment]
oh...................................................................................................................................................................well good day

**Comment by InfornoFire** [comment]
then again, it would be a bug not to register it

**Comment by matcracker** [comment]
It isn't fully working...

**Comment by thebigsmileXD** [comment]
I am working on it, theres a new issue for it.

**Comment by matcracker** [comment]
Oh, I see now
