### ISSUE TITLE
"Invalid Skin" on latest build

### ISSUE THREAD

**Issue by peepzandmeepz** [ImagicalCorp/ImagicalMine#350]
Hi there,

Compiled the most recent version of the source and it keeps kicking about 90% of users that log on for the reason "Invalid Skin".

Thanks and Happy Holidays! :)

**Comment by keithkfng** [comment]
Try using the latest build from Jenkins, that's auto-compiled.
We'll also see if it happens again.

**Comment by robske110** [comment]
NOO I belive the bug is back
Are they using 0.13.1 (No compatibility with 0.13.0)

**Comment by keithkfng** [comment]
It shouldn't... Because the fix was from the official repo.

**Comment by keithkfng** [comment]
I think we need @mwvent - THE SKIN MASTER! XD

**Comment by IMagicalPlugins** [comment]
PEEPZANDMEEPZ

**Comment by IMagicalPlugins** [comment]
I WAS WOOFWOOF170 ON YOUR SERVER

**Comment by PocketKiller** [comment]
@IMagicalPlugins please stay on-topic.

**Comment by IMagicalPlugins** [comment]
hey peepzandmeepz is a enemy

**Comment by IMagicalPlugins** [comment]
i got ip banned on his server

**Comment by robske110** [comment]
Oh god unplug your router plug it right back in...
New IP and wam not banned anymore

**Comment by peepzandmeepz** [comment]
Or instead of calling me an "enemy", how about you make a ban appeal instead? ;) 

As for this bug, it doesn't seem to occur when I used the Jenkins build. Unsure if this should stay open or not.

**Comment by keithkfng** [comment]
LOL who called you an enemy?

**Comment by thebigsmileXD** [comment]
@keithkfng I already deleted the messages

**Comment by keithkfng** [comment]
Wait but who called him that...

**Comment by thebigsmileXD** [comment]
Read in the mail on this comment
 |
\/

**Comment by keithkfng** [comment]
WTF?! Who is @IMagicalPlugins?

**Comment by keithkfng** [comment]
Okay... I think this should be closed as it works on the Jenkins builds...
