### ISSUE TITLE
Cant convert Playername/IP 

### ISSUE THREAD

**Issue by Underpippo** [ImagicalCorp/ImagicalMine#353]

**Comment by PocketKiller** [comment]
please be more specific.

**Comment by Underpippo** [comment]
We  need to convert the Playername for a Party Function in a Plugin :3

**Comment by PocketKiller** [comment]
what do you mean?
do you mean can't change player name?

**Comment by Underpippo** [comment]
Level::getPlayer

**Comment by thebigsmileXD** [comment]
Foreach $this->getServer->getLevelByName->getonlineplayers
