### ISSUE TITLE
changing game modes

### ISSUE THREAD

**Issue by Tolo0** [ImagicalCorp/ImagicalMine#356]
When changing from creative mode to survival mode. The items you have on ur lower bar. Aren't removed.

**Comment by HimbeersaftLP** [comment]
Yes, that's really bad, because on my server, I have Survival and Creative worlds, and the people can cheat...

**Comment by Tolo0** [comment]
Same here. Players where going creative world. Filling slots with diamond block and other items. Then selling.

**Comment by HimbeersaftLP** [comment]
Yes

**Comment by aodzip** [comment]
@PeratX
Would you like to fix this?

**Comment by thebigsmileXD** [comment]
Also, the items that are left are always 5

**Comment by aodzip** [comment]
Genisys fix this. port!

**Comment by thebigsmileXD** [comment]
@aodzip i can't. I finally want to get the food and potions done

**Comment by BlackShadow1** [comment]
Are you working on potion @thebigsmileXD ?

**Comment by Tolo0** [comment]
If u use plugin.  PureGis.  It stops players having the items from creative mode. But u may get random crash dumps using the plugin.

**Comment by thebigsmileXD** [comment]
Because PureGIS is shit.

**Comment by thebigsmileXD** [comment]
Yes, right now i'm making dinner (noodles) and then i'll continue

**Comment by Tolo0** [comment]
Ye a fix would be the best thing 😊
