### ISSUE TITLE
Players nametag and skin bug

### ISSUE THREAD

**Issue by smyb** [ImagicalCorp/ImagicalMine#360]
Sometimes i see players without nametag and with my skin.

**Comment by thebigsmileXD** [comment]
Do they sneak? Or is there a nametag-hide-plugin on the server? (HideMe for example?)
The skins are really creepy.. so less people really have their own skins. they are wether black or the one of yourself

**Comment by thebigsmileXD** [comment]
And don't mark as duplicate

**Comment by keithkfng** [comment]
How is this a notice?! Maybe we should add "Possible Bug" as a label to the issue tracker...

**Comment by thebigsmileXD** [comment]
Yup

**Comment by smyb** [comment]
there isn't any nametag-hide plugin and players aren't sneaking. the nametag is invisible.

**Comment by robske110** [comment]
I never seen an nametag invisible on my server (only when i used healthbars, removed them now)
And the skin bug: BlackSkin: Didn't see it since build #323... You see your own skin on other players: Confirmed x10000000

**Comment by smyb** [comment]
the server is running on ubuntu

**Comment by smyb** [comment]
and i'm using the latest version (this on github) of ImagicalMine

**Comment by keithkfng** [comment]
I don't think this is a bug. Try using Jenkins builds.

**Comment by robske110** [comment]
The skin bug is a bug (you DO see aour skin on other players!)

**Comment by keithkfng** [comment]
That's an MCPE bug since 0.12. I've never seen it on 0.11. Not an ImagicalMine bug, because when you go on LBSG, it's sometimes your skin or its black isn't it?

**Comment by robske110** [comment]
What the hell is LBSG?
Could be an mcpe bug, the Windows10 Version does the best job!

**Comment by keithkfng** [comment]
"Yo stupid..." - (What's 9 + 10 video)
You don't know what LBSG is? Are you kidding me? LOL

**Comment by thebigsmileXD** [comment]
LifeBoat SurvivalGames.

**Comment by smyb** [comment]
![screenshot_2015-12-23-09-52-42](https://cloud.githubusercontent.com/assets/15691329/11973540/cd001522-a95b-11e5-9feb-aeeff2a84d94.png)
![screenshot_2015-12-23-09-52-05](https://cloud.githubusercontent.com/assets/15691329/11973543/cf3c8dfc-a95b-11e5-808c-8f9745fb58d6.png)
![screenshot_2015-12-23-09-52-11](https://cloud.githubusercontent.com/assets/15691329/11973544/d047de90-a95b-11e5-96ac-892398260013.png)

**Comment by thebigsmileXD** [comment]
What is the actual name of the player? Maybe non-Supported charset?

**Comment by smyb** [comment]
no

**Comment by thebigsmileXD** [comment]
> What is the actual name of the player?
