### ISSUE TITLE
Playername

### ISSUE THREAD

**Issue by Underpippo** [ImagicalCorp/ImagicalMine#361]
From a player's name will not be recognized as an entity (Level::getPlayer)
Plesse fix it :D

**Comment by thebigsmileXD** [comment]
I do not understand. Can you explain it

**Comment by Underpippo** [comment]
It's important for a Party-Feature in a Plugin. The Player can make /party
... And then he gehts a code.
But we can not write it because you can not see a entitiy from Player's
Name.

Dan <notifications@github.com> schrieb am Di., 22. Dez. 2015 21:41:

**Comment by Taki21** [comment]
You cannot see Player's nametag?

**Comment by Underpippo** [comment]
No not this :3
You can't transform a Playername into a mob.

**Comment by thebigsmileXD** [comment]
I'll close this due to lack of being understandable

**Comment by matcracker** [comment]
Entities aren't implemented yet.

**Comment by Underpippo** [comment]
Sorry i dont mean mobs i mean entities.
You cant trasform a Playername into a entitiy. (Entity like Snowballs or Eggs)

**Comment by matcracker** [comment]
We know... I repeat, entities aren't implemented yet

**Comment by Underpippo** [comment]
When do you implementiert it ?

**Comment by robske110** [comment]
GetPlayer($name)->
Returns the player object
READ THE DOCS

**Comment by Underpippo** [comment]
Exact this dont work !

**Comment by robske110** [comment]
That DOES work

**Comment by thebigsmileXD** [comment]
It does work for me also.
