### ISSUE TITLE
Redstone doesn't work in build 134

### ISSUE THREAD

**Issue by HimbeersaftLP** [ImagicalCorp/ImagicalMine#367]
Help, nothing works, pressure plates, buttons... Or am I doind something wrong?

**Comment by HimbeersaftLP** [comment]
*doing

**Comment by aodzip** [comment]
Only RedstoneBlock Torch Wire work

**Comment by HimbeersaftLP** [comment]
Is this normal?

**Comment by aodzip** [comment]
and Lamp

because of rewrite redstone , I remove some old function , most of redstone tools won't working and even some of then crash

**Comment by HimbeersaftLP** [comment]
So I should break every redstone thing, so that nobody can crash my server?

**Comment by aodzip** [comment]
or roll back a old stable version

**Comment by HimbeersaftLP** [comment]
Well, I like destroying...

**Comment by aodzip** [comment]
update to 135 , it won't work but won't crash

**Comment by HimbeersaftLP** [comment]
THX

**Comment by thebigsmileXD** [comment]
Why this bug?

**Comment by matcracker** [comment]
Because he changes old fuctions with new

**Comment by robske110** [comment]
Close?
