### ISSUE TITLE
No inventory update on give command

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalCorp/ImagicalMine#368]
Or on other things that give you items

**Comment by robske110** [comment]
?
My kitpvp plugin works, but i am using about ten builds earlier

**Comment by thebigsmileXD** [comment]
I have to open my inventory to refresh it.

**Comment by HimbeersaftLP** [comment]
@thebigsmileXD You mean the items don't appear in the hotbar?

**Comment by thebigsmileXD** [comment]
and neither in the inventory.

**Comment by ZombiePower** [comment]
what do you mean?

**Comment by MCPEPIG** [comment]
It's been fixed :3
