### ISSUE TITLE
Can you compile IM for 0.13.1?

### ISSUE THREAD

**Issue by tankisu01** [ImagicalCorp/ImagicalMine#370]
Title says all

**Comment by SalmonGER** [comment]
You can do it with DevTools, or download it from here: http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine/

**Comment by thebigsmileXD** [comment]
It is already on 0.13.1

**Comment by keithkfng** [comment]
@thebigsmileXD https://github.com/keithkfng/Stuff/blob/gh-pages/Linux32.sh
Took me a few hours to get this right -_-
