### ISSUE TITLE
ImagicalMine Developing Hours (Christmas)

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#371]
Hi all,
Here is a list of developers that will be active during Christmas.
Team members - tick your name off if you match the criteria.
- [x] keithkfng
- [x] aodzip
- [ ] hoyinm14mc
- [ ] matcracker
- [ ] legoboy0215
- [x] Zombie_Power (maybe)
- [x] thebigsmileXD (working on hunger code.. Also i am sick..)

If your name is listed and you are active, add your name. Thanks!

**Comment by ZombiePower** [comment]
maybe :p

**Comment by aodzip** [comment]
sigh 
A normal day for me 
lol
