### ISSUE TITLE
At the connection

### ISSUE THREAD

**Issue by KingDeadKnight** [ImagicalCorp/ImagicalMine#372]
I use the latest build of ImagicalMine and when I go to my server I got this
![screenshot_2015-12-23-23-32-22](https://cloud.githubusercontent.com/assets/15180531/11986260/c16a1f6a-a9cd-11e5-9918-2069e240e73b.png)
Can you help me?

**Comment by keithkfng** [comment]
This happens as a glitch sometimes...

**Comment by KingDeadKnight** [comment]
I know but for this time, I can try every 5minuts and it always happend, even after a restart
