### ISSUE TITLE
Unlimited tools

### ISSUE THREAD

**Issue by Jelly9912** [ImagicalCorp/ImagicalMine#373]
Everyone (no-op players to) have "unlimited" tools :v
Only if you hit someone (sword, axe, shovel... all tools) they are get some damages. This is really annoying... oh and players can duplicate all items in furnace and crafting table (idk how, i know it from players on my server) if this issue is duplicated - sorry :v

**Comment by ZombiePower** [comment]
unlimited? Do you mean unlimited health or amount?

**Comment by thebigsmileXD** [comment]
Like the crafting glich. Tried yesterday. I had 4 diamonds and crafted all armor and tools. And still had my diamonds

**Comment by ZombiePower** [comment]
I am sure, its with the recipes, check out crafting manager X)

**Comment by aodzip** [comment]
unlimited tools fix

**Comment by aodzip** [comment]
no , it is not fix , it is implement lol

**Comment by Jelly9912** [comment]
I mean health and amount ;)

**Comment by aodzip** [comment]
okay

**Comment by aodzip** [comment]
can you test the latest build ?

**Comment by Jelly9912** [comment]
Fron jenkins?

**Comment by matcracker** [comment]
I try and works

**Comment by Jelly9912** [comment]
Yup, it works now. And what with crafting guys?

**Comment by keithkfng** [comment]
Dunno XD

**Comment by BlackShadow1** [comment]
@aodzip work, close this issue

**Comment by thebigsmileXD** [comment]
Crafting is still buggy

**Comment by Jelly9912** [comment]
Yup 😞
