### ISSUE TITLE
iProtector doesn't work

### ISSUE THREAD

**Issue by daany123** [ImagicalCorp/ImagicalMine#374]
When I use the flag, it doesn't change anything, the area still editable. Please check the code because I don't think that is iProtector error, thx :smile:

**Comment by ZombiePower** [comment]
it is

**Comment by BlackShadow1** [comment]
Try /area flag <areaname>  edit

**Comment by smyb** [comment]
plugin fault

**Comment by robske110** [comment]
Nope

**Comment by NML32** [comment]
Spawn protection and iProtect seem to be working fine for me. I'm using build 160 from Jenkins.

**Comment by BlackShadow1** [comment]
iProtector work. @ImagicalCorporation close this issue.
