### ISSUE TITLE
When a Block Y<=2 , Spawn Entity over it can fall pass into it

### ISSUE THREAD

**Issue by aodzip** [ImagicalCorp/ImagicalMine#375]
seems that onGround didn't work correctly when entity first spawn to(or fall to) pos Y<=2

**Comment by aodzip** [comment]
https://github.com/ImagicalCorp/ImagicalMine/issues/290
I think this is the same issue

I test spawn at $nbt->Pos[1]+600 , If there is a block->y>=3 , entity will stand on the block 
If the block->Y<=2 , Entity will direct fall pass the block and drop in void

**Comment by robske110** [comment]
That happens on my spawn too, but it's way over y=2 (around y=50)
Especially when you are in the water, and join again then you will glitch through the block be there again...

**Comment by thebigsmileXD** [comment]
Maybe everything is offset, thats why you don't sleep in bed correctly and water doesn't remove fall damage

**Comment by robske110** [comment]
YES
I realy think it is so, because in my spawn the players spawn not in the middle of the block!
![image](https://cloud.githubusercontent.com/assets/16020100/11991691/7f87b3f0-aa1d-11e5-8d14-81b92b86bde8.png)

**Comment by MCPEPIG** [comment]
It has nothing to do with onGround(), it's something to do with the fix for #290

**Comment by thebigsmileXD** [comment]
Then i'll go and fix it

**Comment by thebigsmileXD** [comment]
And they don't spawn in the middle because setspawn has integer as number.
0,0,0 is the most north east point of a block.
