### ISSUE TITLE
Black skins

### ISSUE THREAD

**Issue by GAalexandres** [ImagicalCorp/ImagicalMine#376]
Some players skin are black, I'm using the #148 build from jenkins.
Oh and if I join with an alex format skin it says "Invalid or corrupt skin", I've slapper on the server to make npc, I had to remove these 2 lines because if a player join when a npc is spawned it will crash the server:

$pk->skin = $player->getSkinData();
			    ~~$pk->slim = $player->isSkinSlim();~~
			} else {
			    $pk->skin = $this->skin;
               ~~$pk->slim = $this->isSlim;~~

**Comment by thebigsmileXD** [comment]
Official bug.

**Comment by keithkfng** [comment]
The slapper issue is a bug with Slapper itself. Don't contact us for those kind of issues.

**Comment by thebigsmileXD** [comment]
Slapper? Wasn't even mentioned

**Comment by GAalexandres** [comment]
@keithkfng it with the #323 build works, but when I use the #148 jenkins build it doesn't work, I don't think is slapper related.

**Comment by robske110** [comment]
I have fixed slapper (since 0.13.1 doesn't use isSlim anymore) Will soon make a pull request to th offical author!
And the skin bug is an MCPE bug the CLIENT handles it wrong on Windows10 it does never work ios half half android (no device lol)

**Comment by GAalexandres** [comment]
Oh ok

**Comment by robske110** [comment]
Or just replace in Slapper/Main.php at line 134 with $isSlim = $sender->getSkinName();

**Comment by robske110** [comment]
AND REOPEN THIS 
###BLACK SKINS
ARE AN BUG

**Comment by GAalexandres** [comment]
same here

**Comment by keithkfng** [comment]
It isn't. It's an MCPE BUG FOR GOODNESS SAKE

**Comment by robske110** [comment]
I known it

**Comment by keithkfng** [comment]
?

**Comment by keithkfng** [comment]
You see it with PocketMine as well. You see it on other servers who run MiNET sometimes... So what is i other than an MCPE bug...

**Comment by GAalexandres** [comment]
Ok but now it is worse, before with the build on github was better
