### ISSUE TITLE
Pressure Plates and doors not working after new redstone implementation.

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#377]
The doors wont open anymore with pressureplates after the new redstone implementation.
Also the redstone is not powered when a pressureplate is next to the block and pressed.

This all worked before the new redstone implementations.

For the time being I removed my iron doors in buildings.. Not nice when you spawned inside such buildings hehe no escape possible :P

**Comment by HimbeersaftLP** [comment]
Look at: https://github.com/ImagicalCorp/ImagicalMine/issues/367

**Comment by aodzip** [comment]
After fix i will close this

**Comment by BlackShadow1** [comment]
This is fixed..
