### ISSUE TITLE
Doors broken after new redstone implementation

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#378]
Doors where working well before. At this moment you have a splitted door after a few times open/close and it will split when a block is placed in front of a door and removed it.

![screenshot_3](https://cloud.githubusercontent.com/assets/1059028/11994143/342ef036-aa3a-11e5-81f8-95c69819d96e.png)

btw i always refer to latest build from jenkins. (152 at the moment)

**Comment by thebigsmileXD** [comment]
Why closed? They still do not work

**Comment by keithkfng** [comment]
This is a duplicated issue. See the label? XD

**Comment by thebigsmileXD** [comment]
No, mail only xD

**Comment by keithkfng** [comment]
LOL you should start using a computer XD

**Comment by thebigsmileXD** [comment]
Well i could, but i am too lazy to start it, plug it in etc
