### ISSUE TITLE
[Management]Should we allow multiple language bug report?

### ISSUE THREAD

**Issue by aodzip** [ImagicalCorp/ImagicalMine#379]
We have many dev speak different language 
Should we allow Multiple language bug report 
and We translate it into English for others.

For example , I can translate Chinese to English . So , If anyone report a bug in Chinese , I will translate it into English.

**Comment by HimbeersaftLP** [comment]
Well, I can translate from German, but, I think, @thebigsmileXD is better in it...

**Comment by robske110** [comment]
I can translate from german, too and I thin quite well

**Comment by HimbeersaftLP** [comment]
I think your English is better than mine, so, you can do it...

**Comment by robske110** [comment]
* Chinese: Supported by @aodzip. Forms: Read,AnswerInChinese,TranslateToEnglish
* German: Supported by @thebigsmileXD and @robske110 Forms: Read,AnswerInGerman,TranslateToEnglish @HimbeersaftLP Forms: Read,AnswerInGerman

**Comment by thebigsmileXD** [comment]
I am totally against that. Why should i want to do that? I have to spend my time in a better way

**Comment by robske110** [comment]
Translating: I agree
Answering: It makes not much difference
Reading: It makes not much difference

**Comment by thebigsmileXD** [comment]
I will not do anything.

**Comment by aodzip** [comment]
I do Chinese things

**Comment by robske110** [comment]
* Chinese: Supported by @aodzip. Forms: Read,AnswerInChinese,TranslateToEnglish
* German: Supported by ~~@thebigsmileXD and~~ @robske110 Forms: Read,AnswerInGerman,TranslateToEnglish 
  * @HimbeersaftLP Forms: Read,AnswerInGerman

**Comment by matcracker** [comment]
Italian for me!

**Comment by BlackShadow1** [comment]
Italian for me too.

**Comment by keithkfng** [comment]
I shall translate English XD

**Comment by SavionLegendZzz** [comment]
i can translate spanish to english(some spanish)

**Comment by robske110** [comment]
@keithkfng from wich language

**Comment by aodzip** [comment]
From English
ahhhhhhhhhahhaha

**Comment by keithkfng** [comment]
I translate English to English. Very simple.

**Comment by robske110** [comment]
* Chinese: Supported by @aodzip. Forms: Read,AnswerInChinese,TranslateToEnglish
*German: Supported by @robske110 Forms: Read,AnswerInGerman,TranslateToEnglish
  * @HimbeersaftLP Forms: Read,AnswerInGerman
* Spanish: Supported by @SavionLegendZzz Forms: Read,TranslateToGerman

**Comment by InfornoFire** [comment]
Ah hem, i love to say JUST GOOGLE TRANSLATE IT ISNT DIFFICULT

**Comment by tankisu01** [comment]
Russian for me!

**Comment by thebigsmileXD** [comment]
:+1:

**Comment by keithkfng** [comment]
Okay, okay, okay. Translation then. But this doesn't match the contributing guidelines - https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
STRICT XD

**Comment by robske110** [comment]
You are able to change them :P

**Comment by keithkfng** [comment]
I won't. I want to keep the issues list small and tidy.

**Comment by robske110** [comment]
We don't need to keep this issue open, but are we now allowed to answer in multiple languages and translate them to english

**Comment by HimbeersaftLP** [comment]
Jay

**Comment by robske110** [comment]
What ^yay^ @keithkfng didn't allow us to answer in multiple languages

**Comment by HimbeersaftLP** [comment]
Jay

**Comment by keithkfng** [comment]
You are, I just said the issue didn't match the contributing guidelines -_-

**Comment by HimbeersaftLP** [comment]
A real 'Jay' now...
