### ISSUE TITLE
Can't break boats/no different boat types

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalCorp/ImagicalMine#386]
If a admin or me places a boat on my server they cannot break the boats, my server has 5 boats at spawn please fix soon

**Comment by robske110** [comment]
Confirmed you cannot break boats at all!

**Comment by thebigsmileXD** [comment]
As i said. Waiting for bugs and crashes with boats.

**Comment by robske110** [comment]
That is an CRITICAL Bug

**Comment by thebigsmileXD** [comment]
Known issue. Boat types also not different.
I'll work on this..

**Comment by CraftingMania** [comment]
use clearlagg and do /lagg clearall it will remove all boats

**Comment by thebigsmileXD** [comment]
Boats removed. They aren't even entities. BoatEntity was the entity spawned, but didn't exist

**Comment by MCPEPIG** [comment]
Boats are entities... Did you not know?!?

**Comment by thebigsmileXD** [comment]
*facepalms so hard that my hand and head turn red*
If you could read, the whole world would be happy.

I won't even explain.. Too dumb, but because its christmas, heres a link:
https://github.com/ImagicalCorp/ImagicalMine/tree/master/src/pocketmine/entity

**Comment by EpicSteve33** [comment]
I have clear lagg and boats are not going away its annoying this isn't fixed

**Comment by EpicSteve33** [comment]
I can't get rid of boats they are everywhere
