### ISSUE TITLE
how to turn off the thunder?

### ISSUE THREAD

**Issue by miker059** [ImagicalCorp/ImagicalMine#387]
please help

**Comment by thebigsmileXD** [comment]
Really annoying. Weather should be removed again

**Comment by matcracker** [comment]
I think the #380 must be reverted... I'm rewriting the weather with more API for devs and collocated in the right files

**Comment by keithkfng** [comment]
This doesn't match the contributing guidelines - https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
Please review your issue's opening post and edit it to match it.

**Comment by keithkfng** [comment]
Didn't mean to close that, stupid GitHub.

**Comment by thebigsmileXD** [comment]
Thunder should be first of all removed again.

**Comment by matcracker** [comment]
I do a branch for the weather, isn't complete yet

**Comment by dterweij** [comment]
Like the weather :) Better then only sun and night haha
Just a thing, if I am correct I do miss a /weather command. I did saw my kids on pc versions do /weather clear command or is that a plugin ?

**Comment by robske110** [comment]
That command is on pc. If weather gets implemented correctly they will be able to do that as default cmd and plugins should be able to do that to... #API

**Comment by matcracker** [comment]
I'm fixing the last bugs so I can merge it :)

**Comment by matcracker** [comment]
Fixed

**Comment by miker059** [comment]
thank you)

**Comment by miker059** [comment]
now all the time it's snowing or raining... (. How to completely disable the weather in the server settings?

**Comment by thebigsmileXD** [comment]
We'll maybe add a switch in the pocketmine.yml

**Comment by miker059** [comment]
why it's raining constantly, just either stronger or weaker?

**Comment by matcracker** [comment]
You can use the command /weather clear for return the sunny :)
