### ISSUE TITLE
when the bench will be able to make stone items? 

### ISSUE THREAD

**Issue by miker059** [ImagicalCorp/ImagicalMine#388]
stairs, carved blocks, etc.

**Comment by thebigsmileXD** [comment]
.. I wonder that the StoneCutter is back -.-

**Comment by keithkfng** [comment]
I'm starting to be more strict. https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
This doesn't match the guidelines. Please review them before posting an issue. Be more descriptive, in other words.
