### ISSUE TITLE
SERVER CRASH BREWING STAND

### ISSUE THREAD

**Issue by NycuRO** [ImagicalCorp/ImagicalMine#390]
Server crash!
Please fix :

 "Fatal error: Call to undefiled method pocketmine\inventory\CraftingManager::matchBrewingRecipe() in phar::///root/PocketMine-MP.phar/src/pocketmine/tile/BrewingStand.php on line 181 " 

Fix please.. :(

**Comment by thebigsmileXD** [comment]
I never saw
"Undefiled"

**Comment by Taki21** [comment]
Replaced "n" with "l" ...Jus' Undefined XD

**Comment by thebigsmileXD** [comment]
And please remove all old brewing stands 😅

**Comment by thebigsmileXD** [comment]
Sure? Not because a file is missing?

**Comment by BlackShadow1** [comment]
it's only a missed function, can anyone test it?
