### ISSUE TITLE
getchunk() error

### ISSUE THREAD

**Issue by CLiu13** [ImagicalCorp/ImagicalMine#393]
[CrashDump_Fri_Dec_25-16.04.32-UTC_2015.txt](https://github.com/ImagicalCorp/ImagicalMine/files/72216/CrashDump_Fri_Dec_25-16.04.32-UTC_2015.txt)

**Comment by thebigsmileXD** [comment]
https://qsnapnet.com/snaps/2raarm9m8y4d952
Just to see what happened.

**Comment by thebigsmileXD** [comment]
I am sure its MyPlot or ManyWorlds. Have you created the world with ManyWorlds?

**Comment by CLiu13** [comment]
It is because of SpleefPE I believe; the world unloads every time so that it can reset. However, I don't know what is the true cause of this. I have created a MyPlot world, but with /p generate, not ManyWorlds.

**Comment by thebigsmileXD** [comment]
-.-"
SpleefPE isn't finished at all!

**Comment by CLiu13** [comment]
Ok. Is there anything I can do to try to fix this myself?

**Comment by thebigsmileXD** [comment]
Yes. Uninstall it.

**Comment by robske110** [comment]
That was an realy rude and funny answer <-You manage to get me write such things in an developer chat...

**Comment by thebigsmileXD** [comment]
I updated the Readme in SpleefPE.
