### ISSUE TITLE
Generator bug

### ISSUE THREAD

**Issue by Ad5001** [ImagicalCorp/ImagicalMine#394]
When I start my server , it crash.
Here is the crash dumb the only thing I know its about world generators name

PocketMine-MP Crash Dump Fri Dec 25 16:34:46 UTC 2015

Error: Class name must be a valid object or a string
File: /src/pocketmine/Server
Line: 1153
Type: E_ERROR

Code:
[1144] 		}
[1145] 
[1146] 		if(($provider = LevelProviderManager::getProviderByName($providerName = $this->getProperty("level-settings.default-format", "mcregion"))) === null){
[1147] 			$provider = LevelProviderManager::getProviderByName($providerName = "mcregion");
[1148] 		}
[1149] 
[1150] 		try{
[1151] 			$path = $this->getDataPath() . "worlds/" . $name . "/";
[1152] 			/** @var \pocketmine\level\format\LevelProvider $provider */
[1153] 			$provider::generate($path, $name, $seed, $generator, $options);
[1154] 
[1155] 			$level = new Level($this, $name, $path, $provider);
[1156] 			$this->levels[$level->getId()] = $level;
[1157] 
[1158] 			$level->initLevel();
[1159] 
[1160] 			$level->setTickRate($this->baseTickRate);
[1161] 		}catch(\Exception $e){
[1162] 			$this->logger->error($this->getLanguage()->translateString("pocketmine.level.generateError", [$name, $e->getMessage()]));
[1163] 			if($this->logger instanceof MainLogger){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux s5 2.6.32-042stab113.10 #1 SMP Mon Nov 30 10:34:34 MSK 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
HelpOp 1.0.4 by hoyinm for API(s) 1.9.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
PerWorldChat 1.2 by EvolSoft for API(s) 1.10.0
ReasonWL 1.1 by CreeperFace for API(s) 1.12.0
WorldGM 8 by Exxarion for API(s) 1.12.0
SurvivalGames 1 by LegendOfMCPE for API(s) 1.0.0
Slapper 1.2.5 by jojoe77777 for API(s) 1.12.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
SimpleBroadcast 1 by Dutok for API(s) 1.0.0
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
SurvivalGamesPE 0.0.1.beta by kvetinac97, Creeperface01 for API(s) 1.13.0
ArtificialIntelligent 0.1 by onebone for API(s) 1.12.0
AntiTower 1 by xpyctum for API(s) 1.0.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
TNTRun 1.0.0 by ItalianDevs4PM, Flavius12, fycarman, luca28pet, XEmAX32, xionbig for API(s) 1.12.0
WorldPlayerLimiter 0.4 B2 by EvolSoft for API(s) 1.4.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
mcg76_CTF 1.5.2 by minecraftgenius76, MCG76 for API(s) 1.8.0
EconomyPotionDispenser 0.0.1 alpha by Khinenw for API(s) 1.12.0
FloatingTexter 1.1 by Heromine/Jon, Flavius12 for API(s) 1.12.0
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
Unlimited 1.0.0 by Primus for API(s) 1.12.0, 1.13.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
AdminJoin 1.3.1 by ZacHack for API(s) 1.12.0
PowerMute 1.0.0 by Falkirks for API(s) 1.7.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
BanClient 1.0.1 by luca28pet for API(s) 1.12.0
GodMode 2.3 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
LightningJoin 0.4 by Jelly9912 for API(s) 1.13.0
SpleefPE 1.0.0 by thebigsmileXD for API(s) 1.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
SkyBlock 1.5.6 by  for API(s) 1.12.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
ServerChannels 1.2 by EvolSoft for API(s) 1.11.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
MultiInventory 1 by luca28pet for API(s) 1.12.0
2BitCmds 1.0.0 by 2BitRealms Dev Team, DevBrad, Lilcrispy2o9, 64FF00 for API(s) 1.12.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
REChatFilter 1.0.0 by MinecrafterJPN for API(s) 1.3.1
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
ToyBox 1.2.1 by aliuly for API(s) 1.10.0, 1.12.0
UUIDBanning 1.0 by Savion for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
Portal 3.0.1 by ljyloo for API(s) 1.0.0
CrateKeys 1.0 by Savion for API(s) 1.12.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
WalkingParticles 2.0.0 beta by CyberCube-HK Team & hoyinm14mc for API(s) 1.13.0, 2.0.0
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
GrabBag 2.4.1 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
MyPlot 1 by Wies and Exxarion for API(s) 1.0.0
SimplePortals 0.0.3 by Falkirks for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrVPA1z2zayfwWjdN7ZHUnWl2VHHXcu8Uea1k70Yuelc+WNByJBiTFJsARpW73pf79dfJAAZcey
pevc613G4pLYb+wuliD+1SqihLUm/dF+vzfuDw7H7RbLc563Jv9qFcsMbrVOr08/ffr4qdVuJUwI
OkfYcUyFIClNGElKUZAZI5Tc0jgKCJ99ZX5BeA4QUeRROoeRYRTjsD2R+3sZ929YkUQp27tk+S3L
4X4MV8BFf3/4Z7uVxeU8SluTkMaCtVs+Dxiy0++PRoDDK7ziTxgCl/twqX6N9Y0o3Nn5Lsv5bRSw
nByRc3bL4qm+vqApcJ9PJnNWGNjb5QcQoh6DVzDuu2IRic6P6sGM5cVyx2vFiKwjWFGAUKIbsJCW
cdEJeZ7Qwmu1iddK/JzNI556rd3dXXJ0dETSMo53/6W4PNBcesU2eHSo/aAoHLoKem0UtN/TN4p8
qZjZ71vM0GLhCH1CCzoF4M4u6QKdO57HgdjzWnD1nTQ6QuFaUd0fVKj2vv+e/P2W5sTzajN7ntSc
52lNeY7EpNbF93sK33BVT6iQlOW0QD0AZ23FCPwRjAXwR9/mOfzmWQFaEVop+6NKC/s1YskSCJ2y
O2WBHSl+jVdTMQwYZOMahVKXRCR+Uwil9t4HO7v/RH1KkB53UDFx2GCi82OURoXiwVCpDDfurTwN
DngV+TefpC4UDzMqmIFpFGNj3z99WviLHc87vfeZVAz5jmmPHA9WpOFzcL/OjzII7NQecU7TeQme
ubPb+bHIaSpiIHUppzfMjNrWXclk1xjrFNHg1PjNqJVJdBcqkoCedg2/tdFhEjvckCgVBU19xkNy
QaP0XEJBBIgVwIsP0eG31qse2dmdENvrVHTp/OjnVCxOyiTbmXEeM5rutv7ZbikWY4ws8JQAvQAD
/e44YLfA0KyM4qA16UE0ynnBfQ4PDg/bLZpF8rH+sNuHx+ZRAZe9Nf+DATm9iaMZjukedBFQol7g
+jxKy3si9smgO+4OB53eaABCz/pIqEde9cnlxZRcgPE+8Fsy7JF+bzIcwf/JxeUvZNDr75P7w/H1
eAQos0UGCPcBTx8p/MFSkKSFeHvq7jUXhiIA5EUsL6rgK1AtP7E4+5jhL82jBrQdhfW6SJOWxYLn
Ai2x4MsoTVDFUlm/wTOvgTJcs5TOYhZUkT1gGfCGg+Cm4GFxYgMSiklAo/M8Rdz8xZzBKco1/Xh5
9eXjp/MTAN2xmYgKZHVRFNlkb+/u7q7rL2cs98sZ6yxuuj5PUMromKdFzuPPlnQ1zBKw3x06wp3R
+CbKb4Qj3ngD8SJfUS09z2bgW8JhSgEZpiz/goH5eEELSwwH7Jpq4Brq9JbHl8CWI0u/1xCmyMt1
ZbFJex5O1VqSy6s3n64+T1eMJLSVGDCDeLvFDRroE6OCp1/OLcEqkGOeviPScc6Ar/wMg4Ij1WAD
E+WacFOkbxlH6uHdhcW+gVjcH7rmuL+nOcK3xrgm6Xk17XUmDYUYIDoQNStrXJb5bQTl3TsQRVgy
uXDbLo5k5wyCbfAxvDienjrS9TYQTmjac6T9HNNcxjQDH7HF0JDGbOnuu/PlK//K2QH+tz0TCUXa
85K1+b+4zOhdapvBQFz+99eZ7f2Xz3ZNdcOJfhklWcze5jDYp8IOZM07j7rXSVnwm635VYMslBEr
fKxhpDcBMFtEAuqjX6Aws8Rq3mlm055jtm1JdULzmw9DAdZq0F8BrDmJ7JkPs/qRmAB3bPlAgm6/
O2MFdX3z5pbBmor6rw8ArmN4CDG813e9dfhyb3XYAqM2ItfjzmsMCioKIz+i8fu0YHEcQUizvfXh
+67wfVdqnrIZ/NteMNEIPY9WzEQ1M2DpR3hcx5/TIrrid07YrGGPTs37bOkXZbK1yVmRBGEs6msI
cAZT9woXLqEjgwNuTsVGvSQWfL6I/GyL0V9j9DybD/dqvcgKC5FFOcPyds8g3XOwgAquooQd8ySh
aeDowIVbShi4Wfzk1xU7tlED+u9A/x3qv6MNFAO0PM/h6zkZ/rgUBU/exBDW7DTpgF1bj9fJlZtY
2qbteQ1OnrDvw4nzFBYOPFm+mb63RLSAtoDAeff108HnMYsOZOSqLTvU16PK0v3NYxZTrAMznueI
sW61fRpEBUS4ZsltwCt59hrz0DUs969f9UaHrnampxc0u+ABTohtxa6MJTRLJE7Pky01BqxBqNb1
ec3ok0V6Y8Zb3O5dJjSOO/847kzVQn6vgHS6l0AogJsOnar4egNyr9RdEujq7KCZwKay2XIRpYxc
MZrAze2HyJobU4lpzp4XFGtW9yws2AmY5rxgfsHtiGgBbRWA3zcKl2ZMfL1pzKsprxXwHhIV8HRw
pbVnSYHR/8PVpzK1w74CfLv+bL0voIig6Qm7FaMpriDPYnoblaKPyTFc+jSH+Ixclj4dHGYM/ffX
0+TNr0N84B7wzqL59txBMf1i3bjS7GkVmAgyjemS5edRAuPzZhxxb7qF3Yi8Xae3Mtp0Le/wsOHC
61QIqP6gFnTLdwfs+gYE/tYD63qhFvYqBGzN0DYfnncOIj5Z6T04GazWw54jG3bQypy9e39pN880
5IlJMR6dnfV62xP2WiH0PE2/+vH8OAfjTOQ3OEDS9wVLjqlgjqktYFPeRjqESVPGy9U+YfuhRdlz
BFeIIewBK7C4hieeU+cl/vxgfH18dWYJVcMa3ZBmNY/vCGSPCxwE4tkBloAXx+/gry3m4QbCSVY8
DxtUnucXIdR9V2donPfpM9rXS14W5YxJ65YCkvgq43U1OOX4guckEsCNcGLYIw+srM4JjbNFI8v9
sgCS6d0z/d0uRr+hJY0cXN5lzfNsLtdZ4cEz+Gb2it274btxoxHUXFF/YjmXr6Z/5mmb1Llua1Pd
ZWaNGK6lA2XMy0iwC2ZJZgG/0RTf+juLQJNFv3ZYWMNKn9NYpq/AEqOGPRF3p3mUlGLVGBvHoUwi
9rzScOJ5NlPrNMSqqhJfULnt5eat5tJs9HS0fXq2WWXtGgF3ITl5cR1FY/YVluU5B3TWho5O9sCi
Y0V82R6Fx3/mUeo0Rg3M9YJhc47+g/o/Uf9me3Oyoqz0ITe3rPkODhtQF2VhT8oa9oQ3PzgvDzbx
YqScAGUMpjUTa8mRldlKw8SGNmzyn+6XWKTXrXMfLnOvaHbFT7i97tEQdxYOml6G1tna2r+gWcED
7nk18TWs8paCL0Zun7mGNb2rwX+9INuaUSraL44bFVN7tRwg6DseXOhdXlpMA7G7kY1X8X95P1Lz
9JwK9TyaL4oU0n0j1rlwS0hIBo6QP7M4Xr5+3axANsl1kvazXphC+Gah+5LHgJ4IccWCwfJfJFHM
fj3Z3myysXqeYeY5Muna9HLBs9UiWUKbSfpgGy9v1qyJm01RAQxVXVHN3TqGu1m+jbnz9rECNVdH
40dfO27WvtP0nmObM+rL/XvTnDtvampos0BoLO2uGHhIzoLrLZbtNXV8PSMv1pdIrsohNYtGq0HB
mtsOBn9hs0FyYP3cuOGgsIDM/8cL9ond0dyu9C2gE9n7L47sG0X0mp1nxUO5r/B4QdOUxc52GPfG
CzZf9TeZag71zaomWRGflSvl+dnTDWO1X68/SvxvrNPaMqRuWLGfYSPYYmudiqpcHmPrxC6oDKg5
DftrVOubyDArl7KN43kWC+vs/ynjInqf3kLtxPOlvQ3IvfHoS/n/QGXokn7OZBq8jYrjJLCnUQV6
wtPwuU+MxokgJ+zWvIKCn29zivHlPIr9PBLZcsDx5efW42hN3/OuLabXeUO9YKI4x3Wz3Siwoc8P
Hpu0Ki3Km27cPMXdn2dR7PbgHPATdr0wDU6W/zz94Mg43OBNs4vW8xosPXcp46LTLxjflZBL9lpV
kgBVxisJQgKbjdeGhQvhL3JASXbMr/5g+Pc5iBIj9d3t1dIavdkuj8zZv5/RqTaouimTqzpZ+J2G
IfOdroIDbrpCY9Piu+TLxfZmLGKDaGvRd6/Wm7tXfPmW39sNBQV4In988x3KYAvvUAq+nPH77bT0
ZjR4sJenRcU+7uf3J7CGxzWs3cm1oA3Tutq4pLdb3eqs8L1gBfgzn60uABH4RJP2v3X/zFc+q1aK
Soy12n95QWOn8ycB7uaH1RbT12XM+dZCkSKKvUv8u24n9sFFyTKnSRRgRbCnsMmYfIyfJP3Cls6m
sAr2l/rr8S/P8dULmi7lBgBn13cNbPrqcL3Qs2nESYAD9W3gsz6NwEI6nU9xk6ofO98TrNxqCtYj
q5uHj/H7nmP8vuenX2QRSP6HPLYI2cbao8mk5z3A9voB6JymwWoEktAXbOH7j7WgYmCoCiyauzWE
fJfT2VtqpwgDcYUbPStd9u28+TJ7ujt/V317DmzO6PwveUNmVGL1JVkcP9CXROh/VV8SGKr7koq7
Ndthza/WDKjZ2hs+3Qx7smli9doe8oO6r/hIk0x9z2axuFmLTCKpXhl/oXm28rJYAl1L99d6ffiC
pNTcA38Z8zvr0tk0VSso1NQ9T0iO74Bjs0NTc79OYltOY277gQY82rv4EjFBYF6RB7+We0EYcLYa
612i4OJLS1TFE0QCw9uTmzWUGlTlIVaMa+DNJeBwHfv21twIIG3wjanctF+mmDImrHl80or40TCF
eotBKDM6lsvHbqbOTogwx7deTasrcszTMJoTPBXCS1+d5RE5YT4Z7JP+GL9qHvXI56tj+VWzlya8
CI6qxfaETE+JWp166d0CuOjEkSiOoPZPYd3By9THGIvbJDvUX0TsliXgvkI+IPCDtU6mdsWC3o/6
YxgVg793whjfillP0TRKQAEWJOEzdYkbuhIesKOel4Y8B4IVhIehly5oHvg811fZbSZHBVEYRn4Z
F0scVx1XUJ0nceSl5oAJFlQXeAbH0dn5mysvVSbv/F6yfCkxakAOHqxI4a9uBiUzFGXB0ffyPxCw
LHhH0FumlCTFTeUbEgm4jdhdJ4jUF/ZAl6d4GEdHiWMJn2KqUgpYQKSXdZ+8ylkgCpgyHZ/GIB+V
mpUj1ff3UXaE3g3/q0DobEf918N9ACX0XhtMHOG1khsnzJGkgZ+s18cLLJMYfUmeA0B86UZlLklK
byJgD1Lv9e5cTD3wk1fkasEEI0bVhOaMgAIIcC3gBy2Ij84jzzGJUj8uAxbAD7LixwrbJU9gbIgo
mlgFDVmbcNSuQKRkljN6Q5a8zDU2EoUElBuFkaQBjpKDN0LJIVF/YHcVwj19woggdzz9W0HwS1Ga
E7RnAiKDuuMliEDwrAQl/d2CpaTMoHYJAEEXUeI/g3CCF+TV1QJqj04MQOAm1gc7EDxmRapP20hE
cB1zoBL9IRWsBh8vmK/lcYcCIyb3sbR7F91EGQsi2uX5fA+v9s7Bx655eP3+8uP1ePi6M7jGcVKl
FaoJ8VphTr2WIvZlIf2UFBy4gqAPEuszZcBs5hSKQN2WupX8Mjx8BsSTJg7YbeQzsoCcEUujJxK1
mrc1WRlG5R2xKIuAo8urMyqQJRVwiB9zwQLD3BucSQSjD/BDdF1HbiNK/henqHxITlZT800Ifq+o
Bl8uYCxFDxYc+NK0lAGpRkZKAe4JkR0cRMoJSQqehAQRKK3VtzrA3gyYs0mcyvBgcGHOxKBEwJnB
V5Dl2ZJoD5MDdDip7ttKefUlAtVDaFgSGgQkZ0L5JbILnngDbFEBpQ3GWgLeOGOoGzAD+72kMRpo
Ht3Cs7c0LhnZ0WQhwu9K9IomhDKZhjpgYTzhYwL3FfUPZQJrPJxyb8Qy9a+ouIE5kd/AJOuqJz6D
YaT3GnHxuUUOub0EV4HnRZvIcEJ05I1wfydUZ6BBgTlYKggSG8KSMoXZhY9o7JfSmUAumII5v4fM
UDBQBYglJ0JasYcaNiy9D3Em40M4Y9skKv4GOixyOS5gmIOkhzZGkx2QAixPBko3UpKOlnYicZl5
jUknX+pZ/S7mM1A15nuibhC5gRHjWMLmdLYsgDVyqVjqSSYigSY3UQHku4ski1L9BBOFwmQsokqv
MAI3gtDG8HUP4gkhnhiayiVArFI69JyDRBwnD+pPUppLRjuSuQnpGWHIKxnTCwhONPh/IAbWUU8I
gYXAhkJAZs0kHzrAVXxpfILAtMOUD3Gp4grpGtb6vcGo5g4WQRGXqQ1nrUDCvgzomstqZvaBIASn
QPmgfKaDnTIzJ3Uy4LAySGFGgy4xojymaqViKNdimScwNqjHFHaFBWZqPfNNGFN0PmLgwbwpB3VX
B6AidEkMas2Yj+lVSEUh10rvamwlCuiWZaIWedjTMovdR9jSGhjWGpjTfAb+0fF5HKuaUs3GBzUt
HQ5Z0qOIHgXzPaFpKdO5zQ0UPCX4yW7bxJEVR9GeouKyfIch8Se1D3bJR5VB5RV4y4KXcVCxEkHc
uUtJzb7ybZJJ7kHUca9XS0tenck5sxJbpR8pHJVwYc4TE6TVaP1Ex45oDUuDQNqgq27ygHc1RmMp
6S/K9EYYK8hPpWRolWDkE9czKB9RRWdbTuscih2hHupgpYHVU41NITNOoCfW67HF9QlXg5umxcSC
FZoa6uJR1PSDW9WDTHRQjoOvG01orzFE8ZZVKzyJEv/BmgFtZhWR4EyxyrozPGNMlkEUa29ItuCB
OsrJyatKZX1XhbYZq/KvDl6v7IBo7mHwyJcFYm+TTt+aAirPStKdwrADAWp/bKJTnd3VcW8lVgky
hGojq9EA1Jx1yU+wDpTH8iVYLB1PP7dhLHAxgzh2FwXFQmUEHSEqAh1JYEIOqnKkLlWEVJH1cJe8
CWAuLmgc7sESRFVQAQN/1MSArPJTntqT2aoHLGxOnXZ6j1MXyzAat1VgQOJfohRqWhAP3IrJaYAV
xudpOjX1Sb2iwBIMB8ltUYi0zNKsowFuXYj/AjYr55Oq5PmR9LHU0dkLq1z5gKlwhYyIC2YqX1X9
K9317bpVkD1YkhYluNLe3DfqxrMARIMB91jGyj2ZKW6JOnZQrfPUaX2KO1SBdAYflFtoH3RPdZyQ
6oxFI6A8cwTZx1NThApz1KEBERnXkoXFAii5WOVIzm1t1lcfPl6dToiM5/B/v4RlYQrLQolKtmTQ
qJpJTb1i0nKAN44tfVj3QDTSUks/k6kP+EG/KtC3Bj2dojAoqgyoHA37BnhHp70qWrg3TDw0tfol
TnAUFg8ltEju9GFSPUCrTQZwo//QDVb43V09yQWzedGugmceykWhbiAQBoFN0cSSQ1lXLsbrVToG
D7lyw0pOhRAa39GlUPg1poaPOZlBu9ibhJepnVyEriMNMygK4lRLHIj4eDEho28NpzlAAyWHwtPM
bKT/evAIBul9KVMr4hlTGGcsxEgm2zgY8dA0FmbV3rHCp4mel/QWD3WFuhOPkfmD4fIxW+q2h852
VVklg0wo32aY0FoFwrCM5YNcgDt3cFJHvkpRcgGZY5cBXAYQG8V95biCUzNI4HGjeEitcnxMXJUm
HjARqrg20QW9J7SpJVjB+TLn1N7StJB25U80iEphDdXWoZpTOa3NcO2dOALqJhXXsKfYKbMAfNZm
l/gxo4qY7F66uVYJUi9Ta1m6q8LoaHpHI9mF+L1kJdPWN2dwBqYTUbKOAENOyOELMWY8K+MKo77C
5LeCHP/J+dwBrSoBVEO1I/1NoI6VknVjsYL3qxCDLcsJMQWoMT2e31lmUH7VdalyYRmGTLlj2pWQ
kNVoTR4J7CvAHUWyFVhDaTLDj1LMY/hPhjvVmZiYEIfNFDxVlCi4yvDasYzv6/WIFThxZnSw6dWE
VcmrAc8WWZSG3HadBUd/kcS7Vl8UirOK35SnywSXLXKuCbCDsBjHFZl+gNQPSAHATymh8zlkPN0g
qRpRWNPiWas3j0unOEOU4jHOUJNqOminWMUC3qSemBgz5WlHFwt2xSrhPHOaasfYb5UtPxbzDPNl
W+4XwEYUHqZqSkaonEKo+RkYQ+2WnsjHqhRfog1hlluIiH5VY9U2JZTJolAp1gRWjU9ZUD1gaIgV
VeGeuUcUFUeQ8IzVTu8p5n9ziUUV0NIMTQxn+iZMGuwZTMhv+LMDqa4tmwj/NLhV5K3LJLuDLQUz
6yG1VDXvKeQa9KGWuFzgy4wqZDWDqkhwOzCwrAsPRwxNWbKhfxN85YEhQafGmuqE4LuPyeCHg/b+
6/t+e3g/bA9+6P8QQIWgouMOvkj3MYYdHfbIHOaFUFej/d1Wu4VfWaeoHvka7hgyoX00LvqZfQ3J
aF69Ust8fFhfiN/jqGBDdXBvR50R/Ic6yVftQZj5UHUt6kPLaQxzjeY1QJ2mbq7KPK4uQr1ZFk+I
U295wyKr7s7rl3zzpAYvIABUG5W+CmfXYTLTB6+bh6GIXWZFdXk5PZfUcM9p5kOVWYtZUOQ6sJWS
cRHd11rRnQS9+6CP9D6xUC92AfrdezAlC8PDWeCP92e9GaPhYTiiARuHvXF4ODpk42A0DMLgcDAm
38lDgxJeCybkjBA170vQvTzBWP8i+5IuGoF08CXhoLffG8JPSXnojw8PZ+PZzB/2guGYhkPqD0dh
EIxmB7P92cHhQcj24T9JebpAC0lBUBcFv2EpJLG8Oq3vC6M3ECyUtuQ3Uksq30DhJj984I8oU1fq
tFDJYqSH//nnvwF8Cc0+
===END CRASH DUMP===

**Comment by thebigsmileXD** [comment]
Information for team members:
Settings: FLAT world type as default. Generator settings not changed

**Comment by thebigsmileXD** [comment]
How did you try to call the world?

**Comment by Ad5001** [comment]
I have a lot of worlds but the bug happend when I install new plugins but it keeps when I uninstall them :(

**Comment by aodzip** [comment]
@thebigsmileXD 
FLAT works well (on mine)

**Comment by thebigsmileXD** [comment]
Same for me @aodzip

**Comment by Ad5001** [comment]
But I think the crash dont come from the flats worlds but idk witch one bug because everything works fine before i install & uninstall those plugins (I dont do anything with them).

**Comment by keithkfng** [comment]
1. You didn't use code blocks for the crash dump.
2. This doesn't follow the contributing guidelines - https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
