### ISSUE TITLE
Build 190 changed to 13.0?

### ISSUE THREAD

**Issue by EnderKenji** [ImagicalCorp/ImagicalMine#401]
![screenshot_2015-12-26-03-00-53](https://cloud.githubusercontent.com/assets/15629214/12004398/b597f65c-ab90-11e5-916f-31bfd5cf736b.jpg)
Look at the 'Prison' server

**Comment by thebigsmileXD** [comment]
ImagicalMine is for 0.13.1 now.

**Comment by MCPEPIG** [comment]
That doesn't answer his question.

**Comment by thebigsmileXD** [comment]
Heres the answer: The server is outdated.
@MCPEPIG Then why didn't you answer?

**Comment by MCPEPIG** [comment]
He wants to know if build 190 is for 0.13.1 or not. Fucking read.

**Comment by thebigsmileXD** [comment]
> Look at the 'Prison' server

That was what he wrote, but yeaa.
> Build 190 changed to 13.0?

From the title:
Why should the version have changed to an older one?
