### ISSUE TITLE
Crafting bug

### ISSUE THREAD

**Issue by smyb** [ImagicalCorp/ImagicalMine#402]
look at this [video](https://youtu.be/YSolxjG94Bw)

**Comment by thebigsmileXD** [comment]
Can't see a bug there..

**Comment by Jelly9912** [comment]
@thebigsmileXD Joke?

**Comment by MCPEPIG** [comment]
You must be blind, what he was holding disappeared.

**Comment by Jelly9912** [comment]
This is the most annoying bug after respawn page (i know, fixed)

**Comment by MCPEPIG** [comment]
and it's obvious what's causing it but don't want cause idgaf about getting bugs fixed right now

**Comment by thebigsmileXD** [comment]
i am blind.. Poor cookies

**Comment by Jelly9912** [comment]
And diamond axe

**Comment by MCPEPIG** [comment]
Everytime someone crafts something, an item disappears from his inventory

**Comment by BlackShadow1** [comment]
I think I can fix this.

**Comment by thebigsmileXD** [comment]
@BlackShadow1 Good luck.. btw, you cant craft any of the newly implemented items.

**Comment by BlackShadow1** [comment]
Thanks. I'm going to add them.

**Comment by MCPEPIG** [comment]
Srsly, just look at the commit history and you'll find the cause.

**Comment by BlackShadow1** [comment]
ok @MCPEPIG .

**Comment by MCPEPIG** [comment]
32a28b4d1ef5166a76518c0fcc255b677260790f

**Comment by thebigsmileXD** [comment]
It was there before that @MCPEPIG

**Comment by BlackShadow1** [comment]
Tell me if there are nw bug on the crafting, this issue i think can be close.

**Comment by Jelly9912** [comment]
I can't make many items e.g. sticks, preasure plates and... i can't make crafting table XDDD

**Comment by CLiu13** [comment]
I have the same issue too. Players can craft nearly nothing.

**Comment by ZombiePower** [comment]
hm....

**Comment by thebigsmileXD** [comment]
I tried sticks and crafting table, and chest. But only tried with oak..

**Comment by aodzip** [comment]
zzm give out a fix solution I will try later
2015年12月27日 下午3:47，"Dan" <notifications@github.com>写道：

**Comment by PeratX** [comment]
@aodzip You can port the Crafting System in Genisys to IM. Mine does not have problem.However,Genisys uses the Crafting System written by Zzm before,it has problem too.

**Comment by aodzip** [comment]
@PeratX 
I will try . and thx

**Comment by PeratX** [comment]
@aodzip I think I found the problem

**Comment by aodzip** [comment]
@PeratX 
如果你能解决这个问题是最好的
我还没有彻底理解iTX的工作模式和代码风格，做Porting 可能各种Mess up

**Comment by PeratX** [comment]
@aodzip Try it now!I have pushed!

**Comment by aodzip** [comment]
comment above I really cant explain it clearly in English sorry guys

**Comment by BlackShadow1** [comment]
The problem that some item can't be crafted is a bug, it appear after commit 
https://github.com/ImagicalCorp/ImagicalMine/commit/0af7911c6ed68db7f4883ed0f1c81918f0441d66

**Comment by PeratX** [comment]
@BlackShadow1 I will try again,thx!

**Comment by BlackShadow1** [comment]
;)

**Comment by CLiu13** [comment]
Still having issues. :(

**Comment by smyb** [comment]
is impossible to craft

**Comment by ZombiePower** [comment]
agreed... how did $item->getCompoundTag() make sense??

**Comment by BlackShadow1** [comment]
I don't know but work.

**Comment by PocketKiller** [comment]
is this fixed?

**Comment by PocketKiller** [comment]
no longer happening for me

**Comment by thebigsmileXD** [comment]
I'll check

**Comment by zzm317** [comment]
=-=
@PeratX 你什么时候用过我的craftmanager了
你特么明明给我覆盖了每次都是我都懒得修改了

**Comment by thebigsmileXD** [comment]
International chat now allowed?

**Comment by aodzip** [comment]
He just say something dont want you understand , but don't worry .

**Comment by PeratX** [comment]
@zzm317 当然用过了。。。然后你那个暴力破解失败了

**Comment by zzm317** [comment]
@PeratX 啥？

**Comment by zzm317** [comment]
@PeratX =-=反正。。这边测试下来没问题。。没有出现合成失败或者合成不减少项目的情况

**Comment by zzm317** [comment]
@thebigsmileXD just lazy to translate what i want to say into English

**Comment by thebigsmileXD** [comment]
Actually.. Crafting is fine now, no more duplicated/cheated items. Cant craft stairs ;)
We tested for several hours

**Comment by zzm317** [comment]
@thebigsmileXD I will add the things soon

**Comment by thebigsmileXD** [comment]
@zzm317 Still missing cobble stairs ;)

**Comment by zzm317** [comment]
@thebigsmileXD added

**Comment by thebigsmileXD** [comment]
Thanks. Played survival 4 hours yesterday with 6 players. Noone was complaining. (And could you answer the line note i left?)

**Comment by zzm317** [comment]
@thebigsmileXD where?

**Comment by thebigsmileXD** [comment]
idk anymore. i asked if items in the shape
```
"   "
" i "
" b "
```
have to be in exactly that position

**Comment by zzm317** [comment]
@thebigsmileXD ==
ShapedRecipe and BigShapedRecipe
must be in right order
or the table in PE will be changed

**Comment by zzm317** [comment]
@thebigsmileXD so i almost rewrite the manager..I will never want to do this again..

**Comment by thebigsmileXD** [comment]
@zzm317 i mean: if i put the ingrediants somewhere else than said in crafting manager (torch e.g), will i still be able to craft these?
Instead of putting the items like
```
"   "
" i "
" b "
```
i put them like
```
"i  "
"b  "
"   "
```

**Comment by zzm317** [comment]
@thebigsmileXD it works
but the table in pe will be like this
i  
b

**Comment by zzm317** [comment]
@thebigsmileXD and because of this you can write interesting things like 
torch
stick   ==> torch
stick

even
TNT TNT TNT
TNT TNT TNT  ==>   cake
TNT TNT TNT

**Comment by zzm317** [comment]
@thebigsmileXD but the Ingredients will only cost the things you write in setIngredient()

**Comment by zzm317** [comment]
$this->registerRecipe((new BigShapedRecipe(Item::get(Item::CAKE, 0, 1),
			"XXX",
			"XXX",
			"XXX"
		))->setIngredient("X", Item::get(Item::TNT, 0, 9)));

**Comment by thebigsmileXD** [comment]
@zzm317 I remember this from bukkit/forge.. but in forge it was like:
```
Torch:
"c"
"s"
slab:
"xxx"
ironblock
"xxx"
"xxx"
"xxx"
```

**Comment by zzm317** [comment]
@thebigsmileXD =-=My poor English...
Just try this you can know why i added so many "   " into the manager


$this->registerRecipe((new BigShapedRecipe(Item::get(Item::CAKE, 0, 1),
"C",
"C",
"C"
))->setIngredient("X", Item::get(Item::TNT, 0, 3)));

$this->registerRecipe((new BigShapedRecipe(Item::get(Item::CAKE, 0, 1),
"C  ",
"C  ",
"C  "
))->setIngredient("X", Item::get(Item::TNT, 0, 3)));

**Comment by thebigsmileXD** [comment]
xD have no time for that :P

**Comment by zzm317** [comment]
@thebigsmileXD =-=.
give you a chinese saying:'时间就像海绵里的水，挤一挤总是有的'

**Comment by thebigsmileXD** [comment]
@zzm317 true

**Comment by zzm317** [comment]
@thebigsmileXD do this project has a gitter?

**Comment by thebigsmileXD** [comment]
Sure.

**Comment by robske110** [comment]
Not anymore :)
