### ISSUE TITLE
Stairs bug is back

### ISSUE THREAD

**Issue by EnderKenji** [ImagicalCorp/ImagicalMine#403]

**Comment by EnderKenji** [comment]
And the Server keep 'frozen' , is it a IM problem?

Another server without latest IM doesnt hav this prob, 

## Sorry for add another issue here, I dont want to add too many issue threads.

**Comment by smyb** [comment]
#320  #404

**Comment by BlackShadow1** [comment]
It's fixed?

**Comment by smyb** [comment]
i didn't try it yet but i think it is

**Comment by thebigsmileXD** [comment]
How to test it?

**Comment by BlackShadow1** [comment]
Place a stairs in your spawn, deop you and test if this is breakable in the spawn..

**Comment by smyb** [comment]
if other blocks can't be destroyed but the stairs can , this bug is not fixed

**Comment by thebigsmileXD** [comment]
Yes, its fixed

**Comment by BlackShadow1** [comment]
Well.

**Comment by BlackShadow1** [comment]
close https://github.com/ImagicalCorp/ImagicalMine/issues/320
