### ISSUE TITLE
"Building terrain"

### ISSUE THREAD

**Issue by Tee7even** [ImagicalCorp/ImagicalMine#406]
I have two servers running ImagicalMine and there is an issue that occurs too frequently on both of them. When I join the server, the game just gets stuck on "Building terrain".
![image](https://cloud.githubusercontent.com/assets/6763610/12004784/1af8b198-ab88-11e5-8094-42cad651cdb5.png)
The console just says that I've joined the server, but there is no "Player joined the game" message.
```
2015-12-26 [04:13:16] [INFO]: Tee7even[/78.25.120.93:17500] вошел с id сущности 1 на (world, 144.404, 69, 159.0283)
```
Sometimes, if I wait for too long, it finally joins the server. It may be solved by deleting the player file like "tee7even.dat", but it will occur again. And it doesn't happen just with me, other members of our team also stated that they faced this issue:
![image](https://cloud.githubusercontent.com/assets/6763610/12004811/bc302f18-ab89-11e5-80f5-4241e472a30a.png)
There was no such problem before switching to ImagicalMine.

**Comment by smyb** [comment]
connection problem? never happened to me

**Comment by Tee7even** [comment]
Did you read it completely? I have said that it doesn't only for me and there is no such problem with another software. Is the connection problem the one for all of our team or does our connection break when we install ImagicalMine?

**Comment by keithkfng** [comment]
1. Have you deleted your server.properties file when switching to ImagicalMine? They are different.
2. Try reinstalling ImagicalMine by following the instructions @ ImagicalMine.imagicalcorp.ml

**Comment by thebigsmileXD** [comment]
This happens when you accidently run 2 servers on the same port. Check your config.

**Comment by Tee7even** [comment]
@keithkfng The problem still stays.

@thebigsmileXD Again, did you read it completely? The problem can be solved for a while by deleting the player file, I don't think it would be so if I was running two servers on the same port. In fact, what it would do, if any other software runs on the same port, is:
```
[16:28:34] [CRITICAL]: **** FAILED TO BIND TO 0.0.0.0:19132!
[16:28:34] [CRITICAL]: Perhaps a server is already running on that port?
```
Why do some of you, guys, stop reading the issue and reply with irrelevant commentaries?

**Comment by PeratX** [comment]
It seems that ImagcalMine does not send a PlayerStatusPacket

**Comment by thebigsmileXD** [comment]
I wont help anymore.

**Comment by keithkfng** [comment]
@Tee7even Do you want help? If you don't want it, get out. That's no way to talk to somebody who has been developing the whole project so you can at least USE IT.

**Comment by keithkfng** [comment]
1. Did you reinstall? Follow the instructions on the project website.
2. What are you running the server on?
3. Update to the latest build. You can get it off Jenkins. I'm too lazy to post the link XD

**Comment by Tee7even** [comment]
Hm... It was a little hard to understand your last sentence, but seems like
I figured it out. If you're not happy with my response to @thebigsmileXD's
*not related* answer, then ok. I'm sorry, if I said something bad, didn't
mean to offend anyone. So, yeah, I want help, if I wouldn't, I wouldn't
write here.

2015-12-26 23:02 GMT+03:00 Merry Keithy 2015 <notifications@github.com>:

**Comment by Tee7even** [comment]
1.Tried a couple of times, no effect.
2.A game server hosting service: 24Serv.pro specifically. If you are going
to blame it, then I'd like to remind you that other PM fork and PM itself
runs fine there.
3.Will update as soon as I can and I'll say if anything will change (or
not).

2015-12-26 23:50 GMT+03:00 Merry Keithy 2015 <notifications@github.com>:

**Comment by BlackShadow1** [comment]
I think is a host problem, all the other server haven't this bug..

**Comment by Tee7even** [comment]
@BlackShadow1 I've tried to contact them, they said, this problem occurs to players with creative mode and it's problem of IM.

**Comment by BlackShadow1** [comment]
I haven't got this bug on my server, What build of IM do you use?

**Comment by Tee7even** [comment]
Right now, 176, but it was present in earlier builds.

**Comment by keithkfng** [comment]
We'll look into this issue, but this doesn't happen when hosting on a computer.

**Comment by robske110** [comment]
I am hosting my server on an private computer and i once ran in the issue! But i got about 10Comments on my youtube server videos, wich describe that issue!

**Comment by thebigsmileXD** [comment]
Actually.. Someone (ChipsCrafter) joined my server some days ago and asked me to join his server amd if we wanna be partner servers.
I really had issues joining his server, i had to join 3 times because the first 2 times the terrain is loading and the server kicked be for not being audentificated.

He runs it on a v-server.
But the server himself ran perfectly, like.. Almost like lifeboat.
Maybe v-servers are a problem?

**Comment by keithkfng** [comment]
English lesson: You can define the server as "him". It's "it", because it's a non-living object. Hope you learnt something XD

**Comment by thebigsmileXD** [comment]
Logic lesson:
You *can't*

**Comment by keithkfng** [comment]
Don't get it -_-

**Comment by smyb** [comment]
![screenshot_2015-12-27-12-02-27](https://cloud.githubusercontent.com/assets/15691329/12009976/fce1e3fe-ac91-11e5-913c-51a1c4e9e04a.png)
@keithkfng , you wrote: " You can"  :joy:   XD

**Comment by keithkfng** [comment]
Oh LOL

**Comment by HimbeersaftLP** [comment]
I'm also not hosting my server myself, but  every player can join without problems...

**Comment by CraftingMania** [comment]
it is because you are using an anvil world 

or

an infinite world and you are the first to join the server after it is generated

i suggest using pm importer if you are using anvil world then import the map to mcregion then use the mcregion map

**Comment by Tee7even** [comment]
>it is because you are using an anvil world
>
>or
>
>an infinite world and you are the first to join the server after it is generated
>
>i suggest using pm importer if you are using anvil world then import the map to mcregion then use the mcregion map

Heh, this problem occurs with worlds generated by PM and IM itself and the number of players on the server does not affect it.

**Comment by remotevase** [comment]
@CraftingMania ImagicalMine does NOT support anvil worlds, only MCRegion

**Comment by remotevase** [comment]
Never mind, @CraftingMania, I mesread ur post
