### ISSUE TITLE
Axes aren't stackable

### ISSUE THREAD

**Issue by smyb** [ImagicalCorp/ImagicalMine#407]
![screenshot_2015-12-25-23-21-31](https://cloud.githubusercontent.com/assets/15691329/12004862/9f3b6ee2-ab7d-11e5-808e-b61c8c56ced8.png)

**Comment by smyb** [comment]
right ?

**Comment by smyb** [comment]
i didn't try with swords, pickaxe, hoes, shovels

**Comment by keithkfng** [comment]
https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
