### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by yungtechboy1** [ImagicalCorp/ImagicalMine#408]
When i get 50+ people on my server it begins to lag too much...
My server is good...
Is their any way you can clean up the code to make it go faster?

**Comment by MCPEPIG** [comment]
Same here. It lags less with official PocketMine.

**Comment by keithkfng** [comment]
redstone-calculation=off in server.properties if you're not using redstone.
Less chunks loaded in pocketmine.yml
@MCPEPIG -_-

**Comment by aodzip** [comment]
Maybe we don't use preprocesser

**Comment by yungtechboy1** [comment]
I know thats one option but I would like to have 100 players with no lag... Im skimming 65 today (Server Released Today) so I know I can get 100 Easily but I dont want their to be massive lagg

**Comment by aodzip** [comment]
turn off redstone won't lag?

**Comment by keithkfng** [comment]
Yup

**Comment by Tee7even** [comment]
You just suggest people to turn off the features? Are you, guys, fine with your software lagging? I do understand that it won't be fixed immediately, but you should think about optimizing the code and other ways to improve the performance (a php-7 rewrite, for example).

**Comment by BlackShadow1** [comment]
It's impossible rewrite to PHP7. YAML extension isn't released for PHP7 version and it's basically for IM

**Comment by Tee7even** [comment]
Well, maybe, but I know other PM fork. And it, as it's devs say, is being rewritten for php-7. I don't know it in details, but I think it's possible. If not now, then in future.

**Comment by BlackShadow1** [comment]
Can you give me the link?

**Comment by Tee7even** [comment]
There is a github link, but I think that there is not much activity:
https://github.com/PocketMinePlusPlus/PocketMinePlusPlus
And there is their VK community (you can, possibly, not understand it well, since a half of the news are just in Russian and another half is translated to broken English), there is more activity:
https://vk.com/pocketmine_plus_plus

**Comment by BlackShadow1** [comment]
Uh, thanks.

**Comment by keithkfng** [comment]
Oh for goodness sake, why don't you rewrite everything in PHP 7 then?
-_-
https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
