### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by saymon00** [ImagicalCorp/ImagicalMine#414]
[16:54:07] [CRITICAL]: **** FAILED TO BIND TO 0.0.0.0:19132!
[16:54:07] [CRITICAL]: Perhaps a server is already running on that port?

**Comment by BlackShadow1** [comment]
It's a bug cause to 2 pocketmine app opened, 1 open the server and 1 not. @ImagicalCorporation close this issue

**Comment by Tee7even** [comment]
If you are running it on the local machine with Windows 10 Edition opened, just change the port, the game uses the same port.

**Comment by saymon00** [comment]
ok thanks ^^
