### ISSUE TITLE
Furnaces Crashes MCPE Client After Server restart

### ISSUE THREAD

**Issue by yungtechboy1** [ImagicalCorp/ImagicalMine#416]
Ive crashed multiple times cause of this bug... But on Windows 10 it dosen't crash :/

**Comment by thebigsmileXD** [comment]
@aodzip they and trapped chests work on Genisys.

**Comment by yungtechboy1** [comment]
Genisys?

**Comment by aodzip** [comment]
@thebigsmileXD
So can you port them here?

**Comment by thebigsmileXD** [comment]
Should we ask first?

**Comment by keithkfng** [comment]
No I've asked @PeratX and they think that ImagicalMine and Genisys will be a great project TOGETHER

**Comment by aodzip** [comment]
I think dont need to ask.

**Comment by thebigsmileXD** [comment]
Okay :)
By the way.. On their server, (aah i see.. The owner is the leader of the project. Met him yesterday) boats now work he said, they follow the player.
