### ISSUE TITLE
Joining the server...

### ISSUE THREAD

**Issue by Lookinsss** [ImagicalCorp/ImagicalMine#417]
When a player joins the server, it loads to full but then it stops and I can't join it. Please fix it!

**Comment by yungtechboy1** [comment]
Works fine for me... Check ur World to see if its corrupt

**Comment by Lookinsss** [comment]
But it's really bug. World isn't corrupted at all. But when I join in Survival it works well, in creative - no.

**Comment by keithkfng** [comment]
https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md
This doesn't match the guidelines.
You haven't given us any other information. Please review your issue. Thanks!
