### ISSUE TITLE
Crafting Not Working On Windows 10

### ISSUE THREAD

**Issue by yungtechboy1** [ImagicalCorp/ImagicalMine#419]
On 2 X 2 and 3 X 3 I can not craft most items

**Comment by BlackShadow1** [comment]
Know this bug. this is the cause https://github.com/ImagicalCorp/ImagicalMine/commit/0af7911c6ed68db7f4883ed0f1c81918f0441d66

**Comment by keithkfng** [comment]
-_-
Search for duplicates before making another issue.
