### ISSUE TITLE
what is error?

### ISSUE THREAD

**Issue by Seetch** [ImagicalCorp/ImagicalMine#424]
```php
Error: Call to undefined method pocketmine\Server::getNetwork()
File: /s_api/src/seetch/sapi
Line: 104
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: sapi v0.1 beta by seetch_

Code:
[95] 	public function quitMsg(PlayerQuitEvent $e) {
[96] 		$e->setQuitMessage(null);
[97] 		foreach ($this->getServer()->getOnlinePlayers() as $p) {
[98] 			$p->sendTip(F::DARK_AQUA. $e->getPlayer()->getName(). F::GOLD. " " .$this->config->get("quitMsg"));
[99] 		}
[100] 	}
[101] 	
```

**Comment by BlackShadow1** [comment]
This is not a ImagicalMine problem, but a plugin problem.

**Comment by Seetch** [comment]
code 104 line

    public function makeMOTD(){
        $string = F::BLUE. F::BOLD. "Skypllex | " .F::WHITE. $this->getSubs(). F::DARK_GREEN. " subs";
		if($this->getServer()->getNetwork()->getName() != $string) {
            $this->getServer()->getNetwork()->setName($string);
            $this->getLogger()->info($string);
		}

**Comment by thebigsmileXD** [comment]
> $this->getServer()->getNetwork()..
Call to undefined method pocketmine\Server::getNetwork()

Its undefined. As the error says, theres no getNetwork()
