### ISSUE TITLE
Jenkins build server very slow

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#426]
As I download the phar builds from jenkins, I want to say that this build server is very slow.
A lot of connection errors, download speeds are between 0 and 100Kb/s overhere. The services should be improved a bit. 

Could not even get this one, tried a lot but it wont download ( download instruction from http://imagicalmine.imagicalcorp.ml )

--2015-12-27 13:40:05--  (try:20)  http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine/lastSuccessfulBuild/artifact/releases/*zip*/releases.zip
Connecting to jenkins.imagicalcorp.ml|125.211.202.141|:8080... failed: Connection timed out.
Giving up.

**Comment by aodzip** [comment]
okay
I need a global CDN

**Comment by dterweij** [comment]
Indeed put it in a cloud or use mirrors that are synced with rsync orso.

Trying for 2 hours to get the 221 :) I wait for some hours for a retry,

Connecting to jenkins.imagicalcorp.ml|125.211.202.141|:8080... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 3199318 (3.1M), 3133782 (3.0M) remaining [application/octet-stream]
Saving to: “ImagicalMine-IC_1.0dev#221.phar”

 4% [>                                      ] 131,072     5.38K/s   in 12s

2015-12-27 16:12:19 (5.38 KB/s) - Connection closed at byte 131072. Retrying.

p.s. i have 40Mbit and geo is NL, jenkins is 17 hops away with a lot of timeouts and very high packet lags.

**Comment by thebigsmileXD** [comment]
I don't have this problem in germany.

**Comment by BlackShadow1** [comment]
I've got this too in Italy..

**Comment by HimbeersaftLP** [comment]
It's also slow here in Austria (NOT Australia), but it works....

**Comment by robske110** [comment]
I am living in 'Bayern' normally, its slow there but does work...
Here in Austria (Skiing currently) its much faster! 'Österreich'
Traceback in Austria:

**Comment by thebigsmileXD** [comment]
Whats that app? Well, i am always directly on the server and it downloads within 5 seconds

Remember: The filesize is already > 3mb

**Comment by keithkfng** [comment]
It works perfectly fine for me. I just like using the installation script provided on the website. It works very well.

**Comment by dterweij** [comment]
Well if something works fine for you does not mean it works for everyone :P

Anyway, I hope you guys are doing something in the near future about it. Sometimes I have it in 5 minutes and most of the time I have to restart the wget a few times and maybe after 40 mins I have the file :)

tho it is irrelevant to the code as issue, but relevant in general as reachable. I liked the builds/releases on github itself. Then I have them in 1 sec :) Why not use that again... let github handle the datatraffic and use jenkins server to build and commit as test release (everything can be made automaticly right). Just my mind. For now  I and others have to do with the slow connection and packetlosses as you seems find it irrelevant as it works fine for you :)

I don't mind filesizes, its not the issue. I download a DVD  under 10 minutes. and 3MB as in ImagicalMine can be just in 1 second :) In about 5 months I upgrade to 200Mbit line.

**Comment by keithkfng** [comment]
What, so you want us to upload EVERY SINGLE BUILD TO GITHUB?! No.

**Comment by Tee7even** [comment]
Jenkins builds are not releases. Continuous integration is used for testing purposes **during development**. Then, when the plan for a new version is done and all the issues are solved, a new release is uploaded to wherever. Forcing everyone to use testing builds is complete disrespect to quality.
```
What, so you want us to upload EVERY SINGLE BUILD TO GITHUB?! No.
```
Well no, we want you just to fix the problem with CI server :)

**Comment by keithkfng** [comment]
LOL not my problem with the server XD

**Comment by Tee7even** [comment]
But you can upload one build to github and change download links to decrease the server load, don't you?

**Comment by keithkfng** [comment]
Why can't we just stick with Jenkins?

**Comment by Tee7even** [comment]
Ummm, because it sometimes is really slow, no?

**Comment by dterweij** [comment]
I am tired of it. I realy can not use the slow chinese located jenkins website to download the builds.
So now I pull the source (master) from github and run JenkinsBuild.php myself. New versions in 1 second :)  I might go build a simple website arround it so others can benefit from it.
(Would be fun to have the jenkins website source to make it identical hehe.)
