### ISSUE TITLE
New Small bugs

### ISSUE THREAD

**Issue by Jelly9912** [ImagicalCorp/ImagicalMine#427]
Players can't make stairs (tested on oak wooden stairs) and this:

**Comment by Jelly9912** [comment]
![screenshot_2015-12-27-14-32-30](https://cloud.githubusercontent.com/assets/13715380/12010721/7f868bd2-acb2-11e5-8398-d7bbdef62ecc.png)

**Comment by Jelly9912** [comment]
2 brown carpets

**Comment by BlackShadow1** [comment]
Player can't make stairs and stick, am i wrong?

**Comment by remotevase** [comment]
just fixed on Jenkins. Build 222 came out a few seconds ago

**Comment by keithkfng** [comment]
I'm literally going to kill you all. Stop duplicating issues please.

**Comment by thebigsmileXD** [comment]
@keithkfng how is this duplicated?

**Comment by keithkfng** [comment]
Stairs...
