### ISSUE TITLE
Broken download link at jinkens?

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ImagicalCorp/ImagicalMine#439]
So.. i followed the instructions 

After you have everything setup, go to the Jenkins server and download the latest stable build. Then, delete the old PocketMine-MP.phar, drag the new ImagicalMine phar in and rename it to ImagicalMine.phar. Delete the old server.properties file, ImagicalMine will create one with the default values on startup. Run ./start.sh to start ImagicalMine.

after downloading the installer at imagiclmine.me and still dont work..before i use to be able to just rename the phar file and run it in the pocketmine i already have installed. Can someone please tell me what the issue is here bc im loosing my mind XD i would of posted on the forums but there not open yet?

**Comment by XxDXM-hippiexX** [comment]
if i name it Pocketmine-MP.phar....


Warning: require_once(phar://C:\Users\admin\Downloads\PocketMine-MP\Pocketmine-MP.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "C:\Users\admin\Downloads\PocketMine-MP\Pocketmine-MP.phar" has a broken signature in C:\Users\admin\Downloads\PocketMine-MP\Pocketmine-MP.phar on line 1

Call Stack:
    0.0012     127624   1. {main}() C:\Users\admin\Downloads\PocketMine-MP\Pocketmine-MP.phar:0


Fatal error: require_once(): Failed opening required 'phar://C:\Users\admin\Downloads\PocketMine-MP\Pocketmine-MP.phar/src/pocketmine/PocketMine.php' (include_path='.;.\ext') in C:\Users\admin\Downloads\PocketMine-MP\Pocketmine-MP.phar on line 1

Call Stack:
    0.0012     127624   1. {main}() C:\Users\admin\Downloads\PocketMine-MP\Pocketmine-MP.phar:0

bin\php\php.exe: Exit 255


if i name it ImagicalMine.phar it just says no valid installation

**Comment by Tee7even** [comment]
1.Install PocketMine
2.Delete PocketMine-MP.phar
3.Download IM and rename it to PocketMine-MP.phar
4.Drop it to PocketMine folder
Is this really hard?

**Comment by XxDXM-hippiexX** [comment]
I did that

**Comment by XxDXM-hippiexX** [comment]
So i fixed it by downloading the zip from github..and running out of the src file

**Comment by XxDXM-hippiexX** [comment]
broken download link?

**Comment by keithkfng** [comment]
The forums is open, and you rename it to ImagicalMine.phar, not PocketMine-MP.phar. We dropped the support for PocketMine ages ago.

**Comment by keithkfng** [comment]
The Jenkins link is also working perfectly fine. It seems to be an issue with your network.

**Comment by Tee7even** [comment]
>and you rename it to ImagicalMine.phar, not PocketMine-MP.phar. We dropped the support for PocketMine ages ago.

@keithkfng With PM installation it won't work other way, what are you talking about?

**Comment by thebigsmileXD** [comment]
Jenkins got broken after my food merge but its now fixed

**Comment by keithkfng** [comment]
You need to rename it to ImagicalMine.phar otherwise it won't find a valid ImagicalMine installation. We changed it because we didn't like PocketMine as an original name XD

**Comment by PocketKiller** [comment]
@keithkfng he might not have edited the start.cmd or start.sh.

**Comment by keithkfng** [comment]
You don't need to if you followed the installation method provided on the website. You do if you upgraded from PocketMine though.

**Comment by Tee7even** [comment]
>You don't need to if you followed the installation method provided on the website. 

Are you serious?
>You need to install PocketMine first before installing ImagicalMine on Windows. Follow the instructions below to install PocketMine and ImagicalMine. After you have everything setup, go to the Jenkins server and download the latest stable build. Then, delete the old PocketMine-MP.phar, drag the new ImagicalMine phar in and rename it to ImagicalMine.phar. Delete the old server.properties file, ImagicalMine will create one with the default values on startup. Run ./start.sh to start ImagicalMine.

**Comment by keithkfng** [comment]
That's only for Windows -_-
If you actually WENT ON THE WEBSITE, there's a different method for Mac, Linux and ARM devices.

**Comment by Tee7even** [comment]
Is Windows an exception or what?

**Comment by keithkfng** [comment]
I couldn't be bothered to make an installer XD
With the other ones, I only made a shell script. Much easier than having to make an exe file...

**Comment by thebigsmileXD** [comment]
Just saying.. I installed it on windows with the installer and everything worked fine.
I don't understand what your problems are. Even the configs were right

**Comment by Tee7even** [comment]
Did you call your phar "imagicalMine"? If you named it "PocketMine-MP", then of course it works.

**Comment by keithkfng** [comment]
Of course it doesn't. I think we know it better than you. I renamed it to look for ImagicalMine.phar. Everything has changed. PocketMine is not ImagicalMine you know.

**Comment by Tee7even** [comment]
I think, you have a mess in your brain... You just said you didn't change anything for Windows...
![image](https://cloud.githubusercontent.com/assets/6763610/12025283/368ec950-adbe-11e5-9030-b0bf9f2f0438.png)

**Comment by keithkfng** [comment]
Except for the start script. Seriously? You don't understand? OMG

**Comment by Tee7even** [comment]
Yes, a normal man can not understand you. The logic is simple:the website provides us with a link to download a PocketMine installer, If the start script isn't changed (and of course it isn't changed there!), then it looks for PocketMine-MP and it will work only if your phar is named "PocketMine-MP". But in your opinion:
>Of course it doesn't.

Logic? I think the only logic that you follow is:
>I think we know it better than you.

**Comment by keithkfng** [comment]
I barely use the PocketMine installer -_-
I just run it from the source on Linux so don't ask me about Windows-related issues -_-
