### ISSUE TITLE
Speed effect sticking

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ImagicalCorp/ImagicalMine#441]
When you are given the speed effect sometimes the effect stays after it is gone or removed.

**Comment by thebigsmileXD** [comment]
DUPLICATE. Read the fucking contributing file

**Comment by MCPEPIG** [comment]
Not duplicate.

**Comment by thebigsmileXD** [comment]
-.-" it is. 
"Speed effect doesn not work"
