### ISSUE TITLE
Weather & Message

### ISSUE THREAD

**Issue by EnderKenji** [ImagicalCorp/ImagicalMine#442]
it wont auto clear... need manual clear.. pls fix

and this:
https://ton.twitter.com/1.1/ton/data/dm/681270116969877507/681270117007667200/3OvyLXvp.jpg

**Comment by keithkfng** [comment]
There's no image -_-

**Comment by EnderKenji** [comment]
![3ovylxvp](https://cloud.githubusercontent.com/assets/15629214/12014648/0d078b4c-ad6b-11e5-9bca-dd43c1194bd8.jpg)
This message

**Comment by keithkfng** [comment]
Ah, yes. Tell @McpeRusty to turn off auto-updater in pocketmine.yml. I'll delete auto-updater messages now.

**Comment by EnderKenji** [comment]
Okay . Thanks <3 

and wht about weather?
