### ISSUE TITLE
Breaks VIP Slots

### ISSUE THREAD

**Issue by XFuryMCPE** [ImagicalCorp/ImagicalMine#450]
? VIP Slots just doesn't work after putting this on

**Comment by PocketKiller** [comment]
What is $this?

**Comment by Taki21** [comment]
Vip Slots = Plugin...This is not an ImagicalMine Issue! Plugin's Fault!

**Comment by keithkfng** [comment]
This is an ImagicalMine issue. The API version was updated to 1.13.2, so you need to update plugins.

**Comment by Taki21** [comment]
xD Really!

**Comment by matcracker** [comment]
Yes, now is avaiable weather and experience API

**Comment by MCPEPIG** [comment]
The API version doesn't matter.

**Comment by keithkfng** [comment]
They were in plugins. Unless they're backwards-compatible.
