### ISSUE TITLE
Connection problem(reported by Jazzwhistle and remote_vase)

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#451]
You may have to restart the server a couple of times as you join, then disconnect, but eventually it will work flawlessly. Apparently, when you join, a file must be created. After that file is created, the server will crash, Then, you start the server, join, and it works. Then you disconect and another file has to be created. The file will create, then the server will crash. Next, you start the server, and everything works well.
Any ideas? Build #177 worked fine, but build #178 didn't.

**Comment by keithkfng** [comment]
@ZombiePower I think this was fixed ages ago LOL

**Comment by ZombiePower** [comment]
yep
