### ISSUE TITLE
latest build. food can't be consumed 

### ISSUE THREAD

**Issue by Tolo0** [ImagicalCorp/ImagicalMine#454]
Just started using build #255 and now no food can  be consumed.  Players on my server are literally starving to death 😅

**Comment by PocketKiller** [comment]
can't eat? can i have a pic?

**Comment by Tolo0** [comment]
U can eat. But u basically eat no stop. It can't be consumed

**Comment by Tolo0** [comment]
It seems any food u already have when server reboots works fine. But any food u buy. Doesn't work

**Comment by PocketKiller** [comment]
buy?

**Comment by PocketKiller** [comment]
as i know that happens because of lag, create a Test server with no plugins and test.

**Comment by dterweij** [comment]
Food you already have -> you can eat.
Food you get from a Kit (AdvanceKits for example) -> you can eat.
Food you buy (from a economy shop) does not work. When you want to eat, it animates that you eat but hunger does not become less. 
Serious bug indeed.

**Comment by thebigsmileXD** [comment]
Just saying: me and @matcracker were on the Server yesterday (5.175.226.133:19133) and it worked alright. Are you sure you have the latest build?

**Comment by Tolo0** [comment]
Just tested it on my test server that had 0% lagg. Any food bought with EconomyShop buy signs. Don't work until reboot. It's like the food isn't registered lol.

**Comment by Tolo0** [comment]
![screenshot_2015-12-29-09-38-01](https://cloud.githubusercontent.com/assets/13458191/12032457/7106e8f4-ae10-11e5-9d4f-bbb0a803c610.png)

**Comment by thebigsmileXD** [comment]
Again: are you sure you are on the latest build?
by the way.. try opening your inventory and closing it again.
Can i have your ip so i can test?

**Comment by Tolo0** [comment]
I'm on build #255 atm haven't updated yet. Ip is 198.50.199.21

**Comment by thebigsmileXD** [comment]
I also use 255 currently. But i haven't tested with pe, just wih win 10

**Comment by thebigsmileXD** [comment]
Tested. They work after you drop them on the ground..

**Comment by thebigsmileXD** [comment]
@Tolo0 can you get on? i want to test more food, but without money?

**Comment by thebigsmileXD** [comment]
@matcracker saw ya lefting :eyes:

**Comment by thebigsmileXD** [comment]
Seems to be plugin fault, but i'll try to fix it.

**Comment by thebigsmileXD** [comment]
```php
$player->getInventory()->addItem($item);
```
That might be the problem

**Comment by thebigsmileXD** [comment]
Yea.. that was it. There was a function added in PlayerInventory.php which shouldn't be there.
@Tolo0 Can you install the latest version?

**Comment by Tolo0** [comment]
I'll do it now and inform

**Comment by Tolo0** [comment]
Still doesn't work 😣

**Comment by thebigsmileXD** [comment]
Place a sign.. when they drop and take up it works.

**Comment by linuzo** [comment]
Yeah I can confirm this issue.. However it seems to work with Genysis for some reason..

**Comment by thebigsmileXD** [comment]
Because the genisys food is still basic like every other pm version

**Comment by ZombiePower** [comment]
fixed?

**Comment by thebigsmileXD** [comment]
How should i fix this when i work on rails. I close issues when i fixed it, so don't spam "fixed?" Everywhere

**Comment by zzm317** [comment]
Already added food craftingmanager

**Comment by thebigsmileXD** [comment]
This actually isn't plugin fault. BattleKit has the sign. every plugin that uses ```getInventory()->add()```

**Comment by thebigsmileXD** [comment]
I'll fix that.

**Comment by zzm317** [comment]
@thebigsmileXD =-=food can add hunger and can be crafted=-=
why you reopen it==

**Comment by thebigsmileXD** [comment]
@zzm317 The problem was not the crafting of food..
> Just tested it on my test server that had 0% lagg. Any food bought with EconomyShop buy signs. Don't work until reboot. It's like the food isn't registered lol.

The issue is you can't eat food added to the inventory via ->add()

**Comment by zzm317** [comment]
@thebigsmileXD OK ,I know...

**Comment by thebigsmileXD** [comment]
new issue for this https://github.com/ImagicalCorp/ImagicalMine/issues/578
