### ISSUE TITLE
jenkins is offline how to get builds

### ISSUE THREAD

**Issue by IMagicalPlugins** [ImagicalCorp/ImagicalMine#455]

**Comment by IMagicalPlugins** [comment]
how do i get builds with jenkins offline

**Comment by IMagicalPlugins** [comment]
wait nvm

**Comment by IMagicalPlugins** [comment]
when i go to jenkins.pocketmine.net/job/pocketmine-mp/lastbuild and click the builf it goes offline

**Comment by dterweij** [comment]
This is ImagicalMine  you posted a link of PocketMine-MP.
(And yes, the PocketMine-MP build server seems down for about 1 or 2 days now, ask why at PocketMine-MP project)

**Comment by aodzip** [comment]
…

**Comment by keithkfng** [comment]
@IMagicalPlugins you'll be banned soon for using the name. Please either change it or delete the account.

**Comment by Tee7even** [comment]
>This is ImagicalMine you posted a link of PocketMine-MP.
>(And yes, the PocketMine-MP build server seems down for about 1 or 2 days now, ask why at PocketMine-MP project)

They just copied PocketMine's documentation @ http://imagicalmine.readthedocs.org/en/latest/installation.html

**Comment by TBNRFrags2468** [comment]
where
