### ISSUE TITLE
Redstone torch cant invert (turn off)

### ISSUE THREAD

**Issue by intagaming** [ImagicalCorp/ImagicalMine#458]
Redstone Torch just cant turn off
I used the right way to turn it off but it doesnt seem to work
Please fix this...

**Comment by thebigsmileXD** [comment]
Critical crash with Redstone torch
```[10:07:48] [NOTICE]: InvalidArgumentException: "Argument 2 passed to pocketmine\level\Level::setBlock() must be an instance of pocketmine\block\Block, integer given, called in phar://C:/Users/Administrator/Desktop/Server/MinecraftPE/ImagicalMineTestServer/ImagicalMine-IC_1.0dev#255.phar/src/pocketmine/block/LitRedstoneTorch.php on line 91 and defined" (E_RECOVERABLE_ERROR) in "/src/pocketmine/level/Level" at line 1486
```

**Comment by intagaming** [comment]
Havent fix yet guys ?

**Comment by thebigsmileXD** [comment]
Theres a rewrite of restone.
Work in progress

**Comment by intagaming** [comment]
I thought that was the single one
Im very need the torch to make things unique
Hope it will done fast :D

**Comment by thebigsmileXD** [comment]
In very need to lag the server? Good luck.

**Comment by intagaming** [comment]
Just need to do the "The Maze Runner" maps :D 
It needs Level and Redstone Torch, so . . .
Also i known the lag :D 
Still waiting . . .

**Comment by thebigsmileXD** [comment]
There are no repeaters or comparators yet

**Comment by intagaming** [comment]
There are. JackFrostMiner has made a video that show us how to make the Repeater with Redstone Torch, 2 Blocks and Redstone Wires. Redstone Torch need to be invert to do this. :(
Link: https://www.youtube.com/watch?v=z7Y6x1CuSEc

**Comment by thebigsmileXD** [comment]
I know. But thats still no repeater, and there are better ones out there

**Comment by intagaming** [comment]
Still Acceptable so . . . TORCHHHHHH :(

**Comment by thebigsmileXD** [comment]
So... REWRITE.
I'll start soon.

**Comment by intagaming** [comment]
I know :D I don't really very need it at the time so . . . Be patient and work :D
Thank you then :P

**Comment by thebigsmileXD** [comment]
@intagaming Welcome

**Comment by aodzip** [comment]
Fixed
