### ISSUE TITLE
New crafting bug? old one seems to be fixed

### ISSUE THREAD

**Issue by XxDXM-hippiexX** [ImagicalCorp/ImagicalMine#460]
The bug that would remove items from your inventory when crafting was fixed..but now..somewhere above dev #224 there is a bug stopping all crafting. You craft the item and it stays for a sec until you try to place it or use it. I tried this with no people on the server as well to make sure it wasn't lag and there seems to be no trick or anything to get crafting to work.

**Comment by XxDXM-hippiexX** [comment]
Or i think its above dev #224 anyway..id downgrade but for some reason i cant download it from Jenkins i get a corrupt file from a bad connection or something.

**Comment by thebigsmileXD** [comment]
@keithkfng why me?

**Comment by BlackShadow1** [comment]
@XxDXM-hippiexX What item? You've tried all or some?

**Comment by XiangZhao969** [comment]
I am having this problem too, the item after crafting auto-disappear, and the original item will be in your pocket, like there is nothing done. If I tried to click the crafting button muptiple times, it will kick me out for the reason: "Flying is not enabled in this server" (?!)

**Comment by Jelly9912** [comment]
I'm losing players because of that error :(

**Comment by Tolo0** [comment]
I'm having the same problem and I'm on the latest build #265 . Players can't craft dark oak slaps. Just returns to dark oak wood plank.

**Comment by Jelly9912** [comment]
Players can't craft anything ,_,

**Comment by BlackShadow1** [comment]
It's the commit https://github.com/ImagicalCorp/ImagicalMine/commit/0af7911c6ed68db7f4883ed0f1c81918f0441d66 that have broken the code of crafting, the team doesn't understand this. Try reverting this in the source code fix the bug but the team says no...

**Comment by Tolo0** [comment]
This should be classed as Bug. Critical. Crafting is very important on all server's.

**Comment by XxDXM-hippiexX** [comment]
I dont see how its being pushed off as other stuff is being fixed..nothing can be crafted..nothing..ever XD im running dev 224 now and crafting is fixed there bug the furanse is not /:

**Comment by XxDXM-hippiexX** [comment]
whatever is in 224 dealing with crafting..its perfect no bugs..do that again XD

**Comment by NML32** [comment]
Fingers crossed that it will be fixed soon.

**Comment by smyb** [comment]
tested, i can't craft anything

**Comment by Tolo0** [comment]
I think this crafting bug. Should be a priority.

**Comment by smyb** [comment]
i agree

**Comment by PocketKiller** [comment]
i am trying to find out what's the problem, but nothing till now.

**Comment by BlackShadow1** [comment]
@PocketKiller i found the problem. i'm creating a pull request.

**Comment by PocketKiller** [comment]
@matcracker @BlackShadow1 your fix isn't working.

**Comment by smyb** [comment]
reopen

**Comment by BlackShadow1** [comment]
D:

**Comment by PocketKiller** [comment]
new : raklib blocks the client when crafting .-.

**Comment by PocketKiller** [comment]
@BlackShadow1 didn't you hear me?
i said : "i tried it already, not working"

**Comment by BlackShadow1** [comment]
sorry... but i know the new problem. 5 minuts and tell me if it's work..

**Comment by matcracker** [comment]
Anyway, "$this->hasCompoundData() and $this->hasCompoundData()" don't have sense -.-

**Comment by matcracker** [comment]
Tag not Data*

**Comment by BlackShadow1** [comment]
I didn't do that @matcracker, i did $item->hasCompoundData and $this->hasCompoundData ..

**Comment by BlackShadow1** [comment]
public final function deepEquals(Item $item, $checkDamage = true, $checkCompound = true){
		if($item->equals($item, $checkDamage, $checkCompound)){
			return true;
		}elseif($this->hasCompoundTag() or $item->hasCompoundTag()){
			return NBT::matchTree($this->getNamedTag(), $item->getNamedTag());
		}

		return false;
	}

**Comment by SavionLegendZzz** [comment]
use a different raklib that is what i have done and it dosent block me(changed IM's source code raklib/spl)

**Comment by PocketKiller** [comment]
what? i typed words wrongly xD

**Comment by PocketKiller** [comment]
Fixed!

**Comment by PocketKiller** [comment]
but items don't go directly to hotbar.

**Comment by Tolo0** [comment]
So happy this is fixed. Thanks guy😉

**Comment by PocketKiller** [comment]
I knew who made this bug.. Gensys (https://github.com/ImagicalCorp/ImagicalMine/commit/4d036e844d1962bbf2b49eb0ecfa62a6367f2e00)

**Comment by Tolo0** [comment]
Guys can't u use some of Gensys codes. Like the spawn eggs. Wall pictures and boat?

**Comment by ZombiePower** [comment]
Good Job @PocketKiller :+1: Codes from other projects shouldnt just be copied carelessly....
