### ISSUE TITLE
2016 New Year Developing Hours

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#461]
Hi developers,
Just wanted to confirm with you if you'll be online during the New Year. Tick your name below if you are Thanks!
- [x] keithkfng(I'll be taking a break off ImagicalMine for sometime. I'll see you all again in 2 days. If you need help, email me at keithkfng@imagicalmine.me)EDIT: Too much chaos around, can't leave.
- [x] aodzip
- [ ] matcracker
- [ ] thebigsmileXD
- [ ] PeratX
- [ ] ZombiePower
- [ ] legoboy0215
- [x] PocketKiller (will have exams in 2 weeks)
- [x] DRedDogPE

**Comment by aodzip** [comment]
If my PC can be repaired and finish exams lol

**Comment by thebigsmileXD** [comment]
Because of that my email didn't came through.. ^^^^

**Comment by thebigsmileXD** [comment]
I won't be online. I'll code a plugin (bricks are firecrackers) and celebrate new year with many friends.
After that i'll close my 0.11 server and change the port of the 0.13 server to the 0.11 one)
Anyone knows a cool firework plugin?
