### ISSUE TITLE
ThrownExpBottle and ThrownSplashPotion cause hit animation (0 damage)

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalCorp/ImagicalMine#464]
We should really prevent this from happening.

**Comment by EnderKenji** [comment]
and can't drink potion on survival mode.

**Comment by ZombiePower** [comment]
elaborate please?

**Comment by thebigsmileXD** [comment]
You can. Latest Version? Do you get the potion from a sign shop plugin?
