### ISSUE TITLE
Rain Rain Constant RAIN!!!!

### ISSUE THREAD

**Issue by DRedDogPE** [ImagicalCorp/ImagicalMine#466]
There is constant rain and i havent seen anyone report this. Even after /toggledownfall or /weather clear 1000000 the rain will stop for a second and turn back on.... it gets annoying cause it makes the server seem very miserable. I dont know what could be causing this either

**Comment by InfornoFire** [comment]
Iv played on a server and it does rain alot

**Comment by GAalexandres** [comment]
same here

**Comment by thebigsmileXD** [comment]
Its really much. Every time the server starts it rains. Also, (i already told him) Lightnings only appear once (instantly) when you do /weather thunder
@matcracker

**Comment by miker059** [comment]
i agree with you absolutely. /weather clear doesn't solve this problem.

**Comment by matcracker** [comment]
Don't worry, I'm working on this but I don't know the duration time of rain
and rain + thunder. I search in the wiki but I don't find anything

**Comment by InfornoFire** [comment]
Uhh mat cracker, remember these codes can be completely different from regular minecraft (MCPE and pc etc) There was a bug where hunger drained so quick which was not MCPE fault

**Comment by matcracker** [comment]
It's not possibly fixed @ZombiePower ...

**Comment by ZombiePower** [comment]
I don't know, as you set raining time? why do you need that? (I have actually done the background knowledge for this- I can be wrong)
