### ISSUE TITLE
Slow redstone.... 

### ISSUE THREAD

**Issue by DRedDogPE** [ImagicalCorp/ImagicalMine#467]
I wonder if we can speed up redstone a little, i dont think its the server being laggy but redstone seems to take a while to update.

**Comment by PeratX** [comment]
@aodzip will work on it later.

**Comment by thebigsmileXD** [comment]
Its actually pretty bugged.. i think the whole code is just messed up. Broadcastredstoneupdate, redstoneupdatenormal..

**Comment by PeratX** [comment]
@thebigsmileXD Is Genisys's redstone more quickly?

**Comment by thebigsmileXD** [comment]
With dumb logic ;)

**Comment by PeratX** [comment]
@thebigsmileXD In fact, my redstone is just DFS...

**Comment by thebigsmileXD** [comment]
DFS also means Dynamic File System, a bit confusing. But yea.. i think we should rewrite it again.. maybe i'll do it next year.

**Comment by PeratX** [comment]
@thebigsmileXD Depth First Search...

**Comment by PeratX** [comment]
I think if we use BFS,it will be better...

**Comment by aodzip** [comment]
I ask one of my collage professor . May be I can get some help from her.

**Comment by PeratX** [comment]
@aodzip Wow,amazing,,,

**Comment by aodzip** [comment]
Improved 
Close
