### ISSUE TITLE
crafting is broken again 

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalCorp/ImagicalMine#471]
Whenever i craft something in survival it doesn't take any of the materials and it doesn't give me the item I'm crafting like whenever i craft a wooden pickaxe it doesn't appear in my inventory

**Comment by MasterWolf** [comment]
Same

**Comment by MCPEPIG** [comment]
OMG, noobs, stop duplicating issues. Are you 2 cause you can't seem to read.

**Comment by EpicSteve33** [comment]
Sorry lol
