### ISSUE TITLE
Bug with slowness effect

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/ImagicalMine#474]
![screenshot_2015-12-30-10-30-21](https://cloud.githubusercontent.com/assets/15706847/12048189/6b107868-aee0-11e5-972e-4b698d206079.png)

**Comment by robske110** [comment]
Please provide more Info, or ImagicalCorp will close this!

**Comment by robske110** [comment]
https://github.com/ImagicalCorp/ImagicalMine/blob/master/CONTRIBUTING.md

**Comment by ZombiePower** [comment]
its at infinity

**Comment by keithkfng** [comment]
Couldn't leave. Too much chaos going around.

**Comment by PocketKiller** [comment]
@zombiepower nope, i have this too, sometimes when u join/respawn, you get an infinite slowness effect... but it doesn't actually effect your speed.

**Comment by alex2534alex** [comment]
@PocketKiller , u don't right. it actually affects the player's speed.

**Comment by alex2534alex** [comment]
Pleeease, fix!

**Comment by alex2534alex** [comment]
Players may not run because of this

**Comment by PocketKiller** [comment]
true, i was out-of-date.

**Comment by alex2534alex** [comment]
thanks))

**Comment by keithkfng** [comment]
Doesn’t match guidelines.

**Comment by ZombiePower** [comment]
@PocketKiller ikr! the effects aren't exactly working
