### ISSUE TITLE
Bug log

### ISSUE THREAD

**Issue by Wang8902** [ImagicalCorp/ImagicalMine#475]
ImagicalMine Crash Dump Wed Dec 30 10:50:56 UTC 2015

Error: include(phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/event/entity/EntityTeleportEvent.php): failed to open stream: phar error: Cannot open phar archive "/storage/emulated/0/PocketMine/PocketMine-MP.phar" for reading
File: /src/spl/BaseClassLoader
Line: 128
Type: warning

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[119]      * Called when there is a class to load
[120]      *
[121]      * @param string $name
[122]      *
[123]      * @return bool
[124]      */
[125]     public function loadClass($name){
[126]         $path = $this->findClass($name);
[127]         if($path !== null){
[128]             include($path);
[129]             if(!class_exists($name, false) and !interface_exists($name, false) and !trait_exists($name, false)){
[130] 	            if($this->getParent() === null){
[131] 		            throw new ClassNotFoundException("Class $name not found");
[132] 	            }
[133]                 return false;
[134]             }
[135] 
[136] 	        if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[137] 		        $name::onClassLoaded();
[138] 	        }

Backtrace:
#0 /src/spl/BaseClassLoader(128): BaseClassLoader->loadClass(boolean)
#1 (): BaseClassLoader->loadClass(string pocketmine\event\entity\EntityTeleportEvent)
#2 /src/pocketmine/entity/Entity(1551): spl_autoload_call(string pocketmine\event\entity\EntityTeleportEvent)
#3 /src/pocketmine/Player(3551): pocketmine\entity\Entity->teleport(pocketmine\math\Vector3 Vector3(x=126.06101989746,y=62.2,z=157.62872314453), NULL , NULL )
#4 /src/pocketmine/Player(803): pocketmine\Player->teleport(pocketmine\math\Vector3 Vector3(x=126.06101989746,y=62.2,z=157.62872314453))
#5 /src/pocketmine/Player(750): pocketmine\Player->doFirstSpawn(boolean)
#6 /src/pocketmine/Player(1690): pocketmine\Player->sendNextChunk(boolean)
#7 /src/pocketmine/Server(2524): pocketmine\Player->checkNetwork(boolean)
#8 /src/pocketmine/Server(2243): pocketmine\Server->tick(boolean)
#9 /src/pocketmine/Server(2121): pocketmine\Server->tickProcessor(boolean)
#10 /src/pocketmine/Server(1722): pocketmine\Server->start(boolean)
#11 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/, string /storage/emulated/0/PocketMine/, string /storage/emulated/0/PocketMine/plugins/)
#12 (1): require_once(string phar:///storage/emulated/0/PocketMine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.13.2]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.4.0-g26e4aff-00681-g25b399a #1 SMP PREEMPT Wed Nov 18 20:13:43 CST 2015 armv7l
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, android

Loaded plugins:
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
EconomyProperty 2.0.6 by onebone for API(s) 1.12.0
EconomyPShop 2.0.2 by onebone for API(s) 1.12.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
EconomyTax 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyUsury 1.0.1 by onebone for API(s) 1.12.0
SignStatus 2.1 by xpyctum for API(s) 1.0.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0
Portal 3.0.1 by ljyloo for API(s) 1.0.0
RandomItem 4.2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
HealthBar 1.0.0 by LegendOfMCPE for API(s) 1.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWwtv28ay/itbJcCRD0RJpJ5WoeLkOM49PXAS3di5uUB1YKzIpcSG5LLcpWWlyH+/M7PLl2yn
TtKit0CMpua+Zme+mZ2ZffjXjo4S0Vm444k7nnnTybTXibnS53ku887i144+ZNDc2fM8jdJtp9dJ
hFJ8i3VR6sdFILrZjueLwWCgtMyhZSCSIuZaBIPhYCX990K/jFLR+HRervo4ZqByf5BRdYI9xI1I
9QD+RfowOKdfVyIWmcz1OTbBoOxkwUIexSJgWjKZiZQpnQueLBhSZALZXrAznqZSm3aq57m/i24E
W3c+m8t1h4UyZzBJYAAIizh+ASwAAl8lucriwT+5EmeAt7qQPBA5SogzGOoP9YIeMRADpXnzXkfn
3IfvnzpPhuyhEV3oCcgd1To/xPCbKrobKWPB0xOg/cRl3U93BsgBClarbr0m3cEv0tp6fY/2iLTH
7ii9qe6uO5m4MDeIcM0LLXHKa5/H8VdMOboz5SrmB8BkZOZqkWzRcn7Qllq32Snherde/4/wQekj
Zn93b5euN+0Pp+7QPZ2fzsbT3mE59fpe78PSncz6U28+80bueDwZnfTYq7cXF8z+IibHDzE5H46O
eDQNfxRvxM3kIW5mk+ED3ATyRZQrfZnxfdoypulDtNzp6UPElEiDV+JWn+2K9H2L2uwOtUuR3wA1
b+KNH6Dm74T//pXQe5m3ic0fJOaNj1E3LYB65LeJnD5IxPXcTxBZ5dIHTyrz9tIbPkTOnXneA+SU
5mAGLTLuXdQrJ9QdT08foHR97csUllrht83qTCYZ19EmbnoEJjc/g4H1WpQKHcVqvX7Jo/RCbreN
XuUK/lKXWVH4jaGP7ZfFxTZK1cAA5rEuaisXvxRRLq5l6ovu13L8oAYokHX+87HXEd/C7INh9vFB
EIA02uwswHZFr+PLQCCqrnsKJBj+/B24jVGg/Q641TuRCxYpxpmPNFFMDDZA1fWG1RgqujWJf2Q8
50lpYE9TDqkTdvHaI0aNEbnQRZ4yXJ3UNq7aBlSe2HJWbOLIZ2GR+jqSKaujLU1z8iv1npaj4ecp
LMkdW7Knehcp54cwSlsDvqcBs8aAKOyaMd8tlyyFLMYSnTf6UD9rcNTZ0jk97hN2vyPkrsVtpLSd
tAdWEytxwngasO+iVIs8hOzkE30ge4n0ve2GuREqY62PprYib4Ve8RxMtnvCli2ZRi4Naw/Uu1zu
WSr2jHB6JfULWaTB+a0vMsS8u+5Qg1EsQ9MOscO6Y0AYeXd4+Uj1oyNw8MfqnWQxo8dHvcxY1D99
TFvEQchE6J0MjrBZd2RarwJkjXDsolRvRBgLsp6mHZwQTi+JWPfucOeHSF1qcO5+t4R8doQd0Vks
WiO7FpJ5i+uPnY/fEtJvCem3hPRbQvotIf3rJaS9zlakIucx5k6Av4JQAv7d7Q8DcQNcbYooDjqL
IaRbudTSh5RmMZr3OjyLqJs76nvQbRtpKA4f+QMDcv4+jjY4pj/rY0VBmdWicxGlxS2kQuBxd1Jp
NuqP+0Nn603FmIehMxxO5y4UJ5vR6SlnECcuX67Y6s35+cvVFXsHyd4recPcOfOGC3e0GI/Y2eUV
FNwJZKrJzQwzMjxxWXQm/Smx/gEWOhQ9KA5N47VUJSNQQQUIuLmMgk6VdirE6xwsVSaHZ6sfsWQF
aFT2Goh6/WH/FGogpOxkrjBYylRs4B8qgeD8CWEnJgBX+9urfrv0e2TLI1se2/IYykBHpBwWSFAm
xYGAPD3AyaBNyVA/b1YkHNPnkg2IPIZz4AWiT1MKSpMXndXry6t3r99cPIeqvdioSIO8mIABKmX/
gpKRe+CwDceQeH8eJE1NfQ48RpIaokqyx8N0xlWUyrso2fq/Pkg+CVJhVMn1eIj+LTd38cHKY3DG
f4lF9bPcVGgYKR4PxQVHD3WMBdV+gYdxUfo/QOUx8FOJaJl7vIyQimQi14e7clYtx7JOf0dZLb9f
JnlmOaykb7D8GQhc7mR2j/hU/QUe4Tdl/xwJFTBRi2dZerxslyKO74pGtceSzf48C1bATyWkZe4z
ZLxXffdq78+UsanIz9bjFb+9KyJWHks4+stFLM1vK1yMRI+H5a0q8ns8l6nutdNqkuZPUn6BDFVS
luw9Qs7LaJviiVGhGlI2Khsygvpa8t1mB18XyR3Vf6FnqieFHWOTgUdIYTc/gEhTWc3apq7Gd3WF
+yY/56EW+b9Xr6DtqKKlw68QssHSet3m71NidnZaZwq2ibAb2xWbvi+TQZvDQZMYIZJrHrfAoIom
DqO7OMQ/H2Ipfy+VmjlRUPyNu3ba4H+BsKtDzpMouBIcvonaAKV8A8FdJj9qkTQkbVQ2pB33vZak
F8//91FOa1Q5py+GAaZar2uuzPnFIw27yMVK5ElzddZ1bQfkHecO0/GLF8Ph75Y6XBt6oM6SgcZn
Lc7l1bM3V29Xv6lRHGkPSWoqKLLgvgiLmA77mmK36lt+afxJzTbDzNdosMXA5yixdOlRjieq9+yg
bcMX7H/+qHjCDUv1Vrhi8RHy/kvwWO/+yfOGqHXdcdQctqW8EFvg7nX48mx1/kk/RJcxn9Rf51wp
PHOHjoaWFbbiZb2urx8/0yE12RzUwn3EYyS8VhTglkum6Pizb/cSkcBTpyerqsTOZBpGW4ZXpOt8
nT7Bo67nwmejIXOHi7G7GM3Z26szOurCDoaeg8Au34kYuBH/WBen03CzLsYCFij8f3K6LsJwOH8j
AqVBsXg7qoXSUbo9adBAnS7dU3fsYeUWKCYyEMshlhJ+62R0yK2WLtUoNHwHTwvNxdTScbF6vwOU
4kjppQxDrDAqcn4pRH5YyrRRlYM1lb0Cofw8oru6pTkhZgkogxUKj0VbB57EjtRBKS67R97uupgG
Y6iab4IJNo+mULPZTJry4sX8MpV5AlEJaYK4+cGJoyQCGLz5S6zEB3NOkQVci5JVvBkvUl9YPBzu
7yJxIxIwLmUFvInE3gkABA79LF48juXeCeNou6uwMRjyNAIWyrGmLpGbsmLH88CXubDF7CazX0EU
hpFfxPqwHJHG6IRXy9xRQqNy1ZJEAOZiYyB7mcdBXaeECBpdCI/n5y+evb24wlrUTz+DEA3DguXf
6QfkKLR0FL8p+SGFO02NhzIHdCr7sbW5NT7H57GPp9qoakMCj2Ors+v+IYlxTTB0qcyn5VDk1J1W
Bb0laBtE+oRd7YQSrJSb8VzgQwAG84Gp77hmvnnQsBHlHXgAH+zOakRal2hUMkQCxzQVD0WPSXxj
oJAk2+SCv2cHWeSWFotCBmJHYUQzgOJyWB/xAQm/EvuK3CAQIQfdKbaX6d8041km8JkFoJvglS2Y
ywHYZ3gdbuSm1w1Fts3pGUV/naIhG2KLdcqeXO1yAYqAKuAi5um24FvB8L0EQWaNXkVQpmP36AOB
ikPP8NrKSNEeCAyU7k6k/X30PspEEPG+zLcDLA0uQO/XMrz+8fL19XR06njXOA5grAgt2Brc9Hbd
wYne7QRih28y8OKNgZT2CgXUlPNU0W2HaSY0iVPgA76EJpUG4ibyBdtBBhWTkhMgbEyunpLCAdSr
XaEDievJvLlBZqx78WOp8Joc2XqGa5OhDdMljElE2E3E2X+j24Iu5L4c27JgGFhxIOys9/jQRKZK
Ajd2FqMqbgmBDwMjhMgEhkDSQfRl5gUA4lQ3OMDWBpiqyZ+Toyzp4GsAdAQMzBUsAlndHJi1I+hu
3WrVWsPw5F0EQMsUTIoHAcuFMpZH72UiUH0iOOwSyYdhcNgIxANAF78UPEZ1bKMb6HvD40Kwrp0S
YtAJEDfzgTunK2IHtIl3cQtoxZlfFckGb+ZC9kwdUv+Kq/cMb0dhAfWx/S0ogeyzFBJ77XLIMwow
CeiteozcFrPuDUy2BzAkgJrCxIFggeiMdUmRwsrBLkT7kkwGnwJlwOQteFkITQcUh0w9rVhDVA07
P4a4QrELrsQei/TfADmd06hAYKwjKzway7ogAeiZeYgIyeBYKRdECVerCTC0Vv8rlhsAFjMUZqoZ
xR30SYnY8s0B4nOfXRpWhjR5pFC9ZqWDTPuIGCOwGYYWG79slSJcwgjMBdwUvV9AKiH4iHLG8rkU
MI5Gu5Ugh8SlgZjBPFti0gTEBRuuyVWQV9Y7fMz1/5x9zO8+wTyG1a9iHqJZRvNbV1XxY6kpBksK
wyd4GcsNzlmy5A69seEKNjuRpHCEa5EerNE7gpK7ar25MBW4mgBtjHo4sB6EWWnkxiXktymsUMAN
vcNDsBo4IXDH5OFxrZtuawq4SANWX72SjTvCGV6jC8EIR937dzuj2DYpBwgz4WMgVAQL8mowNmMr
AQBJkalaTEh1jZzq5F6GrNQjI/WW5xvQv+PL2D6RwhV2L6pkTsiKHcPsGInJZlpQyG1yAelIAbZw
0it9wpExWGswfjUMS9+Q1FbWZ69NvKMSWMROFnFQMRKBB9mnrGYd7ZZlxDkIOB0OjYzsyQtaCXd8
I9mKGV0JFeYyKV0sjrXtTtMrNXQKQljVHZvCPfbTGIc7Ah8fzSiD9wVZPTpEqiyfXaI0zGTKPVqe
OSQgynRyMAfAXKamhaRKNduFcjq1fD6XZtix+jAIYKZkhjUpmFlst99BZgpEkMCC7RqprS2UE2FD
Fb0/SWqdpuaVUJW6gWnEJhJuuIYtBSYiHLNcCIBgT9Yr0QI0ialtNc5oI6qYSO7mSdN9lS248POD
Rto95rgNY8bYR9M6umQF3MpkarxKHWtpo4CBzj62tQo0Y6HS8tRn/4JtDsC7hFwYDPds9bYHY4GD
DfiffRTonfHatL4r8g6RX7CZTQzqlEERMI2uffYsgPW043E4wB0tZTGBADuzE8GUxv5k2lyQVXRu
0GrkSee3uPgwDeJxzyxsnPhdlEIWCWKB2QgybYz1b1fpqswU6pwdkyActAdfv8aEPc0cW2zmZLjl
3RTbhU06fmAuJhs2smBWSc1lRqnIj+1EmWmurSogjNR5osJnSHhM3mODrW+gBb8WqMak5cavtW8Q
ZRKJfIMkZsdEXa15obikcB9A1GRhdohjhixYAk1bu58AgejoCdkFkwMjJafEW/TBc+KOTDemBzD1
XW7sk2nKJl9fnS8YeV34zy9yfCIMoCOhKMliymCJPTtzxV6l4mctbfmwjwBPYmUlK6KQBJyg1Wi0
HG9oQwi6MhOZ0IxwH4z1NhzZVd+uLn2YyYUvcbmigBuuRGOyrgsL5Z5ZesyDBve+BqH9/gktWiWa
XJA5XCFl3FrZExsmwDGZ+TD0G03SJrbe3aIjoF0QZk/oDni85wdlaFs6DTtq+W8yo2eJLNJmAFA2
ZyuZQPaRGm4Z8PQFPhds/PBQnuMLbcO7odGOOsw99e4dTdaVCrOP3AhDbSNC9ER0uoIeC9VQUTVn
Lg3XZzzfJb+BoIv5XYTbZYHbr+xgjwZsLKoSGnIUIVeaUCVcrBsLi5i6SQWm6ih6kW1CCW3BctyP
g2EA2RKqnyXuhMzaUPhgHf+SE40aA0wl/5EyENBSGS/5LePHuGTmGagIanto64KM9A0PokI1hlk9
cMsdLVIz1Nod9odsBX0SHm7Z47KaQdhqC24moXOiOgoaxuuNXcl7/y7z1v/teUR7dNiPF8Lq146n
ZU/1jgJlLdj8i6hlMjNvLhEb842h6YjwOqU16QB6yLQ5wnPIjhQiiVAm+L4Vj1xsrWvdAx6eLZhJ
7kqV4nPaIoNkx2R8xiDJeZhEw9ICKjMcZSdEohMs7jlOVFVSHU82EVi+6WLP7cwefWGcER4n5Fzt
mKk1MdYaibFem8lXzg3t2sEDnnZNFU5atdkui9JQ1maA7zwXZsp+47wPEiHiL5XpIcE0n1aIAnxV
xSjuW2wzq5uJYbA1zvh2C9HHHg5Uxy6YI+KfLLy/XxrDD5JT9/GDeBlTJhUfjwabMK0Lo4A8dWxw
rjNAqpVZ48DoDM8M6RBLxDLDaNWDMkiAJ3S6TMUgMwkhUxYANsSnFOM8drKh1ZyJ8yYRZm9RGjlE
AQmn0ibAlQ7PUkMNmeaSvjoCZb/f3wdJHEG4MVo5v+UYb00BExagb5lYlNxQExg77pQX7Cf8dCDI
9Gjr/B+kaLxgmYY0T1tJiHK/YDZt5fE27cbuO7ylzS1FMUUZA4qdQCIRAaM2xDdYp1mJAfpieBqO
S5dCUj3bgr24eHa18L6f9Sant25vdDvqed+73wcQiY3X6upcQAE8zHI+ZFuwb2VK48kJHW6LWy1S
BIQubs8gDjXeJaMJNYoQDrbVdVbmY1dbUL/EkRYj85baMc+2P5jH1eZ6euPjn2RU/fHgNA3w3q2s
MH+JWJaKPK4KYRSDmRNp19x5hzqrWrdJ/b2D1Wvu6qDTz6q6bcZb1WRjznKrzpATHjJdS6A5MhQ0
xL1cXdCs+J35kMvVYw8gMD3Ztl9sgi8UXJScOXj/5Q0nwxF8Pv0R9BaOZiPBJ0EwmYzms6k7Hk75
fOh5fLyZ89FsPHbnG288FOwpzLTaISzVC7tMqui2Bt1u1m0HFwWt//4Kamm+uZiEPodMdQzTDsPZ
zJ/N59PJBKYenXojMRpuTmenQUDzqV0iawgVLSzVljQy4ENnLd+LFOJMXtW8E/w9eAQDVH8CNQdO
lyT4QAE7fIgyU/L6487Hj/8H+1tGKg==
===END CRASH DUMP===

**Comment by PocketKiller** [comment]
try to chmod the phar file to 777

**Comment by keithkfng** [comment]
Contributing guidelines...
