### ISSUE TITLE
Jenkins stuck at build #273

### ISSUE THREAD

**Issue by MasterWolf** [ImagicalCorp/ImagicalMine#476]
![screenshot_2015-12-30-13-01-34](https://cloud.githubusercontent.com/assets/15979343/12049867/bd486e00-aef5-11e5-9c18-6aa7559d3b90.png)
![screenshot_2015-12-30-13-00-32](https://cloud.githubusercontent.com/assets/15979343/12049868/bd4d7490-aef5-11e5-9900-586642ce2d0b.png)

**Comment by PocketKiller** [comment]
true

**Comment by PocketKiller** [comment]
oh forgot.. @aodzip has the HTTP server.

**Comment by PocketKiller** [comment]
maybe because @ZombiePower has made a syntax error, can't @aodzip delete the progress?

**Comment by MasterWolf** [comment]
Thanks @aodzip !

**Comment by ZombiePower** [comment]
@PocketKiller That was removed earlier
