### ISSUE TITLE
Snowballs have too much gravity D:

### ISSUE THREAD

**Issue by matcracker** [ImagicalCorp/ImagicalMine#477]
When you launch snowballs they spawn inside the player

**Comment by thebigsmileXD** [comment]
I don't think the gravity is wrong. The launch point is wrong because everything is offset

**Comment by matcracker** [comment]
But someone change something... Because some days ago works perfectly.

**Comment by thebigsmileXD** [comment]
I tested.. its horrible, when you jump you can just throw them with some luck..
But potions do work fine

**Comment by CLiu13** [comment]
Yeah, snowballs just drop straight down, even if I do some crazy acrobatic jumping.

**Comment by PocketKiller** [comment]
the bug is made by Gensys.. stop copying from gensys, it made the crafting bug and this.. where you did the huge update from gensys on Player class @thebigsmileXD

**Comment by thebigsmileXD** [comment]
As i said. I'll fix everything, i messed it up.

**Comment by thebigsmileXD** [comment]
Also @PocketKiller genisys fixed many things. For example the furnace.

**Comment by PocketKiller** [comment]
@thebigsmile sorry i meant not to do not copy Genisys anymore.

**Comment by legoboy0215** [comment]
I originally fixed the snowballs.
