### ISSUE TITLE
Pressureplates and doors not working

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#478]
Pressureplates and doors does not work anymore since yesterday.
Doors are split (when manualy open them) and pressureplates don't switch doors.

I removed the doors/plates from some buildings :)

**Comment by ecoron** [comment]
not 100% shure but i think this cames from the issue #493

**Comment by matcracker** [comment]
No, we must update the redstone API with blocks

**Comment by dterweij** [comment]
Seems pressureplates are fixed. They are working again.

**Comment by thebigsmileXD** [comment]
Ah, thanks for testing, forgot to do that.
