### ISSUE TITLE
MEGA CRAFTING BUG! CRAFTING NOT WORK!

### ISSUE THREAD

**Issue by NycuRO** [ImagicalCorp/ImagicalMine#480]
Craft wood,axe and all other and after 2 or 3 seconds disappear ! Please fix bug !!!!!
And add all crafting recipe!!

**Comment by PocketKiller** [comment]
Duplicate.. STOP DUPLICATING ISSUES!
and you always use many !...

**Comment by NycuRO** [comment]
Sorry,i don't know it's duplicated.....fix please bug or not?
