### ISSUE TITLE
Fire Removable with a click

### ISSUE THREAD

**Issue by PocketKiller** [ImagicalCorp/ImagicalMine#484]
Hello,

when you place fire (anywhere) you can remove it by just clicking on it xD that doesn't exist in singleplayer.

Thanks.

**Comment by BlackShadow1** [comment]
It's like the survival, or am i wrong?

**Comment by PocketKiller** [comment]
you're wrong.

**Comment by BlackShadow1** [comment]
D:

**Comment by BlackShadow1** [comment]
The real bug is: flint and steel can't be consumed..

**Comment by thebigsmileXD** [comment]
You can only consume food :p

**Comment by MCPEPIG** [comment]
He means durability dummy...

**Comment by BlackShadow1** [comment]
Lol

**Comment by ZombiePower** [comment]
I do remember in early November, @thebigsmileXD ws talking about fire durability in pocketmine

**Comment by thebigsmileXD** [comment]
Right. Fire is currently not a ticked block. It does not turn off by itself.
I asked the PocketMine devs to add the age of the fire. On 3 it would die.

**Comment by ZombiePower** [comment]
do you want to add fire durability? as I want to work on it (I will make a different branch)

**Comment by thebigsmileXD** [comment]
Well, in bukkit and mcpc it has a tag "age". If the age raises over 3, the fire extinguish.
I would like that, but i think the ticking is too slow to fit it..

**Comment by ZombiePower** [comment]
still an issue?

**Comment by thebigsmileXD** [comment]
Could you FINALLY STOP SPAMMING "FIXED?"/"STILL AN ISSUE?"?!!
If its not closed its still an issue!

**Comment by ZombiePower** [comment]
i am trying to update the threads... and no i cant...

**Comment by ZombiePower** [comment]
https://github.com/ImagicalCorp/ImagicalMine/commit/ac92c24f0039b99e58b691524a6c0b67c40ede6f
