### ISSUE TITLE
Fatal Errort: Ocelot entity typo ?

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#489]
There is a file named as:
src/pocketmine/entity/Ozelot.php

I have the following error to make a phar: 
Fatal error: Uncaught exception 'ClassNotFoundException' with message 'Class pocketmine\entity\Ocelot not found' in /usb4/ImagicalMine/ImagicalMine/src/spl/BaseClassLoader.php:144

The animal is named Ocelot with a C not a Z :)

**Comment by matcracker** [comment]
The original name is Ozelot, anyway we fixed ASAP

**Comment by BlackShadow1** [comment]
Sorry..

**Comment by BlackShadow1** [comment]
@matcracker can you rename the file and write in the file "abstract class Ocelot"? I'm forgot this before..

**Comment by thebigsmileXD** [comment]
Actually the codename is Ozelot. It comes from Sweden or where minecraft comes from..
Maybe the class not found can be fixed in the registered entities

**Comment by dterweij** [comment]
Almost fixed @thebigsmileXD  :)
Fatal error: Class pocketmine\entity\Ozelot contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (pocketmine\entity\Living::getName) in /usb4/ImagicalMine/ImagicalMine/src/pocketmine/entity/Ozelot.php on line 32

**Comment by thebigsmileXD** [comment]
I know. I searched for the parameters also (width, height, range etc.)

**Comment by thebigsmileXD** [comment]
By the way, its 4 am here. (Almost 5 am)
The latest version is successfully compiled. Good night
