### ISSUE TITLE
Undefined index: pocketmine\entity\ThrownExpBottle crash (build 279)

### ISSUE THREAD

**Issue by andris155** [ImagicalCorp/ImagicalMine#490]
ImagicalMine Crash Dump Wed Dec 30 23:37:28 GMT 2015

Error: Undefined index: pocketmine\entity\ThrownExpBottle
File: /src/pocketmine/entity/Entity
Line: 556
Type: notice

Code:
[547] 		return false;
[548] 	}
[549] 
[550] 	/**
[551] 	 * Returns the short save name
[552] 	 *
[553] 	 * @return string
[554] 	 */
[555] 	public function getSaveId(){
[556] 		return self::$shortNames[static::class];
[557] 	}
[558] 
[559] 	public function saveNBT(){
[560] 		if(!($this instanceof Player)){
[561] 			$this->namedtag->id = new String("id", $this->getSaveId());
[562] 			if($this->getNameTag() !== ""){
[563] 				$this->namedtag->CustomName = new String("CustomName", $this->getNameTag());
[564] 				$this->namedtag->CustomNameVisible = new String("CustomNameVisible", $this->isNameTagVisible());
[565] 			}else{
[566] 				unset($this->namedtag->CustomName);

Backtrace:
#0 /src/pocketmine/entity/Entity(561): pocketmine\entity\Entity->getSaveId(boolean)
#1 /src/pocketmine/entity/Projectile(82): pocketmine\entity\Entity->saveNBT(boolean)
#2 /src/pocketmine/level/format/anvil/Chunk(308): pocketmine\entity\Projectile->saveNBT(boolean)
#3 /src/pocketmine/level/format/mcregion/RegionLoader(173): pocketmine\level\format\anvil\Chunk->toBinary(boolean)
#4 /src/pocketmine/level/format/mcregion/McRegion(248): pocketmine\level\format\mcregion\RegionLoader->writeChunk(pocketmine\level\format\anvil\Chunk object)
#5 /src/pocketmine/level/Level(1139): pocketmine\level\format\mcregion\McRegion->saveChunk(integer 12, integer -43)
#6 /src/pocketmine/level/Level(1127): pocketmine\level\Level->saveChunks(boolean)
#7 /src/pocketmine/Server(2406): pocketmine\level\Level->save(boolean )
#8 /src/pocketmine/Server(2550): pocketmine\Server->doAutoSave(boolean)
#9 /src/pocketmine/Server(2243): pocketmine\Server->tick(boolean)
#10 /src/pocketmine/Server(2121): pocketmine\Server->tickProcessor(boolean)
#11 /src/pocketmine/Server(1722): pocketmine\Server->start(boolean)
#12 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/servers/server3436/PocketMine-MP.phar/, string /home/minecraft/multicraft/servers/server3436/, string /home/minecraft/multicraft/servers/server3436/plugins/)
#13 (1): require_once(string phar:///home/minecraft/multicraft/servers/server3436/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux pe.infinityhosting.hu 3.14.32-xxxx-grs-ipv6-64 #5 SMP Wed Sep 9 17:24:34 CEST 2015 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
ZipPluginLoader 1.1.3 by aliuly for API(s) 1.10.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
LimitedCreative 1.0.0 by basprohop for API(s) 1.10.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
BannerStop 1.0.0 by  for API(s) 1.13.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
SimpleGamemode 1.0 by MamayAdesu for API(s) 1.2.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
MCG76_WorldEdit 0.5.2 by minecraftgenius76 for API(s) 1.8.0
ServerAuth 2.11 by EvolSoft for API(s) 1.11.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtO4lu28a2vzJXLnDtQtS+WYWD5zpOmws78Yucm4dXFsaIHEqMSQ7LGVpWi/z7O+fMcJOXOIkL
3AfEaCPOdvZthsO/WjqMRWveH4374/5sMpq1WxFX+jTLZNaa/9XS2xSGW4nUoSda7VYslOIr7Hqf
+CIIE+GzEJ5u5yyV3rXQMXS5rkh0qLeue7nO5CY5vU1/llpHCCDIo+hVGCGEdM2zebfbXctYdHGd
l/FAd+M8AmT0qER2IzJlf4ej4aR7QVjOYbZzftFBEF2Ved0Kedfg7p7SD8xIEavB+OhUmBZBZ2s+
Hk/aLZ1xYHj+W2uvxx5dtj+e9A/u595McF6shF7wG/Ha319KGQmeHACuvf5DcC8y+VF4Gkjenw0+
A1oB3Dc/XzYAD+4AjsSNiLqBzGKuuzy5CaPuyTpPrveHvdkDCCoi7kcyfBxJ7GViFcqk+45+ziT3
Rbbfnw530NEi1zWrXJdoc10iznmh5c9hwrNtA/HoiYjPPYN6fzCaPY60WOK6dWKdF5ss1MLI6Ykk
M7lEoRGd4wfoPMN/9/v94eFTqSo4MYowBIWJFiuRsf6gzYpnZzQkzJPPYB5M78dM4zUkqiH36R2o
C/JKkG9v8lmABShGsGYPwhqPezuwzIjzwpfHuZaLGiwCdfggqMFo+AAoCC/XTVfsPQilP+g/AgW8
xIOIKLMmuP5D4PrTweABcErzTDfB3HXkKvrtjyaHD0C6uvJkonSWe7phuCcyTrkOl5E4gRivjJlb
k203IOXg9woMj4fgDKtVbRaADZMVe67QXQL8MkhfuSyN8lWYqK6R7pDto2oz8UceZuJKJp7Yf2b2
HtQepqWD1u+f2i3x92XaL8x5QIwRUGse8EiJdsuTvkDSxqMpAHK1qzOh8yxhNP4TLB6PZjTyiZ4P
4Rkfxj3q7P74I7X61GI/sne0WjG9FkytZaYZhgaW8FjQxIGdSI1hseq/LFKjGxob2bEutcbUSvNl
FHosyBPIWjJhVdI9+IumTZo8KBEF8/kPRMcboED9Bh4Isp/PPfSO34m98bRibzwr2Du8F2GRJQ26
Sc+iC4P9f+z/oNehAvUBCjAzGbCLiG9FdmDn9u1cV9NE5wWKxNd85bwIfXbEErFhC2J/322Fvttq
MzuxxuUBUTwZlLAAczULWbzkq/0D9o+jI+a23JbFPSzn34P9JFdaxrh2l4pqpElNiceSM3oa+H+H
CgPTw1jshBqyUFlcdqhEOS5RfhJgp4bNSY2OPFFC7z9CDQD69L0E/F4Cfi8Bv5eA30vA7yXg31gC
tlsrkYiMR1hoITzwckhV/U7PFzdA5DIPI78170FxlkktPQkTh7N2i6chTeuPOj2Ytgo1NHtP/IMF
Gb+OwiWu6UwJQk5l2Lx1Fib5LUtFJ0yg6IREsJZKg0Q665wNEd1w4NzCn7PKlBOmNxNnMmIQ6hbn
F+wD1KgLkbJD1p/OB6P5cMROTheXbNDrj9ntbHIF5QAwsk4Bz7gz6Qyg9adIgL/WAJo9M3glVUEH
dFAjokZZoSoU1kWeiQuRxdSwxFd97YYwB4SK5xqqPYUpfTJ69Qrk8LsV5G8oyUGHOkTCwT+AJnAf
KIJ9kQKFuAjGlAz0y3pHzLFebl0ZeJAzCwJqj1hkg6PBtMXl8bvL9xfQsRFLBakF+tZapwosDTS4
zpcdT8ZdWmkNtYIC3C/COI3EudkZ1PneGagxD7w3GH8JEfS6wXfv69luooXws0uG5fvi7eLyw9t3
Zy/rnCd5FAFPpxCpZLw9vnhd46fWWVckaKhz2FSkTMQS/r/DURs1an8H5W+ffoe2PbTtkW2PoP2V
krBkQPFkKAdaoEKrc/EEUfxvmBq1m7hck8fuSNO6gZOmUHgU5tG2ad3foOYd7CYrfLFV80h85Imf
SSCuFhKdIiTDxgwiLVdaZN1dfis7WYgoumso1LtrKdPPW8pnfb5uiV+gfthcRqX+LXFPMIB/v75Y
RFLXPbvsqnMHuuyMmtyF/5JqnfNfXz5bTCshum6NiC/TefiRYKz9bgkC2AyhZtJQS8i6idc666yC
j/Imp2cv/6fB4+HXswigXLdCvGvY96rqPjYBjnN+cnHarTEBfJ6suT4RiWrwWetsevGOQk9vZLQA
up+L1wrvl/jvZrPpCKAEoXb0NXJ1FsYwxz/JBFSSN6LG2u5Ikz8TlWscLrmCmmYt02cLVCVE2Hjc
oeVhbpuZaIEU3Y0w2PufFGGIyyZxT4gwP/PktRZxjb+ip8lb/3Gf632jz1mkT3I4S/k5X4XepYjE
hcw0r+eA3ZGm2Q13S79nTo4GHGzWdfol7IAEoOxf6Iat1Tof950G8cOvJ/5NeA1mtf31PanE4q4/
f1EN9y+5vOs42LnrN6P/FzXcR7ksPcxw8QRRmBL4FxBBbE/PGyV6ObCj36ZAznnMt8e+UHlDJt+Q
zGOEyBGi6yqiZGUp2W0/jc2TtVD6DIu4Zm6renc2YE9IbrNvSW4l4m/MblbfZxx3pbu2TL1fsSH5
u5JABPSUJmqJe4LyjqMN36pFyjdJjcd6b5PHO7vni3UYhSlbwE+E72Seq+RMCa6yYF2XE0kKSYKM
Xmx9PpvIz09+mU6uPsgs8k99PBipUsXOSLOoHu/yWZ77rEQS5mo6eS57jb3VdOK6ZuvjuhskSABB
rlvShvuf109MJubY7xgIrwecqnMnt/ef4Iz9/jccC5SYixNJS8VnXPJ+jzyJBM/O+GpVDzRl3+5O
eCeSnglQnf82wOr8uSqYEvldm3z6jqFGV7fiBtjFAx+s1XdOtahrt7IZfv5Q63NqrB2Z3WG59YrT
q00Fu5rWA4ddSFf19M1HXQQEw7BS+BqKRwr0VovD9e7PHIIYESsjY3YpePxscapOxnMZQYO1T3jU
yTNgWoui4DPnzB3Y4KQi0yGe/7X2LsoWO5FJEK4YvvZ3MzfZw8PYl8Jjwx4bDOfDwXwwY7+cm8NY
nBBL7R+5ea/HpzPzEzmO85t59C7X4m3kM9MKHPvATzAaAkm2PQT+GxB+BxAI3BDrpFCRH/UP+8MB
dm7WIAonCpU+kkGAPVBnyjzx8BAI34c73FuH4kbEIAl1JBOChNHfSc2+GpR91MfeTPhKQyp0PB55
ecRpxCyI+a0Fp46GPcISRXLjBFG4WpeYDViehDFIvIEqlsuio6iJjghMIDOgtOyzgNY88z2Zle30
JrWr/TAIQiBOb4+IfXPQr2XmKKHxSF0dYTe9KXPQwI+IAEoG1YASwq/Nw2siRy9PXx2/P7vEXmO+
zh+5yLYWr+3KPBSJIQqfOylXCoD7Rz/SH8gl19LBV3N24U0oNo4fmksKR5OaHsP0aAxF3Biq69kM
tktDHMPT+vIYr7ONIzRIhtUX88gW84z0QibJQHqs8X4ETJSBlSnBCnEwngm6HAKKxVsiXDMPLUSz
pWBh4kW5T5dg2B1XQFgLGcPKAAHswlQ8EG0mYQQsF0CyZSb4NdvKPLOwWBgw0GoYhIQBFJqBucG+
DgC/EZsSXNcXAQeVKraRyT8142kKsZuhJGO8PQKmtgXyGd33IL43a5GwPF1l3Me3KG6CQjXA5m7C
9i7XmQCngC6gAgq6Vc5XguHVGxKZVYAKoR1JgB/+SULFpVD1epaL5kIgoAg3IulswuswheqCd2S2
6mKrewZKvpLB1evF26vJ8NAZXOE6EGMJaM5cCI0rt4WIPqwFyo5pCfQkPgMu7es3UFPGEwUOCHKj
YZImUQp0wJPQpFJf3ISeYGsoUiNScgyAjUdVKOleEfSrda59ib5oXiUgMcdM/UnANcDEaCP6UUS/
vpZam57rDttfmGkUoQL+MQN79O08M0kdGK6OMSwwDEf0ws9kIXYTcvbf6E0whbyqOKCuyNtbrGEh
RytXErixVBpVcwuJ5QqMGNIJGBJJB2p7mAnpyUc5VwMOELuUCpjEDITgT8mBCzggMYYBhoG5g0Uh
rcsts3YI0627l6M1Oj9AIQ3GACbJfZ9lsPsjy0Uy8dU1kMMVJF0MtwzsdSlQIKA08UfOI1TnKryB
uTc8ygXbtyghgRwAcIMPwozAIO+ANeBb4jmMIuY3ebzEd8YBO1bbxLvk6ho8JoP9merg+HsFEkH7
LpjEWesMNjI5mBTMVm1GgZDZqAkm3wYxxCA1hTmfxALZFfviPAHPwykEe0EmB/yAc2byFiK8FiAC
YIdcJSlJQ6kacl4H6OE4BT25zUL9T5CczmiVLzD1kBXvrGX7wAHomQ1QIsSDY7mcEyT0dkwX2ZZ8
/ZdILkGwWFYw0w3mF4caY1oMO/DlVgNBbGFI6RHyUKF6TaQAnjYhEUbCZpjWDJxC/orkEoRgLhDm
IGMkBCqAGFNgNOoHZnIy2pUEPiQ6DMoM8KyISIcIm7OeS6GGorqGUMX9/3DysUR7hHhM199EPJQd
qbnBaMJMSY+Fphi4FKZa4RfUIM4dkqDiDiXlMnREhdg8iuaWtNLZ+oAH4oyPBkYzHHAGYdyMcoCE
ojEB9wShYWh4SKZGllCBRZQe0NHNNJeyNcIA16vc2MQixPAW4wemR5reuTsZebZVNMgvFR5mUXPL
E2k1AjZrSwZAjCJVFZtQpBo+1cG9BFmuh4brFc+WoHzHk1FkqkJ0r3ulSraEpNg1zK4Bx415klO+
rlMBtUwOhnDQLgLCjiVYUzBBNQiKwBBXJtZhb02ypJbCm6555JeEhBA+NgmrSEejZSlRDgxOej3D
I9t7RW5wJzCSrZjVJVNBJuMivuJaO+7UQ1JNp8CEVd2uKdxjP7V1WFp7dC/MyJteslA0pE6kDPdA
yA0zJXibfDOD6kWZSQ4WEFgIVbAQVKFm6yWHE0vnS2mW7aoPMwCWWWZZHYLBYqc9A8+UhWCbAbZr
uLa2UCDCgTJ1PwrKTRKhURdl3QemEZk0uOQatj5YhnAskRVe6WM2JJEDmqrWjppItBRlQqRYs1eP
XcUIOn621Qi7zZx+zZgx8RFaRxekQFgZT0xUqRIt7Tswy/km1lkFmrXQaWnqsF9hfwXiPYJCGgz3
5OJ9G9YCBUuIP5vQ12sTssm/S/AOgZ+zqa0KqnpBkWBqUzvs2Ad/WvMo6MIOwZQwvgA7s4gApbE/
mdQdskzNNVi1Iun0Fp0PayAetY1jI+IPUDbKDbAFZiPItDHRv79ILooyoSr4sQLCRRsI9C5W+0nq
2Ga9IIMtoVjmq7mtOF6wPlYaNq1gSUnDRTmpKI6tRVFmulYVc9avikTFunhtPQeD6a48I1qIa76q
IS32kY1NhygqSGZum5rtFk215oXsksI9fIdKFmaXOGbJnJUXVA1DdIKC5GKVrkxQ4g34EDlxO6dr
6EGY+i415KOkur03by9P54yiLvzn5bAzS2BnRoDozQWqjsizmEvyShUfN7TlwSYEIonllayIUhJQ
glaj0XIGPZtCMJSZzIRmhBtm7LfpyHp9s7uIYaYQXqC7IoNLrkQN2X4fHOUeLG02gIH+fQNCe50D
clol6lSQOVwiZNyX2aMPJiAwGXyY+o0maQdcbY0xENAeCEsnDAfmvN3AtnBqdtSI32RGx7HMk3oC
ULZgK4hA8hEa7hcgNuMjCObhpTyDXt/QbmA0sw4z4enOYjKuRJg96FIYYEsRYCCiQxUMWKiFEqg5
66lFvv6I1IUfpHCs7ULcagvceqVbe6xgU1FZz1CcCOjGUhEVbRQL8oimSQWW6pgPS0wmoe1Xhnt5
sAsAW0jqo8RdkHENhd9b4Ie5aNOYX0r2d3SB8ix0cc5vGd+VS2ouJwu/MoeGKoZko++4H+aqtsyq
gVvqyEfNUmt2ON8okg7VnDz1wRRrW2QPj7SNIeEGu0qChvBqU1fQ3rlLvA1/Gx7SBh0247mw+rXr
yeup31GgrDmbfRW0VKZ5ZKHZZ8xMO4DdhFzSAekh0ebo0CE7AsZHWLaBwhO0hrK3b6MDHrLNmant
CpXiJe88hVrHFHzGICl2mDrDwgIoU1xlESLQMTY3HBGVndTH42UIlm+m2PM9sz+fm1iERwkZV2tm
ek2KtUZirNcW8mVsQ7t28HCo2VNmk0Zvuk7DJJCVGeDd4blB2amdFUIdRPQlMtnGWOWThyiQryoJ
xW2LHWbVMBEMtsYZX60g+diDgfLIBUtE/G7neoebJkEIT91HEArM2DLp+M5ysAozPDcqyBLHZueq
BKRemVai2TvBE0c6AhORTDFdtaENPOD5ni5qMShNAiiVBYh7jfcvINHjJJtbc9QPeGQNCLOvP2pF
RA4Vp9ImwxUhz0JDHZnhAn5FoZEKvnu7RyZRCPnG6OX0lmPCNQ2sWAC+JWJeUINSSuutJL8W9fYq
nrPmZYj5Cg8Due+vIO401mbxnS6wvBxcMN7pW+320UdeuzNdc7peFkH1g2KSYLFbMVvG4sCe9oL3
nTvT1ppyqKJ6BWVOnwgAd7bAqMmNsBIB9MTwaB8jB2WeCtucvTo7vpwPfpq2x4e3/fbwdtge/NT/
yYc6wATNfbwr62GAO5r12ArcS5nWaIwfNohbLRJkmC6SnkASrN23R+utNSEXrcoPPlMPp9qG+iMK
tRiaTwQc8zXCn+abAXMZZ+lBTbWuvhblEbgtz6oO80lr0cqzqGwEYaTx5giA7pt3toFOy9FVXD2v
IXSUV2Q+qvI+P77Djpf2m9BiMtSj21RXHGiOBPk1dhcXZ4QVn1MP6shq7RYYpk8R7BMbd5A65Jw5
+NZs0Bv3hvD4w2uMCMPpUPCx74/Hw9l00h/1JnzWGwz4aDnjw+lo1J8tB6OeYD8Apos1ioVuixBi
qcLbSuj2oMBO6COj70Rgd7nQS/hmYhx4HKrkEaDtBdOpN53NJuMxoB4eDoZi2FseTg99n/CpdSwr
ESryadXkNDTCh8laXosEklxW9nwQ/BqCkRFUZww9W05vd/AtK074M0xNa9AZtT59+j/qkmPC
===END CRASH DUMP===

**Comment by thebigsmileXD** [comment]
1st: this is duplicated
2nd: are you sure, you are on the latest build? We fixed it.

**Comment by andris155** [comment]
build 279 = Not fixed this bug
