### ISSUE TITLE
Console Spamming

### ISSUE THREAD

**Issue by EpicSteve33** [ImagicalCorp/ImagicalMine#491]
It's spamming could not tick level "lobby" and i cannot join anymore

**Comment by EpicSteve33** [comment]
Hopefully this can be fixed

**Comment by thebigsmileXD** [comment]
Which build? Its like the grass block once.

**Comment by EpicSteve33** [comment]
I'm using the src like i always do

**Comment by thebigsmileXD** [comment]
Which is slower.

**Comment by EpicSteve33** [comment]
I'm going to use the Phar from now on it isn't spamming with it

**Comment by thebigsmileXD** [comment]
Fixed now
