### ISSUE TITLE
Sometimes Jenkins stucks

### ISSUE THREAD

**Issue by MasterWolf** [ImagicalCorp/ImagicalMine#492]
![screenshot_2015-12-31-10-47-49](https://cloud.githubusercontent.com/assets/15979343/12062831/0d7bfdfe-afac-11e5-9bb5-21a7c71857f4.png)
![screenshot_2015-12-31-10-47-31](https://cloud.githubusercontent.com/assets/15979343/12062830/0d7b444a-afac-11e5-8b13-82df58032dcb.png)

**Comment by thebigsmileXD** [comment]
@aodzip maybe you can create me an account. I am the most active dev and might stop builds that stuck.

**Comment by keithkfng** [comment]
@thebigsmileXD I have an account - contact me via Gitter or email.

**Comment by thebigsmileXD** [comment]
@keithkfng but i am a bit more active, especially at night

**Comment by MasterWolf** [comment]
Try to make more Jenkins accounts to controll builds.

**Comment by MasterWolf** [comment]
How many accounts do we have at the moment? I think 2-3 will be enough
