### ISSUE TITLE
Error: Could not tick level "worldname": Undefined variable: down

### ISSUE THREAD

**Issue by ecoron** [ImagicalCorp/ImagicalMine#493]
since build 274 a new error is spamming the server.log:

```
[CRITICAL]: Could not tick level "worldname": Undefined variable: down
```

not 100% shure but i suggest it occurs in
```
src/pocketmine/block/HeavyWeightedPressurePlate.php
src/pocketmine/block/LightWeightedPressurePlate.php
```
at line 71 in the onUpdate method where $down isn't  initialized.
Could be this is also the source for some issues with not working PressurePlates.

**Comment by matcracker** [comment]
Found the problem, I fix it

**Comment by thebigsmileXD** [comment]
Finally someone who also gives te error line. Thank you.

**Comment by matcracker** [comment]
Yesterday I fix the same problem on stone and wooden pressure plates, someone delete the $down = $this->getSide(0)

**Comment by thebigsmileXD** [comment]
I will.
