### ISSUE TITLE
CRITICAL: Could not tick level

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#494]
[14:03:34] [CRITICAL]: Could not tick level "world": mt_rand(): max(12000) is smaller than min(14000)

When creating a phar. And if I start the phar, It floods the console with it.

**Comment by thebigsmileXD** [comment]
@matcracker weather system?

**Comment by dterweij** [comment]
Yes i think to.

In Level.php

**Comment by matcracker** [comment]
Yes and no, I do that the ticks don't go over 24000 so do /time set 0 and all work

**Comment by dterweij** [comment]
I shall try

**Comment by dterweij** [comment]
I cant get in the game and i cant send commands in console

**Comment by matcracker** [comment]
Do you use the last build?

**Comment by dterweij** [comment]
Yes from few mins ago

**Comment by lolcraftboy14** [comment]
It font work plz fixs it

**Comment by lolcraftboy14** [comment]
It dont work plz fixs it

**Comment by matcracker** [comment]
Oh wait, I found the stupid problem! I wrote sunrise and not sunset xD

**Comment by thebigsmileXD** [comment]
xD
