### ISSUE TITLE
Smail Description

### ISSUE THREAD

**Issue by ThanhSotu** [ImagicalCorp/ImagicalMine#495]
OS: OS X
PocketMine Version : PocketMine-MP_Alpha_1.6dev-1266
PHP Version : 5.5.14

Long description about the Issues
<link to crash dump>

**Comment by Charelene** [comment]
What a descriptive description. ![4Head](https://pp.vk.me/c627928/v627928959/3b6f7/L0CkMqJduiQ.jpg)

**Comment by ThanhSotu** [comment]
:)

**Comment by robske110** [comment]
Please provide more info
You just said i'm using this.

**Comment by PocketKiller** [comment]
please read the contributing guidelines

**Comment by PocketKiller** [comment]
... he did <link to crash dump> while typing this, lol.
