### ISSUE TITLE
Request: Weather

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/ImagicalMine#498]
Would it be better if weather was clear by default and toggled on with the /weather type and duration command?  My users are complaining that it's annoying and it has been suggested that it may be causing lag and client crashes.

Thanks

**Comment by matcracker** [comment]
Sorry but it's default in Minecraft, made a plugin if you want ever cleat the weather

**Comment by keithkfng** [comment]
Well, you could use TimeCommander and issue the command /weather clear every minute if you wanted to achieve that. But there's no way of getting rid of it forever included in the actual software.

**Comment by thebigsmileXD** [comment]
Weather switch incoming

**Comment by NML32** [comment]
looking forward to it @thebigsmileXD
