### ISSUE TITLE
Gitter chat room is just displaying 404

### ISSUE THREAD

**Issue by robske110** [ImagicalCorp/ImagicalMine#500]
(using the link in the readme)

**Comment by PocketKiller** [comment]
true, the gitter chat deleted.

**Comment by PocketKiller** [comment]
SOMEONE DELETED THE GITTER PUBLIC AND PRIVATE REPO ACCESS SERVICE

**Comment by thebigsmileXD** [comment]
xD

**Comment by robske110** [comment]
@keithknfg

**Comment by PocketKiller** [comment]
@keithkfng i can create the chat room, but i can't without your permission.

**Comment by keithkfng** [comment]
Gitter chat room was deleted because of abuse. Please use the official forums.
