### ISSUE TITLE
Duration of /weather clear <seconds> not working.

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#505]
When you do /weather clear 900 then you expect that the weather is clear for 10 minutes. But after 20 seconds orso the weather changes.
II did try various times but whatever I type as seconds (even 99999), the weather changes back to automatic after about 20 secs.

**Comment by matcracker** [comment]
Wait, it's correct... If the weather is raining or thundering and you put /weather clear 10 the weather is clear for 10 seconds but the return raining or thundering... I you want to remove their just do /weather clear

**Comment by dterweij** [comment]
But of i do /weather clear 300  it should be clear weather for 5 minutes. Thats not the case. It starts rain/snow/thunder within 5 minutes.

**Comment by matcracker** [comment]
Because rain or thunder have an duration between 5-10 minutes

**Comment by dterweij** [comment]
So you say that the /weather clear <seconds> command,  the <seconds> is a lie? So whatever I put in for <seconds> the rain/thunder/snow always kick in?  Then its useless to have the parameter <seconds> or say <seconds> can be max 5-10 minutes.

It should shutup any weather event until <seconds> is reached right ? If I command it to be 3600 secconds (1 hour) to be clear weather it should be clear for 3600 seconds (1 hour) and no rain/snow/thunder should be shown.

**Comment by matcracker** [comment]
It's not a lie, I don't decide this rule, the Minecraft developers decide that. Anyway the <seconds> parameter is useful for turn off rain or thunder for X seconds but when the X seconds gone return rain or thunder and after the 5-10 minutes (I think to decrease to 4-7 minutes) the weather return sunny.

If you do /weather clear 3600 the weather is sunny for 1 hour; end the hour can return rain or thunder

**Comment by dterweij** [comment]
Issue should be open. Its a bug.

**Comment by matcracker** [comment]
No! It's not a bug, try this in Minecraft PC, it's the same thing
