### ISSUE TITLE
Where i can Find ImagicalMine Phar?

### ISSUE THREAD

**Issue by ZhenMC** [ImagicalCorp/ImagicalMine#506]
Hello Where i can find ImagicalMine phar? I tried Jenkins it .dev

**Comment by ZhenMC** [comment]
But its .dev*

**Comment by matcracker** [comment]
Rename it into .phar and work

**Comment by thebigsmileXD** [comment]
http://jenkins.imagicalcorp.ml:8080/job/ImagicalMine/ There are only .phars

**Comment by matcracker** [comment]
If you download with the phone, it downloads with .dev xD

**Comment by thebigsmileXD** [comment]
Why that?

**Comment by matcracker** [comment]
I don't know

**Comment by HimbeersaftLP** [comment]
My phone downloads it as .phar
