### ISSUE TITLE
Banned when dead

### ISSUE THREAD

**Issue by Edwardthedog2** [ImagicalCorp/ImagicalMine#511]
On a hostingmyservers.com server I own, me and my sister both got banned when we died. She fell out of the world and was banned, and to see if it really was the kill that caused it, I tried "/kill" and was banned as well.

**Comment by thebigsmileXD** [comment]
Not imagicalmine fault. Check your configurations and plugins

**Comment by dterweij** [comment]
Hint:
hardcore=off
