### ISSUE TITLE
XP Orb AI (no despawn entity/add xp)

### ISSUE THREAD

**Issue by PocketKiller** [ImagicalCorp/ImagicalMine#512]
i've edited IM code for testing, it made if a player/entity die it drops XP (will commit it later) and look at the pic (will be commented) the xp keeps going around me and follow me! if i run very fast, it drops and forget me xD so when the player tries to pick it the xp isn't despawning and not adding XP D:

**Comment by thebigsmileXD** [comment]
Dont understand the second part.

**Comment by PocketKiller** [comment]
what sentence exactly?

**Comment by PocketKiller** [comment]
![screenshot_2016-01-01-21-00-28](https://cloud.githubusercontent.com/assets/13422058/12071870/8ab354e6-b0cb-11e5-972e-e718b38a24a5.png)

**Comment by PocketKiller** [comment]
more images incoming, needs time because of my slow network -.-

**Comment by PocketKiller** [comment]
![screenshot_2016-01-01-21-00-37](https://cloud.githubusercontent.com/assets/13422058/12071882/60307d56-b0cc-11e5-9b4e-ed2bf9c8466a.png)

**Comment by PocketKiller** [comment]
![screenshot_2016-01-01-21-00-59](https://cloud.githubusercontent.com/assets/13422058/12071886/9131db84-b0cc-11e5-9891-ded0bafb92e6.png)

**Comment by thebigsmileXD** [comment]
The current orbs also follow you. (Just a bit glichy).
I like to add drops to orbs, furnaces and others. Because i might work on enchanting

**Comment by DRedDogPE** [comment]
@thebigsmileXD That would be very useful!

**Comment by dterweij** [comment]
If you break a lot Ore blocks (coal, iron, gold etc etc) It is a mess arround the player. I can't see clear anymore because a dozen of XP orbs is surrounding you and following. When running fast they cant follow you that fast and drops on the floor  or stays in the air vibrating very fast.
The orbs are gone after you logout/login again. Also the XP you got from mining, is lost after each logout. You always start at XP=0.

**Comment by thebigsmileXD** [comment]
Is there even xpdrop currently on orbs? If so, @PocketKiller added it

**Comment by thebigsmileXD** [comment]
The non despawning ones are some created by the client.. creepy thing

**Comment by aodzip** [comment]
Some item drop cant pick up too…
I think it is the same thing of entity offset

**Comment by thebigsmileXD** [comment]
Entity offset i may be able to fix.

**Comment by zzm317** [comment]
@thebigsmileXD you could get the ai from genisys

**Comment by thebigsmileXD** [comment]
Xp already drops on ore.

**Comment by thebigsmileXD** [comment]
And now the never-despawning exp orbs are fixed, ores drop exp, furnace gives exp, mobs drop exp.
