### ISSUE TITLE
how to disable rain

### ISSUE THREAD

**Issue by TylerAndrew** [ImagicalCorp/ImagicalMine#513]
how do you make the rain stop using the last imagicalmine to the current one

**Comment by matcracker** [comment]
Or you delete the pocketmine.yml (do a copy of your old configuration) and then start the server or add manually in the section "level-settings" the part "enable-weather: false" like that https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/pocketmine/resources/pocketmine.yml#L106
