### ISSUE TITLE
How to install ImagicalMine on CentOS  (wget)?

### ISSUE THREAD

**Issue by KubixQ** [ImagicalCorp/ImagicalMine#514]
Tittle says all. ^^

**Comment by keithkfng** [comment]
If you actually read the README you would have found the answer.

**Comment by dterweij** [comment]
Should be open:

CentOS 6 - 32 bit:
[danny@server02 pocketmine-pe]$ curl -sL http://get.imagicalmine.me/Linux32 | bash
[danny@server02 pocketmine-pe]$ curl -sL http://get.imagicalmine.me/Linux32 | bash
[danny@server02 pocketmine-pe]$ curl -sL http://get.imagicalmine.me/Linux32 | bash
[danny@server02 pocketmine-pe]$
[danny@server02 pocketmine-pe]$ curl -sL http://get.imagicalmine.me/Linux32 | bash
[danny@server02 pocketmine-pe]$ curl -sL http://get.imagicalmine.me/Linux32 | bash


Nothing happens.

**Comment by dterweij** [comment]
CentOS 6 - 64 bit:
[danny@server03 test]$ curl -sL http://get.imagicalmine.me/Linux64 | bash
[danny@server03 test]$ curl -sL http://get.imagicalmine.me/Linux64 | bash
[danny@server03 test]$ curl -sL http://get.imagicalmine.me/Linux64 | bash
[danny@server03 test]$ curl -sL http://get.imagicalmine.me/Linux64 | bash
[danny@server03 test]$

Nothing happens.
![im_inst](https://cloud.githubusercontent.com/assets/1059028/12076797/d9b6f5ac-b1bb-11e5-926d-7f57f8a22e22.png)

**Comment by dterweij** [comment]
Also, there is no A record for hostname get.imagicalmine.me

[danny@server02 pocketmine-pe]$ host get.imagicalmine.me
Host get.imagicalmine.me not found: 3(NXDOMAIN)

That means, the world can't even get a Imagicalmine installation at all.

**Comment by keithkfng** [comment]
Weird... I'll look into it now.
Try get.imagicalcorp.ml for now.
