### ISSUE TITLE
Installing ImagicalMine on CentOS.

### ISSUE THREAD

**Issue by KubixQ** [ImagicalCorp/ImagicalMine#516]
Hey, I trying to install ImagicalMine on CentOS, but I have this error when I type ./start.sh :
./bin/php5/bin/php: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by ./bin/php5/bin/php)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by ./bin/php5/bin/php)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./bin/php5/bin/php)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/pocketmine/bin/php5/bin/../lib/libz.so.1)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/pocketmine/bin/php5/bin/../lib/libyaml-0.so.2)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/pocketmine/bin/php5/bin/../lib/libleveldb.so.1)
./bin/php5/bin/php: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by /home/pocketmine/bin/php5/bin/../lib/libpng16.so.16)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/pocketmine/bin/php5/bin/../lib/libpng16.so.16)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/pocketmine/bin/php5/bin/../lib/libcurl.so.4)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/pocketmine/bin/php5/bin/../lib/libcurl.so.4)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by /home/pocketmine/bin/php5/bin/../lib/libcurl.so.4)
./bin/php5/bin/php: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/pocketmine/bin/php5/bin/../lib/libcurl.so.4)

**Comment by keithkfng** [comment]
You need to install the extensions for goodness sake -_-

**Comment by thebigsmileXD** [comment]
All in one.. apt-get update && apt-get upgrade --fix-missing

If it tells you packages are corrupt, then tell me, i know a fix for that

**Comment by dterweij** [comment]
CentOS uses yum not apt-get.

And yes, the PHP 5 and PHP 7 packages are not working like the above GLIBC errors.

Therefore, I could not find a WeakRef for PHP 7 yet so my own attempt to fire up PHP 7 is stuck until I get the WeakRef for PHP 7.

I am using a older PHP 5 package from Pocketmine-MP. That seems working fine. But I still want a PHP 7 working package....

**Comment by dterweij** [comment]
So this issue has to be open until solved!

**Comment by keithkfng** [comment]
1. I don't think PocketMine will really ever get completely updated to PHP 7 because of the extensions(they're not updated)
2. I fixed the shell script. CentOS... Try Linux's installation script.
3. The shell script uses PocketMine's PHP binaries. It gets them from http://imagicalcorp.ml/binary, where all the binaries are for the available/supported operating systems. So it should work perfectly.

**Comment by keithkfng** [comment]
Can't fix the subdomain problem.... It doesn't seem to like me :(

**Comment by dterweij** [comment]
Okay nice. PHP7 extentions is a slow progress. Dunno why that is. I just wait for the WeakRef and hope it will work and not wants another one :) For the record, I am using PHP 7.0.2 from REMI repository as system PHP. By using zts-php binary it uses the pthreads extension.

[danny@server03 minecraft-pe]$ zts-php -v
PHP 7.0.2RC1 (cli) (built: Dec 27 2015 09:23:59) ( ZTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
[danny@server03 minecraft-pe]$ zts-php PocketMine-MP.phar
[18:13:34] [CRITICAL]: Unable to find the Weakref extension.
[18:13:34] [CRITICAL]: Please use the installer provided on the homepage, or recompile PHP again.
[danny@server03 minecraft-pe]$

Lets gets our fingers crossed :) (http://blog.famillecollet.com/pages/PECL-extensions-RPM-status)

If the extentions are not updated, i think PM should use alternatives and get rid of the not updated extentions. That means, if Weakref is not updated and maintained anymore, PM should not use that anymore and use other methods/extentions that are up-to-date.

**Comment by KubixQ** [comment]
So how to repair my issue?
Where I find the "extentions"?

**Comment by keithkfng** [comment]
Well I'd suggest you to follow the installation method provided on the ImagicalMine website.

**Comment by KubixQ** [comment]
I'm installed ImagicalMine, I recive message "ImagicalMine installation finished. Run ./start.sh to start ImagicalMine." and displays error (published in issue)..
