### ISSUE TITLE
Experience ball AI 经验球AI

### ISSUE THREAD

**Issue by ibookcc** [ImagicalCorp/ImagicalMine#521]
Experience ball AI can not be absorbed by the player will always be around the player
If you walk fast, you will stay where you are
经验球的AI无法被玩家吸收会一直围绕在玩家身上
如果走的快的话就会停留在原地

**Comment by thebigsmileXD** [comment]
They do get absorbed, i tried it. But some are somehow not absorbed. But this is a duplicate.
