### ISSUE TITLE
Permission nodes for new commands

### ISSUE THREAD

**Issue by InfornoFire** [ImagicalCorp/ImagicalMine#523]
Well, where would they be located because /xp 9999999999 freezes the server with incredible lag, might be a ram issue, but what are the nodes anyways.

**Comment by robske110** [comment]
Players shouldnt be able to use /xp (only ops)

**Comment by thebigsmileXD** [comment]
There are permissions. Check in the commands. But how to set them to op only?

**Comment by robske110** [comment]
What you have not made it so that players cannot issue /xp???
I will come up with an pull request this evening if it is so!
(The cmd should be in /DefaultCommands/ right?)

**Comment by InfornoFire** [comment]
robske110 i want some ops to NOT be able to do it, due to lack of responsibilities at my moderators, admins, and headadmins wana play around. I use pure perms. I do remember something like - pocketmine.command. anything but just to be sure i want to know what they are.

**Comment by robske110** [comment]
https://github.com/ImagicalCorp/ImagicalMine/tree/master/src/pocketmine/command/defaults
Go to the File for the command!
As example:
https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/pocketmine/command/defaults/ExpCommand.php#L38
So it is '''pocketmine.command.xp'''

**Comment by robske110** [comment]
And this thread/issue you should have opened on forums.imagicalmine.ml/me

**Comment by robske110** [comment]
sorry

**Comment by keithkfng** [comment]
There is no imagicalmine.ml -_-
