### ISSUE TITLE
Map Convert on Import :P

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#524]
Okay, maybe this feature request is a bit too complicated and advanced XD
Basically, single player MCPE saves worlds into the LevelDB format. A lot of people simply just take the world out and drag it into the worlds folder of PocketMine/ImagicalMine, and then think it will load. It won't. So my suggestion is to add a built in-converter. Of course, I already found one - https://github.com/ImagicalCorp/MConverterUltimate - but that one is written in Java... Could it be ported over, or does someone want to willingly rewrite it in PHP? XD

**Comment by HimbeersaftLP** [comment]
Good idea!

**Comment by thebigsmileXD** [comment]
Nope. PocketMine said they have a converter in PocketMine, but they don't. Also, this converter never worked for me

**Comment by keithkfng** [comment]
Cos you don't know how to use it XD
I converted a map for LegoCraft using that

**Comment by dterweij** [comment]
Good.. maybe. I have on a old spare phone our first map. But it is suddenly crashing when we all go in it. It lags a lot too. It is just the old phone that have problems, Thats the reason I went to a linux server version as I have linux and have linux since redhat 1.0.
Tho i still dont understand how this convertions works.
What uses ImagicalMine and what uses MCPE (map from 0.12.x).
So what convertertype I need? Why so much types? Every minor version has a new type map orso?

**Comment by InfornoFire** [comment]
#lel, so if you can convert mcpe to imagicalmine/pocketmine whats left is convert pc to pe and pe to pc. Now who would be able to do that.

**Comment by thebigsmileXD** [comment]
WorldFixer plugin. Just came out. Well, yea.

**Comment by InfornoFire** [comment]
Wheres world fixer

**Comment by thebigsmileXD** [comment]
http://forums.pocketmine.net/plugins/worldfixer.1600/

**Comment by InfornoFire** [comment]
Now thx, now, Why is the rest of pocketmine down and why did all plugins just updated after christmas?

**Comment by thebigsmileXD** [comment]
No idea and offtoppic

**Comment by BlackShadow1** [comment]
PocketMine is not down! Replace https with http. The security connection https with the server is down.

**Comment by InfornoFire** [comment]
ok sheez, so, keithfng, i think no one is gonna do that at this point. Maybe next week or so someone would volunteer.

**Comment by InfornoFire** [comment]
How do you work the java version

**Comment by InfornoFire** [comment]
Im getting fustrated at this, i think you raised another army like you did in the forums, who likes to make a youtube video tutorial on this.

**Comment by InfornoFire** [comment]
lel, unable to access converter.jar

**Comment by InfornoFire** [comment]
Yo, did someone deleted my comments?

**Comment by thebigsmileXD** [comment]
Yo, me.

**Comment by Tolo0** [comment]
This work? For what ur saying maybe.
[pmimporter_v2.0dev1.phar.zip](https://github.com/ImagicalCorp/ImagicalMine/files/81409/pmimporter_v2.0dev1.phar.zip)

**Comment by InfornoFire** [comment]
Exsactly how do you use it

**Comment by InfornoFire** [comment]
Uhh, dev 2.0 doesent work, this work tho
https://github.com/Muirfield/pmimporter/releases/download/1.5upd2/pmimporter.phar
Old version but it works. If a tutorial is necessary here
https://www.youtube.com/watch?v=0DNvcNbe3Xw

**Comment by Tolo0** [comment]
So u can use minecraft main game worlds on server's now?

**Comment by InfornoFire** [comment]
Basically, the non inf world types

**Comment by Tolo0** [comment]
So it would have all the different biomes and the random dessert temples. Witch huts. Villages. Caves?

**Comment by InfornoFire** [comment]
Yea

**Comment by Tolo0** [comment]
Wow that would be amazing.  The default maps generated on server's are so boring. 😝

**Comment by Tolo0** [comment]
That YouTuber tutorial is confusing 😕 I can't do it.

**Comment by thebigsmileXD** [comment]
Don't spam. Use the forums.
