### ISSUE TITLE
Forums

### ISSUE THREAD

**Issue by xHFx** [ImagicalCorp/ImagicalMine#527]
I will pay for hosting for your forums if u nheed it kik me : db_mack or dm me at @DarkRealmsPE <3 Keep up the good work

**Comment by keithkfng** [comment]
Thanks for the offer :)

**Comment by xHFx** [comment]
Ill pay for the server for a year <3

**Comment by xHFx** [comment]
As a donation

**Comment by thebigsmileXD** [comment]
What server?

**Comment by xHFx** [comment]
I was gonna buy a server for a year , to host the forums on :D
