### ISSUE TITLE
Forum: Confirmation e-mail doesn't work

### ISSUE THREAD

**Issue by HimbeersaftLP** [ImagicalCorp/ImagicalMine#528]
I got the mail, but if I klick the link, it still shows up the message: 'Your account is currently awaiting confirmation. Confirmation was sent to **********'.
I tried many times, but it doesn't work. Am I doing something wrong?

**Comment by keithkfng** [comment]
Please send your username and the first three letters of your email to either @ImagicalTeam on Twitter, right here, or keithkfng@imagicalmine.me

**Comment by HimbeersaftLP** [comment]
Ok
