### ISSUE TITLE
Rail, Minecart, Boat in Creativ mode 0.13.1 iOS and Android

### ISSUE THREAD

**Issue by Robertino55** [ImagicalCorp/ImagicalMine#530]
Rail, Minecart, Boat

Thank you very much for your work. We have installed a server for Children, which runs under Window7, 64bit, PHP 5.6.4 (05.06.10 does not work) - Creative mod. Daily updates your latest build. Children are the Android and Apple iOS current version of Minecraft PE 0.13.1 alpha.
I wanted to ask why we do not work the track and trolley, boat.
Rail are going to ask only one direction, the Minecart can not put them on a jet boat does not work well. Sometimes we are not render landscape in larger distances.
I do not know if it's no problem on our server. Can you please advise.

Thank you and have a nice New Year 2016

Robert Kupka and Children Team :-)

**Comment by thebigsmileXD** [comment]
Rails are Work in progress, Minecarts are entities and so not implemented and boats are work in progress.

**Comment by Robertino55** [comment]
thank you very much for your quick response. So we'll have to wait. I feared it Basie server.

once again thank you for your work

**Comment by thebigsmileXD** [comment]
:+1: welcome
