### ISSUE TITLE
Players seem to be able to break signs and noteblocks

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalCorp/ImagicalMine#531]
On my spawn the 3rd time signs (Standing signs) are broken and noteblocks are missing.

**Comment by InfornoFire** [comment]
Lol, HOW MANY SPAWN PROTECTION BUGS ARE THERE.
Make a song of it, parodies are hard to make.

**Comment by thebigsmileXD** [comment]
Fixed via d3ae687

**Comment by BlackShadow1** [comment]
''' class Noteblock extends Solid implements RedstoneConsumer '''
we don't have RedstoneConsumer interface.
