### ISSUE TITLE
Check please.

### ISSUE THREAD

**Issue by EnderKenji** [ImagicalCorp/ImagicalMine#532]
Is now plugins cant register Config.yml?

**Comment by EnderKenji** [comment]
![screenshot_2016-01-03-23-50-15](https://cloud.githubusercontent.com/assets/15629214/12079461/ce3bd882-b274-11e5-8f0c-cf6e99382752.png)
Im using ImagicalMine

**Comment by robske110** [comment]
Please show us the plugin code / say wich plugin you use and if it is working with original pocketmine
### If working with original pocketmine
# VERY_CRITICAL_BUG

**Comment by EnderKenji** [comment]
*Image here*

![screenshot_2016-01-03-23-50-15-1](https://cloud.githubusercontent.com/assets/15629214/12079502/7192a92e-b276-11e5-91bb-7150e0b7fed0.png)

I use a private plugin... called MCPEMMO, created by savion.

**Comment by EnderKenji** [comment]
> class Main extends PluginBase implements Listener
{
 public $players = array();
public function onEnable() {
@mkdir($this->getDataFolder());
		  @mkdir($this->getDataFolder() . "MCPEMMO/Players/");
		//$this->config = $this->getConfig();
		$this->getServer()->getPluginManager()->registerEvents($this,$this);
		$this->getServer()->getLogger()->info("MCPEMMO Enabled");

**Comment by robske110** [comment]
Is it working with ORIGINAL pocketmine?

**Comment by EnderKenji** [comment]
Idk.. i just use imahical mine, plus im on phone , its need a lot of time to change

**Comment by EnderKenji** [comment]
Idk.. i just use imagical mine, plus im on phone , its need a lot of time to change... im sure is **pocketmine.yml** problem...

**Comment by robske110** [comment]
I thought they reverted it to pocketmine.yml in newer versions!

**Comment by thebigsmileXD** [comment]
Plugin fault.

**Comment by BlackShadow1** [comment]
Is the plugin.yml fault. Check the code of the plugin.

**Comment by EnderKenji** [comment]
Okay... btw, can u change bck some code, VIPslot is not working anymore... now im pretty sure is IM problem... i told zombiepower... but he still havent fix yet...
