### ISSUE TITLE
Vanilla server, players can use /op, /kick, /pardon.. every command

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalCorp/ImagicalMine#534]
Even /stop.. noone has perms for that except for the console

**Comment by robske110** [comment]
Ops should be able to issue /stop
What have you done?

**Comment by thebigsmileXD** [comment]
exactly nothing, its a vanila server, and noone has op rights. They op each other..

**Comment by robske110** [comment]
Ah, now understood!
So everyone has every rights since wich build?
I planned to update from build #150 (jenkins) to the newest because it seems stable now, but with that bug...

**Comment by keithkfng** [comment]
DefaultPermissions.php?

**Comment by thebigsmileXD** [comment]
I am not sure.

**Comment by robske110** [comment]
![image](https://cloud.githubusercontent.com/assets/16020100/12088852/1ffcde86-b2df-11e5-8a89-2d8f30b0ac9e.png)
On the test server 5.175.226.133:19133 it works!

**Comment by thebigsmileXD** [comment]
You mean you cant execute or you can

**Comment by robske110** [comment]
Screenshot
I can't (tried /op,/time set,/gm 1)

**Comment by InfornoFire** [comment]
Works for me with pureperm, temp solution.

**Comment by thebigsmileXD** [comment]
Close. Fixed.. They used another Account

**Comment by thebigsmileXD** [comment]
( @ZombiePower thx xD)
