### ISSUE TITLE
Add reason for stop

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/ImagicalMine#537]
1. Add an opportunity to show why the server stopped. And this can be done as follows: /stop [reason]
2. Please add this permission: 
   pocketmine.command.gamemode.other — Allows the user to change the gamemode of other players.
And also change meaning of this (pocketmine.command.gamemode) — Allows the user to change their gamemode

**Comment by keithkfng** [comment]
1. Maybe.
2. Why not just do /gamemode 1 <player>
IMPORTANT: This doesn't match the contributing guidelines because this isn't an issue. Try posting on the forums.

**Comment by alex2534alex** [comment]
@keithkfng , just I want to add donate for my server. And how can I prevent them from changing a foreign gamemode?

**Comment by robske110** [comment]
1. you can already define the reason in pocketmine.yml (To add this on command wouldn't be difficult)
2. No answer to that

**Comment by alex2534alex** [comment]
That's why I want the implementation of point 2

**Comment by dterweij** [comment]
Features should not be build yet. Fix bugs and add more functionality. (Survival mode is not 100% playable or crafting is not crafting everything or make the stonecutter or AI for example).

**Comment by thebigsmileXD** [comment]
Crafting is almost fixed.
And stonecutter is removed, didn't you know this?

**Comment by robske110** [comment]
And MobAI please not! <---DatEnglish
Realy please do NOT implement this...
It will be laggy as hell...

**Comment by HimbeersaftLP** [comment]
You can do 2. with the PlugIn GrabBag and the permission 'gb.cmd.gmc' and 'gb.cmd.gms'. Then the players can do /gmc for Creativa and /gms for survival. They can't change the gamemode of other players. I hope I could help you.

**Comment by thebigsmileXD** [comment]
I see.. Grabbag is messing that up.. Thanksnow i can fix my server

**Comment by InfornoFire** [comment]
LOL, Theres a code in the pocketmine.yml in the settings, shutedown-message "lalaallalaal"

**Comment by InfornoFire** [comment]
Thing is, essentails pe 1.1.3 i think, has gmc gms, etc, it also has things like /tpa etc. so theres your fix, btw you may need to use a permission thing for essentails for it

**Comment by thebigsmileXD** [comment]
I use GitHub 2.0.0. Works like a charm on PC.

**Comment by ZombiePower** [comment]
I like it :)

**Comment by dterweij** [comment]
Hmm Stonecutter removed. Did not know that. Removed forever or being fixed in the feature? As some blocks can't be made in survival. Tho I have at the moment a lot of chests with Stones after I baked the Cobblestones. So smooth stones can not be made yet. Fine then I shall try to bake other things if i figured out how :)

**Comment by thebigsmileXD** [comment]
Stonecutter is removed in Singleplayer because you now should be able to craft everything in the crafting table.
But still.. the recipies are not in the crafting table yet, as long as i know.

**Comment by InfornoFire** [comment]
Mojang had the idea, meh people didnt like it

**Comment by InfornoFire** [comment]
Someone close this because it is not fallowing guidelines, all questions are answered, alternatives are found, if this guy got last words make it quick

**Comment by TBNRFrags2468** [comment]
Hey does this song sound good?

Minecraft Drag Me Down In Progress By TBNRFrags2468

Ive got a diamond for a heart
Im not scared of the farts
You've never seen it look so easy
I got a emerald for a soul
And baby your a Note
But Baby your the only season


If i didnt have you there would be all this left
The shell of a man who could never mine his best
If i didnt have you id never see the fun
You taught me how to KILL someone yeah

**Comment by InfornoFire** [comment]
R.I.P Inforno_Fire 10000001-King Of Flames, will ban you from this web after regenerating.

**Comment by TBNRFrags2468** [comment]
why

**Comment by ZombiePower** [comment]
remove the second line.... sounds cheap...

**Comment by keithkfng** [comment]
@TBNRFrags2468 you will be banned from the organisation and all its repositories if you keep on acting like this.

**Comment by ZombiePower** [comment]
should this be added?

**Comment by keithkfng** [comment]
@ZombiePower first one yes. Second one no.

**Comment by DRedDogPE** [comment]
https://github.com/ImagicalCorp/ImagicalMine/commit/e03965fd753d02975de1c6ad2caa1dd7038f795e should have implimented this

**Comment by thebigsmileXD** [comment]
:+1: but left a line comment
