### ISSUE TITLE
Suggestion: Implement mob AI using plugin EntityManager.

### ISSUE THREAD

**Issue by MasterWolf** [ImagicalCorp/ImagicalMine#539]
Here is link for plugin EntityManager:
https://github.com/milk0417/EntityManager

**Comment by MasterWolf** [comment]
Dumb github... I don't want to close this!

**Comment by thebigsmileXD** [comment]
You want to. It always crashes

**Comment by BlackShadow1** [comment]
Is for API 2.0.0

**Comment by lolcraftboy14** [comment]
How can get the dowload link

**Comment by BlackShadow1** [comment]
https://github.com/milk0417/EntityManager here.  Click download ZIP and download DevTools from http://forums.pocketmine.net/plugins/devtools.515/ so, drop they on the plugins folder and start your server. Write in the console "makeplugin EntityManager".

**Comment by lolcraftboy14** [comment]
Y don haf a pc

**Comment by lolcraftboy14** [comment]
Y door it on android

**Comment by BlackShadow1** [comment]
It's same..

**Comment by lolcraftboy14** [comment]
It font work

**Comment by lolcraftboy14** [comment]
It dontwork

**Comment by thebigsmileXD** [comment]
Get google translate or a teacher

**Comment by lolcraftboy14** [comment]
Lol

**Comment by InfornoFire** [comment]
Delete your bad comments, anywho masters and blah, remove the phar and put src, drop the master in plugins, must stop before you put it in. /makeplugin (name found in plugin.yml) lalalallaa this took forever to find.
