### ISSUE TITLE
Call to a member function setHeldItemSlot() on null   -- Crashes nearly every 10 mins

### ISSUE THREAD

**Issue by DRedDogPE** [ImagicalCorp/ImagicalMine#540]
ImagicalMine Crash Dump Mon Jan 4 14:06:02 UTC 2016

Error: Call to a member function setHeldItemSlot() on null
File: /src/pocketmine/Player
Line: 1801
Type: E_ERROR

Code:
[1792] 
[1793] 		$this->server->getPluginManager()->callEvent($ev = new PlayerLoginEvent($this, "Plugin reason"));
[1794] 		if($ev->isCancelled()){
[1795] 			$this->close($this->getLeaveMessage(), $ev->getKickMessage());
[1796] 
[1797] 			return;
[1798] 		}
[1799] 
[1800] 		if($this->isCreative()){
[1801] 			$this->inventory->setHeldItemSlot(0);
[1802] 		}else{
[1803] 			$this->inventory->setHeldItemSlot($this->inventory->getHotbarSlotIndex(0));
[1804] 		}
[1805] 
[1806] 		$pk = new PlayStatusPacket();
[1807] 		$pk->status = PlayStatusPacket::LOGIN_SUCCESS;
[1808] 		$this->dataPacket($pk);
[1809] 
[1810] 		if($this->spawnPosition === null and isset($this->namedtag->SpawnLevel) and ($level = $this->server->getLevelByName($this->namedtag["SpawnLevel"])) instanceof Level){
[1811] 			$this->spawnPosition = new Position($this->namedtag["SpawnX"], $this->namedtag["SpawnY"], $this->namedtag["SpawnZ"], $level);

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux Zulu.HostingItAll.com 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
Alias 1.2.0 by ZacHack for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
WorldFixer 1 by CreeperFace for API(s) 1.12.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
LiveSigns 1.2.1 by aliuly for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CustomAreas 1 by luca28pet for API(s) 1.12.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
VIPSlots 0.0.4 by iJoshuaHD for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
PaintMyLawn 1.2.0 by shoghicp for API(s) 1.0.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
Jail 2.0.2 by hoyinm14mc for API(s) 1.13.0, 1.13.1
SpawnMgr 1.3.0 by aliuly for API(s) 1.10.0
SignWarp 1.5.1 by aliuly for API(s) 1.10.0, 1.12.0
EliteLogger 1.0.0 by DRedDog for API(s) 1.10.0
PurePerms 1.2.3 by 64FF00 for API(s) 1.12.0
ClientBan 1.0.0 by  for API(s) 1.12.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
WorldProtect 2.2.0 by aliuly for API(s) 1.10.0, 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNW41v2ziy/1d47gKXPFj+juN6kQK5NN1mX7L11en13q4OAS1RtjaSqBWpON5F//ebGVKfSduk
yS5eUKASRc73/GZIyX90dBiLznw4ORi+HE7H01G3I7JMZp35Hx29S+FR5/Tq9P37d+873U4slOJr
HDvhUcS0ZJzFIl6JjAV54ulQJkwJ/VZE/pkW8TKSem+fwWCSRxGsD8IIF/dV5vVT6V0LHYeJ6C8i
vhMZPI/gDmSZDYafup00ytdh0pkHPFKi2/GkL1Co4eHLEdCA2XA1hitXu/o7vQmV80qJ7EZkzqu1
0AtafcETkDfb23deeSDx6Y1I9N534oYdsURsmWF8LmGmfYR0usztmOUsE1zJxO3s739vGE4swzBA
Ms6rUJ3wxBNRJPy9/f0/zKQDO6mUy4ukEnv2BoQ7F/xGXBhj7u13GZGC8f8NvetyuGA5LbU9LOlm
QudZYifM7PAnc/vSzp8NBjVhDW8QF1TS4Y0opAVbt6UNE7SFzHZo0KYzB0ao2WBU8BTgHEto/AhC
d2eA+m+lXvEMn58lvrgFbgW7SV3F2eCgVHFaBEB6XfPpUnOdqwXHCNsraBxWU0EemgFL2tPn8/N3
P5z9dLX8cHJyulzatbNmnPlcc0sdqBUMSsMP7xpepXybLKQKKUeOjo4oJRhPfBYqJUqDJDwWvuZr
59USV5yLGxHt07S97yK8AZHvBjtN+8fuJ1jcJvSL26kouZ3/7O+zMAHtIWhlwAx947/hnUBoCW3M
a28/x+ffwKPLPvPw/7708GfzkLQEkwIC6Ix7kPO/dF4M2N7+nFWQ4bpLq72XcbV5ncfp3krKSPBk
H6h01iIRGY8QL2CWAnlBt2Fv4Isb0HWVh5HfmQ8AYzKppSdh4njW7fA0pGnDSW8A09ahhtvBA/9g
Qcavo3CFa3qHRCFHHeH+PEzyW/ZzHuW9t1LpMFmf6eMo6nkyZuPecNAbjZ1b+HOU9p0wvZk60wl7
MWTLiwW7zAW74BkbzthwMp/M5qMJOzm9ZKPBcMJuZ9Or6QQ4pZsU+Bz0pkANbn8XCSjYGcH9wDy9
kqoQBAboJqKbEmkVWus4CjldWMnNfbdhxRHR5LneyEyhe37m3lvIBjQ8mfAXtCHOggGR8BWAY2eu
sxxQ3BcpiIar4JmSgX5dH4g5Ar5h6roXcHcScYX8I8lRocW75eXHd+/PX8PQVqwgFEFIzCTQ4l9S
i/diyzO/Jn9tsKbEqDdsKHD++t8N4QekIShh/x/Z/8ffrhOwcN1KGqPdwxRb5Jn44WxZ06oYafpl
0PbLdPLmzWDwbG65MvRc17IvLyo1lpfH7y8/LOpKdDZap2re70M6bfIVxnwf15kKq/oFDVD0o8wi
/014K7KarrXBmrpN/0FRA3mzNwgXz6Vtxdd1GzI8wGPH0ZbvFKFaI5eq0brnRhBfo6bnFpswClO2
hP8gS9fPplRKdJUl67qcRCKcd91zUKyu4T3OtPq9FjeXgLZ1oCiHmjE5vBOUCwLxCwBxdil43FAN
sPBbNSv4u25NkkdGZSlZv6QByp5Dt7QM10ld22qsDY3DprY8CvNo92z+M+RcNwL+Cvk/CEfuU5ZH
4ldoKzIJFGu9uGNrQR9aTNGPudIi61fagjlOcqVlfByJTNct0hhuGmXaNMnpjYyWoN+zGaXO2nVb
gnwlBMAo2+22J0AmJN/T16jjP3iCnWpNvWKkmbctZ99XRp5SLizTx9SKYx+8+CZvwE4x9JVqsZG7
MImHk9i76xkqhmO6GD1FrUIW161J9QC1TqCzy875el2PuHKsBTltxc4FtIP+u+DiZHH6XP4pmd+F
zQenYF2ufqVNlWO4+7ybYjT62VIY5R4fzVLx7OmFbL8ZbUqp+nUlQNMLvg69SxGJhcy0adittu0n
TSeP2xXzPqAdPB1oY50+Jv3+dbbA7Wvda+VQXQGQrDdpKhD+KNUm529fP5vjSorQeFZCPK4mhr8S
jY3fL0kUjdqpH+rjTLdbtWL4DtpcrYTmV7ADu3oxmMxaTcHpBU8vpI+J9EwZmoqYpzGRdN0tSiZA
Mp5p285Vcj42mGvC9pcxjyLn5xNncU/dbPDBYKferx4cxUjTWAcPKZjDbzeN5doO7C+FxD1F8lQp
keiQRwpgtVKpMdxG5vF9yKwMBN5tB58S/HUxngujG6rhxgxY6YvdebPNr49+ZeOsNnK9Cb30uWK+
oAc7s0qIh4N2U/WCWL+uEEF2sqPIbgRyNdhskQZtn/9ZQA0CUJarx+D1MozTSHzkWVrTpTbYavfa
/nvDo+swu1ZPjFqgo/RlxhMVUJACzm5rt42wqzQPLHPXVSTwFgR23YbwD7DAjzysV126bXtw9LBG
cVw1is1tnD3B/5IFjNjHwAQV9mQi493x4qyD4aYU7D/sGAzYbZpMxK5mjUoo1/0VlHBdq8pDoh7R
rRb53m4lMi9fCWdz3UdiGPaEmRfr+tFEOdTuTQZ/QsjXTXQ3/GkLH6+zxwX/OrkT+naoVZAesq0t
D82eHP8EJItMauHp+3QFIU2w/wV739IiWPEiIHku1+vGAVV99CtbrNfvhf9arp8N/GqsH3uguBBZ
rFpHimasXbPGf92hIglQu3zywaKhQhvIEDAUNtSNDWQx9mW3PdtGquD3+ApFWd+uUBYt66IfthO1
fdrWvb/neIpalTBF9bGCffPpW43KpxYatDYbxXD7OHXwZ8LVXUSixiM1sjymq/5GTGqo3oiRtyJK
G+B051G7tk+efl7ZqkxfM9aGBPmLwLulvQW/kw3XLeyjoXYdfwD0fW0bVgPW++oefTOhwJedz0Ai
ylVdPRkQicgnfOfHM1AejFSEOL1P7UEQg510KPAF4YtFecdOZBKEa4ZfcLiZm7yA/ov9yBM2YcPx
fPJyPhmxD5cn+FZyis/ty2k08NFHHgSR+IFH/HZXe5bKTB8NXw7HIxyMRYyfAURhHMIovlDF0TXH
cV8cDWkOvwU34ycb6mh8QKSw7XFs5oElj4ajGY5vN2ARIKb0EdEx7nF+y0W2O5JJbSiDvvJIBgEO
4XUvhX4T8tk/+h/6A65S+0cfRQTmBBCVrK4OM6+h/4areZLIPPGEFdHh3iYUNyIGzFeW500oto4f
mtfvoCUti6Dbd4IoXG90IYhRiydhDJ2zXWvGYrkqBgKZAbPSQnbphme+J7PyPr1J7Xw/DILQyyO9
MzYx78i1zBwlNL6TVkc4TO/fjeMSsYU4qgaVEH5tDn4edBREEJ+oRq6lo/iNsNwy4SsNPbrj8QiY
cvKOeYQvpMu87e3iCEONIRwwj6Isz2g6BRsDNdlZjIeBPMLqALHHLjdCCVaIzXgmmN4IBuwUXHDN
PHSGZivBwsSLcl/4cMHuxDjSWqJbZYAE2jQVD0SXSXiSKSTJVpng12wn88zSYmHAwPphEBIHMHwG
gQgoB4R/EtuSXN8XAQfTK7aVyd8142kqeMbQaDHoit8m7fA7Kfwywqi93YiE5ek64z4Q6LkJ5o0h
NncT9uJyAzjnRDAEUkQ8Wed8LRh+JEUWszmmQriPJNAPfyeb4tKTjfCsFs2FIEABISLpbcPrMBV+
yHsyW/fxrn8OoXslg6uz5bur6filM7rCdWDGktCcuYCFa7eDjD5uBNoOvxODHazP8JsxpTOyr8Z2
H8IC7EaPyZokKcgBV0KTS31xE3qCbQDxI3JyDIRN5FcsaX8J42qTa19ilphvqFAYk6CMvsDyexA5
PLlWZCJMUxAFtQbX1kPMivM3o8UxJihDLMHZtsywm5CzfyKcwBSClaIAzRmWAFy43MA6jjGtJAhv
hTKe5ZYQyxXELJQLiBsyBmx6YSaUHB/NWj1wQKAV6FCRPyUAK+jgJ0KY9wyiGwIIRV3tmA07mG7h
rnxaWe3FxxD8IhOIQO77LBPKBCqKCaF5DeJwBaUDgYxBeK4E2gMMKH7LOX0EuIb9ecJueJQLtmdZ
QiXYB+KGH8CsQLh3wPm4WZnDU+T8U07fDkL2Hatd4l1ydQ0Jkl1DvvXw+QfwmfWVURJnbTIJQAsR
BLNVl1HvxSyYQYR3wQwxWE1hHSezQIHEsThPwME4hWgvKcJAH8jFTN4C1GoBJgB1KDOSUjS0qhHn
LMCEps8eIXG7LNR/x68gM1rlC6xBFLSttWwPNAA/sxFahHRwrJZzooTJbeofpfYPkVyBYbFXYGaY
UVlECIvFmq92GgRiSyPKgJiHCt1rgAF02oYkGBmbYX2x5dUOKbJLEEK4QOgL/AYPqQQAKQVH435Q
JqegXUvQQ2Imoc2Az5qENPV6zgYuIQthuAZk4v7/c/Gx1fqC8FhFnyQ81L6U+FtkK+Wx1BSDlMJW
Q/iFNMizEGk4GE2MVNA6hpKqF+aiQoYe4beVrsy3IbACqPExxmiGA/kgTKYR6ssEAAwyFOyG6PA5
sxpzQgMVUUHAXDfTXCrPSAOyr8pkA0fI4R1CCBZEmt67OxnVto0ymDAVHtZNRWZBWY2NzdpSAbCk
SFWl5nhg9VT79wpktR4brdc8W4H/HU9GkekQMcPutSqFE4pi1zC7BnI35klOFbouBTQvOcTCfrfA
hFYw2GgwuBoEBTbEVZT12DtTHukOImIj88gvBQkBQbYJq0THuGUpSQ4KTrFFTojRG8qEO9hIsWJW
l0oFmYwLiMW19rlTR6WaT0EJ67p2KNwTP7V12Kl7mxxKrbH3OUU9AiINomS4j0FtmGmXu5SeGfQr
ykxysGXA1qeihaQKN9tEeTm1cr6WZlnbfVgEsLEyy+oUDBc77Rl0pkIE7S7ErtHaxkLBCB+U1fuL
pNwkERp9UXZ6EBqRqYQrrmFfgY0IfX8MBRDiyaISJaDpY+1TA0YrUdZEgpsXdfgqnmDiZzuNtLvM
GdaCGWsfsXV0IQrAysHUoEpVa833yTnWbII760CzFgatTD32FvY6YN4jaJ0hcE8WH7qwFiRYAf5s
Q19vDGpTfpfkHSI/Z4e2MahaBtPO1ab22LEP+bThUdCHPYHpYnwBcWYZAUsTfzKpJ2RZnWu0an3S
6S0mH7ZBPOqaxEbGH8MEmk5QC8JGUGhjrf+wSBZFp1C1+NgE4SL6BBT7+yR17G29J4PNmljl67lt
Ol6xITYbtrJgV0mPi45SEY5tRNFputYVUEaqPlGxvvnmvcv6a8+YFnDNVzWmxS6vsc0QRROJcoMm
ZoNFU214obrkcA9/W0ARZpc4ZsmcxfBobbcfoBAdkqC4N/iVlgEl3qAPyIkbOF1jD8bUd6WhHCXX
vfjp3eXpnBHqwj8vh71YAnsxIkQHQeg6Es9yLsUrXXzc8JYHmwVAEqsrRRGVJJAEo0Zj5IwGtoQg
lJnKhGGEu2Ect+XIZn1zuMAw0wsvMV1RwRVXosZsbwiJcg+XLhvBg+F9D4T2evuUtErUpaBwuETK
uBOzJylMADAZflj6jSdpz1tthhEIaBeE3RPCgflu1NC2dGpx1MBvCqPjWOZJvQAo27MVQqD4SA23
DIDNeDlnk88v5RmM+kZ2Q6NZddjw5eje1RRdiTDbzpUw1FYiQCSiIxZELHRDSdUcvNSgzyDfkt9A
0cX+LsTdtcDtV7qzJwm2FpUNDQFFQIeSBSxaGAvyiKZJBaHqYIqGnikltAXLcPsOgQFkC1P9KnEn
ZHJD8RhjJSasxAJT6t9yBhq0cMYFv2W8bRfYA3lUH6p4aPqCgvQ998Nc1ZZZP3ArHSWpWWrjDudD
t4KYhCdcTp76EIuVgLAzF9wwofO6qgoawauNXSF7767wFv+2PKQ9OuzHc2H9a9dT2tO4o8BZczb7
JmqpTPPIUrPXWJpahN2EctIB66HQ5hzPoThSaEk0ZQxYrfGExo4OLTzgEdqcmeaucCn+rCVPodkx
HZ8JSAIP02hYWkDlEFdZhkj0AG+3HBmVgzTG4xW+jDJT7Omd2aPPDRjhcQL+tIaZUXtkYoLERK/t
5Etww7h28DyoOVKWk8ZouknDJJBVGGwk+p5Y9mqng9AIkXyJTHYxtvmUIQrsq0pBcd9iH7PqMQmM
P9RifL2G6mMPB8pjF+wR8QdG1/drY+RBcuo+efAXKqbNg7aAY3ExN1idIXjsa4Q5sxf0CDyL28I5
+wUvHUDULu0T/4MUTcoXNbd+Ekk1tmiOzQ6lOLmlrcd9B5u0kyPIVlQeMY5jqJohCGrrWU104koC
0BXDc16MU8LfitucvTk/vpyPvj/sHry8HXbHt+Pu6Pvh9z6UHZOie/jyxcN0OpoN2Bqcqczd5GCf
zn3FrRYJGoRePZ8A6NZ/tYTIUL8H9FuXX4+kHk62N+o3fPM9Nj+1csyvun43v70yL/9WHpTxTfXj
UR5BoPCsGjC/bS3u8iwqb4Iw0vgODUgPzRc/gU7Lp+vqe5Z1XA1vIG7Ny2OY/6tq/BwgXplDz3Iy
dEO7VFfKaI6y+XXVl4tzkgA/vUk9aGOqxTtQnn7dZa/YQQ8lRSswB1/AjAYHgzFcfneG+0RvOput
pquVNx744ykPxtwbTwLfn6wOVwerw9lhIA7gj32Hn9Zs0ETlNz+pVOFt5QC7T7UThqjaexHYTRaM
Ej8RBLOV700PVoOV4MEsmHBfTIPBNJhNZmLqT8Z+4M9GU+KnNrGsbKgozVRT09A4AiZreS0SgNis
HPko+HUmAmMo+pnBjtPbBPzUECf8HqbmbtQ76Hz69F+sx5P9
===END CRASH DUMP===

**Comment by SavionLegendZzz** [comment]
this is when you kick a player when joining or about to join

**Comment by keithkfng** [comment]
@DRedDogPE don't you know how to use code blocks -_-

**Comment by thebigsmileXD** [comment]
I told him how to..

Also, ReasonWL fault.

**Comment by MCPEPIG** [comment]
I don't see ReasonWL in the loaded plugin's section...

**Comment by thebigsmileXD** [comment]
Then VIPSlots or ClientBan.
Anyways, that was already reported once.. and i tried to fix it in PocketMine, got rejected also it fixed up some bugs
