### ISSUE TITLE
LGPL violation?

### ISSUE THREAD

**Issue by BlackShadow1** [ImagicalCorp/ImagicalMine#541]
https://github.com/PocketMine/PocketMine-MP/pull/3850
Look.
http://www.gnu.org/licenses/lgpl-2.1.html#SEC3

**Comment by PocketKiller** [comment]
what?

**Comment by BlackShadow1** [comment]
"These modifications to PocketMine by @ImagicalCorp violate the LGPL (see http://www.gnu.org/licenses/lgpl-2.1.html#SEC3 2-b) on the PocketMine project, so I doubt anyone is going to merge them into this project."

**Comment by thebigsmileXD** [comment]
Because they do not work with our redstone system? no thanks.

**Comment by Falkirks** [comment]
I don't think anyone is going to call you out on it, but you don't display prominent notices in files of changes you made in the derivative work. However you do use git, so that contains the needed information (it just may be in the wrong place technically).

**Comment by ZombiePower** [comment]
@Falkirks "untested garbage"... can you define what it means in your view?

**Comment by Falkirks** [comment]
@ZombiePower I am not referring to this project. I am referring to the bits and pieces that were cut and pasted out of this project. I have the utmost respect for the work you are doing here and your code looks lovely :smile:

**Comment by ZombiePower** [comment]
Just wanted to know :)

Anyways, its good that you are back :D

**Comment by keithkfng** [comment]
I have never seen @Falkirks comment on one of the repositories I manage XD
