### ISSUE TITLE
.exit when reloaded

### ISSUE THREAD

**Issue by TBNRFrags2468** [ImagicalCorp/ImagicalMine#544]
hey i have the timecommander plugin and i set it to reload every 30 min and when it finishes it says.exit
and exits

**Comment by TBNRFrags2468** [comment]
well actually function bin/php/php.exe: Exit 1
it just not good

**Comment by TBNRFrags2468** [comment]
My plugins

ImagicalMine 1.0dev: Alias 1.2.0; DDNSUpdater 1; DevTools 1.10.0; Economy2 0.1.1; Economy2Shop 0.1.2; EssentialsPE 1.1.3; EconomyAPI 0.1.0; FloatingTexter 1.0; ItemCasePE 1.0.8; LeetAuth 1.3.1; LeetTP 0.0.5; MineReset 2.1; PurePerms 1.3.0-PREMIER; RealTime 2.1.1; SignStatus 3.0.0; Slapper 1.2.5; PureChat 1.3.3; AdminFun 1.0.0; KitPro 4.1; TapToDo-LEET.CC 1.0.0; TimeCommander 2; VoteReward 2.1
and none crash

**Comment by InfornoFire** [comment]
Lol, Leet is bad, and also give a pastebin link of the config

**Comment by BlackShadow1** [comment]
Leetshit! I hate leet so much...
