### ISSUE TITLE
spawn eggs

### ISSUE THREAD

**Issue by Tolo0** [ImagicalCorp/ImagicalMine#549]
When given a spawn egg. They never run out. 1 egg gives u infinite supply.  The number doesn't decrease.

**Comment by matcracker** [comment]
I'm working on this in another branch, please don't use spawn eggs.

**Comment by Tolo0** [comment]
Ok. Keep up the good work 😉

**Comment by thebigsmileXD** [comment]
We will, and as long as i know @matcracker , he'll do a great job

**Comment by matcracker** [comment]
Ok, now you can try, everything work except cow and rabbit... I don't know why, the network id it's correct...

**Comment by thebigsmileXD** [comment]
@matcracker i'll check that

**Comment by matcracker** [comment]
Found the problem... I use "use pocketmine\item\Item" and not "use pocketmine\item\Item as drp"

**Comment by thebigsmileXD** [comment]
Can't find th size ANYWHERE

**Comment by matcracker** [comment]
Of rabbit? xD

**Comment by matcracker** [comment]
Fixed, they aren't registred

**Comment by Tolo0** [comment]
Can I use spawn eggs in latest build now ?

**Comment by matcracker** [comment]
Yes, now I'm sure that all entities (only eggs) spawn.
Il 06/gen/2016 15:04, "Tolo" <notifications@github.com> ha scritto:

**Comment by Tolo0** [comment]
Do I use build #344 then?

**Comment by Tolo0** [comment]
I mean #334

**Comment by thebigsmileXD** [comment]
Its a branch

**Comment by Tolo0** [comment]
I have no idea what a branch is. I'm not a pro php coder like u guys 😅

**Comment by thebigsmileXD** [comment]
A branch is like a branch of a tree. You copy all files, modify as long as you want, and then copy the files back to the master branch via pull request

**Comment by Tolo0** [comment]
Ty for the info. I think I'll wait for the next build 😅

**Comment by matcracker** [comment]
Yes wait the next build, I'm preparing for release it! :D

**Comment by Tolo0** [comment]
I know This is off topic. But do u guys no if it's possible.  To generate a world like the one on offline main game world. With all the different biomes?

**Comment by thebigsmileXD** [comment]
Do this.. Will you change something in the Server.php? (Entity registering for example) If so, i'll wait coding my stuff so we don't get conflicts.

**Comment by matcracker** [comment]
Yes wait @thebigsmileXD, I'm registering the last entities

**Comment by thebigsmileXD** [comment]
Okay :D
