### ISSUE TITLE
Bug about player join

### ISSUE THREAD

**Issue by Ad5001** [ImagicalCorp/ImagicalMine#550]
There is a huge issue with player connecting, that 3 days ago and that doesn't stop.
I thought this is a bug by getting some thinks about the player that are not physic (like UUID).
The bug happened when a player trying to connect on my server (that's the same thing for EVERY PLAYER) it crash the server before I can't do anything :( .

Here is the crash dump
Error: Trying to get property of non-object
File: /src/pocketmine/network/protocol/PlayerListPacket
Line: 60
Type: notice

Code:
[51] 
[52] 	}
[53] 
[54] 	public function encode(){
[55] 		$this->reset();
[56] 		$this->putByte($this->type);
[57] 		$this->putInt(count($this->entries));
[58] 		foreach($this->entries as $entry){
[59] 			if($this->type === self::TYPE_ADD){
[60] 				$this->putUUID($entry->uuid);
[61] 				$this->putLong($entry->entityId);
[62] 				$this->putString($entry->name);
[63] 				$this->putString($entry->skinName);
[64] //				$this->putByte($entry->transparency ? 1 : 0);
[65] 				$this->putString($entry->skinData);
[66] 			}else{
[67] 				$this->putUUID($entry->uuid);
[68] 			}
[69] 		}
[70] 	}

Backtrace:
#0 /src/pocketmine/network/RakLibInterface(208): pocketmine\network\protocol\PlayerListPacket->encode(boolean)
#1 /src/pocketmine/Player(939): pocketmine\network\RakLibInterface->putPacket(pocketmine\Player Player(6), pocketmine\network\protocol\PlayerListPacket object, boolean , boolean )
#2 /Slapper_v1.2.8.phar/src/slapper/entities/SlapperHuman(44): pocketmine\Player->dataPacket(pocketmine\network\protocol\PlayerListPacket object)
#3 /src/pocketmine/entity/Entity(1512): slapper\entities\SlapperHuman->spawnTo(pocketmine\Player Player(6))
#4 /src/pocketmine/level/format/generic/BaseFullChunk(154): pocketmine\entity\Entity->spawnToAll(boolean)
#5 /src/pocketmine/level/Level(2616): pocketmine\level\format\generic\BaseFullChunk->initChunk(boolean)
#6 /src/pocketmine/level/Level(2277): pocketmine\level\Level->loadChunk(integer 20, integer 23, boolean 1)
#7 /src/pocketmine/level/Level(2893): pocketmine\level\Level->getChunk(integer 20, integer 23, boolean 1)
#8 /src/pocketmine/Player(731): pocketmine\level\Level->populateChunk(integer 20, integer 23)
#9 /src/pocketmine/Player(1671): pocketmine\Player->sendNextChunk(boolean)
#10 /src/pocketmine/Server(2532): pocketmine\Player->checkNetwork(boolean)
#11 /src/pocketmine/Server(2251): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server(2129): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server(1730): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(pocketmine\CompatibleClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/jar/pocketmine/PocketMine-MP.phar/, string /home/minecraft/multicraft/servers/server73/, string /home/minecraft/multicraft/servers/server73/plugins/)
#15 (1): require_once(string phar:///home/minecraft/multicraft/jar/pocketmine/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6dev #0 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux s5 2.6.32-042stab113.10 #1 SMP Mon Nov 30 10:34:34 MSK 2015 x86_64
PHP Version: 5.6.10
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
HelpOp 1.0.4 by hoyinm for API(s) 1.9.0
BetterGenerators 0.8.1 by Chezzik for API(s) 1.12.1
iControlU 1.3 by Falkirks for API(s) 1.6.0
PerWorldChat 1.2 by EvolSoft for API(s) 1.10.0
ReasonWL 1.1 by CreeperFace for API(s) 1.12.0
WorldGM 8 by Exxarion for API(s) 1.12.0
MSpawns 1.5 by EvolSoft for API(s) 1.11.0
SkyBlock 1.5.6 by  for API(s) 1.12.0
SimpleBroadcast 1 by Dutok for API(s) 1.0.0
AdvertisingKick 1.0.0 by  for API(s) 1.0.0
ArtificialIntelligent 0.1 by onebone for API(s) 1.12.0
AntiTower 1 by xpyctum for API(s) 1.0.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
Slapper 1.2.8 by jojoe77777 for API(s) 1.12.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
iProtector 3.1a by LDX for API(s) 1.9.0
TNTRun 1.0.0 by ItalianDevs4PM, Flavius12, fycarman, luca28pet, XEmAX32, xionbig for API(s) 1.12.0
WorldPlayerLimiter 0.4 B2 by EvolSoft for API(s) 1.4.0
EssentialsPE 1.1.3 by LegendsOfMCPE Team for API(s) 1.12.0
EmptyWorld 1.0.0 by aliuly for API(s) 1.12.0
PureGIS 1.0.0 by 64FF00 for API(s) 1.12.0
ItemCasePE 1.0.8 by aliuly for API(s) 1.10.0, 1.13.0
mcg76_CTF 1.5.2 by minecraftgenius76, MCG76 for API(s) 1.8.0
EconomyPotionDispenser 0.0.1 alpha by Khinenw for API(s) 1.12.0
FloatingTexter 1.1 by Heromine/Jon, Flavius12 for API(s) 1.12.0
DisguiseMe 1.1 by Falkirks for API(s) 1.6.0
Unlimited 1.0.0 by Primus for API(s) 1.12.0, 1.13.0
AlwaysSpawn 2.2.2 by Philip Shilling for API(s) 1.12.0
ItemCMD 1 by TonyDroidd for API(s) 1.12.0
SimpleAuthHelper 2.0.4 by aliuly for API(s) 1.12.0
AdminJoin 1.3.1 by ZacHack for API(s) 1.12.0
PowerMute 1.0.0 by Falkirks for API(s) 1.7.0
PopupAlerts 1.3 by EvolSoft for API(s) 1.12.0
TapToDo 2.2.1 by Falk for API(s) 1.0.0
BanClient 1.0.1 by luca28pet for API(s) 1.12.0
GodMode 2.3 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
BetterVIPSlots 2.1 by ItzBulkDev\iJoshuaHD\Ad5001 for API(s) 1.12.0
LightningJoin 0.4 by Jelly9912 for API(s) 1.13.0
SpleefPE 1.0.0 by thebigsmileXD for API(s) 1.0.0
EconomyShop 2.0.7 by onebone for API(s) 1.12.0
FactionsPro 1.3.2 by Tethered_ for API(s) 1.12.0
PurePerms 1.2.2 by 64FF00 for API(s) 1.12.0
VoteReward 2.1 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0
ServerChannels 1.2 by EvolSoft for API(s) 1.11.0
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
BuyCraft 1.2.1 by Falkirks for API(s) 1.0.0
MultiInventory 1 by luca28pet for API(s) 1.12.0
2BitCmds 1.0.0 by 2BitRealms Dev Team, DevBrad, Lilcrispy2o9, 64FF00 for API(s) 1.12.0
ChestLocker 1.2 by EvolSoft for API(s) 1.8.0
REChatFilter 1.0.0 by MinecrafterJPN for API(s) 1.3.1
ServerMail 0.0.2 by tschrock (tschrock123@gmail.com) for API(s) 1.0.0
BlockEffects 1.0.5 by GmWM for API(s) 1.12.0
UUIDBanning 1.0 by Savion for API(s) 1.12.0
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
Portal 3.0.1 by ljyloo for API(s) 1.0.0
CrateKeys 1.0 by Savion for API(s) 1.12.0
ManyWorlds 2.0.3 by aliuly for API(s) 1.10.0
WalkingParticles 2.0.0 beta by CyberCube-HK Team & hoyinm14mc for API(s) 1.13.0, 2.0.0
EconomyLand 2.0.9 by onebone for API(s) 1.12.0
GrabBag 2.4.1 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0, 2.0.0
EconomySell 2.0.7 by onebone for API(s) 1.12.0
PureChat 1.3.3 by 64FF00 for API(s) 1.11.0
SimpleWarp 2.1.0 by Falkirks for API(s) 1.12.0
SimplePortals 0.0.3 by Falkirks for API(s) 1.10.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPYty2ziSv4Jypm6dK+sty7amnLvEj8QZO9HFzmZul1suiIQkxiTBIUjbytT8+3U3QBKkLFuy
tVt7VZOZjMQm0C80uhsNCPP7VuqHYmvY6e922/uDfr+9sxVwlZ4kiUy2hr9vpfMYXm9FMvVdsbWz
FQql+BRBV8ncj6YslWwqUhYnMhZJOmdywiIZNeT4u3BT6DDJguDUD7BHPOPJsNVqzWQoWqEfCTfh
k7QVZgEgp6/fedKKpXsjUnzdGtHXC/jauBg1sXtLJa7dIhLpnUxuWkA+la4MWqOAz0Vy7qt0xLEV
9IqRC83B2t2hawANt4YDUEyacNDB8O9br9psGaYv/ObcH59FqUgm0HobtPp6yMqGjmNaOk5O1HHq
VBtvRORKT2yPpQwEj14DG686CzR1t+2D3sEyEjVuGm/izJDYtttrRMzgG7zeWZdhpod7hxmGWfmN
eO+y1mXAY7CQ69tOs9vcLwdTaXhLRKmf+kLlDT9kIY+2+/2aaJpy443HU/6AJKvzSnz1FnRKbMxb
J/Sx3dntdIEBw6Pj5Ew6js1l442K+V10JR9VKhHsLxAMxK0IWhOZhDxtTUUkEt9tveNKnMLEOZpl
0Q1wUdeC5tJxNJsF/bdBUDGZ3SXUzvG/291BZ1DDS68dR3PjOIYdx6nw03jjR36qWbOpDR6n1t3b
e5gavW+8CST3NFIf7HUKquu2d1jxvVeaVIfI7T1Obv+g9yg5cFrrUNtfNvv2ep1H6cQyzgKeiseI
EYWDZRQ6g73OklmgROR9EvcPDEZn0UVdiuQW0HV3e90l6NyZcG8+6SlUxdZZiq27W2dOv2m8Aade
w9JdiqXTPXgEyyiRLsQdmVTR9Zah6+z12kvQqZQnaRXN4pws4852f7CMsetrV0YqTTK36oKOZBjz
1B8H4ggiqToHs4ZBzh2k3TJL/QBcyQX3o3M5nVqtAC3G1k0EzALZI1gUiaTM517veZ3iIJv6kWpp
re6ybTSMRPyW+Ym4lhEEww2KtXTEMOC/3vrHHztbYnM5zMuzB+BH62drOOGBEjtbGOCRu90OoIaW
u134dNI/8GvPgPoEirNx4LtskkVu6suImeTg9e/YZJeaOOlP6cxXjTeJUBASX/+MrwbVVxD7381T
sW0eUSu63d5CO8gYtl2ZwX8NDAJOAnHvte6wbzpAnBDcndUaMa7YT/h9rjk8MK2d1J/YxNnh4SFT
IpgMh1f/Ozq5fnt8TB0G7aKDzdPXr2fH2xpv402W+R7xMug82PhcRtOisY6WZ6ZD98EOl2SaRZeI
h1o5g94qzdWNH30quuCotVqLnbT2TRdIJiMI2wkM5pz9F+uwIWvr7rurUjyGHEh3GRRd/hBgXKTF
vXW0uF8iwMd8yPBhr23s8o8/M+A/M+A/M+A/M+A/M+A/M+A/M+B/9wx4Z4ucFw8wyUQ+IXWESN5p
DjxxCwyOMz/wtoZtSExNpNga9vZ3tnjsU7NOr9mBZlM/hcf2in+gQ8JvAn+MfZp7TQRkmEzB87kf
ZfdM7bJuc9DsdRvtfhdscdxBQm0G0f3yYsQuIL/9JG9Zr8067WGvD/+yi8tfwF2APu/3B9eQXQHH
sxgQ7gKeDlL4AU4AnhFvW7+9liqnCAB6COihyMMVquWDCOLPMX4zPBrATkVh7SbS5Fk6k4nC7Gcm
YdkQoopJWX+HNgdAGZ5FxMHsgRmYFZDjeyIG1rAPvFNykh7bgJDjcsBgcxxNO//EtQNMHHg/+nx5
9e3zl/NjAN2JsfJT5HSWpjGY0N3dXdOdj0XiZmPRmN00XRmikO9ECinPe7KAlNguZFx4ZUvbhsyk
U5X2aCZ+/PBvKuJ2utDqmfK6Gp/jjImRacGIdgSl4JdXb79cfR3ZYkcQgkE6/0hCBiuDr5ZYJcyS
p9PsVWQ55cGNn9yoijCD54+d72qimePY9B8bOSPCSCTfZBJAwOepJUUFXDXDbnVYTm5lcAlsVcel
/XxZbNIrDAVZoDImKIAZxNtMb9D6vgiuZPTt3BKsAFVGp1O1tEQAX8kpLjJq1vZsqRJDty7RY2ND
anh/YXGfQyzm96ujcX/PE4Q/yrdZ+q/EuCHpOCXtVRwCB/emGhREzGBcXGJubHuAHFK1r91V7Kvz
/JEwVF9oWpc383cBxDpLnAJUk6c5qEi0KYvKya1jUZd+GAfiXQItXa7sCV9/Y0+PyngcZ6msOuEX
zPUaVcjpFthYQaq3HvCa+gpSml/8ypDU39QDanvpyLxAqGOe3HzqKbCwGvkFwIriQY+J7/o8wPpB
EPgQquyhe/h9NZrWYqmMxBj+bsy7GXyOwwte/JIXkHsJi6tIDyvrK3knElviArbUTO/juZtm4aYM
taAIsljEV+D/FMz4Cotsk4oIFXDdLGshVs3kdOa78caGK0foODYb1afVPCOk5bNsjNleK0faqmAB
DVz5oYC1WMgjr6KCKtzSQbci/fnxrwujuIMKMJ9d89kzn/3n6wVIOU6FrbWcq65E2U7VQGoJVHO/
Or7f5Xcp9vDP5kY4L5SFK7N/lKlUhm8DcFB2kK6Aq4IMVonULxDCJg3L+SojTxjnw1H7BPJkGc7f
js4sCS2gLR8w3jx42m0uM8cu+dzSLHvmuV+YaefF3lZozoEXx6lIsWpyeeL5KfjmeoaZgxfC5TWs
lfg1LNyvX7X7NSsenVzw+EJ6OJk35HVjEfI4JJSOc4ecCeAMYozJRks+n0xJa87KYrZ1GfIgaPzt
qDEydZMU8v9WCF4MXlboFBnUWxB7IXkiYFVle/XAW5ZH2JXgIbzcuHMvmcnTKcPYeu685LRlYcFF
7yiRqXBTaXs6C2hrAIyebz3qzQ9e6K1Lwiu56ockBTyNi6PRScsSAsPWp6svWWTHKw14PIfcOksh
9+HRsbhV/RGulk4DfutnqoNBfTJ3eQKRBbnMXN7dj2l39teT8O2vPWxwD3jH/nRjxqB5frZqqsK0
jAZy75Fv6ITQP6n7kOrLajbaZ+9WqSK8IJIvsvDC9d6JUrjXAwvn0YkdO2xw1TLA5ddMX0yRz88T
NDY9/Tc1zDYbjqMr3c+ZCcShZrBVEQ01EMbpnPRqy18Cn5gXYEhZMN+YxBodhEBkgELDOgNsycwD
8R1SvUQCQquQ3YgfCAZnn45P/tqyZMYCWpaI92eXdu3MQJ5QyKB/etpub0wh1xqf4xjyxZf1PT/0
y0NhjgMEPUtFeMSVqNi/BayLu//0+Be5U+/lhgDihC5wEot1cvbQne4Nro+uTi2ZSli9kFNzWsWO
Ccwa8PB7mA9fHL2HT1vK/efLRpw4zhT4chw3nUASfHWKQ3MWrVGXn8sszcaCxjZTYMaLfJep8Uji
2Z5jXwE3quLVlzSoevZ2s8N4EM9qUf+XGZCM7tYzdjsxf0RJBjfYe5Uzx7GZXGWlDm1SP5peiftq
PKu9qLn5qqQfRCJpI+yjjHZYGfs3Vo+tMrP6XgUoY5r5SlwISzIL+Eg9fNO7FZ6hilZd4WCFQfoa
BRTP7SBUwp5wuaPEDzO1OBYv9UEx4XWcLGfEcWyeVqlyBXd8rqgybde5LGh1adqt+6LRzA/8mF3C
RwDWsbGwEhNeZdA6DieW6JjLYqKx3PooTlwc1yPHxfHyCt6VjObHifQ9b3PZsMbnOIb4+qVzXATh
xmi1zFN/VS8j9F+eCtlrzBWi4YwYeXbev05StCA9VeSh+UfpV4y5gFVnaa/uQv/G3Q/cvdnYqBeE
tTroMMiKm6NY5r3IUttllrAnnM2DXnPvBTMRCYdAGCNdycNKYsRZvFDYs6G1Efkn1/Usyqsm7Q8v
yq54fCWPpb1GN5C6t+wsjs2milQpj1PpSccpaa8wJu84GKJf3cgpYXXTqrFf1g42NSQF6We7jIKn
VikGyPleehfmhLmRMofYBf/a8Yh/dcnfsLROONCnV/56NroMZLp4rKV4UZGyU6sU/XiXBTfH4hZW
Lx+lmmX8wzHuEe62253NjWyFn3VEPPenszSCqF9z5FW4JSAEuoqAH0UQzA8O6tnvCxItIr1W1IbQ
JCaVJWsBesJ/pzMx9qcq9APx6/HGnIWN1HFyXtYRyayKLmcyXlydEbSefuxtYPN3xcVYfWtCAT/F
3oRhbqVNU/qJiRolsrJnWkLrOUQtHb4SoOlEeNcbm0cWcdwopYfVB41qKhC+Va1OpGH1/cHuv65S
RAxYX19cLdJYQOS/ylR8EXc8sZdqFvARz7iO/3+J3y+5Wcun0DnboxmPIhHYA1p78Yxjcy841lQl
/rK8ijLm02whez99evtDnyLt9EP3kWX2DrmllyX0p7itYXG1SszO5kdY9rKjdQ6qT8HOCsn8C0QY
Z3OqwDmOxcEKIlzg0eyz6BayK5nM7bN01RdLV9WbTx2rlNeZSN13fnoUevYUKkBPmBm2+yJ4ECoG
+VO+lwpf3yUcXcu5H7iJr+J5Vx7Qb+E260FL8o5zbfG8yjGLmVDpOS6p7RKCDV3fb7ygxGwRfulh
2xM8sXvqB9XiaQX8xKhe5IVpkXwcfaqI2Hv+cYkqVsepcbTuQqeKzuyTv88giLS2iugAmgwWIgMB
6/Xy2vimyp0lgJJt59863d5/T0GUAKm/3lgiarDnP6NB3uzva+wv5KiakaAlH51KPZlMhFtdGNng
uiHUDv2+D79dbGy2IjLwsxb56tOKheevZ8ewssV1j116tqA1maoSXfLbJ49lrxPtCd0zlg0f5Xhx
1YDAJ2qW/6ZHn77LcbG80FKsVA9LUh5USmEEqJ5cWay6fJ8HUj46AdfZyNFEsZiHn6tWJh9MwecJ
D30Pg2BLYyNPBGlFKn4R88ppvgL2YmtdR9ajX9Yx1Qse6f31yo8FSmDdVHur7TS/cIM5BAbooMFa
RZRvmDhG0xEejHYDYUu08KouV5vhcbvar6DwR1ZH+COrD79Q2sP+gy3LuTeQatd5dJwHuF7d+5zz
yFt0PwR9xtHLf1bRIgB+Cq9imFtBxvcJH7/jdnTIIVXZ+nXH8ujRiNy5mhXUM0azetZ80bCnwOWY
T/8lm0W5Rqw6lgiCB+pYCN1EHWvBSz23kAUMlYUszd2KdZ/6T+tyUL2E1Xu66vNUfcCqKT1kBmX5
bEk1SP/mzuLwZbUgQlLsnX7jSbywa0rA6kB3VtpJWz97qv/m4jKQd9Zj5bxbqZ+JIe44ihi+A4bz
g7WG+ZV3j3VwVgtKyOH1tUFvFT20V9s5Jl4fMfi6nLHmKRe1ZPFJafG3zRwyEgETPh8IWlc0zc1G
PobBrVej4okdyWjiTxlecOQkTvTqm/DYRx6xAev0hp2DYb/Lvl4d4a+vB/g+lKl3WKzDhmx0wvTK
BV/ezYCVRuCr9BAyZABAei6zyEWHRLcrcHfmi1sRwmgr04TOMzRiffwX9H+o6fAATKQxCXDXodKS
R34I2qjAQjnOAXhgK5SeOGzj00QmQLyAyckEoTNYMLoyKZ7j29j09vzJxHezIJ3r/sUvkxtKpHj0
Rx0imG63AJDwrEe80Ojw9PztFYK0STR+y0QyN7gNKAE/lhPG780YMk9IbrzD/6Q/IHqWyobityJX
IqkiorK6Ad364q7hgZ45KJd4kBHeM9XQYlZUE6H3z9UzA/dJmZR5ToSnUnC2DZcHLt7RgSNg+us7
Hvz4EOcD/GMB0UIPOwe9XQKG/N4MsDrUEK0RnGiH+oAowPBn+UWEas7DAA2RYeBjLtlglhB5MkUG
I8cqVx6QcbKrmVCC5YPBeCIYqIWBBAq+8JS5aHIpZG/Mj9wg88CagcDCJNDYLmUo8KqvdBGr4hOx
wyTqXCFSNk4Ev2FzmSUGG/MnDNTtT3yiAQaVgAVDVCfUn8RdgbDliQkHo1LsTkZ/SRn+PognDMc5
BJFB9cEcRGB4RZOW/m4mIpbFkB54gKCJKLX2NcIhPrBXVzMI742AdhkZZE7TjE8Fw0uTSH1mrJQP
z7DmhpzjBylYdz7Ce060PNWuwEgeX0TUvPNv/Fh4Pm/KZNrCpxZeI3QtJ9dnl5+vB72DRvca+5FK
C1RD5mxNEu5saWLfZmS9eM0aXtfCQGJzuwYMG8YBvB3G069Jt8Qv8ALfREpD7Ilb3xVsBulOQIMe
Emo9w0uylHTQGzXLUk/iFNCXvSFL2lUxN5BKeDlzb3F+MfRadDGHDqLs1ufsf3D6UiOayHlaNWTo
6HXnyxn05WjBSgJfhpYeQG6QsUyBeUJYAAMhOSEBgpYQXDyttfJVA9gbA3M2iRNyHDkukJ+h88K7
6sBWkOXxnBkLow7G0RTvbaW8+uaD6sFZzBn3PJYIpe0S2cVbZoAtriB9QA/NwBrHAnUDwyB+y3hA
1+T5t9D2lgeZYNuGLESH14Re0wQnRzGsASOMV7oM4b2m/ikLx3jFy4S9VfPIveLqhuFFOzDJmrrF
VxgYst5cXGw3SyD3y8BUoL3aYeRSmPHNPh72hAwINKgwfpOCICoiLMwimF3YxGC/JGMCuWAKJvIe
IkkqQBUgFk2EqGAPNZyzdDbBmYyNcMbuMD/9C+gwTaifJzBukYXWerNtkAJGnnW1bkiShpF2SLjy
eY3hKZmbWf0+kGNQNSYLTL9gdJ4R/Vgopnw8T4E1dqlZahMTvsIhz70CyHfnE4ukfobhQ2PKR0SR
liY+mBG4NoEbCIhnAv4kp6lNAsTKyKCnEiSSOHlQf0RpSow2iLkha+fCsFfk01NwTtz7fyAGJmFP
CIEJwwuFgCgbEx/GwRV8GXyKwbTDVEB4JVdIN2et0+72S+5goeFLCm04axUSpourci6LmdkBguCc
PG2D1KaBhah8TppgICH9jmBGgy7RoyxTtVYxpHkBxQn0DbqZxq6xwEwtZ37uxjSdz+h4MG5Sp+Zi
B1SESadBrbFwMbwqUhRyrfWu+xaigG5FrEqRe20js3q9hC2jgV6pgSlPYB0OaZAMAp2H6tn4oKbJ
4JAl04uZXjDfQx5lFM5tbiDhycBOXu/kfmTBUIylaL9MpXHCH5Y22GSfdQSlJ7CWmcwCr2DFB79z
F7GSfW3bLCbuQdRBu11Ky16d0pxZ8K1kRxpHIdwkkWHupHVv06Jhe7TaSINAZkAXzeQB66r1xoTS
xevcVD4K9Esycq0ERj5xMYTyMZ167tC0TiDZUbpRAzMNzJ5KbBpZbgRmYh0MLK6Ppe5cH1oMLJih
6a5VPJqaabhRPVCgg9QcbD3XhLGanCi+snKFJ1HiX3M/pJVEgjEFOuqOeQpLNEyD6J5IhTf0MePl
aPLqVNm81a5tLIr4a5zXK9sh5u/QeSTzFLHvsEbHmgI6zhLpRpqzAw5qd5B7pzK608oCw6qnXagZ
ZN0bgIazJvsAK0dQ+yHk6GDqR6OvO9AXuBiDH7vzvXSmI4LxEAWBBhEYsr0iHSlTFUUqsho32VsP
5uKMB5MWLEF0BuUJsEdDDMhqO5WRPZmtfMDCVsnTTu5x6mIaxoMd7RiQ+Dc/gpwWxLuie3ZBh5hh
fB1Fozw/KVcUmIJhJzpkg0izOIobBlDNC2ntK8bZdFikPG9YB1MdE70wy6UGeYaryCPORJ756uxf
665j562KtWCZmmZgSq2pm6sbr3hQNQbyVXVtjSPy5JbpKzn1Oo8aGwNEFZAxuKDc1Nig6dTQnYYs
hJfTYvUDAlKxBtnHe2GUdnO8QgM8Mq4lU4sFUHK6yBHNbTOsrz59vjoZMvLn8K+bwbIwgmUhoaJ6
Dg6qYdJQL5i0DOBtZSxdWPeANzJSk51R6AN+0K5StK1u24QodIo6AmpDw3oCvjFhr/AW1Re5P8xz
9Uuc4CjsmCthkdzuwKR6gNYO68KLzkMvROo2X5tJroTNizGVK8SOi0JTRmB4qbSmiSmHHl1ajJer
dHQetHLDTE67EP0LGY3fYKrZWCUyGBN7G+I911ZwUSaPzJlBURCnXuKAx8eHIes/1p0nAPW0HBpP
PbKxzkF3CQayvkjoFfFYaIxjgZdtMyrr0JXlM2Fj1uUey33m3vOS30Kox7wTrwb6IXD5GM9N2cNE
uyKtIiczoQ2D3LUWjnCSBdRQKjDnBk5q39UhihaQCVYZwGQAca647xJXcHoGKR6iFYXG42LgKjTx
wBChisshuuD3jNe1FOsbUYVXWkt9hIwpf+GenymrqxkdbjilaZ13N9aJPSBv0n4Nq5CNLPbAZm12
mRsIrolR1bMaa7Ug5TK1lKW5KIzxpnfcpyrEb5nIhBl9g8G4DHrTUDCQQ7b/TIz5fbwao3nC4LeA
HP/SfG6AVrUAugDbIHtTqGOtZFNoLOCdwsVgKXPI8gQ0H3q8ezaLIf0q81JtwuSG8nQnL19CQNa9
DXkksKsBdxzJFmAD5eEYfweRN6M6Kro7XZkY5i4OiykJVzOm4TrCG8PKbd+sRyzHiTOjgUWvOqwI
XjV4PIv9aCJt05lJtBci3rTqopCcFfxGMpqHuGyhuaZgHJTFOK7ITANWNiAB8GJwxqdTiHimQFIU
ojCnxTvcb5ZLpzlDlGoZZ6hJPR2MUSxiAWvSLYb5MCVRwyQLdsZKcBlXimpHWG+lkp8IZIzxcof2
47EQhRfG5ikjZE4TyPkFDIY+fDukZkWIz3AMYZZbiJjZ5rFymwzSZJXqEJs7VoNPj6BukNNQC6rC
k1hLFBX4EPDyUTu55xj/80dMqoCWYWiYc2ZewqTBmsGQ/R2/NiDU7VAR4R85bu15yzTJrmCTYPl6
SC9V850MWoM+VBKnBT5FVEXZDKqCriMGlk3iURHDUCY2zHeGWyLoEkxoLKkOGe6MDLs/7+3sHtx3
dnr3vZ3uz52fPcgQtHfcxr1q+j9OHO632RTmhdJP/V28TBl/ch2hemgL7wgioX39L9qZ/QzBaFps
QMcuNjYP6rfAT0VPX07c0Pcg/9C3Fetd/rELWdes/H908ADmGk9KgP5/ieRPWRIUDxNzABMv/dM7
qZM0Lt5Oyy3xaViCZ+AAinNA31XlFHQ41kXyojEksfM4LR4vR+dEDQ8yxi5kmaWYKUeuPVspsVT+
fakVU0kwG/wdpPdFTMxiF6A/ncFQislkf+y5g91xeyz4ZH/S554YTNqDyX5/Xwy8fs+bePvdAfuJ
7lMKZSmYohmhSt7noHu6pdl8Y7tEFweBNXCDsdvebffgK1HuuYP9/fFgPHZ7ba834JMed3v9ief1
x3vj3fHe/t5E7MIfojya4QiRIKiLVN6ICIJYUlzA+E3wG3AWWlt0e9qc0w4UHqHDBj/8WD916UAk
seib7n/88X8Lan4z
===END CRASH DUMP===

**Comment by robske110** [comment]
SlapperV1.2.8's fault 
BUT SLAPPER 1.2.8 WORKS ON ORIGINAL POCKETMINE SO IT IS AN COMPATIBILITY ISSUE

**Comment by Ad5001** [comment]
Oh! I wasn't exerting that because it was working good before ! I will try uninstall it.

**Comment by Ad5001** [comment]
Yep it works thanks but idk why its slapper (ik its creating fakes players an that can be that) but it were working before O.o

**Comment by robske110** [comment]
I can send you an working version

**Comment by Ad5001** [comment]
Ok thanks because older version were buggy ;D

**Comment by thebigsmileXD** [comment]
The issue is because we fixed the skin bug, they not.

**Comment by robske110** [comment]
They fixed the skin bug as well commit https://github.com/PocketMine/PocketMine-MP/commit/90c3e66e6b87ad8763669850d70c108f364dcaa2

**Comment by thebigsmileXD** [comment]
But not the black ones

**Comment by TBNRFrags2468** [comment]
thebigsmile

**Comment by TBNRFrags2468** [comment]
Minecraft Drag Me Down In Progress By TBNRFrags2468

Ive got a diamond for a heart
Im not scared of the farts
You've never seen it look so easy
I got a emerald for a soul
And baby your a Note
But Baby your the only season


If i didnt have you there would be all this left
The shell of a man who could never mine his best
If i didnt have you id never see the fun
You taught me how to KILL someone yeah


HOWS THAT FOR PEOPLE WHO HATE MOJANG ITS GREAT
