### ISSUE TITLE
New secret feature (fishing)

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalCorp/ImagicalMine#555]
I need help with that. How to make the line to appear and being linked to the player/hook?
Hooks can spawn, but don't despawn when you click again. They just spawn more hooks.
![minecraft_ windows 10 edition beta 06 01 2016 23_15_15](https://cloud.githubusercontent.com/assets/8733998/12156583/03e9f564-b4cc-11e5-84a1-d4ec266bface.png)
Also, i need the splash animation that "swims" to the pole/hook, currently its on the hook only.
And i really neet the looting table. (What loot you get when you catch something)

**Comment by ZombiePower** [comment]
@thebigsmileXD test server ip?

**Comment by thebigsmileXD** [comment]
@ZombiePower why don't you read the readme? ;)

**Comment by ZombiePower** [comment]
thanks xP

**Comment by DRedDogPE** [comment]
http://minecraft.gamepedia.com/Fishing#Junk_and_treasures

**Comment by DRedDogPE** [comment]
Loot from fishing

**Comment by thebigsmileXD** [comment]
Someone makes the calculation?

**Comment by thebigsmileXD** [comment]
@KillerXtream Tell me how this is a bug?
