### ISSUE TITLE
Gamemode creative 

### ISSUE THREAD

**Issue by Tolo0** [ImagicalCorp/ImagicalMine#556]
When in creative mode. If u put diamond block. Potions. Weapons. Any item. in side bar then disconnect from game then back on. U keep all the items on side bar in survival mode. If u have a creative world with gamemode creative.  Then I suggest u close it before players start farming items lol.

**Comment by Tolo0** [comment]
[VidTrim_9125.mp4.zip](https://github.com/ImagicalCorp/ImagicalMine/files/80552/VidTrim_9125.mp4.zip)

**Comment by thebigsmileXD** [comment]
Aaahhh, i see. Your default gamemode is survival? And i bet you use Alwaysspawn.. yea, and.. LIAB / PerWorldInventory?
If you use Alwaysspawn, thats actually a bug of the plugin.

**Comment by Tolo0** [comment]
Out of those 3 plugins I use always spawn. How can I fix this then? I need always spawn.  Or server crashes 😕

**Comment by thebigsmileXD** [comment]
Ask the alwaysspawn dev. its a critical bug in his plugin..

**Comment by Tolo0** [comment]
I tested AlwaysSpawn on my test server and it's not that. These are my plugins. Any advice what could be coursing it?
![screenshot_2016-01-07-13-29-08](https://cloud.githubusercontent.com/assets/13458191/12171570/dc2060fa-b542-11e5-8d73-2f5fcb2893d4.png)

**Comment by ZombiePower** [comment]
What is your test server ip?

**Comment by Tolo0** [comment]
192.95.52.180:19132

**Comment by Tolo0** [comment]
I just tested it again and it could be AlwaysSpawn lol. It seems only certain times stay. Like potions. Spawn eggs

**Comment by Tolo0** [comment]
I just removed always spawn plugin and the items from cmode still stayed so it's not AlwaysSpawn 😣

**Comment by thebigsmileXD** [comment]
@matcracker haven't you done it so that players hotbar get cleared?

**Comment by Tolo0** [comment]
Ok so I've removed all the plugins. The server now has 0 plugins on it. And this bug still happens. But I found a fix. On server.properties. I had Force gamemode set to on. I disabled it and now the bug has gone 😅
![screenshot_2016-01-07-14-41-39](https://cloud.githubusercontent.com/assets/13458191/12173770/9d059daa-b550-11e5-9f39-78e4eea68d89.png)

**Comment by thebigsmileXD** [comment]
Really? Maybe thats the reason it works on my server nowadays..

**Comment by Tolo0** [comment]
U can test it for ur self on this server.
167.114.107.186:19202
Log on as Tolo for OP.

**Comment by thebigsmileXD** [comment]
I tested, i still get my creative stuff

**Comment by Tolo0** [comment]
I left force gamemode on. So u could see the bug.

**Comment by matcracker** [comment]
Only when people change from creative in survival
Il 07/gen/2016 16:07, "Dan" <notifications@github.com> ha scritto:

**Comment by Tolo0** [comment]
Switching game modes is fine. U only keep the items if u log off while in cmode.

**Comment by DRedDogPE** [comment]
Maybe use PureGIS? (I made a custom version for multi world support)

**Comment by Tolo0** [comment]
I tried PureGis but keep getting crash dumps. Could I try ur custom version?

**Comment by DRedDogPE** [comment]
[PureGIS_v1.0.0.zip](https://github.com/ImagicalCorp/ImagicalMine/files/81546/PureGIS_v1.0.0.zip)
Here is the custom version.
