### ISSUE TITLE
What have you done to PlayerListPacket?!

### ISSUE THREAD

**Issue by jojoe77777** [ImagicalCorp/ImagicalMine#559]
PlayerListEntry? This makes Slapper crash. Why did you add this?

**Comment by thebigsmileXD** [comment]
Because its for skins. Read the changelog of slapper and you see -.-"

**Comment by jojoe77777** [comment]
What I mean is, why did you make all the entries have to be PlayerListEntrys, not arrays like PM?

**Comment by keithkfng** [comment]
@kam187 this is your call XD

**Comment by robske110** [comment]
@thebigsmileXD He is the dev of Slapper!

**Comment by thebigsmileXD** [comment]
Uh, i wasn't sure anymore.
