### ISSUE TITLE
ImagicalMine Crash at Death

### ISSUE THREAD

**Issue by BukkitPlaysMC** [ImagicalCorp/ImagicalMine#560]
My Server keeps crashing when a Player dies: 
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 130968 bytes) in phar:///PocketMine-MP.phar/src/pocketmine/nbt/tag/Compound.php on line 85

**Comment by thebigsmileXD** [comment]
You have too less memory.

**Comment by dterweij** [comment]
No, it has a memory leak.
My server crashed too now a lot of times.

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 337904 bytes) in phar:///home/danny/minecraft-pe/PocketMine-MP.phar/src/pocketmine/Server.php on line 1910
[16:17:48] [EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by BukkitPlaysMC** [comment]
I have 5GB, I already gave it 3 GB more because of Crashes. It's definetely ImagicalMine's fault, as @dterweij said.

**Comment by keithkfng** [comment]
It was actually PocketMine's fault, I remember this issue. It happened on my server running on Ubuntu as well. Dunno why it happens

**Comment by robske110** [comment]
I had that memory issue on my old pocketmine server too!
As I began working on 0.12 support i completely made new worlds configured configuration files searched plugins and progra... And suprise no memory leak!
I think its because the worlds or some plugins.
My PC has 24GB of ram so this would not be an prob either!
I have an pretty big world on my server but i can't notice any memory leak! Maybe world corruption?

**Comment by robske110** [comment]
Oh and is there any way to see WHATS in the memory?

**Comment by zzm317** [comment]
have you set the limit in pocketmine.yml?

**Comment by ZombiePower** [comment]
dies? death in anyway or a particular way?

**Comment by BukkitPlaysMC** [comment]
When he gets killed

**Comment by KillerXtream** [comment]
Known bug...

Update the build. #45x builds have this trouble fixed for me.

Thanks!

**Comment by keithkfng** [comment]
I think this was mentioned in the memory leak issue already.
