### ISSUE TITLE
100 call limit

### ISSUE THREAD

**Issue by aodzip** [ImagicalCorp/ImagicalMine#566]
Should I set it to unlimit for redstone
Or divide updates in to small parts

**Comment by zzm317** [comment]
@aodzip 请上qq找你有事

**Comment by intagaming** [comment]
That will be no more errors if you follow this:
"YourServerDirectory\bin\php\php.ini
Open with Notepad++
Detele the line "zend_extension=php_xdebug.dll"
or just change that line to ";zend_extension=php_xdebug.dll" to comment it.
Then no more error."

That will make Redstone  MUCHHHH faster. I swear. And no more errors too.
Have you try this ?

**Comment by aodzip** [comment]
Just try , seems a good way .

**Comment by thebigsmileXD** [comment]
Cool, cool! Thanks

**Comment by robske110** [comment]
But that what @intagaming said will not fix the 100 call limit so you should increase or delete it
That what @intagaming said will reduce general server load by disabling some debug extensios! I am sure that debug level will not work anymore after that!

**Comment by thebigsmileXD** [comment]
Well, i'll try to do it and then let the server crash.
