### ISSUE TITLE
LOAD = 100% all the time.

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#567]
The LOAD is now always 100% (even when no players are online)
Some performance tuning is needed.

![screenshot_6](https://cloud.githubusercontent.com/assets/1059028/12177294/9e229fec-b56b-11e5-8db0-f7beff4368eb.png)

**Comment by keithkfng** [comment]
Another reason why you SHOULDN'T USE WINDOWS TO HOST SERVERS! Do people get the point? Windows was never meant to be used for servers... Just learn UNIX COMMANDS

**Comment by InfornoFire** [comment]
Lol. I use a mac

**Comment by thebigsmileXD** [comment]
Uhm.. Same load on linux for me. But my main server runs on windows.

**Comment by dterweij** [comment]
I use Linux keith :) Still 100% load.

**Comment by dterweij** [comment]
I think I go back a few builds. I dont like the 100% issue. Dont want to fry a CPU Core.

top - 01:52:20 up 56 days, 11:48,  4 users,  load average: 1.07, 1.09, 1.02
Tasks: 533 total,   3 running, 529 sleeping,   0 stopped,   1 zombie
Cpu0  :**100.0%us**,  0.0%sy,  0.0%ni,  0.0%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu1  :  0.3%us,  0.3%sy,  0.0%ni, 99.3%id,  0.0%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu2  :  6.1%us,  1.7%sy,  0.0%ni, 90.8%id,  1.4%wa,  0.0%hi,  0.0%si,  0.0%st
Cpu3  :  3.1%us,  2.0%sy,  0.0%ni, 92.9%id,  1.7%wa,  0.0%hi,  0.3%si,  0.0%st
Mem:   3889920k total,  3834476k used,    55444k free,    59404k buffers
Swap:  4095996k total,  1816180k used,  2279816k free,  1559048k cached

    PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 194774 danny     20   0 1479m 791m 3404 R **100.0** 20.8 354:36.46 ImagicalMine 1.0dev

**Comment by MCPEGamerJPatGitHub** [comment]
That's why ImagicalMine is terrible.

**Comment by MCPEGamerJPatGitHub** [comment]
@keithkfng PocketMine is meant to support Windows so we need to implement low CPU brother

**Comment by keithkfng** [comment]
You star ImagicalMine. And then say it's terrible. Great "support".

**Comment by MCPEGamerJPatGitHub** [comment]
@keithkfng I pretty much star every single repo that I see

**Comment by keithkfng** [comment]
-_-
That's not how stars were meant to be used for...

**Comment by MCPEGamerJPatGitHub** [comment]
@keithkfng I don't care, it's my account and I do what I want to do

**Comment by thebigsmileXD** [comment]
But actually he is right. Use watch instead.

@keithkfng i also use windows, but same bug on linux machines.

**Comment by MCDad** [comment]
Not getting that on my Raspberry Pi 2...

Unloaded server running, no players 31%.  While loading a player CPU load shoots up to 125%.  Steady state with 1 player 55%-ish.

Haven't got to the bottom of whether xdebug is loaded in my version of PHP 5.6.10.  Running Jenkins #388.  Checked using top.

**Comment by MCPEGamerJPatGitHub** [comment]
@MCDad Did you load it on PHP7?

**Comment by dterweij** [comment]
Info: 

[danny@server03 bin]$ pwd
/home/danny/minecraft-pe/bin/php5/bin
[danny@server03 bin]$ ./php -v
PHP 5.6.2 (cli) (built: Oct 17 2014 07:28:17)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
[danny@server03 bin]$ cat /etc/centos-release
CentOS release 6.7 (Final)
[danny@server03 bin]$

No xdebug.

Latest phar (build my own phar from git pull and a modified jenkinsbuild script).

My system: 64bit CentOS 6.7, DELL R300 rackserver (have that one for 4 months and works way better then a regular PC tower as server (he died after 6 years running :-())
The PHP 5.6.2 32bit package is the only one that works. The 64bit and newer packages have GLIBC errors (they compiled it wrong is my guess as they look for libs inside the /lib(64)/ and there are they not).
But still 100% load. Tonight I go find the build that is working fine and stay there for a while until this is fixed. Don't realy want to hurt my CPU :)

Good luck developers to finding the bug.

**Comment by MCDad** [comment]
@MCPEGamerJPatGitHub, not yet.  Haven't found a PHP7 binary compiled for ARM7 and RPi.  Not sure if the ARM7 Android will work.

**Comment by thebigsmileXD** [comment]
YAML is missing

**Comment by zzm317** [comment]
=-=On my PC works well
![image](https://cloud.githubusercontent.com/assets/8464161/12199661/bbe8a6c2-b654-11e5-819f-46bb4d746912.png)

**Comment by thebigsmileXD** [comment]
Really? PocketMine didn't update to PHP7 yet, because YAML extension wanst done..

**Comment by PeratX** [comment]
It is because of weakref extension

**Comment by matcracker** [comment]
Why assigned me? xD

**Comment by keithkfng** [comment]
Will be looked at in performance updates
