### ISSUE TITLE
Items in brewing stand disappear on close

### ISSUE THREAD

**Issue by MCPEPIG** [ImagicalCorp/ImagicalMine#568]
When closing a brewing stand, all items in it disappear.

**Comment by thebigsmileXD** [comment]
Would you read other issues before creating a new one you would know why.

**Comment by MCPEPIG** [comment]
Guess what, dummy, this isn't duplicated. You're just as stupid as before.

**Comment by ZombiePower** [comment]
https://github.com/ImagicalCorp/ImagicalMine/issues/384
