### ISSUE TITLE
error NetherWart.

### ISSUE THREAD

**Issue by Driesboy** [ImagicalCorp/ImagicalMine#571]
Fatal error: Uncaught exception 'ClassNotFoundException' with message 'Class pocketmine\block\Player not found' in /Users/Ronny/Desktop/Lobby 2/src/spl/BaseClassLoader.php:144
Stack trace:
#0 [internal function]: BaseClassLoader->loadClass('pocketmine\\bloc...')
#1 /Users/Ronny/Desktop/Lobby 2/src/pocketmine/block/NetherWart.php(24): spl_autoload_call('pocketmine\\bloc...')
#2 /Users/Ronny/Desktop/Lobby 2/src/spl/BaseClassLoader.php(128): include('/Users/Ronny/De...')
#3 [internal function]: BaseClassLoader->loadClass('pocketmine\\bloc...')
#4 /Users/Ronny/Desktop/Lobby 2/src/pocketmine/block/Block.php(670): spl_autoload_call('pocketmine\\bloc...')
#5 /Users/Ronny/Desktop/Lobby 2/src/pocketmine/Server.php(1668): pocketmine\block\Block::init()
#6 /Users/Ronny/Desktop/Lobby 2/src/pocketmine/PocketMine.php(469): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\MainLogger), '/Users/Ronny/De...', '/Users/Ronny/De...', '/Users/Ronny/De...')
#7 {main}
  thrown in /Users/Ronny/Desktop/Lobby 2/src/spl/BaseClassLoader.php on line 144
logout

**Comment by ZombiePower** [comment]
thanks for notyfying!,

i need to remove the extension of nethercrops line 24
