### ISSUE TITLE
[Dev] Notice this , affect performance

### ISSUE THREAD

**Issue by aodzip** [ImagicalCorp/ImagicalMine#572]
Thanks to @intagaming

after unload zend_extension=php_xdebug

load 22% -> 1%

Who knows xdebug for ? Errlog generate and code trace back? We can add a switch for set Server in Developer mode or Production Mode 

Developer mode : 
enable full log
enable xdebug trace

Production Mode
Disable Log
Disable xdebug

**Comment by ZombiePower** [comment]
seems good

**Comment by aodzip** [comment]
a ext that make php 22 times slow .
omg

**Comment by thebigsmileXD** [comment]
https://en.wikipedia.org/wiki/Xdebug
Its for the debugging when you increase the debug level

**Comment by intagaming** [comment]
I found this on Google after i get the "reached" error. It said that disable that xdebug can remove the error.
I didnt think that it can help the server reduce the lag, seriously, after i try to disable it :D 
Good to see that it helps you :P

**Comment by thebigsmileXD** [comment]
@intagaming It removed alot lag. Combined with disabling the log file it runs atleast 50% faster.

**Comment by keithkfng** [comment]
Wait you guys removed the log file already?!

**Comment by thebigsmileXD** [comment]
I am on it

**Comment by thebigsmileXD** [comment]
Talked alot with my job instructor

**Comment by keithkfng** [comment]
So you did it locally first...

**Comment by thebigsmileXD** [comment]
Not even. I am on it.
Heres another nice method to reduce lag:
Using timecommander to execute /gc every 3 minutes. Never had to restart my server since i do this.

**Comment by keithkfng** [comment]
WTF is the command gc?

**Comment by thebigsmileXD** [comment]
You can enable it in pocketmine.yml, there you can enable /gc and /status
/gc = GarbaceCollection, like useless cycles, unused chunks etc

**Comment by keithkfng** [comment]
Okay - maybe I should get to work with the install script than chat all day... XD

**Comment by dterweij** [comment]
xdebug is very handy. Used it with PHPStorm to debug PHP projects. Yes I coded but not in de mood anymore :) Takes too much personal time last years :) My age is almost 45 so let the younger generation take over hehe

**Comment by thebigsmileXD** [comment]
@dterweij xD

**Comment by aodzip** [comment]
seems 100 call back is the xdebug limit 
so
Should Redstone Work with over 100 call for fast update or still make it every 99 as a update turn?

In Bukkit seems no 100 call back limit

**Comment by PeratX** [comment]
@aodzip You are right. Recurse level is limited by XDebug

**Comment by aodzip** [comment]
I think this is not a good limit for Redstone Calculation
Bukkit doesn't have this limit
I think we can remove this in production server

**Comment by thebigsmileXD** [comment]
Thats true. Was a problem also when many things update (cacti crash, sign crash, sugarcane crash)
The limit is shit.
You can't even do a foreach function more than 100 times

**Comment by aodzip** [comment]
But in someway this ext makes our use tick more lol

**Comment by aodzip** [comment]
Remove xDebug I can safely remove RedstoneTick 
reduce more nouse timer , cpu time ,  memory use

**Comment by aodzip** [comment]
And make a switch of Logger ,
reduce packet send by raklib
Load become less and less

**Comment by aodzip** [comment]
100 player with 0% load
#JustKidding

**Comment by PeratX** [comment]
That is impossible to reduce packet... Every packet send by server is necessary...

**Comment by thebigsmileXD** [comment]
@aodzip I am working on the log file switch. The latest build has it disabled by default, read on https://github.com/ImagicalCorp/ImagicalMine/commit/44d4dc897ebc9270c72412adbc7b5d9bc225ec25 why

**Comment by thebigsmileXD** [comment]
@aodzip Jenkins is stuck again, i still have no perms to stop it

**Comment by robske110** [comment]
Please do not remove the log file! I need it urgent!

**Comment by thebigsmileXD** [comment]
@robske110 why should you use it? and what you think is better: 30% load extra or a dumb log file

**Comment by robske110** [comment]
Because I need to ban griefers by their IP

**Comment by thebigsmileXD** [comment]
@robske110 Tghen use the console like a normal person does. You really open this large file every time just to lookup a name?

**Comment by robske110** [comment]
If the server restarts i will have no way to get the ip via the name!
And some plugins and hosting providers need this file too!
Again please do not remove it due to these reasons

**Comment by thebigsmileXD** [comment]
Latest update is best. Faster logging, its enabled.

**Comment by zzm317** [comment]
@aodzip ACK Packet is needed to check client is online=-=

**Comment by robske110** [comment]
Ok, whats up with the zend extension now?
I would jus comment it out by default and let users decide if they want more lag...

**Comment by ZombiePower** [comment]
offcourse no one wants lag....
