### ISSUE TITLE
Code "Player::$sendMessage" error

### ISSUE THREAD

**Issue by Ad5001** [ImagicalCorp/ImagicalMine#574]
Hi again,
I started code a few days ago with a simple tellraw plugin using "Player::$sendMessage" .
I convert it with pmt.mcpe.me its say there is no problem and when i use the command on my server , it say "Undefined property : pocketmine\Player::$sendMessage". I search on pocketmine's forum and no one got that bug . Then I search on ImagicalMine Code and I found the "Player::$sendMessage" but it don't work. I think it's a bug for that reason.

**Comment by matcracker** [comment]
Use $player->sendMessage ("Message");

**Comment by Ad5001** [comment]
I was already using it but it doesn't work! 
use pocketmine\command\CommandSender;
use pocketmine\command\Command;
use pocketmine\event\Listener;
use pocketmine\Player;
use pocketmine\event\player\PlayerChatEvent;
use pocketmine\plugin\PluginBase;
   class Main extends PluginBase {
          public function onCommand(CommandSender $sender, Command $cmd, $label, array $args){
                 switch($cmd->getName()) { // Command name
                         case "tellraw":
                           if($sender->hasPermission("btell.command.tellraw")){
                                 $sender->sendMessage("§a§l[Tellraw]§r§a Message has been display if you had tipe EXACTLY the player name!");
                                 $this->getServer()->getPlayer("$args[0]")->sendMessage("$args[1]");
                                 $this->getServer()->getPlayer("$sender")->sendMessage("§a§l[Tellraw]§r§a Message has been display if you had tipe EXACTLY the player name!");
                                 $telled->getPlayerExact->sendMessage("$message");
                           }
                           return true;
                           break;
                         default:
                           if($sender->hasPermission("btell.command.tellraw")){
                                 $sender->sendMessage("§4Usage: /tellraw <player> <message>");
                                 $this->getServer()->getPlayer("$sender")->sendMessage("§4Usage: /tellraw <player> <message>");
                           } else {
                                 $this->getServer()->getPlayer("$sender")->sendMessage("§4You don't have the permission to access TellRaw");
                           }
                          
                  }
          }
          public function onDisable() {
                 $this->getLogger()->info("\nTellRaw plugin has been disable!\n");
          }
   }

**Comment by ZombiePower** [comment]
any crashdumps?

**Comment by thebigsmileXD** [comment]
```
$this->getServer()->getPlayer("$args[0]")->sendMessage("$args[1]");
                                 $this->getServer()->getPlayer("$sender")->sendMessage("§a§l[Tellraw]§r§a Message has been display if you had tipe EXACTLY the player name!");
                                 $telled->getPlayerExact->sendMessage("$message");
                           }
```
Many PHP syntax mistakes.
```getPlayer("$sender")``` must be ```getPlayer($sender)"
```telled->getPlayerExact->sendMessage("$message");```
Missing () after getPlayerExact. The line isn't even needed. Also $message is undefined
```$this->getServer()->getPlayer("$sender")->sendMessage("§4Usage: /tel``` to ```$sender->sendMessage("§4Usage: /tel```
Want more info?

**Comment by Ad5001** [comment]
No because it do not crash my server but saying "An unknown error has happened while executing the command" (or something like that (I do not have my iPad with me)) and he says what I said before on the console.

**Comment by Ad5001** [comment]
When I learn PHP , he said that work too but I will try changing it :)

**Comment by ZombiePower** [comment]
getPlayer("args[0]") ??

**Comment by ZombiePower** [comment]
if you want some help, go on the imagicalmine forums :)

**Comment by Ad5001** [comment]
Ok 
(PS : if it's args[0] is's because the command is "/tellraw <player> <message>")

**Comment by MCPEPIG** [comment]
You do not put " around non strings!

**Comment by thebigsmileXD** [comment]
Why do you always post duplicate? Oh right! You don't read!
