### ISSUE TITLE
Crash Dump - Cannot use object of type pocketmine\player\PlayerListEntry as array

### ISSUE THREAD

**Issue by BobbyTowers** [ImagicalCorp/ImagicalMine#576]
ImagicalMine Crash Dump Fri Jan 8 03:31:18 ACT 2016

Error: Cannot use object of type pocketmine\player\PlayerListEntry as array
File: /src/pocketmine/network/protocol/PlayerListPacket
Line: 59
Type: E_ERROR

Code:
[50] 
[51] 	}
[52] 
[53] 	public function encode(){
[54] 		$this->reset();
[55] 		$this->putByte($this->type);
[56] 		$this->putInt(count($this->entries));
[57] 		foreach($this->entries as $entry){
[58] 			if($this->type === self::TYPE_ADD){
[59] 				$this->putUUID($entry[0]);
[60] 				$this->putLong($entry[1]);
[61] 				$this->putString($entry[2]);
[62] 				$this->putString($entry[3]);
[63] 				$this->putString($entry[4]);
[64] 			}else{
[65] 				$this->putUUID($entry[0]);
[66] 			}
[67] 		}
[68] 	}
[69] 

Backtrace:
#0 /src/pocketmine/Server(0): pocketmine\Server->crashDump(boolean)
#1 /src/pocketmine/Server(1862): pocketmine\network\protocol\PlayerListPacket->encode(boolean)
#2 /src/pocketmine/Server(2334): pocketmine\Server::broadcastPacket(boolean)
#3 /src/pocketmine/Server(2307): pocketmine\Server->updatePlayerListData(boolean)
#4 /src/pocketmine/Player(1793): pocketmine\Server->addOnlinePlayer(boolean)
#5 /src/pocketmine/Player(1714): pocketmine\Player->processLogin(boolean)
#6 /src/pocketmine/Player(1703): pocketmine\Player->authenticateCallback(boolean)
#7 /src/pocketmine/Player(1698): pocketmine\Player->tryAuthenticate(boolean)
#8 /src/pocketmine/Player(1973): pocketmine\Player->onPlayerPreLogin(boolean)
#9 /src/pocketmine/network/Network(255): pocketmine\Player->handleDataPacket(boolean)
#10 /src/pocketmine/Player(1896): pocketmine\network\Network->processBatch(boolean)
#11 /src/pocketmine/network/RakLibInterface(145): pocketmine\Player->handleDataPacket(boolean)
#12 /src/raklib/server/ServerHandler(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#13 /src/pocketmine/network/RakLibInterface(84): raklib\server\ServerHandler->handlePacket(boolean)
#14 /src/pocketmine/network/Network(165): pocketmine\network\RakLibInterface->process(boolean)
#15 /src/pocketmine/Server(2544): pocketmine\network\Network->processInterfaces(boolean)
#16 /src/pocketmine/Server(2278): pocketmine\Server->tick(boolean)
#17 /src/pocketmine/Server(2156): pocketmine\Server->tickProcessor(boolean)
#18 /src/pocketmine/Server(1757): pocketmine\Server->start(boolean)
#19 /src/pocketmine/PocketMine(469): pocketmine\Server->__construct(boolean)
#20 (1): (boolean)
#21 (0): {main}(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT SERVERMACHINE 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWmtv28gV/SsDeYHahSiLelsLL+B1nG4KJ3Fjp9t2tTCG5FDimiK5nKFldZH/3nPvDCnKtrZB
2w81gpicx33Nua+hf+uYZK06c380HgxG/mw663ZUWeZlZ/5bx2wLTHWu7q8+ffr4qdPtrJXWcklj
lzLLciMqrUQe/KJCI/JY0HpR5OGDMuskU4tFkcqtKheLG/59nWhzlZlyK6QWsizlFiTjJCV6p7oM
T3dbTzNlNnn5cFqUucnDPD3dkbiRtApbUyzszMdnX7qdIq2WSdaZxzLVqtsJ80iRAuM+SGPl2Mfv
hflCjwM3NOShogrSJBRxlYUmyTOhMtp7fPIbLRnxkoX5xqwS7X1XKq3M8cm3NDXenyoq8/3WqGP3
Soaw6yYv1r3LzHGYV/jfjSmYJFH6xG6Yug1xXioZrp4tIst9Q89bK+HMrV6YJG4zF+fn50KrNJ7P
7/5+c3V/8eaN3XDWbGjL9PnzuzfHlu5P/Z9ZkEn/1ZXXebasV/pupf/qylsIvFs7cGsHX7F26NYO
v2LtyK0dNWu/KECAdJ2Mv1rXyW43vdZnwC+zBjoTMl4HaDOlDIGvnzpHffEcuLeqfFTlcf9kvucJ
dtj7LiylXr2p1sVxkOepktkJCB/5h8j4s8ngGSXnGXAu5xpt97K+QXBhGLd5DA7xGAyHo1elnc+D
MpdRKGu6e/SGh+n1pwe0r4pIGrUT9400co/o6AVRu/jYn54NDxCVUfQxo1jglrbpjQ/T858rbWeA
kTIPEeeuc0SUPWKTw8T6wwPEZGVWwFoSQu9LmaYBDLlHdHqQ6ORsdoAooHvRortHb3aQ3tn0kJB5
Zp9uSvVS6zNxKDZ/sL+PB+PxAcIrmUWpolN+BUB+/6Cos7PJIdQ7ps0xfS8NouQeXf+gxJ/kw3US
IAKrMoYLHyPr/UeSO18q5UOaBKeagejg/wNvLI/P+oc0eCZEzesqC2WhqxQHGu1zG361PjPCtJVq
sbBi1X7i5Kq5vabV6N+etD8Zf7VW7nz2WYwPBo3xaPS1R94weUZ8cpD4YDo7EDzgQfv+6E8PUvHH
k9+hcmOFy/cDkD87GNqn40NhUhtZPjubl154w4/v8Xg8mpwdoHR/H+aZNmUV7tMb9MWxjz37g77g
vPXbWibZl93Uz93OUmWqlCnVVKCrUSkhFfq9fqQesTOokjTqzPuow1xO6syHKCRlkfAyf9TrY9ky
MXjtf+UPNlgk057elClUmaRitfNjkkX5RosPd+L26tNfrz69v7j84d2HKzHp+YKlEdNJH+rUC6fi
+0rDMlqLqyjhSo9MlIRKkCcI/0Qk49kELIpVAQbj3qRHb/9UGRTrDPDat5P3uSYB3n34cIcBftmg
8mxqUAz8BIMVsoSowKl7t87Yg30KVRpUcth3dNO8ics8i5OloGp4US6yo7dlIv4sMzET/eF86M/7
M3FxeScGfX9C8+vcROd3+Qb0xWUpY0ODlodX5KU598/84YAGN6vEKC9Fsj3P45hGqHJHuas8W517
qDIT9ajWSCf6PM+YUiE3mUeHqbgsPndc5ZPbpM8HfaaVpvnGi9NkuWro280yS9YoxvcIrvOgHljC
OmuUKOc+vaHYhTzNmCO0kmUUogyu34vHwu2OkjhOwio1W7vfwtPkpYcK3aA81Oc0nEKt1CPMnCOA
pNFuTCsVtZZQyXz+5urtxefrOxpVmQxS5f1aqXLrWLqhEv5Uy0PPvUJqDeLR+R/5ByapTO5p+ajc
RtKp3OIE1ok591jcUkXa5JnyQpmGFPHJxHY1gazx4952nRJOxHs4pAgZIlXJyxkpAnYTuzjgvb8B
csTdCn2KqA2BRksJ1AoC/DQepBGh7d0CJZIsTKtIRXgQLxBKtG7zteLO7iVNLWPVFTlmgEGQFAEa
lgexzavS0RJJLHCeSZwwBxxlCTilWyL8QW0acqeRiiUOU4tNnv3BCFkUSpaCDLmWVOKk6RbiCyrh
rd4b1D6iKpaljECgt8gI/JbYfJGJo7tVqQB6DEGKVGbLCl2roJKYTeYcRSd4T3PQT/7JRqWtlysV
Oi32N0KAlTGFnp+eqqy3SR6SQkWJ7OXl8pTeTqmgvc/j+3e3H+8nwzNvcE/7YMaG0FwsOipbLjrE
6MeVItsJk0OeLBLQUmjubXBMpcw0VwJ2mq3JkkIOPCnDR4roSxHMZnQaWYOw9aUdS26JMa5XlUEs
hBfaJp6EsWlChGmuVWTFuiCPFhQvIIlwMU08JlL8hbwBS9grPDczh6wVkT+6XWGfJJRq5A3huNij
ko4Q3RdoiF0ACKzdxc07rDSrPCI77SY8iBVAqB35K/a/mg40FhQaBOAKRJCowVY4HC2ojWdvbWZ3
Zjj6MYGh8wyQQuMg0NNb5JGYlMYhjtRVyeFQAG+BInvA6OrXSqZ0HMvkEWsfZVopcexYIjCfgLjl
hyihKAh7OM3lEn0UZonzh2odwNpwpwu9zcI7qR8EFTZwoB7Nf8YhMD5rJWnVqswRrgEJrNZdwXFM
uHgHyHZhhjWspikns1k2KqCxdZVRc4BRpn3LkIE+cK4yf0JsNgomgDoM9awRjaxqxXkXk4fSEvLE
rkjMH2A5ur7BUKQoNTAKn+0Vx9CA7oUGZBHWwXNazpkSeasNiuyrf0rzAIbVeWyEHRYcKykmrdVS
BlsDgcStFaXPzBNNx2s9HTptEhaMjS0oIbmY64Y02yVOABeEKQT8jEnFiBE1R3v8UKZi0C5z6JGT
a5DNwGfJQtogPhf9BYcKjsoGoUZG/+fiU0H3O8JTov2vhEc2K5i/C1WNPI6aFnApypSIMk4a4lmL
5PcHIyvVjSqTnNMR+aImhiEHZCdd428+WCHURIQxXuHBH5T1NA7jOZrjDB4Ku1F0OGRWa04USSlH
ePJ1u2zBCZdowPt2nmzDEXH4SCGEMhwv771cTGrbOBTBhIUKKRFqNgvJam1s9zYKwJKq0Ds1h32n
pz55VSCn9dBqvZRlgPP3UICntnAjD3vVqgwnEsXtEW4PfHcts4pTblsKlCMVsHDSrWPCMzA4NNi4
Gsd1bFjvUNYTH22+4zcgYpVXadQIkiCCbDKxE51wKwqWHApO0BGwjuLoLXvCi9jIWLG7G6XiMl/X
IZb2unmvHZVaZwol3NE9h8Ir+Gnto7o4XFXZg7b2vmbUU0DkQZIszeFn0EbY+rnL7lmiANF2kUc1
ANUyO1pEqj5m5yhnEyfnm9xue358lASoUrLb2hQsF7fsf6AzJyIUsMCu1dphoWZEE032/l1Si8x1
+k3pBmikNhMGdLvDhQjfVyABAk8uKrED2sLUzdpgFKgmJ3K4OWqHr3qGHL/cGqLdFZ7fAjPlPmbr
mVoUhJXxxEaVXa7lzoESXWTDnTtAuxeDTqae+AHNEcx7jloYwL28+dzFXkgQIP5sksisbNRm/27I
e0x+LqauMNiVDJoN01raExcR/Gkl0/gURb6tYiIFnDlGYGnxl2dth2yyc4tWq066eiLnozJIpl3r
2MTYddQ9ccffI2A3yvWfb7KbulLY1exUBNGmDWL9ggr2rPDca7smQz+ngmo5d0XHd8KnYsNlFqoq
ebquKDXHsZWqK82FOwqkkV2dqMWpNtJUAMzpMrSmRVyLdItp3Qnu9Q2qLiJJbmhiOyZe6uBF6vKB
hzCiYYS5LZ7dMhdrTC1dPwGFCOhUp2WAHEDKQUnu0UfkpI7MtNjDmOalNOyjfHRHHz7eXc0FR138
Cys0VxmaKyaUrIuUK1gWz3FuxGuO+GLvtEL0EYgkTldGEackSEKoMYScQd+lEAplNjMRjKjlpXGX
jpzX7w/XMczWwrfkrqRgILVqMTv24SivcOmKASb81yaUCXsn7LRataVgONwRZWqt3L2FoI9qlh+l
fnuS3MTuulsKBNwFUfVE4UCmG7nVlraj08LRXvxmGF2s6fteKwFoV7PVQpD4RI1aBsRmepyL0eGt
ssRoZGV331T3so7wzwav7mZ0Zcr2kYGy1AJFHxcF38lQxKJjaKjam5pW6LOR71Y+IulSfZdQu6yo
/Sq27mrA5aKmoOFAEUtt2KpsFxfG4irlZbkGVD1y0SS0qYRbsJL6cQADZGtT/ZJTJ2R9Q8s1YWXN
sZISTKP/s8Mgg9aH8V4+CfncLu4mWUU7POyfBYP0k4ySSre2uXOQTjp2UrvV4Y7Wo1qhmERXYp79
4LUTEK22kpYJ38ntsqAVfNfY1bL3Xgrv4t9GJtyjox+vlDtft5/dnsc9jcOai9l/RK3IC/s9gmxj
nyk1PSO8yNgnPViPhLYXfx7jSJMlyZRruoWmKxc36rvwQPdkc2GLu/pI6dK5KlDs2IrPApKDhy00
HC1QmdIux5CIjul1I4lRM8hjch0kQL5d4q7obI8+t8GIrhPoy6ywozbHOpBY9LpKvgluhGuPLnj2
R5p0sjdarIoki/MdDFY5nT2z7LXu+1AIsXxZnm3XVOazh2jYVzeCUt/ipsVumgUG1qSQyyWyj7sc
aK5dqEakz9YPr2tj5SFy+jV5yF4WynzEz3cDE3Z2bg+gzDyXnHcVII/mRevC6JLuDPkSS6V5Qdmq
i3doQDd0pi7FUJnEqJQVjI38lFGep0UutdKl/hL+2CIi3AeKVg1RoeDUxia4OuA5anRCdrqmr58Z
ZbPZvGaSNEG6sady9SQp39oXKlhA3wkxr6XhKYCdOuW5+IkePSSZLrfOPxNFGwXrMqR928pK1P2C
bdrq+27uxl67vOXmlrOY5oqB1F6jkEggqEvxLdGZKwvAT4Kux8l1OSXtuM3F2+uLu/ng22l3fPbk
d4dPw+7gW//bCJnYRq1jUyrFf91yPuuLJfCt7dtofMKX2+rJqIwMoulb0iXyUOtrSxCiGlnt/opH
psC7LHcD9g+S3BsBrrUZyWPZzMVJCqzylyPf5083sSma2RXczn6/wkRC5VEz9Yt2n7YGPZ/+4Cks
t4VpZm9vrpnmgD79REHYECnCcifYJxW7Xgzz37yDJVUcz4IonIyDfqBkPItHMlKTuD+JZ6OZmkSj
YRRHs8FEfNOhT0XafmBz5OALZIWopet6q39N+cuUexLjHmnqwQ+ER1+JBv1xf4hHZj8MJ7NZMAmC
cNiPhhMZD2U4HMVRNAqmwTiYzqaxGuOH2Zv8QWWI7c569BEsKexnvEFvRK/2m9yAFcfzE32kqM8k
X9NUvz/0/cEZ5m/efLRG6o3st8KbFR0o7WYr3nKp+rf31w23TRQ9NfTatPFMbUtLMIxsysS0Rn5U
8gEBwx4SmwqF8Y4EWytpVtOLUUP7gdGz8ml2db3bEthL+WZgK/mjDMzBNAp3n+F08skoaDbuo9wg
VDSs1hZzjsY/KOF8vOGEhyVTMg/xf3tFWnG7w/RIhS9f/gWfz8xn
===END CRASH DUMP===

**Comment by thebigsmileXD** [comment]
1st. USE CODE BLOCKS https://guides.github.com/features/mastering-markdown/
2nd. Already fixed.

**Comment by thebigsmileXD** [comment]
3rd duplicated
