### ISSUE TITLE
Can't consume items got via $player->getInventory()->addItem($item);

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalCorp/ImagicalMine#578]
To close the other messy issue.

If a plugin does ```$player->getInventory()->addItem($item);```, you can't consume the item

**Comment by HimbeersaftLP** [comment]
And sometimes it's in big letters, am I right?

**Comment by thebigsmileXD** [comment]
what? no.

**Comment by Driesboy** [comment]
work

**Comment by Driesboy** [comment]
close this

**Comment by thebigsmileXD** [comment]
I talk about something else, idiot.

**Comment by Driesboy** [comment]
Yes but it work with economyshop and thy use it

Dries C
Op 9-jan.-2016 11:51 schreef "Dan" <notifications@github.com>:

**Comment by thebigsmileXD** [comment]
@Driesboy instantly when the items are added?

**Comment by Driesboy** [comment]
Yes if you tap on the sign yes

Dries C
Op 9-jan.-2016 20:27 schreef "Dan" <notifications@github.com>:

**Comment by Jelly9912** [comment]
When I bought steak with economys shop, i can eat this after drop item :V

**Comment by thebigsmileXD** [comment]
Right, after dropping.. Thats the bug.

**Comment by PocketKiller** [comment]
somehow it is fixed

**Comment by keithkfng** [comment]
Some things magically get fixed :)

**Comment by thebigsmileXD** [comment]
Its not. Still can't consume them, jaut tried

**Comment by keithkfng** [comment]
You're using CS not IM -_-

**Comment by thebigsmileXD** [comment]
I tried on IM. Do you think i would say that if i don't really try?!

**Comment by keithkfng** [comment]
You use CS everywhere -_-

**Comment by thebigsmileXD** [comment]
I SAID I TRIED WITH IM SO IF YOU DON'T UNDERSTAND ITS YOUR PROBLEM

**Comment by keithkfng** [comment]
LOL that was a comment not an argument -_-
