### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Driesboy** [ImagicalCorp/ImagicalMine#579]
Fatal error: Declaration of pocketmine\inventory\BaseInventory::addItem() must be compatible with pocketmine\inventory\Inventory::addItem(...$slots) in /Users/Ronny/Desktop/Lobby 2/src/pocketmine/inventory/BaseInventory.php on line 39

**Comment by Driesboy** [comment]
what

**Comment by thebigsmileXD** [comment]
fixed

**Comment by Driesboy** [comment]
no

**Comment by Driesboy** [comment]
pocketmine\inventory\Inventory::addItem(...$slots) in

**Comment by Driesboy** [comment]
work

**Comment by thebigsmileXD** [comment]
No crashes so far?
