### ISSUE TITLE
Flower Pot

### ISSUE THREAD

**Issue by BlackShadow1** [ImagicalCorp/ImagicalMine#580]
When you place a flower (like blue orchid) in a flower pot, the flower return always red flower. I think $item->getDamage() doesn't work for case red flower.

**Comment by thebigsmileXD** [comment]
Known bug. Check the issues, duplicated

Im/Pm cant send the meta via the packets. Same bug like the duplicated fish.

**Comment by aodzip** [comment]
If can't then upload the whole block

**Comment by BlackShadow1** [comment]
Sorry.
