### ISSUE TITLE
Can't craft sticks

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/ImagicalMine#582]
they vanished from crafting menu
Build# 410

**Comment by SalmonGER** [comment]
I don't have this issue.

**Comment by NML32** [comment]
@SalmonGER are you using the latest build?  It started a build or so ago for me.

**Comment by SalmonGER** [comment]
@NML32 Yes i am, but i also edited the CraftingManager.php file. But i didn't added the crafting recipe for sticks.

**Comment by BlackShadow1** [comment]
@zzm317 had you broke the crafting manager?

**Comment by SalmonGER** [comment]
@NML32 It is implemented: https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/pocketmine/inventory/CraftingManager.php#L95

Try making your own .phar with DevTools. (Thats how i made my .phar)

**Comment by ZombiePower** [comment]
fixed

**Comment by zzm317** [comment]
@ZombiePower why do you time to close the issue 
you should go and check the mistakes you write

**Comment by ZombiePower** [comment]
you fixed it -_-
