### ISSUE TITLE
Windows 10 Beta Crafting

### ISSUE THREAD

**Issue by SalmonGER** [ImagicalCorp/ImagicalMine#584]
**There are some crafting recipes that aren't optimal for the windows 10 edition.**

**Example: (Jack o'Lantern/LIT_PUMPKIN CraftingManager.php Line 82-86)**

$this->registerRecipe((new BigShapedRecipe(Item::get(Item::LIT_PUMPKIN, 0, 1),
			**"    ",**
			**" X ",**
			**" Y "**
		))->setIngredient("X", Item::get(Item::PUMPKIN, 0, 1))->setIngredient("Y", Item::get(Item::TORCH, 0, 1)));

**But this version would be better, or am i wrong? (and it works for me):**

$this->registerRecipe((new BigShapedRecipe(Item::get(Item::LIT_PUMPKIN, 0, 1),
			**"X",**
			**"Y"**
		))->setIngredient("X", Item::get(Item::PUMPKIN, 0, 1))->setIngredient("Y", Item::get(Item::TORCH, 0, 1)));

**ImagicalMine right now: (Jack o'Lantern is only craftable in the crafting table)**
![unbenannt2](https://cloud.githubusercontent.com/assets/15953947/12211758/a009d7aa-b663-11e5-8e18-a6111366980c.png)

**"Other" version:**
![unbenannt](https://cloud.githubusercontent.com/assets/15953947/12211757/a0096194-b663-11e5-9f7e-8172530e7595.png)

**Here's what i would do:** https://github.com/SalmonGER/ImagicalMine/commit/d8b98bc3a533327028b9e2b52d93c3effb75d599

**Comment by SalmonGER** [comment]
Sorry if this isn't a issue for you guys, but for me it is. (Since i use the win 10 version)

**Comment by intagaming** [comment]
Hnmm sound perfect.
Im using windows 10 edition too, and have the same issue with u.

**Comment by zzm317** [comment]
Sorry i think LIT_PUMPKIN can be only craft by crafttable

**Comment by zzm317** [comment]
But if you write like that,the things in PE will be a mass

**Comment by SalmonGER** [comment]
For the players on my server everything was fine. Strange.

**Comment by SalmonGER** [comment]
@zzm317 The official PM version is also like this. And LIT_PUMPKIN is in singleplayer per inventory craftable.

**Comment by thebigsmileXD** [comment]
Lit pumpin can be crafted in the player crafting field (2*2) ;) @zzm317
