### ISSUE TITLE
Rail in creative mod

### ISSUE THREAD

**Issue by Robertino55** [ImagicalCorp/ImagicalMine#591]
Hello,

I tried to use the Rail in a creative mod. If I use the server log shows these messages. Ask go only in one direction, and if I try to do is turn and turned away.

![image](https://cloud.githubusercontent.com/assets/16038548/12216321/9932d36c-b6dd-11e5-8e80-edc4b7028ad6.png)

Server Log:

pocketmine\block\RailBlock::place,93  class=
pocketmine\block\RailBlock::setDirection,165  class=
pocketmine\block\RailBlock::setDirection,181  class=
pocketmine\block\RailBlock::setDirection,221  class=
pocketmine\block\RailBlock::place,93  class=
pocketmine\block\RailBlock::setDirection,165  class=
pocketmine\block\RailBlock::setDirection,181  class=
pocketmine\block\RailBlock::setDirection,221  class=
pocketmine\block\RailBlock::place,93  class=
pocketmine\block\RailBlock::setDirection,165  class=
pocketmine\block\RailBlock::setDirection,181  class=
pocketmine\block\RailBlock::setDirection,221  class=
pocketmine\block\RailBlock::place,93  class=
pocketmine\block\RailBlock::setDirection,165  class=
pocketmine\block\RailBlock::setDirection,181  class=
pocketmine\block\RailBlock::setDirection,221  class=
pocketmine\block\RailBlock::place,55  class=
pocketmine\block\RailBlock::setDirection,165  class=
pocketmine\block\RailBlock::setDirection,211  class=
pocketmine\block\RailBlock::setDirection,221  class=

**Comment by thebigsmileXD** [comment]
..you know they are work in progress?
