### ISSUE TITLE
Crash when using #4xx Builds

### ISSUE THREAD

**Issue by KillerXtream** [ImagicalCorp/ImagicalMine#593]
Hey guys!

I'm running ImagicalMine (most recent build) and this is the output

CentOS 7 DebugX (php) (srv.Worker)

Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 130968 bytes) in phar:///var/games/mc/servers/fgioujohs/ImagicalMine.phar/src/pocketmine/level/Position.php on line 1203

---------------------------------------------------------------
I'm running the server in:

CentOS 7 

128GB RAM
20TB Disk
Intel Xeon PR @ 12.1 GHz

----------------------------------------

What can i do?

**Comment by TBNRFrags2468** [comment]
ill check my server
and look

**Comment by TBNRFrags2468** [comment]
im developing a website and i cant read it until i fix it it has so many codes

**Comment by TBNRFrags2468** [comment]
this isnt really a bug its the build







My Server

ModedWarfare.zapto.org port 19132

**Comment by robske110** [comment]
DUPLICATE

**Comment by robske110** [comment]
#592

**Comment by TBNRFrags2468** [comment]
i got a crash dump and its the build

**Comment by robske110** [comment]
@TBNRFrags2468 @KillerXtream  Please move the conversation to #592 as this is an Duplicate!
