### ISSUE TITLE
new crash dump.

### ISSUE THREAD

**Issue by Tolo0** [ImagicalCorp/ImagicalMine#594]
![screenshot_2016-01-09-18-19-32-1](https://cloud.githubusercontent.com/assets/13458191/12217631/8fa0b302-b6fe-11e5-82a6-dd1ca7b92110.png)

**Comment by SalmonGER** [comment]
Are you sure youre using the newest build?
https://github.com/ImagicalCorp/ImagicalMine/commit/920fa3d2cf80289d4e03ebf954d46a29c3733b3e

**Comment by Tolo0** [comment]
Nope lol. I'll update and repost if happens again.

**Comment by ZombiePower** [comment]
that issue was fixed, 3 days ago (common error: Item:FLOWER should have been Item::RED_FLOWER)
