### ISSUE TITLE
pvp glitch 

### ISSUE THREAD

**Issue by Tolo0** [ImagicalCorp/ImagicalMine#596]
When killing a player. Ther items don't drop.  But they lose there items 😕

**Comment by ZombiePower** [comment]
are you using 1 vs 1 plugin?

**Comment by Tolo0** [comment]
Ye lol. That effect it?

**Comment by ZombiePower** [comment]
yes

**Comment by Tolo0** [comment]
Ok ty.

**Comment by robske110** [comment]
The bug has been fixed in 1vs1 already!
