### ISSUE TITLE
Forums have moved

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#597]
The forums have moved over to forums.imagicalmine.net. There's no working redirect from the old site because I'm too sleepy XD

**Comment by PocketKiller** [comment]
:D

**Comment by NML32** [comment]
I don't think the link is working.  It just takes me to a free hosting site.

**Comment by robske110** [comment]
It takes me to hostinger.de too!

**Comment by SalmonGER** [comment]
It worked for me a few hours ago. Now it doesn't.

**Comment by keithkfng** [comment]
Will check.

**Comment by keithkfng** [comment]
LOL you guys keep going on the site - exceeded CPU quota 382 times!

**Comment by keithkfng** [comment]
@aodzip check out my message on Gitter - will host site on me own servers instead :)

**Comment by SalmonGER** [comment]
@keithkfng Can we somehow get to the forums right now?

**Comment by DRedDogPE** [comment]
http://forums.imagicalmine.me/

**Comment by SalmonGER** [comment]
@DRedDogPE Thanks. :D
