### ISSUE TITLE
pocketmine\block\RailBlock::place, message filling up console window

### ISSUE THREAD

**Issue by NML32** [ImagicalCorp/ImagicalMine#598]
pocketmine\block\RailBlock::place,78  class=
pocketmine\block\RailBlock::place,88  class=
pocketmine\block\RailBlock::setDirection,165  class=
pocketmine\block\RailBlock::setDirection,187  class=
pocketmine\block\RailBlock::setDirection,221  class=

**Comment by thebigsmileXD** [comment]
Already fixed
