### ISSUE TITLE
Crafting really got broken now.

### ISSUE THREAD

**Issue by thebigsmileXD** [ImagicalCorp/ImagicalMine#601]
@zzm317 It broke more than before.
![minecraft_ windows 10 edition beta 10 01 2016 21_18_02](https://cloud.githubusercontent.com/assets/8733998/12223811/7d86a59e-b7e1-11e5-8d90-dfc040038e2d.png)
![minecraft_ windows 10 edition beta 10 01 2016 21_18_05](https://cloud.githubusercontent.com/assets/8733998/12223812/7dbd3794-b7e1-11e5-91cc-fd8e5e154cf2.png)
![minecraft_ windows 10 edition beta 10 01 2016 21_18_14](https://cloud.githubusercontent.com/assets/8733998/12223813/7de5355a-b7e1-11e5-9c0d-17e5ef03fe1e.png)
![minecraft_ windows 10 edition beta 10 01 2016 21_18_17](https://cloud.githubusercontent.com/assets/8733998/12223814/7e3708da-b7e1-11e5-9625-77eb7a246367.png)
As i said, the empty lines are wrong

**Comment by zzm317** [comment]
I know
but if you do not wrote like that，the things in android will mass up
win10 is after android and i have never tried that

**Comment by zzm317** [comment]
so you can decide delete or keep the empty lines
PS：if you delete the empty lines，players who play though android will open a issue to report the ingredients are not in their right place。。。
prehaps we should try to solve this problem in a different way such as check their version before send the crafttable to them。。。

**Comment by zzm317** [comment]
and i think you should try delete the empty lines and than retry the crafting

**Comment by MCPEPIG** [comment]
Oh and you can't craft crafting tables or sticks with planks that aren't oak

**Comment by zzm317** [comment]
@MCPEPIG
that has already be fixed i think。。。
i tested the sticks with other wood

**Comment by BlackShadow1** [comment]
0.14 is going to add PC crafting. So you can delete the empty lines after the update.

**Comment by zzm317** [comment]
if that is true,the empty lines can be deleted

**Comment by BlackShadow1** [comment]
https://twitter.com/_tomcc/status/685516382931447808
:D

**Comment by zzm317** [comment]
lazy to join the test group XD

**Comment by robske110** [comment]
Should be fixed now

**Comment by PocketKiller** [comment]
LOL Only on Windows 10 right?
