### ISSUE TITLE
RAM memory consumption incredible

### ISSUE THREAD

**Issue by SMGcraft08** [ImagicalCorp/ImagicalMine#603]
My server uses a lot, can no longer connect, it starts to consume up to 20 GB and then crash. Error Code:
Fatal error: Allowed memory size of 20971520000 bytes exhausted (tried to allocate 130968 bytes) in phar:///home/PocketMineEditionPocket_0.13/PocketMine-MP.phar/src/pocketmine/level/Position.php on line 1203

OS : Ubuntu 15
RAM : 24
Core : 4
Dedicated server :VPS

(Google translation)

**Comment by robske110** [comment]
Duplicate

**Comment by dterweij** [comment]
Don't make a new issue. Look at #592 . And read issues before make a new one :)
