### ISSUE TITLE
It's all about performance.

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#605]
Over the next few days(and possibly weeks), you'll see most bugs put on hold for a while. This is because of more developers coming in and current developers working on improving ImagicalMine's performance. What's the point of server software with all the features of MCPE when it lags so much not even 1 player can join? Got any suggested developers, or want to join in to help us out? Either post your comments below or fork the repo, improve it and make a PR!

**Comment by legoboy0215** [comment]
So... I can't view what was fixed from ClearSky, so summary?

**Comment by keithkfng** [comment]
I don't know either. But I do know that there is a lot less lag.

**Comment by legoboy0215** [comment]
How....

**Comment by keithkfng** [comment]
Ask @aodzip XD

**Comment by robske110** [comment]
I don't like this :( Will stay on 429... Realy you didin't even test how well it goes with this project!

**Comment by keithkfng** [comment]
Excuse me? I've already tested this thanks.

**Comment by legoboy0215** [comment]
:( I want to know what changed :P Basically nothing doe.

**Comment by keithkfng** [comment]
Crashes chrome whenever I go onto the commit page -_- so annoying...

**Comment by legoboy0215** [comment]
How do you know that??? Me too :P

**Comment by thebigsmileXD** [comment]
@aodzip and me fixed up some messed up code and found perfect settings (remove pocketmine.yml)
On my server.. 6 players and me, max 5% load

**Comment by keithkfng** [comment]
See my other message.

**Comment by legoboy0215** [comment]
So... Summary? What could I change in my build?
