### ISSUE TITLE
possible bug

### ISSUE THREAD

**Issue by Tolo0** [ImagicalCorp/ImagicalMine#606]
Not sure if this is related. But sometimes when going invisible. Your name tag is still visible.

**Comment by keithkfng** [comment]
How did you go invisible? Potion?

**Comment by Tolo0** [comment]
No. With plugin EssentialsPE. Doing /v Command.  Never had this problem before. So thought it could be related to pocketmine build.

**Comment by dterweij** [comment]
Not seen here last week. My son does like attack me with snowballs in invisible mode :) I dont see him i just see the snowball floating or other block when holds.
