### ISSUE TITLE
Crash when Join 

### ISSUE THREAD

**Issue by FaanMaario** [ImagicalCorp/ImagicalMine#608]
Hi,

I'm using the latest version of ImagicalMine (dev#431) and when a player try to join, MCPE crash instantly.

here the error on the console:
[WARNING]: RuntimeException: "yaml_parse(): reading error encountered during parsing: invalid trailing UTF-8 octet (line 1, column 1)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 124

Thanks for helping me :)

**Comment by robske110** [comment]
Your pocketmine.yml is corrupt

**Comment by robske110** [comment]
Forget that one of your plugins configs are corrupt

**Comment by FaanMaario** [comment]
How I can know what plugin config is corrupt?

**Comment by robske110** [comment]
Copy the server
Then put all plugins out except one and see if the msg appears! If not go on with another plugin until you found the error!

**Comment by FaanMaario** [comment]
Thanks I'll try that :D

**Comment by FaanMaario** [comment]
Thanks a lot, there was the SimpleAuth config :D
