### ISSUE TITLE
New ImagicalMine. New features. No lag.

### ISSUE THREAD

**Issue by keithkfng** [ImagicalCorp/ImagicalMine#609]
Everything has been reset - but your favourite features remain - redstone, crafting and much more to discover for yourself. We'll be moving old features and porting it to the new ImagicalMine version ASAP. However you like it - there is no lag. It's simply all ready for you to use. Have fun!
Team members - working on auto-disabling xdebug right now.

**Comment by TigerHix** [comment]
Good to know! Please keep up the good work.

Is there a list that has unfinished/unimplemented features documented? I would like to contribute to ImagicalMine in my upcoming holidays, but not sure where to start off.

**Comment by keithkfng** [comment]
Yes... We need to improve a lot more things, now @aodzip and @thebigsmileXD are working on something else now -_-

**Comment by Tolo0** [comment]
Where can I find this new version?

**Comment by thebigsmileXD** [comment]
On something better and not so lagging. We are currently planning to do enchantments.
Then mob-server-client-offset fix
Same time fixing up many bugs with anvils, oven etc
