### ISSUE TITLE
Building Iron Golems and Snow Golems

### ISSUE THREAD

**Issue by kniffo80** [ImagicalCorp/ImagicalMine#610]
Hi guys, 

this is not really an issue, but a feature request. I'm a experienced JAVA programmer and my knowledge regarding PHP is limited. I would try to modify the code on my own, but maybe, someone is here who is capable doing this in no-time ;)

It would be cool, if this is possible. With a local game, it's possible - just tried it.

Here's some stuff on this:
http://minecraft.gamepedia.com/Iron_Golem
http://minecraft.gamepedia.com/Snow_golems

As i already wrote: with latest 0.13 alpha it's possible with Minecraft PE.

Thanks for paying attention.

Greetings
Michael

**Comment by ZombiePower** [comment]
You can already build snow/iron golems

**Comment by kniffo80** [comment]
Hmmm ... just built a Snow Golem in latest release. But had no clue how to build an iron golem. Just tried it as in MCPE local version - doesn't work.

Ah and you can build snow/iron golems locally not only with a pumpkin but also with a pumpkin latern. Anyway, Snow Golem works, Iron Golem not.

Maybe, you can give me a hint, how i should build an iron golem?

**Comment by thebigsmileXD** [comment]
Thats also already made..

**Comment by keithkfng** [comment]
But I thought we reset everything...

**Comment by thebigsmileXD** [comment]
It already was in ClearSky

**Comment by kniffo80** [comment]
Can someone explain how to build an iron golem? I'm using latest ClearSky built from master ...

**Comment by thebigsmileXD** [comment]
Hmm.. Maybe search up in the Wiki?

**Comment by keithkfng** [comment]
Didn't you have to make a T with iron blocks and make a pumpkin the head? Something like that.
And maybe we can move to Java if ImagicalMine fails -_- Get @kniffo80 to write a proxy :)

**Comment by ZombiePower** [comment]
ImagicalMIne fails?

**Comment by kniffo80** [comment]
@keithkfng  yes, you're right. Just form a T from iron blocks. Place a pumpkin in mid-top of the T and voila, there should be an iron golem. But it doesn't work, not with pumpkin and also not with pumpkin latern.

I took a little look at the code (Pumpkin.php) and it SHOULD work.

Anyway - I'm not that familar with the code and deeper knowledge in PHP, so i cannot propose a bugfix. But i'll try locally. Maybe, i get a solution for that.

@keithkfng what do you mean by proxy?

**Comment by keithkfng** [comment]
By proxy I mean a proxy server written in Java by an experienced Java programmer(which is probably you) which can transfer players from one server to another. It's been a very wide spread issue, and I've been finding a person who can do it for ages. Maybe that's you :P

**Comment by keithkfng** [comment]
I think it's time for @ImagcalCorp to move on from server software. The whole point of ImagicalMine was to providea 0.13-compatible phar for servers at the time. So now I am making it move on. And I think I have found the right person to do it XD

**Comment by kniffo80** [comment]
Ah, now i know what you mean. I think, i saw already a Java based proxy project. Maybe, i'll find it again ... 

Anyway - i found a little bug in Pumpkin.php, maybe, you want to fix that. Then, iron golems are possible:

original:
```
$firstBlock = $this->getLevel()->getBlock($block->add(0, -1, 0));
$secondBlock = $this->getLevel()->getBlock($block->add(0, -2, 0));
$thirdBlock = $this->getLevel()->getBlock($block->add(-1, -1, 0));
$fourthBlock = $this->getLevel()->getBlock($block->add(1, -1, 0));
$fifthBlock = $this->getLevel()->getBlock($block->add(0, -1, -1));
$sixthBlock = $this->getLevel()->getBlock($block->add(0, -2, 1));
```

fixed:
```
$firstBlock = $this->getLevel ()->getBlock ( $block->add ( 0, - 1, 0 ) );
$secondBlock = $this->getLevel ()->getBlock ( $block->add ( 0, - 2, 0 ) );
$thirdBlock = $this->getLevel ()->getBlock ( $block->add ( 0, -1, -1 ) );
$fourthBlock = $this->getLevel ()->getBlock ( $block->add ( 0, -1, 1 ) );
$fifthBlock = $this->getLevel ()->getBlock ( $block->add ( 0, -2, - 1 ) );
$sixthBlock = $this->getLevel ()->getBlock ( $block->add ( 0, - 2, 1 ) );
```

**Comment by zzm317** [comment]
@kniffo80
i have not find the difference。。

**Comment by kniffo80** [comment]
The difference are the coordinates ... just take a look at third to sixth block

**Comment by keithkfng** [comment]
@kniffo80 the problem is - a mcpe proxy is different to an ordinary proxy

**Comment by kniffo80** [comment]
@keithkfng do you mean something like this: https://github.com/dragonetmc/dragonproxy ?

**Comment by keithkfng** [comment]
Nope. That only connects to servers. I want it to transfer players to different servers.

**Comment by kniffo80** [comment]
Ah OK. Thanks. But isnt it just moving the players files to the other Server?

**Comment by thebigsmileXD** [comment]
Way offtoppic

**Comment by kniffo80** [comment]
True ;-)

**Comment by keithkfng** [comment]
@thebigsmileXD don't worry. 
@kniffo80 so how can it be done? You can actually have a look at Amoeba-Server but it's not complete for reference.

**Comment by thebigsmileXD** [comment]
@keithkfng Just to remind you: you always complain about offtoppic, then force them to read the guidelines, telling them to use gitter or the forums.

**Comment by keithkfng** [comment]
Not now. I don't care about contributing guidelines anymore. They're all messed up.
