### ISSUE TITLE
Default shutdown msg in pocketmine.yml not working

### ISSUE THREAD

**Issue by robske110** [ImagicalCorp/ImagicalMine#611]
That part of pocketmine.yml isn't working anymore:
```
shutdown-message: "Der Server kommt gleich wieder on!"
```
If i issue /stop it says "Server closed"

**Comment by SalmonGER** [comment]
Du musst /stop Der Server kommt gleich wieder on! schreiben :D. Oder du änderst es in dieser Zeile:
https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/pocketmine/command/defaults/StopCommand.php#L28

**Comment by robske110** [comment]
That worked in some 300 builds! It got broken by this 'Now you can do /stop <reason>' commit...
Und du sprichst auch Deutsch lol, ich hab das gefühl das 50% hier Deutsch sprechen 🇩🇪

**Comment by thebigsmileXD** [comment]
Duplicate

**Comment by robske110** [comment]
Can't find the duplicate!
Could you provide the number?
(I checked before creating this issue and there is no duplicate)

**Comment by thebigsmileXD** [comment]
I am sorry, not duplicated. Was discussed on Gitter. @aodzip fixed it in ClearSky
