### ISSUE TITLE
Workbench problem

### ISSUE THREAD

**Issue by kiyoshi-kurosaki** [ImagicalCorp/ImagicalMine#613]
On workbench, lapis lazuli appears on the right side, but cannot craft annything

Please help

Regards

Kiyo

**Comment by thebigsmileXD** [comment]
Try to put it in another slot when in windows

**Comment by kiyoshi-kurosaki** [comment]
![minecraft pe](https://cloud.githubusercontent.com/assets/10975001/12275184/15d0204e-b96f-11e5-807b-8e5105a8d1cc.png)

Just disappears when i craft something

**Comment by dterweij** [comment]
Confirm. This is now always showing. When pressed a lot of time you can get for free a dozen of stacks. i already filled a Chest with it to see what happens. 
Can't craft other items and items are moving/disappearing in your inventory/bar.

**Comment by MyHwu9508** [comment]
It is possile to play on a Pocketmine Server with MCPE Windows 10 Beta ?!

**Comment by zzm317** [comment]
。。。in android and ios that works well you should know

**Comment by zzm317** [comment]
it is hard to get the balance

**Comment by InfornoFire** [comment]
Beta? Its just mcpe full versions with pc feels

**Comment by thebigsmileXD** [comment]
Start mcpe 10 edition. There directly stands "beta"

**Comment by kiyoshi-kurosaki** [comment]
I fixed the problem myself :D i just write it in :) but good for you to correct :D
