### ISSUE TITLE
Furnace Experience Crash

### ISSUE THREAD

**Issue by SalmonGER** [ImagicalCorp/ImagicalMine#614]
I've just updated ImagicalMine and my (test and normal) server crashs when i smelt iron ore in the furnace. 

**ImagicalMine Crash Dump Tue Jan 12 19:34:48 GMT 2016**

Error: Call to undefined method pocketmine\item\IronIngot::getSmeltingExp()
File: /src/pocketmine/Player
Line: 2989
Type: E_ERROR

Code:
[2980] 						$inv = $ts->getInventory();
[2981] 						if($inv instanceof FurnaceInventory){
[2982] 							if($ts->getSlot() === 2){
[2983] 								switch($inv->getResult()->getId()){
[2984] 									case Item::IRON_INGOT:
[2985] 										$achievements[] = "acquireIron";
[2986] 										break;
[2987] 								}
[2988] 								if($this->getServer()->getConfigString("exp-drop.furnace", true)){
[2989] 									$this->addExperience($inv->getResult()->getSmeltingExp());// smelting experience
[2990] 								}
[2991] 							}
[2992] 						}
[2993] 					}
[2994] 					if($this->currentTransaction->execute()){
[2995] 						foreach($achievements as $a){
[2996] 							$this->awardAchievement($a);
[2997] 						}
[2998] 					}
[2999] 					$this->currentTransaction = null;

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0 #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT SALMON 6.2 build 9200 (Windows 8 Home Premium Edition) i586
PHP version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1

**Comment by thebigsmileXD** [comment]
What have you tried to smelt

**Comment by SalmonGER** [comment]
@thebigsmileXD Iron Ore
http://minecraft.gamepedia.com/Iron_Ore

**Comment by ZombiePower** [comment]
try diamond?

**Comment by thebigsmileXD** [comment]
About to get fixed

**Comment by SalmonGER** [comment]
@ZombiePower Diamond Ore also crashs the server.

**Comment by thebigsmileXD** [comment]
(why should you melt diamond ore lol..)
I tried on ClearSky with Iron, diamonds etc. No crashes, perfect item and exp output

**Comment by thebigsmileXD** [comment]
i see why.. this is old code in IM

**Comment by SalmonGER** [comment]
@thebigsmileXD So can you fix it? I just removed the line but i like this feature.

**Comment by wrewolf** [comment]
https://github.com/ImagicalCorp/ImagicalMine/issues/622

**Comment by wrewolf** [comment]
valid for the smelting of ingots

**Comment by thebigsmileXD** [comment]
@wrewolf That.. is already fixed.

**Comment by wrewolf** [comment]
@thebigsmileXD no, function getSmeltingExp() only in Player.php in Ignot Items php's not implemented
for me, i temporary comment this line, but need implement this method for all smelting  items

**Comment by thebigsmileXD** [comment]
Because the code gets the exp.. no. Won't explain. Is you wanna know, look into the whole code. eg. furnace inventory

**Comment by wrewolf** [comment]
My english bad, but i know how fix error.
Tomorow create pullrequest.
Also issue with Exp 
```
Error: Call to undefined method pocketmine\Player::calcExpLevel()
File: /src/pocketmine/inventory/AnvilInventory
Line: 34
```

**Comment by thebigsmileXD** [comment]
calcExpLevel is in server.php -.-

**Comment by wrewolf** [comment]
https://github.com/ImagicalCorp/ImagicalMine/pull/624

**Comment by thebigsmileXD** [comment]
I give up. You just don't understand what i say right?

**Comment by wrewolf** [comment]
I understand.
I wrote this code returns the Exp and put it in a pull request.

**Comment by BlackShadow1** [comment]
Anvil is too much bugged..
