### ISSUE TITLE
Crash when opening the anvil

### ISSUE THREAD

**Issue by SalmonGER** [ImagicalCorp/ImagicalMine#615]
I opened the anvil and the server just crashed.

**ImagicalMine Crash Dump Tue Jan 12 20:27:32 GMT 2016**

Error: Call to undefined method pocketmine\Player::calcExpLevel()
File: /src/pocketmine/inventory/AnvilInventory
Line: 34
Type: E_ERROR

Code:
[25] 	/*public function sendResult(Player $p){
[26] 		$item = $this->getResult();
[27] 		if($item->equals($this->getItem(0),true,false)) $this->setItem(0,new Item(0));
[28] 		if($item->equals($this->getItem(1),true,false)) $this->setItem(1,new Item(0));
[29] 		$p->getInventory()->addItem($item);
[30] 		$this->setResult(new Item(0));
[31] 	}*/
[32] 
[33] 	public function onClose(Player $who){
[34] 		$who->calcExpLevel();
[35] 		parent::onClose($who);
[36] 		
[37] 		$this->getHolder()->getLevel()->dropItem($this->getHolder()->add(0.5, 0.5, 0.5), $this->getItem(1));
[38] 		$this->getHolder()->getLevel()->dropItem($this->getHolder()->add(0.5, 0.5, 0.5), $this->getItem(0));
[39] 
[40] 		$this->clear(0);
[41] 		$this->clear(1);
[42] 		$this->clear(2);
[43] 	}
[44] }

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0 #0 [Protocol 38; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT SALMON 6.2 build 9200 (Windows 8 Home Premium Edition) i586
PHP version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1

**Comment by Tolo0** [comment]
Lol I was just about to post this issue.

**Comment by ZombiePower** [comment]
there is no calcExpLevel in Player.php

**Comment by zzm317** [comment]
who wrote this file。。。。

**Comment by ZombiePower** [comment]
which file?

**Comment by thebigsmileXD** [comment]
WAIT @ZombiePower
Before you meas up everything again..
Its an missing import

**Comment by Tolo0** [comment]
![screenshot_2016-01-12-22-23-50-1](https://cloud.githubusercontent.com/assets/13458191/12289061/19b6a900-b9d1-11e5-9e82-08780a700341.png)

**Comment by ZombiePower** [comment]
@thebigsmileXD  stop blamng me, for the stuff you did!

**Comment by thebigsmileXD** [comment]
@ZombiePower We see your commits. Messed up fire. Messed up many blocks at all. Messed up buckets. Messed up players. You must be true, most of your commits fail.
And i thought "you'll right go and try to fix it"->(messing it up again..)
I'll fix that.

**Comment by ZombiePower** [comment]
I sincerely apologies due to my common errors.... However, they were mistakes, you do see that I did fix them later. And no... Most of my commit didn't fail...

**Comment by ZombiePower** [comment]
And spacing doesn't fix errors...

**Comment by ZombiePower** [comment]
You should also look at your commits... They have also failed many times.. You should look at yourself first, then talk.

**Comment by thebigsmileXD** [comment]
But muuch less then yours, and i fixed them pretty fast ;)

**Comment by SalmonGER** [comment]
@ZombiePower 

**File: /src/pocketmine/inventory/AnvilInventory**

**Comment by thebigsmileXD** [comment]
Oh.. i never did something incredible with anvils. Just saying

**Comment by Tolo0** [comment]
Guys shouldn't this be a critical bug? My server is crashing even 10 min cos of this.

**Comment by wrewolf** [comment]
Maybe remove this line? Exp level calculated in function addExp...

**Comment by thebigsmileXD** [comment]
Nope. I know the error, ClearSky team works on a fix

**Comment by BlackShadow1** [comment]
Missing function calcExpLevel?

**Comment by thebigsmileXD** [comment]
Fixed via https://github.com/ImagicalCorp/ImagicalMine/commit/d870e51d9fe3cc60eb395974ce8d06e50d108ee4
