### ISSUE TITLE
Weather

### ISSUE THREAD

**Issue by MyHwu9508** [ImagicalCorp/ImagicalMine#619]
The Wheather is bugged out, its always raining, even when i use the command "/wheather clear".
When i use the command it stops for a little while, for like 1 minute, but than its starts raining again.
Currently i'm running the newest version from Jenkins (Build #425)

**Comment by zzm317** [comment]
when i test，my weather works well。。。

**Comment by keithkfng** [comment]
You even spelt weather incorrectly... I don't understand how you would use the command anyway.

**Comment by MyHwu9508** [comment]
It not work everytime it rains all time i can try all it not stops

**Comment by MyHwu9508** [comment]
Without this command it would rain without any brake

**Comment by thebigsmileXD** [comment]
Theres a weather switch in pocketmine.yml. If not, delete it and restart your server

**Comment by MyHwu9508** [comment]
After update all works perfect! Thanks!
