### ISSUE TITLE
Redstone Ore

### ISSUE THREAD

**Issue by MyHwu9508** [ImagicalCorp/ImagicalMine#620]
I must break a redstone ore 5-10times to become the Items. This is only on Redstone ore.

**Comment by ZombiePower** [comment]
its possibly due to lag

**Comment by thebigsmileXD** [comment]
Don't think so. Its like the Brewing Stand bug, and its also diamond, emerald, lapis. Idk the fix anymore. @aodzip found a nice solution

**Comment by MyHwu9508** [comment]
After update and deleting xdebug all perfect! Thanks!

**Comment by thebigsmileXD** [comment]
But! This should not happen with xdebug either
