### ISSUE TITLE
On Build #485 /help permission node is shown

### ISSUE THREAD

**Issue by MyHwu9508** [ImagicalCorp/ImagicalMine#621]
At help command in console it is a bug with /xp there is shown the permission node. 
sry for my bad english :(

**Comment by thebigsmileXD** [comment]
At imagicalmine in issues theres a duplicate :P

**Comment by thebigsmileXD** [comment]
Well, actually, the language files are kind of messed up

**Comment by MyHwu9508** [comment]
Ok
