### ISSUE TITLE
Build 458 WONT LOAD

### ISSUE THREAD

**Issue by TBNRFrags2468** [ImagicalCorp/ImagicalMine#625]
![crash](https://cloud.githubusercontent.com/assets/16389267/12311038/6cdc8842-ba22-11e5-8618-03e872cdfe3c.png)

**Comment by TBNRFrags2468** [comment]
Please Fix dis

**Comment by thebigsmileXD** [comment]
May you be so kind and read?
Theres a red line.

**Comment by thebigsmileXD** [comment]
Red lines with [CRITICAL] aren't just there for fun, ya know?

This whole "remove or it wont start" is shit. I need xdebug to debug my plugins. Else i only get one line. I guess the warning is ok, but not starting is.. Mean!

**Comment by TBNRFrags2468** [comment]
I dont get it

**Comment by TBNRFrags2468** [comment]
im not a genius

**Comment by MCPEPIG** [comment]
You can go on pocketmine.yml then go to debug then set allow-xdebug to true

**Comment by TBNRFrags2468** [comment]
thx

**Comment by TBNRFrags2468** [comment]
OMG TBNRFRAGS2468 just made a speech "IF IM EVER PRESIDENT I'LL MAKE A LAW SO PEOPLE STORE THERE FARTS IN A JAR AND WHEN ITS FULL THEY GIVE IT TO THE GOVERNMENT AND IT WILL BE RATED ON A 1 THROUGH 10 SCALE AND THEY'LL PAY ON HOW BAD IT SMELLS AND HOW MANY FARTS THERE ARE IN THE (COOKIE JAR)

**Comment by TBNRFrags2468** [comment]
hehehe
