### ISSUE TITLE
You guys are working on both ImagicalMine and ClearSky? :p

### ISSUE THREAD

**Issue by XiangZhao969** [ImagicalCorp/ImagicalMine#626]
Which work better in survival server? Is there any difference between them? :p

**Comment by thebigsmileXD** [comment]
Only me and @aodzip
We tried to merge ClearSky into IM, now gave up.
ClearSky runs alot better

**Comment by XiangZhao969** [comment]
Thanks for the reply. So what about genisys?

**Comment by keithkfng** [comment]
I'm trying to get the developers to merge it into one big project - and they won't listen.

**Comment by thebigsmileXD** [comment]
I won't join.

**Comment by keithkfng** [comment]
Because everyone likes wars -_-
Anyway, I won't be working on it anymore. Maybe something else.

**Comment by PeratX** [comment]
PHP7 is available for Genisys !

**Comment by XiangZhao969** [comment]
All developers focus on one big project would be great, it may not easy at all, but the result will be very cool

**Comment by aodzip** [comment]
At least

code quality

**Comment by zzm317** [comment]
@xiangzhao969
that will be unpossible
not all the developers have the basic conscience
and some even find other people's faults and
use this to show he is so great (in one chinese team i have meet one...

**Comment by aodzip** [comment]
@PeratX
You mean join with server crash === Available?

**Comment by zzm317** [comment]
@xiaozhang969
and not everyone has the same idea to work out the same part
so if you don't have a good cooperation, the team will only become more bad

**Comment by zzm317** [comment]
@aodzip php7只是比PHP5快一点
但是bug不少，而且拓展也很少 。

**Comment by zzm317** [comment]
@aodzip 不少的拓展还得你自己编译。。。

**Comment by aodzip** [comment]
@zzm37
最终还是要升级到PHP7的，PHP5早晚还是要end-of-life
而且现在PHP7中运行PM的所有扩展都有了

**Comment by zzm317** [comment]
@aodzip 也只是运行pm的。。。

**Comment by zzm317** [comment]
@aodzip 然而pm本身结构太感人们

**Comment by PeratX** [comment]
Available = players can join, plugins can work...but not stable..

**Comment by thebigsmileXD** [comment]
Yay chinese war..

**Comment by thebigsmileXD** [comment]
But instant crash when you join is not working!

**Comment by PeratX** [comment]
Just ignore it

**Comment by robske110** [comment]
So this project is dead now.
I thought many times it's gonna die now. And now it died (ClearSky merge was so a bad idea:
ImagicalMine: MoreFeatures, LAG, Mid-Stable
ClearSky: LessFeatures, Smooth, Stable
Genesis: Features, OK, MidStable/Stable

**Comment by thebigsmileXD** [comment]
Uh.. Do you know that ClearSky has MORE features than IM? Also, we are currently logging packages to get fishing rods, anvils, brewing stands, enchantingtables working.

**Comment by robske110** [comment]
cool
