### ISSUE TITLE
My litte Bug list

### ISSUE THREAD

**Issue by MyHwu9508** [ImagicalCorp/ImagicalMine#629]
Hello guys I have some problems with my server.
My server is running for 5people Ower lan and we have a core i5 and 16gb ram and ... .
The CPU usage is lower than 5%.
We use the .phar from Jenkins build 45x because the newer ones works more laggy.

Plugins:
Iprotector
SignShop 
Xperms
Itemcase
Worldeditart
Economy (onebone)
Command signs
Multiple Universe
World signs 
Simple home
Dev tools 

So I found a lot of critical problems:

1. Server chunk loading very slow 
2. Server lag on client ?! I play on a Galaxy S6 edge and the map is clear we build nothing and my game is about 10-30 fps this is crazy. 
3. Crafting works very bad because the Crafting table shows no items to craft.
4. Put items into chests / grab items from chests: This is very buggy and I need to put my Iron 6-10 times into the chest to save it there. 
5. A lot more things ...

I need help please! 

Sry for my bad English I hope you understand all. :)

**Comment by KillerXtream** [comment]
Hey there!

We understand the problems, and it will be solved in a future build.

Best Regards!

**Comment by MyHwu9508** [comment]
Thanks for this fast replay :) I hope I can open my server at weekend or next week because this laggs are too hard to play with it...

**Comment by KillerXtream** [comment]
Yes Sir/Mrs.  We will try to develop faster.

Thanks!

**Comment by KillerXtream** [comment]
Answered, closing,

**Comment by aodzip** [comment]
If you need a phar for production server now you can have a look on ClearSky
https://github.com/ClearSkyTeam/ClearSky

**Comment by keithkfng** [comment]
@aodzip obviously you are now advertising. ImagicalMine will be continued no matter what. I will be finding more developers and nobody will stop me.

**Comment by KillerXtream** [comment]
True #ImagicalIsLife

**Comment by thebigsmileXD** [comment]
Its not advertising. Its based on IM but runs better. And no crashes after 6th day

**Comment by keithkfng** [comment]
Obviously - IM is for more features.

**Comment by thebigsmileXD** [comment]
Obviousely.. ClearSky has more features. Or do you log Packages to make fishing rods, anvils, enchanting working?

But i'll still work on IM, and i'll merge some code to fix IM whenever its possible. Because initially ClearSky was made to improve ImagicalMine and fixing it issues without having to use a branch (better for compiling/code cleanup)

**Comment by keithkfng** [comment]
Well I don’t think that’s what @aodzip wants. He’s been working full time and advertising like a maniac.

**Comment by aodzip** [comment]
I just adversting one time , okay?

**Comment by keithkfng** [comment]
XD
