### ISSUE TITLE
Jenkins error.

### ISSUE THREAD

**Issue by KillerXtream** [ImagicalCorp/ImagicalMine#631]
Hey guys!

Currently the ImagicalMine team started a new Project called ClearSky.

I´m currently reviewing the console outputs of Jenkins and please. Use the most recent successful build.

Thanks!

**Comment by thebigsmileXD** [comment]
HAHAHAAAA 😂😂😂😂😂
"The Team"
Only 2

**Comment by MyHwu9508** [comment]
What is different between clearsky and the normal version ?

**Comment by thebigsmileXD** [comment]
Performance. And code cleanup.

**Comment by MyHwu9508** [comment]
This is a very very good idea :D!
