### ISSUE TITLE
crashes when crough

### ISSUE THREAD

**Issue by remotevase** [ImagicalCorp/ImagicalMine#632]
you cannot crouch in the server or it will crash. crash dump is below:
[CrashDump_Thu_Jan_14-21.30.14-ACT_2016.txt](https://github.com/ImagicalCorp/ImagicalMine/files/91292/CrashDump_Thu_Jan_14-21.30.14-ACT_2016.txt)

**Comment by remotevase** [comment]
GOD! I meant to say "CRASHES WHEN CROUCHING"

**Comment by keithkfng** [comment]
Something to do with slapper. Contact @jojoe77777 about the changes.

**Comment by remotevase** [comment]
ok, but it interacts with the player inventory?

**Comment by keithkfng** [comment]
Fixed?
