### ISSUE TITLE
Crashes when player opens "options" tab

### ISSUE THREAD

**Issue by remotevase** [ImagicalCorp/ImagicalMine#633]
Not much more needs to be explained other than the title.Crash Dump file is below:
[CrashDump_Thu_Jan_14-21.28.06-ACT_2016.txt](https://github.com/ImagicalCorp/ImagicalMine/files/91298/CrashDump_Thu_Jan_14-21.28.06-ACT_2016.txt)

**Comment by keithkfng** [comment]
Try getting the newest build - compiled less than a minute ago at this time of writing.

**Comment by remotevase** [comment]
great! works very well!
