### ISSUE TITLE
Workbench problem

### ISSUE THREAD

**Issue by kiyoshi-kurosaki** [ImagicalCorp/ImagicalMine#637]
I fixed it 9 hours ago, but now deleted.....
The bug now appears again.....
So i now fix the bugs for me.

Regards

**Comment by keithkfng** [comment]
Yes because the code base switched around quite a bit. Sorry about that.

**Comment by KillerXtream** [comment]
Adding your code to the Project, thanks for asking.

**Comment by PocketKiller** [comment]
new huge problem incoming in 0.14.0 PC CRAFTING! :0 we should fix this before update

**Comment by keithkfng** [comment]
Maybe we should just get the original crafting recipes from the PocketMine repo instead of mucking it more XD

**Comment by keithkfng** [comment]
Code added. Also added crafting recipes again - let's see how this goes.
