### ISSUE TITLE
Emmmmm, WTC?

### ISSUE THREAD

**Issue by alex2534alex** [ImagicalCorp/ImagicalMine#640]
![screenshot_2016-01-16-10-53-49 01](https://cloud.githubusercontent.com/assets/15706847/12371544/def2a37a-bc3f-11e5-9cb6-bed685f12459.png)
It just stopped :/ 
And no crash file.....
And nothing....
After Snoop_Dog..... Just reload..... And noting about crash

**Comment by keithkfng** [comment]
There is nothing wrong -_-

**Comment by keithkfng** [comment]
Actually somebody might have just done /reload + update your version. You're using an older build.

**Comment by alex2534alex** [comment]
@keithkfng , there is the lack of information about any reload, and it's wrong —_—

**Comment by alex2534alex** [comment]
My build is #4xx

**Comment by keithkfng** [comment]
Gimme an exact build number please.

**Comment by alex2534alex** [comment]
@keithkfng , log with enabled debug
![screenshot_2016-01-16-14-04-57 01](https://cloud.githubusercontent.com/assets/15706847/12372337/2c0fa908-bc5b-11e5-9c05-150aa09c68bc.png)

**Comment by keithkfng** [comment]
Duplicate.

**Comment by gaoyichuan** [comment]
@alex2534alex The build you are using has something wrong with memory. Try getting the latest bulid.

**Comment by alex2534alex** [comment]
Yes, but not in crash file :/

**Comment by alex2534alex** [comment]
Ok.....

**Comment by robske110** [comment]
@gaoyichuan read through this issue (everyone is completely clueless) #592
