### ISSUE TITLE
Glowing Redstone Ore block won't break

### ISSUE THREAD

**Issue by dterweij** [ImagicalCorp/ImagicalMine#642]
The Redstone Ore Block is not breaking. When you go to break it then the block is returning back.
Sometimes it is realy gone after a lot of times trying but most of the time you cant break the block because it is just coming back.
All other Ore blocks (Iron, Gold etc) are breaking fine.

 
![screenshot_8](https://cloud.githubusercontent.com/assets/1059028/12372538/48515638-bc5c-11e5-8d02-21b9c0af845f.png)

**Comment by PocketKiller** [comment]
fixed

**Comment by dterweij** [comment]
Thank you.
