### ISSUE TITLE
cannot start server

### ISSUE THREAD

**Issue by Driesboy** [ImagicalCorp/ImagicalMine#646]
alert> RuntimeException: "unpack(): Type N: not enough input, need 4, have 0" (E_WARNING) in "/src/pocketmine/utils/Binary" at line 335

[CrashDump_Sat_Jan_16-07.05.42-UTC_2016.txt](https://github.com/ImagicalCorp/ImagicalMine/files/93227/CrashDump_Sat_Jan_16-07.05.42-UTC_2016.txt)

**Comment by keithkfng** [comment]
Issue closed until you can read the contributing guidelines.
