### ISSUE TITLE
Command aliases in pocketmine.yml doesn't work

### ISSUE THREAD

**Issue by SalmonGER** [ImagicalCorp/ImagicalMine#652]
Example:
Spawn: warp Spawn

**When you use ingame /spawn it will issue the command /warp Spawn. But now this doesn't work.**

https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/pocketmine/resources/pocketmine.yml#L162

**Comment by PocketKiller** [comment]
STOP DUPLICATING

**Comment by SalmonGER** [comment]
@PocketKiller I can't find this issue in the issue list.

**Comment by PocketKiller** [comment]
check closed ones also.. https://github.com/ImagicalCorp/ImagicalMine/issues/644

**Comment by SalmonGER** [comment]
@PocketKiller And how do i use the imagicalmine.yml ?

**Comment by PocketKiller** [comment]
same as pocketmine.yml.
