### ISSUE TITLE
Redstone Ore crafting bug 

### ISSUE THREAD

**Issue by MyHwu9508** [ImagicalCorp/ImagicalMine#653]
Os: Windows 10 
Hardware : Itel i5, 16GB Ram, 2TB SSHD
Build: I use the Jenkins build #500.

Error:

If I craft from Redstone dust redstone ore, I get for 1 redstone dust 1 redstone Block. And then wehen I can craft from 1 redstone Block 9 Redstone dust. So i have unlimited Redstone and this is for my survival Server a critical bug :). Thanks for help

Sorry for my bad english I am german.

**Comment by keithkfng** [comment]
I think crafting issues were fixed...
