### ISSUE TITLE
RakLib is not up to date

### ISSUE THREAD

**Issue by ChalkPE** [ImagicalCorp/ImagicalMine#657]
`$preJoinQueue` in `raklib\serever\Session` can cause [critical memory hog](https://github.com/ImagicalCorp/ImagicalMine/blob/master/src/raklib/server/Session.php#L433).

[Latest commit on PocketMine/RakLib that removed pre join queue (PHP7)](https://github.com/PocketMine/RakLib/commit/a5cca45a922ca193a616069f885866efc7158c67)

**Comment by cr0sh** [comment]
Yes, I wrote explanation of the vulnerability long ago.

https://gist.github.com/cr0sh/81dd0b04e5cf8a347c3f.

**Comment by dterweij** [comment]
So #592 can be this? So please update it too see if it is solved then.

**Comment by keithkfng** [comment]
Update IM to PHP7?

**Comment by alex2534alex** [comment]
@keithkfng , but what about plugins, which written by PHP5?

**Comment by keithkfng** [comment]
I can't do anything about that - don't ask me :P

**Comment by dterweij** [comment]
Plugin devs should update their own plugins. Tho most of them are opensource so some can be fixed ofcourse by others. But if they are programmed well... they work with php 7 :)
But this racklib update is not for PHP7 only, backport to PHP5 is possible.
Tho I am a "retired" coder, i shall test the racklib update localy on PHP 5 and if in the mood i present ya with a diff file so keith or other can merge it. Dont pin it on me. Can take a while for i have results. At least for two weeks I dont have time (Work and kids). Glad i still have PHPStorm and stuff installed on my linux box :)
