### ISSUE TITLE
Nice Katana

### ISSUE THREAD

**Issue by xxFlare** [ImagicalCorp/ImagicalMine#660]
I would like to congratulate all of you on the hard work!

https://github.com/ImagicalCorp/ImagicalMine/search?utf8=✓&q=katana

**Comment by robske110** [comment]
I thought the katana team was asked and an acknowledge is in the readme!

**Comment by PocketKiller** [comment]
it is on the README.
we are using Katana swords (lol)

**Comment by keithkfng** [comment]
Yes, thank you very much, and nice sarcasm.
