### ISSUE TITLE
Failed to find imagicalmine.yml on start

### ISSUE THREAD

**Issue by MCDad** [ImagicalCorp/ImagicalMine#662]
I'm installing Jenkins #512 to get the updates to server.properties and capture changes in imagicalmine.yml.  I've deleted both files and re-started the server.  Before I get to logging or the server even has a chance at running a Crash dump I get the following

Fatal error: Uncaught exception 'RuntimeException' with message 'file_get_contents(/home/pocketmine/src/pocketmine/resources/imagicalmine.yml): failed to open stream: No such file or directory' in phar:///home/pocketmine/ImagicalMine-IC_1.0dev#512.phar/src/pocketmine/katana/Katana.php:101
Stack trace:
#0 [internal function]: ExceptionHandler::handler(2, 'file_get_conten...', 'phar:///home/po...', 101, Array)
#1 phar:///home/pocketmine/ImagicalMine-IC_1.0dev#512.phar/src/pocketmine/katana/Katana.php(101): file_get_contents('/home/pocketmin...')
#2 phar:///home/pocketmine/ImagicalMine-IC_1.0dev#512.phar/src/pocketmine/katana/Katana.php(79): pocketmine\katana\Katana->initConfig()
#3 phar:///home/pocketmine/ImagicalMine-IC_1.0dev#512.phar/src/pocketmine/Server.php(1577): pocketmine\katana\Katana->__construct(Object(pocketmine\Server))
#4 phar:///home/pocketmine/ImagicalMine-IC_1.0dev#512.phar/src/pocketmine/PocketMine.php(469): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\Ma in phar:///home/pocketmine/ImagicalMine-IC_1.0dev#512.phar/src/pocketmine/katana/Katana.php on line 101
Segmentation fault

Don't ask for a server.log or a CrashDump.  There isn't one.  It's too early in the startup for them to be available.

Work around is to copy pocketmine.yml and imagicalmine.yml in from github

**Comment by FaanMaario** [comment]
Try change pocketmine.yml in imagicalmine.yml :D

**Comment by keithkfng** [comment]
You can't. There are two files.

**Comment by FaanMaario** [comment]
For me it works

**Comment by keithkfng** [comment]
Okay imagicalmine.yml is no longer needed...

**Comment by MCDad** [comment]
But the fault remains... This time I'm using Jenkins #519 and it's the same issue with the Katana code, this time it's struggling to find pocketmine.yml

Fatal error: Uncaught exception 'RuntimeException' with message 'file_get_contents(/home/pocketmine/src/pocketmine/resources/pocketmine.yml): failed to open stream: No such file or directory' in phar:///home/pocketmine/ImagicalMine-IC_1.0dev#519.phar/src/pocketmine/katana/Katana.php:101
Stack trace:
#0 [internal function]: ExceptionHandler::handler(2, 'file_get_conten...', 'phar:///home/po...', 101, Array)
#1 phar:///home/pocketmine/ImagicalMine-IC_1.0dev#519.phar/src/pocketmine/katana/Katana.php(101): file_get_contents('/home/pocketmin...')
#2 phar:///home/pocketmine/ImagicalMine-IC_1.0dev#519.phar/src/pocketmine/katana/Katana.php(79): pocketmine\katana\Katana->initConfig()
#3 phar:///home/pocketmine/ImagicalMine-IC_1.0dev#519.phar/src/pocketmine/Server.php(1577): pocketmine\katana\Katana->__construct(Object(pocketmine\Server))
#4 phar:///home/pocketmine/ImagicalMine-IC_1.0dev#519.phar/src/pocketmine/PocketMine.php(469): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\Main in phar:///home/pocketmine/ImagicalMine-IC_1.0dev#519.phar/src/pocketmine/katana/Katana.php on line 101
Segmentation fault

looks like the Katana.php doesn't catch the Exception.  Also, server logging should only be turned off after the server is stable.  Appreciate we're trying to stop lag but the use case for implementing the switch off of server logging is wrong.  On production hardware you should always log initiate BIT results regardless of your operational needs.

Work around is to copy pocketmine.yml from github

**Comment by keithkfng** [comment]
See my message in the other issue.
