### ISSUE TITLE
IM no longer loads worlds from pocketmine.yml (Jenkins #512)

### ISSUE THREAD

**Issue by MCDad** [ImagicalCorp/ImagicalMine#664]
Repeatable for me...

At the foot of pocketmine.yml define some worlds, for example:

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)
 lobby: []
 world: []
 daddy: []

start IM.  Only "world" is loaded as it's the default world in server.properties.

Functionality used to be that all the worlds listed here would be loaded on restart.  I rely on the autoload feature to get get my server back up after a restart.

Cheers

**Comment by PocketKiller** [comment]
use ImagicalMine. yml

**Comment by MCDad** [comment]
So the error is that there is no indication in imagicalmine.yml that there is an equivalent to the worlds: directive in pocketmine.yml.

The average user isn't going to get that from a trawl of the open issues.  they have to know it exists as a function or have reference to an Information Definition Specification that tells the user where to find that functionality.

The enhancement requires is to have that worlds: stub in magicalmine,yml.  I'd say this issue isn't closed.

**Comment by keithkfng** [comment]
Maybe just merge imagicalmine.yml into pocketmine.yml in stead of having two messy files...

**Comment by keithkfng** [comment]
Try it now, should work...

**Comment by MCDad** [comment]
true it works now.
