### ISSUE TITLE
I cant download imagicalmine from jenkins :(

### ISSUE THREAD

**Issue by SoyPro** [ImagicalCorp/ImagicalMine#672]
Please help me i want to download imagical Mine from jenkins but i cant so someone download the lastest build from jenkins and put it in dropbox or mediafire and put it here and i will able to download imagicalmine, thanks!

**Comment by ChalkPE** [comment]
Why can't you download it on Jenkins? Anyway, here's a latest build [IM#522](http://jenkins.imagicalmine.net:8080/job/ImagicalMine/522/), from [Jenkins](http://jenkins.imagicalmine.net:8080/job/ImagicalMine/522/artifact/releases/ImagicalMine-IC_1.0dev%23522.phar) and [MediaFire](http://www.mediafire.com/download/rbrh6kz49xrqw43/ImagicalMine-IC_1.0dev%23522.phar) :)

**Comment by keithkfng** [comment]
Please don't submit Jenkins errors...
