### ISSUE TITLE
Jenkins Download Issue...

### ISSUE THREAD

**Issue by Taki21** [ImagicalCorp/ImagicalMine#674]
Ok...So when i download from jenkins the latest phars...it encounters a problem:
1. The Regular Phar File is 3 Megabytes (or more) however, ones downloaded from jenkins are only like couple of hundreds KILOBYTES. 
2. When Opening Jenkins PHAR...Not even 1/4 of the phar code is there! CONTENT IS Cut OFF!!!!! xD
3. Lastly...I get the ANNOYING ERROR: require_once(BLAH BLAH BLAH)...

=+=+= This is the cause of the Require_Once Error! =+=+=

**Comment by Taki21** [comment]
![ice_screenshot_20160119-210810](https://cloud.githubusercontent.com/assets/14851895/12437986/c2f64678-bef0-11e5-928a-1c6ddb85938a.png)
![ice_screenshot_20160119-210907](https://cloud.githubusercontent.com/assets/14851895/12437996/df50b880-bef0-11e5-8d83-66f1ff7ca03e.png)

**Comment by Taki21** [comment]
Big Difference in SIze...

**Comment by ChalkPE** [comment]
Please try again. If you're still getting problem, download it from my [MediaFire](http://www.mediafire.com/download/rbrh6kz49xrqw43/ImagicalMine-IC_1.0dev%23522.phar) :)

**Comment by Taki21** [comment]
Thanks @ChalkPE

**Comment by PocketKiller** [comment]
@aodzip needs a Global CDN To speed up the website hosting.
